Repository keymanapp/help.keyman.com, pull requests merged in 2019-09, with the labels that each got.

#32 Preliminary Lexical models documentation
  .gitattributes
  cdn/dev/css/dev-lexical-models.css
  cdn/dev/css/template.css
  cdn/dev/img/developer/120/lm/overview.svg
  cdn/dev/img/developer/120/lm/sencoten-sheets-full.png
  cdn/dev/img/developer/120/lm/sencoten-sheets-save-as.png
  cdn/dev/img/developer/120/lm/whatis-correct-thr.png
  cdn/dev/img/developer/120/lm/whatis-incompr.png
  cdn/dev/img/developer/120/lm/whatis-naiv.png
  cdn/dev/img/developer/120/lm/whatis-on-my-w.png
  developer/12.0/guides/index.php
  developer/12.0/guides/lexical-models/index.php
  developer/12.0/guides/lexical-models/intro/index.php
  developer/12.0/guides/lexical-models/tutorial/index.php
  developer/12.0/guides/lexical-models/tutorial/step-1.php
  developer/12.0/guides/lexical-models/tutorial/step-2.php
  developer/12.0/guides/lexical-models/tutorial/step-3.php
  developer/12.0/index.php
  developer/12.0/reference/file-types/index.php
  developer/12.0/reference/file-types/tsv.php
Labels: enhancement

#36 Remove erroneous fields from KeyboardLanguageInfo in .keyboard_info documemtation
  developer/cloud/keyboard_info/1.0/index.php
Labels: bug

#40 Add link to guide for creating a touch layout keyboard
  developer/12.0/context/keyboard-editor.php
Labels: enhancement, help.keyman.com

#45 Allow users to zoom in on pages on mobile browsers
  _includes/includes/head.php
Labels: bug, help.keyman.com

#43 [iOS] v12.0 content update
  cdn/dev/img/app/12.0/add-keyboard-i.png
  cdn/dev/img/app/12.0/add-keyboard-i2.png
  cdn/dev/img/app/12.0/add-keyboard-i3.png
  cdn/dev/img/app/12.0/add-keyboard-i4.png
  cdn/dev/img/app/12.0/add-keyboard-i5.png
  cdn/dev/img/app/12.0/delete-keyboard-i.png
  cdn/dev/img/app/12.0/delete-keyboard-i2.png
  cdn/dev/img/app/12.0/in-app-picker-i.png
  cdn/dev/img/app/12.0/system-picker-i.png
  products/iphone-and-ipad/12.0/index.php
  products/iphone-and-ipad/12.0/installing-custom-keyboards.php
  products/iphone-and-ipad/12.0/installing-fonts.php
  products/iphone-and-ipad/12.0/installing-keyboards.php
  products/iphone-and-ipad/12.0/installing-system-keyboard.php
  products/iphone-and-ipad/12.0/switching-between-keyboards.php
  products/iphone-and-ipad/12.0/uninstalling-keyboards.php
  products/iphone-and-ipad/12.0/using-keyman-browser.php
Labels: enhancement, help.keyman.com

#39 Adds 'embed' mode to page templates for use with app help
  _includes/includes/embed_footer.php
  _includes/includes/head.php
  _includes/includes/no-menu.php
  _includes/includes/session-embed.php
  _includes/includes/template.php
  cdn/dev/css/app-info-a.css
  cdn/dev/css/app-info.css
  cdn/dev/css/embed.css
  cdn/dev/img/app/12.0/add-keyboard-i.png
  cdn/dev/img/app/12.0/add-keyboard-i2.png
  cdn/dev/img/app/12.0/add-keyboard-i3.png
  cdn/dev/img/app/12.0/add-keyboard-i4.png
  cdn/dev/img/app/12.0/add-keyboard-i5.png
  cdn/dev/img/app/12.0/delete-keyboard-i.png
  cdn/dev/img/app/12.0/delete-keyboard-i2.png
  cdn/dev/img/app/12.0/in-app-picker-i.png
  cdn/dev/img/app/12.0/system-picker-i.png
  cdn/dev/js/kmlive.js
  products/android/12.0/index.php
  products/iphone-and-ipad/12.0/index.php
  products/iphone-and-ipad/12.0/installing-custom-keyboards.php
  products/iphone-and-ipad/12.0/installing-fonts.php
  products/iphone-and-ipad/12.0/installing-keyboards.php
  products/iphone-and-ipad/12.0/installing-system-keyboard.php
  products/iphone-and-ipad/12.0/switching-between-keyboards.php
  products/iphone-and-ipad/12.0/uninstalling-keyboards.php
  products/iphone-and-ipad/12.0/using-keyman-browser.php
Labels: enhancement, help.keyman.com

#46 Adds redirect for alpha iOS help links
  products/iphone-and-ipad/web.config
Labels: enhancement

#44 Update lexical model tutorial
  cdn/dev/img/developer/120/ui/frmAboutTike.png
  cdn/dev/img/developer/120/ui/frmModelsCompile.png
  cdn/dev/img/developer/120/ui/frmNew.png
  cdn/dev/img/developer/120/ui/frmNewLMProject.png
  cdn/dev/img/developer/120/ui/frmNewLMProjectParameters.png
  cdn/dev/img/developer/120/ui/frmNewLMProjectSelectLanguage.png
  cdn/dev/img/developer/120/ui/frmNewProject.png
  cdn/dev/img/developer/120/ui/frmNewProjectParameters.png
  cdn/dev/img/developer/120/ui/frmOptions_CharacterMap.png
  cdn/dev/img/developer/120/ui/frmOptions_Debugger.png
  cdn/dev/img/developer/120/ui/frmOptions_Editor.png
  cdn/dev/img/developer/120/ui/frmOptions_General.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Build.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Details.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Files.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Keyboards.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Select_BCP_47_Tag.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Shortcuts.png
  cdn/dev/img/developer/120/ui/frmPackageEditor_Source.png
  cdn/dev/img/developer/120/ui/frmProject_Distribution.png
  developer/12.0/context/about-tike.php
  developer/12.0/context/index.php
  developer/12.0/context/new-lm-project-parameters.php
  developer/12.0/context/new-project-parameters.php
  developer/12.0/context/new-project.php
  developer/12.0/context/new.php
  developer/12.0/context/options.php
  developer/12.0/context/package-editor.php
  developer/12.0/context/project.php
  developer/12.0/guides/lexical-models/tutorial/index.php
  developer/12.0/guides/lexical-models/tutorial/step-1.php
  developer/12.0/guides/lexical-models/tutorial/step-2.php
  developer/12.0/guides/lexical-models/tutorial/step-3.php
  developer/12.0/guides/lexical-models/tutorial/step-4.php
  developer/12.0/guides/lexical-models/tutorial/step-5.php
  developer/index.php
Labels: help.keyman.com

#49 Update guide to describe using TSV editor in Developer
  cdn/dev/img/developer/120/lm/developer-open-tsv.png
  cdn/dev/img/developer/120/lm/edited-tsv.png
  cdn/dev/img/developer/120/lm/template-tsv.png
  developer/12.0/guides/lexical-models/tutorial/step-3.php
Labels: enhancement

#50 Add 12.0 updates for Developer command-line tools
  developer/12.0/context/index.php
  developer/12.0/context/kmcomp.php
  developer/12.0/context/kmlmc.php
  developer/12.0/context/kmlmi.php
  developer/12.0/context/kmlmp.php
Labels: enhancement, help.keyman.com

#52 Android help: Re-enables non-embedded CSS autodetect
  _includes/includes/template.php
  cdn/dev/js/kmlive.js
Labels: bug, help.keyman.com

#51 Android main help page: WET -> DRY with CSS
  _includes/includes/session-embed.php
  _includes/includes/session-formfactor.php
  _includes/includes/template.php
  cdn/dev/css/app-info-a.css
  cdn/dev/css/formfactor.css
  cdn/dev/js/kmlive.js
  products/android/12.0/index.php
Labels: enhancement, help.keyman.com

#54 Basic keymanweb.com product page
  products/web/12.0/index.php
Labels: help.keyman.com
