Repository keymanapp/help.keyman.com, pull requests merged in 2019-12, with the labels that each got.

#91 chore: rollback incorrect update to constants
  developer/language/guide/constants.php
Labels: bug

#85 [help.keyman.com] update kb0069
  knowledge-base/kb0069.md
Labels: help.keyman.com

#92 feat(developer): unquoted hotkeys
  developer/language/reference/hotkey.php
Labels: enhancement

#95 fix: deprecated keyboard search
  developer/cloud/keyboard_info/1.0/index.php
  developer/cloud/search/1.0/index.php
Labels: enhancement
