Repository keymanapp/help.keyman.com, pull requests merged in 2019-11, with the labels that each got.

#75 fix(web): fix copyright in screenshot.
  cdn/dev/img/developer/120/ui/frmNewLMProjectParameters.png
Labels: bug

#78 fix: Redirect unversioned web link to 12.0
  products/web/web.config
Labels: bug, help.keyman.com

#84 feat: Keyman Core API Documentation
  cdn/dev/img/icon-core-desktop.png
  cdn/dev/img/icon-core-web.png
  cdn/dev/img/icon-core.png
  developer/core/desktop/11.0/building.php
  developer/core/desktop/11.0/c-api/context-api.php
  developer/core/desktop/11.0/c-api/index.php
  developer/core/desktop/11.0/c-api/keyboard-api.php
  developer/core/desktop/11.0/c-api/option-api.php
  developer/core/desktop/11.0/c-api/state-api.php
  developer/core/desktop/11.0/index.php
  developer/core/desktop/11.0/json-schema.php
  developer/core/desktop/web.config
  developer/core/index.php
  developer/core/web/index.php
  developer/index.php
Labels: enhancement

#88 fix: document layer switch precedence
  developer/12.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.php
  developer/language/reference/layer.php
Labels: bug, help.keyman.com
