Repository keymanapp/help.keyman.com, pull requests merged in 2020-09, with the labels that each got.

#206 feat: cloud search 2.0 documentation
  developer/cloud/search/1.0/index.php
  developer/cloud/search/2.0/index.md
Labels: feat

#211 docs: new kbd language methods for Windows Engine
  developer/engine/desktop/14.0/api/IKeymanBCP47Canonicalization/GetCanonicalTag.php
  developer/engine/desktop/14.0/api/IKeymanBCP47Canonicalization/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardFile2/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled/Install.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/FindInstallationLangID.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/InstallTip.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/IsRegistered.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/RegisterTip.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/Install.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/InstallByLangID.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled2/Add.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled2/index.php
  developer/engine/desktop/14.0/api/IKeymanKeyboardsInstalled2/index.php
  developer/engine/desktop/14.0/api/IKeymanPackageFile2/index.php
  developer/engine/desktop/14.0/api/IKeymanPackagesInstalled2/index.php
  developer/engine/desktop/14.0/api/__interface-hierarchy.php
Labels: feat

#214 modify: Change current-version to 14.0
  products/linux/14.0/guide/index.php
  products/linux/14.0/reference/index.php
  products/web/14.0/index.php
  products/web/web.config
  web.config
Labels: feat

#213 docs: Add page on Android System Requirements
  products/android/14.0/_shared/help_links.php
  products/android/14.0/system-requirements.php
Labels: enhancement

#217 fix: Update kmx usage
  developer/11.0/reference/file-types/kmx.php
  developer/12.0/reference/file-types/kmx.php
  developer/13.0/reference/file-types/kmx.php
  developer/14.0/reference/file-types/kmx.php
Labels: bug, fix, help wanted, staging

#218 Add 'using keys' notes
  developer/language/guide/groups.php
Labels: enhancement

#219 chore: add illustration to language overview
  cdn/dev/img/developer/language/language-overview.png
  developer/language/guide/overview.php
Labels: chore

#216 feat: Update Android help
  cdn/dev/img/app/14.0/confirm-dl-ap.png
  cdn/dev/img/app/14.0/confirm-dl-at.png
  cdn/dev/img/app/14.0/khmer-downloading-a.png
  cdn/dev/img/app/14.0/khmer-install-a.png
  cdn/dev/img/app/14.0/khmer-readme-a.png
  cdn/dev/img/app/14.0/khmer-search-a.png
  cdn/dev/img/app/14.0/khmer-settings-ap.png
  cdn/dev/img/app/14.0/khmer-welcome-a.png
  cdn/dev/img/app/14.0/lang-list-ap.png
  cdn/dev/img/app/14.0/lang-list-at.png
  cdn/dev/img/app/14.0/settings-language-ap.png
  cdn/dev/img/app/14.0/settings-languages-ap.png
  cdn/dev/img/app/14.0/settings-screen-ap.png
  cdn/dev/img/app/14.0/settings-screen-install-keyboard-dictionary.png
  cdn/dev/img/app/14.0/settings-two-installed-languages-ap.png
  products/android/14.0/index.php
  products/android/14.0/installing-custom-packages.php
  products/android/14.0/installing-keyboards.php
  products/android/14.0/switching-between-keyboards.php
  products/android/14.0/using-settings-screen.php
Labels: enhancement, help.keyman.com, staging

#221 fix: cloud docs model_info and package-version
  developer/cloud/model_info/1.0/index.php
  developer/cloud/package-version/1.0/index.md
Labels: fix

#223 fix(common): staging for sentry
  _common/KeymanSentry.php
Labels: fix

#220 fix: Update km-config for 14.0
  cdn/dev/img/linux/140/add-input-source-khmer-angkor.png
  cdn/dev/img/linux/140/add-input-source-khmer.png
  cdn/dev/img/linux/140/add-input-source.png
  cdn/dev/img/linux/140/download-khmer-angkor.png
  cdn/dev/img/linux/140/km-config-khmer-angkor.png
  cdn/dev/img/linux/140/km-config.png
  cdn/dev/img/linux/140/mobile viewport.png
  cdn/dev/img/linux/140/onboard.png
  cdn/dev/img/linux/140/package-khmer-angkor-welcome.png
  cdn/dev/img/linux/140/region-and-language.png
  cdn/dev/img/linux/140/region-language-khmer-angkor.png
  cdn/dev/img/linux/140/search-khmer-angkor.png
  products/linux/14.0/common.php
  products/linux/14.0/guide/installing-keyboard.php
  products/linux/14.0/reference/km-config.php
Labels: fix, help.keyman.com, staging

#225 Fix/some broken links
  developer/11.0/index.php
  developer/12.0/index.php
  developer/14.0/guides/develop/imx/guide_imx_web.php
  developer/14.0/guides/develop/imx/web.php
  developer/14.0/guides/lexical-models/advanced/index.php
  developer/14.0/guides/lexical-models/tutorial/step-4.php
  developer/8.0/docs/reference_kmw20_ui_button.php
  developer/engine/android/14.0/KMManager/getKeyboardFontFilename-Deprecated.php
  developer/engine/android/14.0/KMManager/getKeyboardFontTypeface-Deprecated.php
  developer/engine/android/14.0/KMManager/getKeyboardState.php
  knowledge-base/assets/kb0029/kb_explorer62.png
  knowledge-base/kb0013.md
  knowledge-base/kb0018.md
  knowledge-base/kb0019.md
  knowledge-base/kb0029.md
  knowledge-base/kb0030.md
  knowledge-base/kb0037.md
  knowledge-base/kb0056.md
  knowledge-base/kb0085.md
Labels: staging

#227 Fix some broken links
  developer/11.0/index.php
  developer/12.0/index.php
  developer/14.0/guides/develop/imx/guide_imx_web.php
  developer/14.0/guides/develop/imx/web.php
  developer/14.0/guides/lexical-models/advanced/index.php
  developer/14.0/guides/lexical-models/tutorial/step-4.php
  developer/8.0/docs/reference_kmw20_ui_button.php
  developer/engine/android/14.0/KMManager/getKeyboardFontFilename-Deprecated.php
  developer/engine/android/14.0/KMManager/getKeyboardFontTypeface-Deprecated.php
  developer/engine/android/14.0/KMManager/getKeyboardState.php
  knowledge-base/assets/kb0029/kb_explorer62.png
  knowledge-base/kb0013.md
  knowledge-base/kb0018.md
  knowledge-base/kb0019.md
  knowledge-base/kb0029.md
  knowledge-base/kb0030.md
  knowledge-base/kb0037.md
  knowledge-base/kb0056.md
  knowledge-base/kb0085.md
Labels: bug, cherry-pick

#228 fix: Update KeyboardEventHandler
  developer/engine/android/14.0/KeyboardEventHandler/index.php
  developer/engine/android/14.0/KeyboardEventHandler/onLexicalModelInstalled.md
  developer/engine/android/14.0/KeyboardEventHandler/onPackageInstalled.md
  developer/engine/android/14.0/index.php
Labels: staging

#229 fix(developer): broken links
  developer/8.0/docs/reference_kmw20_ui_button.php
  developer/8.0/docs/reference_kmw20_ui_float.php
  developer/8.0/docs/reference_kmw20_ui_toggle.php
  developer/8.0/docs/reference_kmw20_ui_toolbar.php
  developer/core/desktop/14.0/building.php
  developer/core/desktop/14.0/c-api/context-api.php
  developer/core/desktop/14.0/c-api/index.php
  developer/core/desktop/14.0/c-api/keyboard-api.php
  developer/core/desktop/14.0/c-api/option-api.php
  developer/core/desktop/14.0/c-api/state-api.php
  developer/core/desktop/14.0/index.php
  developer/core/desktop/14.0/json-schema.php
  developer/core/desktop/web.config
  developer/engine/android/13.0/KMManager/getKeyboardFontFilename.php
  developer/engine/android/13.0/KMManager/getKeyboardFontTypeface.php
  developer/engine/android/13.0/KMManager/initialize.php
  developer/engine/android/13.0/KMManager/setKeymanLicense.php
  developer/engine/android/14.0/KMManager/getKeyboardFontFilename.php
  developer/engine/android/14.0/KMManager/getKeyboardFontTypeface.php
  developer/engine/android/14.0/KMManager/getKeyboardState.php
  developer/engine/android/14.0/KMManager/initialize.php
  developer/engine/android/14.0/KMManager/setDefaultKeyboard.php
  developer/engine/android/14.0/KMManager/setKeyboard.php
  developer/engine/android/14.0/KMManager/setKeymanLicense.php
  developer/engine/android/14.0/KMManager/showKeyboardPicker.php
  developer/engine/android/14.0/KMManager/showLanguageList.php
  knowledge-base/kb0055.md
  products/web/10.0/ui/index.php
Labels: bug, staging

#231 fix: remove broken links in desktop help
  products/desktop/10.0/docs/context_splash.php
  products/desktop/11.0/docs/context_splash.php
  products/desktop/12.0/docs/context_splash.php
  products/desktop/13.0/docs/context_langsetup.php
  products/desktop/6.0/main/contents.php
Labels: fix

#232 fix: remove broken links in desktop help 🍒
  products/desktop/10.0/docs/context_splash.php
  products/desktop/11.0/docs/context_splash.php
  products/desktop/12.0/docs/context_splash.php
  products/desktop/13.0/docs/context_langsetup.php
  products/desktop/6.0/main/contents.php
Labels: cherry-pick, fix

#234 fix: current-version breaking some links
  _includes/includes/page-version.php
Labels: fix

#235 fix: broken link for Desktop version history
  products/desktop/web.config
  products/index.php
Labels: fix

#236 fix: broken link maintenance
  developer/11.0/index.php
  developer/12.0/index.php
  developer/13.0/guides/lexical-models/advanced/index.php
  developer/13.0/guides/lexical-models/tutorial/step-4.php
  developer/14.0/guides/develop/imx/web/index.md
  developer/8.0/docs/reference_kmw20_ui_button.php
  developer/8.0/docs/reference_kmw20_ui_toolbar.php
  developer/core/desktop/web.config
  developer/engine/android/12.0/KMManager/setKeymanLicense.php
  developer/engine/android/13.0/KMManager/getKeyboardFontTypeface.php
  developer/engine/android/13.0/KMManager/getKeyboardState.php
  developer/engine/android/14.0/KMManager/getKeyboardFontFilename.php
  developer/engine/android/14.0/KMManager/getKeyboardFontTypeface.php
  developer/engine/android/14.0/KMManager/initialize.php
  developer/engine/android/14.0/KMManager/setDefaultKeyboard.php
  developer/engine/web/1.0/content/index.php
  knowledge-base/kb0013.md
  knowledge-base/kb0019.md
  knowledge-base/kb0030.md
  products/desktop/10.0/docs/context_langsetup.php
  products/desktop/11.0/docs/context_langsetup.php
  products/desktop/12.0/docs/context_langsetup.php
  products/desktop/14.0/docs/context_langsetup.php
  products/web/10.0/ui/index.php
Labels: fix

#237 fix: broken links - keyboards
  .github/workflows/ci.yml
  keyboard/basic_kbdinben/1.1/chart.php
  keyboard/galaxie_greek_mnemonic/3.2.1/galaxie_greek_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.2.1/keyboardchart.php
  keyboard/galaxie_greek_mnemonic/3.2/galaxie_greek_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.2/keyboardchart.php
  keyboard/galaxie_greek_positional/1.0/galaxie_greek_positional.php
  keyboard/galaxie_greek_positional/1.0/keyboardchart.php
  keyboard/gff_amharic/1.5/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/1.5/AmharicTyping-English.pdf
  keyboard/gff_amharic/1.6/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/1.6/AmharicTyping-English.pdf
  keyboard/gff_amharic/1.7/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/1.7/AmharicTyping-English.pdf
  keyboard/gff_amharic/1.8/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/1.8/AmharicTyping-English.pdf
  keyboard/gff_amharic/1.9/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/1.9/AmharicTyping-English.pdf
  keyboard/gff_tir_er_7/1.0/gff_tir_er_7.php
  keyboard/gff_tir_et_7/1.0/gff_tir_et_7.php
  keyboard/indic roman transliteration/1/indic roman transliteration.php
  keyboard/khowar/1.0/khowar.php
  keyboard/tamil - visual media/1.2/keyboardchart-modular.htm
  keyboard/tamil - visual media/1.2/keyboardchart-typewriter.htm
  keyboard/thamizha anjal/2.0/keyboardchart.htm
  keyboard/thamizha bamini/2.0/keyboardchart.htm
  keyboard/thamizha typewriter/2.0/keyboardchart.htm
  keyboard/thamizha_anjal_paangu/2.1/thamizha_anjal_paangu.php
  keyboard/tibetan_direct_input/1.4/tibetan_direct_input.php
  version-history/index.php
Labels: fix

#238 fix: check PHP errors in CI
  .github/workflows/ci.yml
Labels: fix
