Repository keymanapp/help.keyman.com, pull requests merged in 2020-07, with the labels that each got.

#189 fix(mac): polish privacy help and make it more searchable
  products/mac/13.0/help/configure-security.md
  products/mac/13.0/images/privacy_files_and_folders.png
  products/mac/13.0/index.md
  products/mac/13.0/start/install-keyman.md
Labels: fix

#187 fix: clarify identifiers for package-version
  developer/cloud/package-version/1.0/index.md
Labels: fix

#192 fix: edit page link was crashing for kb articles
  _includes/includes/com.keyman.help.editpage.inc.php
Labels: fix

#193 Add DefaultKeyboard() and deprecate showLanguageList
  developer/engine/android/14.0/KMManager/getDefaultKeyboard.php
  developer/engine/android/14.0/KMManager/getKeyboardFontFilename-Deprecated.php
  developer/engine/android/14.0/KMManager/getKeyboardFontTypeface-Deprecated.php
  developer/engine/android/14.0/KMManager/index.php
  developer/engine/android/14.0/KMManager/setDefaultKeyboard.php
  developer/engine/android/14.0/KMManager/setKeymanLicense-Deprecated.php
  developer/engine/android/14.0/KMManager/showLanguageList-Deprecated.php
Labels: enhancement, help.keyman.com, staging

#194 chore: merge master into staging (P10S10 changes)
  _includes/includes/com.keyman.help.editpage.inc.php
  keyboard/gff_gurage/0.6.10/gff_gurage.php
  keyboard/malar_malayalam/1.2/malar_malayalam.jpg
  keyboard/malar_malayalam/1.2/malar_malayalam.pdf
  keyboard/malar_malayalam/1.2/malar_malayalam.php
  products/desktop/14.0/docs/about_history.php
  products/desktop/14.0/docs/about_requirements.php
  products/desktop/14.0/docs/about_welcome.php
  products/desktop/14.0/docs/about_whatsnew.php
  products/desktop/14.0/docs/advanced_locale_edit.php
  products/desktop/14.0/docs/advanced_proxy_config.php
  products/desktop/14.0/docs/advanced_tsf.php
  products/desktop/14.0/docs/basic_charactermap.php
  products/desktop/14.0/docs/basic_config_menu.php
  products/desktop/14.0/docs/basic_disable_keyboard.php
  products/desktop/14.0/docs/basic_enable_keyboard.php
  products/desktop/14.0/docs/basic_fonthelper.php
  products/desktop/14.0/docs/basic_help.php
  products/desktop/14.0/docs/basic_hotkeys_tab.php
  products/desktop/14.0/docs/basic_keyboards_tab.php
  products/desktop/14.0/docs/basic_languageswitcher.php
  products/desktop/14.0/docs/basic_newways.php
  products/desktop/14.0/docs/basic_options_tab.php
  products/desktop/14.0/docs/basic_osk.php
  products/desktop/14.0/docs/basic_support_tab.php
  products/desktop/14.0/docs/basic_text_editor.php
  products/desktop/14.0/docs/basic_toolbox.php
  products/desktop/14.0/docs/basic_traymenu.php
  products/desktop/14.0/docs/basic_uninstall_keyboard.php
  products/desktop/14.0/docs/basic_update.php
  products/desktop/14.0/docs/basic_usage.php
  products/desktop/14.0/docs/index.php
  products/desktop/14.0/docs/start_configure_computer.php
  products/desktop/14.0/docs/start_configure_office.php
  products/desktop/14.0/docs/start_download-install_keyboard.php
  products/desktop/14.0/docs/start_download-install_keyman.php
  products/desktop/14.0/docs/start_font.php
  products/desktop/14.0/docs/start_hotkey_set.php
  products/desktop/14.0/docs/start_locale.php
  products/desktop/14.0/docs/start_rtl.php
  products/desktop/14.0/docs/start_tutorial.php
  products/desktop/14.0/docs/troubleshooting_bootstrapper.php
  products/desktop/14.0/docs/troubleshooting_excel.php
  products/desktop/14.0/docs/troubleshooting_font.php
  products/desktop/14.0/docs/troubleshooting_hidden.php
  products/desktop/14.0/docs/troubleshooting_sigma.php
Labels: chore

#195 feat: kb0097 - serialised input control
  knowledge-base/kb0097.md
Labels: feat

#198 feat: kmshell and setup command line options
  knowledge-base/kb0035.md
  knowledge-base/kb0098.md
Labels: feat

#200 chore: add keyman_com global
  _includes/includes/servervars.php
Labels: chore

#201 fix: various site errors
  _includes/autoload.php
  _includes/includes/servervars.php
  _includes/includes/template.php
  _includes/kmdevhtml.php
  _includes/servervars.php
  developer/engine/web/1.0/content/troubleshooting/embedded_fonts.php
  keyboard/ekwunitamil/1.0/ekwunitamil.php
Labels: fix

#125 feat: sentry integration (and common files)
  .gitignore
  Readme.md
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _common/README.md
  _includes/autoload.php
  _includes/includes/servervars.php
  _includes/includes/template.php
  _includes/kmdevhtml.php
  _includes/servervars.php
  composer.json
  composer.lock
  developer/engine/web/1.0/content/troubleshooting/embedded_fonts.php
  keyboard/ekwunitamil/1.0/ekwunitamil.php
Labels: enhancement

#203 chore: add common/jsonapifailure
  _common/JsonApiFailure.php
Labels: chore
