Repository keymanapp/help.keyman.com, pull requests merged in 2020-04, with the labels that each got.

#163 feat: add warning on data loss
  knowledge-base/kb0096.md
Labels: enhancement

#165 Update kb0096.md
  knowledge-base/kb0096.md
Labels: enhancement

#167 docs: remove 'Browser Compatibility' page
  troubleshooting/browsers.php
  troubleshooting/index.php
Labels: bug

#168 Update Howto: send a diagnostic report
  knowledge-base/assets/kb0040/step4.png
  knowledge-base/assets/kb0040/step5.png
  knowledge-base/assets/kb0040/step6.png
  knowledge-base/assets/kb0040/step7.png
  knowledge-base/assets/kb0040/step8.png
  knowledge-base/kb0040.md
Labels: help.keyman.com

#169 feat(android): Add documentation on "Keyman Settings" screen
  cdn/dev/img/app/13.0/settings-screen-ap.png
  cdn/dev/img/app/13.0/settings-screen-at.png
  products/android/13.0/_shared/help_links.php
  products/android/13.0/enabling-system-keyboard.php
  products/android/13.0/index.php
  products/android/13.0/using-settings-screen.php
Labels: enhancement

#172 docs: document wordBreaker joinWordsAt property
  developer/14.0/guides/lexical-models/advanced/word-breaker.php
Labels: enhancement

#173 change(common/lmlayer): document new default search term to key fn
  developer/14.0/guides/lexical-models/advanced/search-term-to-key.php
Labels: enhancement

#175 docs(common/lmlayer): tweak docs for word breaker and search term to key
  developer/13.0/context/model-editor.php
  developer/14.0/context/model-editor.php
  developer/14.0/guides/lexical-models/advanced/model-definition-file.php
  developer/14.0/guides/lexical-models/advanced/word-breaker.php
  developer/14.0/reference/file-types/model-ts.php
Labels: enhancement
