Repository keymanapp/help.keyman.com, pull requests merged in 2020-10, with the labels that each got.

#239 fix: various php errors
  .github/workflows/ci.yml
  _includes/header.php
  _includes/includes/head.php
  _includes/includes/renderLanguageExample.php
  _includes/kmdisthtml.php
  developer/engine/web/1.0/content/index.php
  developer/engine/web/1.0/sub/editdesign.php
  developer/engine/web/10.0/reference/core/focusLastActiveElement.php
  developer/engine/web/11.0/reference/core/focusLastActiveElement.php
  developer/engine/web/12.0/reference/core/focusLastActiveElement.php
  developer/engine/web/13.0/reference/core/focusLastActiveElement.php
  developer/engine/web/2.0/reference/core/focusLastActiveElement.php
  keyboard/hieroglyphic/1.0/hieroglyphic.php
  keyboard/hieroglyphic/1.1/hieroglyphic.php
  keyboard/isis_gujarati/2.0.1/isis_gujarati.php
  keyboard/isis_gurmukhi/2.0.1/isis_gurmukhi.php
  keyboard/isis_kannada/2.0.1/isis_kannada.php
  keyboard/isis_oriya/2.1/isis_oriya.php
  keyboard/isis_telugu/2.0.1/isis_telugu.php
  products/desktop/6.0/main/about.php
Labels: fix

#230 Add "Keyman has the wrong name for my language" item to knowledge base
  knowledge-base/kb0099.md
Labels: enhancement

#245 chore: add and update kb around tsf and chrome
  knowledge-base/kb0094.md
  knowledge-base/kb0100.md
Labels: chore

#246 feat: Add Android guide for adding new dictionaries
  cdn/dev/img/app/14.0/settings-2-installed-languages-ap.png
  cdn/dev/img/app/14.0/settings-download-dictionary-background-ap.png
  cdn/dev/img/app/14.0/settings-download-str-dictionary-ap.png
  cdn/dev/img/app/14.0/settings-str-dictionary-ap.png
  cdn/dev/img/app/14.0/settings-str-settings-ap.png
  cdn/dev/img/app/14.0/settings-suggestions-ap.png
  developer/14.0/guides/lexical-models/index.php
  products/android/14.0/_shared/help_links.php
  products/android/14.0/installing-dictionaries.php
Labels: enhancement, staging

#249 chore: reboot deprecation for Keyman Engine for Windows
  developer/engine/desktop/10.0/api/IKeymanSystemInfo/RebootRequired.php
  developer/engine/desktop/10.0/api/IKeymanSystemInfo/SetReboot.php
Labels: chore

#248 chore: update kmkb0035 for setup options
  knowledge-base/kb0035.md
Labels: chore
