Repository keymanapp/help.keyman.com, pull requests merged in 2020-11, with the labels that each got.

#253 fix: add KCXO statement
  developer/engine/web/14.0/reference/interface/contextExOutput.md
  developer/engine/web/14.0/reference/interface/index.php
Labels: fix

#255 chore: update parsedown
  .vscode/settings.json
  _includes/includes/ext/parsedown/Parsedown.php
  _includes/includes/ext/parsedown/ParsedownExtra.php
  _includes/md/mdhost.php
Labels: chore, production

#256 chore: sync common files
  .vscode/settings.json
  _common/KeymanHosts.php
  _common/MarkdownHost.php
  _includes/includes/ext/parsedown/LICENSE.txt
  _includes/includes/ext/parsedown/Parsedown.php
  _includes/includes/ext/parsedown/README.md
  _includes/includes/ext/parsedown/composer.json
  _includes/includes/history_utils.php
  _includes/md/mdhost.php
  composer.json
  composer.lock
  developer/engine/web/14.0/reference/interface/contextExOutput.md
  knowledge-base/index.php
Labels: chore

#257 chore: Update KMEA KMManager for 14.0
  developer/engine/android/14.0/KMManager/addKeyboard.php
  developer/engine/android/14.0/KMManager/getCurrentKeyboardInfo.php
  developer/engine/android/14.0/KMManager/getDefaultKeyboard.md
  developer/engine/android/14.0/KMManager/getDefaultKeyboard.php
  developer/engine/android/14.0/KMManager/getKeyboardInfo.php
  developer/engine/android/14.0/KMManager/getKeyboardsList.php
  developer/engine/android/14.0/KMManager/getMaySendCrashReport.md
  developer/engine/android/14.0/KMManager/index.php
  developer/engine/android/14.0/KMManager/setDefaultKeyboard.md
  developer/engine/android/14.0/KMManager/setKeyboard.php
  developer/engine/android/14.0/KMManager/setKeymanLicense.php
  developer/engine/android/14.0/KMManager/setMaySendCrashReport.md
  developer/engine/android/14.0/KMManager/showLanguageList.php
Labels: chore

#258 Move howto pages
  knowledge-base/kb0101.md
  knowledge-base/kb0102.md
  knowledge-base/kb0103.md
Labels: chore

#259 chore(common): Add link to knowledge base
  Readme.md
  _includes/includes/phone-menu.php
  _includes/includes/top-menu.php
  cdn/dev/css/template-header-footer.css
  cdn/dev/css/template.css
  cdn/dev/img/helpIconBig.png
  products/index.php
Labels: chore

#260 chore(common): Improve cross-platform compatibility of cdnrefresh.php
  cdn/cdnrefresh.php
Labels: chore
