Repository keymanapp/help.keyman.com, pull requests merged in 2020-12, with the labels that each got.

#262 modify: Change history_utils to handle /api/history 2.0
  _includes/includes/history_utils.php
  developer/14.0/main/history.php
  developer/14.0/main/index.php
  developer/engine/web/14.0/history.php
  developer/engine/web/14.0/index.php
  developer/engine/web/history.php
  developer/engine/web/web.config
  developer/version-history/index.php
  products/android/version-history/index.php
  products/desktop/version-history/index.php
  products/iphone-and-ipad/version-history/index.php
  products/linux/version-history/index.php
  products/mac/version-history/index.php
Labels: enhancement

#265 chore: Use consistent headers between API versions
  _includes/includes/history_utils.php
Labels: staging

#267 feat: add Sentry Javascript support
  .vscode/settings.json
  _includes/includes/head.php
  cdn/dev/js/bundle.min.js.map
  cdn/dev/js/sentry.bundle.5.28.0.min.js
  keyboard/bukawa/1.0/bukawa.php
  keyboard/harlatn/2.1/harlatn.php
  keyboard/inuktitut_4/4/inuktitut_4.php
  keyboard/km_cree/10/km_cree.php
  keyboard/km_ojibwasyllabics/10/km_ojibwasyllabics.php
  keyboard/km_ojicreesyllabics/10/km_ojicreesyllabics.php
  keyboard/kmhmu/1.0/kmhmu.php
  keyboard/korda/2.1/korda.php
  keyboard/korean_morse/1.1/korean_morse.php
  keyboard/laounicodebasic_on_thaikbd/1.1/laounicodebasic_on_thaikbd.php
  keyboard/rac_kashmiri/1.0/rac_kashmiri.php
  keyboard/sil_korean_morse/2.0/korean_morse.php
  keyboard/sil_korean_morse/2.0/sil_korean_morse.php
  keyboard/sil_tai_dam/2.2.1/sil_tai_dam.php
  keyboard/sil_tai_dam/2.2/sil_tai_dam.php
  keyboard/thompsonu/1.0/thompsonu.php
  keyboard/turkmen/1.3/turkmen.php
Labels: feat

#268 feat(linux): Rename onboard package
  knowledge-base/kb0103.md
  products/linux/14.0/common.php
Labels: feat, staging

#273 auto: Keyman for Windows help deployment
  products/windows/14.0/about/credits.md
  products/windows/14.0/about/history.md
  products/windows/14.0/about/requirements.md
  products/windows/14.0/about/welcome.md
  products/windows/14.0/about/whatsnew.md
  products/windows/14.0/advanced/locale_edit.md
  products/windows/14.0/advanced/proxy_config.md
  products/windows/14.0/advanced/text_services_framework.md
  products/windows/14.0/basic/help.md
  products/windows/14.0/basic/languageswitcher.md
  products/windows/14.0/basic/newways.md
  products/windows/14.0/basic/text_editor.md
  products/windows/14.0/basic/traymenu.md
  products/windows/14.0/common/adware.md
  products/windows/14.0/common/free.md
  products/windows/14.0/common/mac.md
  products/windows/14.0/common/old_version.md
  products/windows/14.0/context/fonthelper.md
  products/windows/14.0/index.md
  products/windows/14.0/start/configure_computer.md
  products/windows/14.0/start/configure_office.md
  products/windows/14.0/start/download-install_keyboard.md
  products/windows/14.0/start/download-install_keyman.md
  products/windows/14.0/start/font.md
  products/windows/14.0/start/hotkey_set.md
  products/windows/14.0/start/locale.md
  products/windows/14.0/start/rtl.md
  products/windows/14.0/start/tutorial.md
  products/windows/14.0/troubleshooting/bootstrapper.md
  products/windows/14.0/troubleshooting/excel.md
  products/windows/14.0/troubleshooting/font.md
  products/windows/14.0/troubleshooting/sigma.md
Labels: auto

#272 chore: version history link for beta
  version-history/index.php
Labels: chore

#274 fix: page-version did not handle 404 well
  .gitignore
  .vscode/settings.json
  _includes/includes/page-version.php
Labels: fix

#279 auto: Keyman for Windows help deployment
  products/windows/14.0/TODO.md
  products/windows/14.0/about/license.md
Labels: auto
