Repository keymanapp/help.keyman.com, pull requests merged in 2020-05, with the labels that each got.

#176 feat: package-version api docs
  developer/cloud/index.md
  developer/cloud/index.php
  developer/cloud/package-version/1.0/index.md
  developer/cloud/package-version/index.md
Labels: enhancement

#177 Update kmw_embedjs.php
  developer/language/reference/kmw_embedjs.php
Labels: bug

#178 fix: edit page link for kb articles
  _includes/includes/com.keyman.help.editpage.inc.php
  _includes/includes/com.keyman.help.kb.inc.php
  _includes/includes/footer.php
  _includes/tests/com.keyman.help.editpage.test.php
  knowledge-base/index.php
Labels: bug, enhancement

#181 fix(android): Fix syntax for getLatestKeyboardFileVersion
  developer/engine/android/10.0/KMManager/getLatestKeyboardFileVersion.php
  developer/engine/android/11.0/KMManager/getLatestKeyboardFileVersion.php
  developer/engine/android/12.0/KMManager/getLatestKeyboardFileVersion.php
  developer/engine/android/13.0/KMManager/getLatestKeyboardFileVersion.php
Labels: bug, help.keyman.com

#182 Add GLOBE_KEY_ACTION_ADVANCE_TO_NEXT_SYSTEM_KEYBOARD
  developer/engine/android/11.0/KMManager/getGlobeKeyAction.php
  developer/engine/android/11.0/KMManager/setGlobeKeyAction.php
  developer/engine/android/12.0/KMManager/getGlobeKeyAction.php
  developer/engine/android/12.0/KMManager/setGlobeKeyAction.php
  developer/engine/android/13.0/KMManager/getGlobeKeyAction.php
  developer/engine/android/13.0/KMManager/setGlobeKeyAction.php
Labels: enhancement, help.keyman.com
