Repository keymanapp/help.keyman.com, pull requests merged in 2021-09, with the labels that each got.

#460 fix: logo overlap on some sizes
  cdn/dev/css/template.css
Labels: fix

#465 auto: Keyman for linux help deployment
  products/linux/14.0/reference/index.php
  products/linux/14.0/reference/km-config.php
  products/linux/14.0/reference/km-kvk2ldml.php
  products/linux/14.0/reference/km-package-get.php
  products/linux/14.0/reference/km-package-install.php
  products/linux/14.0/reference/km-package-list-installed.php
  products/linux/14.0/reference/km-package-uninstall.php
Labels: auto

#466 auto: Keyman for mac help deployment
  products/mac/14.0/mac_images/video.png
  products/mac/14.0/start/install-keyboard.md
  products/mac/14.0/start/install-keyman.md
  products/mac/14.0/web.config
Labels: auto

#467 auto: Keyman for android help deployment
  products/android/14.0/android_images/dist-readme-ap.png
  products/android/14.0/android_images/dist-readme-at.png
  products/android/14.0/android_images/dist-welcome-ap.png
  products/android/14.0/android_images/dist-welcome-at.png
  products/android/14.0/android_images/dl-success-at.png
Labels: auto

#468 auto: Keyman for ios help deployment
  products/iphone-and-ipad/14.0/basic/installing-custom-keyboards.md
  products/iphone-and-ipad/14.0/ios_images/add-keyboard-i4.png
  products/iphone-and-ipad/14.0/ios_images/add-keyboard-i5.png
  products/iphone-and-ipad/14.0/start/installing-keyboards.md
Labels: auto

#469 auto: Keyman for windows help deployment
  products/windows/14.0/basic/config_tasks/config_menu.md
  products/windows/14.0/basic/config_tasks/hotkeys_tab.md
  products/windows/14.0/basic/config_tasks/keyboards_tab.md
  products/windows/14.0/basic/config_tasks/options_tab.md
  products/windows/14.0/basic/config_tasks/support_tab.md
  products/windows/14.0/basic/engine_tasks/uninstall.md
  products/windows/14.0/basic/engine_tasks/update.md
  products/windows/14.0/basic/keyboard_tasks/disable_keyboard.md
  products/windows/14.0/basic/keyboard_tasks/enable_keyboard.md
  products/windows/14.0/basic/keyboard_tasks/uninstall_keyboard.md
  products/windows/14.0/basic/languageswitcher.md
  products/windows/14.0/basic/newways.md
  products/windows/14.0/basic/text_editor.md
  products/windows/14.0/basic/toolbox_tasks/charactermap.md
  products/windows/14.0/basic/toolbox_tasks/fonthelper.md
  products/windows/14.0/basic/toolbox_tasks/osk.md
  products/windows/14.0/basic/toolbox_tasks/toolbox.md
  products/windows/14.0/basic/toolbox_tasks/usage.md
  products/windows/14.0/basic/traymenu.md
  products/windows/14.0/common/editions.md
  products/windows/14.0/context/charactermap.md
  products/windows/14.0/context/configuration_hotkeys.md
  products/windows/14.0/context/configuration_keyboards.md
  products/windows/14.0/context/configuration_options.md
  products/windows/14.0/context/configuration_support.md
  products/windows/14.0/context/downloadkeyboard.md
  products/windows/14.0/context/fonthelper.md
  products/windows/14.0/context/installkeyboard.md
  products/windows/14.0/context/manualactivate.md
  products/windows/14.0/context/onlineupdate.md
  products/windows/14.0/context/onscreenkeyboard.md
  products/windows/14.0/context/osk_keyboard.md
  products/windows/14.0/context/osk_usage.md
  products/windows/14.0/context/proxyconfiguration.md
  products/windows/14.0/context/selectlanguage.md
  products/windows/14.0/context/traymenu.md
  products/windows/14.0/context/tsactivate.md
  products/windows/14.0/context/tutorial.md
  products/windows/14.0/context/welcome.md
  products/windows/14.0/desktop_images/toolbox-hints.png
  products/windows/14.0/desktop_images/usage-dynamic.png
  products/windows/14.0/desktop_images/usage-help.png
  products/windows/14.0/desktop_images/usage-none.png
  products/windows/14.0/desktop_images/usage-osk.png
  products/windows/14.0/desktop_images/usage-static.png
  products/windows/14.0/desktop_images/usage.png
  products/windows/14.0/start/configure_computer.md
  products/windows/14.0/start/download-install_keyboard.md
  products/windows/14.0/start/download-install_keyman.md
Labels: auto

#459 fix: edit product help links
  _includes/includes/com.keyman.help.editpage.inc.php
Labels: fix

#462 docs: Add KVS keyboard property
  developer/engine/web/15.0/reference/keyboard_properties.md
  developer/engine/web/15.0/reference/keyboard_properties.php
Labels: docs

#471 auto: Keyman for android help deployment
  products/android/15.0/android_images/settings-screen-at.png
Labels: auto

#472 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/ios_images/add-keyboard-i4.png
  products/iphone-and-ipad/15.0/ios_images/add-keyboard-i5.png
  products/iphone-and-ipad/15.0/start/installing-keyboards.md
Labels: auto

#473 auto: Keyman for windows help deployment
  products/windows/15.0/basic/config_tasks/config_menu.md
  products/windows/15.0/basic/config_tasks/hotkeys_tab.md
  products/windows/15.0/basic/config_tasks/keyboards_tab.md
  products/windows/15.0/basic/config_tasks/options_tab.md
  products/windows/15.0/basic/config_tasks/support_tab.md
  products/windows/15.0/basic/engine_tasks/uninstall.md
  products/windows/15.0/basic/engine_tasks/update.md
  products/windows/15.0/basic/keyboard_tasks/disable_keyboard.md
  products/windows/15.0/basic/keyboard_tasks/enable_keyboard.md
  products/windows/15.0/basic/keyboard_tasks/uninstall_keyboard.md
  products/windows/15.0/basic/languageswitcher.md
  products/windows/15.0/basic/newways.md
  products/windows/15.0/basic/text_editor.md
  products/windows/15.0/basic/toolbox_tasks/charactermap.md
  products/windows/15.0/basic/toolbox_tasks/fonthelper.md
  products/windows/15.0/basic/toolbox_tasks/osk.md
  products/windows/15.0/basic/toolbox_tasks/toolbox.md
  products/windows/15.0/basic/toolbox_tasks/usage.md
  products/windows/15.0/basic/traymenu.md
  products/windows/15.0/context/charactermap.md
  products/windows/15.0/context/configuration_hotkeys.md
  products/windows/15.0/context/configuration_keyboards.md
  products/windows/15.0/context/configuration_options.md
  products/windows/15.0/context/configuration_support.md
  products/windows/15.0/context/downloadkeyboard.md
  products/windows/15.0/context/fonthelper.md
  products/windows/15.0/context/installkeyboard.md
  products/windows/15.0/context/manualactivate.md
  products/windows/15.0/context/onlineupdate.md
  products/windows/15.0/context/onscreenkeyboard.md
  products/windows/15.0/context/osk_keyboard.md
  products/windows/15.0/context/osk_usage.md
  products/windows/15.0/context/proxyconfiguration.md
  products/windows/15.0/context/selectlanguage.md
  products/windows/15.0/context/traymenu.md
  products/windows/15.0/context/tutorial.md
  products/windows/15.0/context/welcome.md
  products/windows/15.0/desktop_images/toolbox-hints.png
  products/windows/15.0/desktop_images/usage-dynamic.png
  products/windows/15.0/desktop_images/usage-help.png
  products/windows/15.0/desktop_images/usage-none.png
  products/windows/15.0/desktop_images/usage-osk.png
  products/windows/15.0/desktop_images/usage-static.png
  products/windows/15.0/desktop_images/usage.png
  products/windows/15.0/start/configure_computer.md
  products/windows/15.0/start/download-install_keyboard.md
  products/windows/15.0/start/download-install_keyman.md
Labels: auto

#457 docs: Document KMManager.applyKeyboardHeight()
  developer/engine/android/15.0/KMManager/applyKeyboardHeight.md
  developer/engine/android/15.0/KMManager/getKeyboardHeight.php
  developer/engine/android/15.0/KMManager/index.php
Labels: docs

#478 auto: Keyman for linux help deployment
  products/linux/15.0/index.md
Labels: auto

#479 auto: Keyman for mac help deployment
  products/mac/15.0/start/install-keyman.md
Labels: auto
