Repository keymanapp/help.keyman.com, pull requests merged in 2021-02, with the labels that each got.

#307 fix: Convert Linux help to markdown
  products/linux/14.0/about/history.md
  products/linux/14.0/about/index.md
  products/linux/14.0/about/welcome.md
  products/linux/14.0/about/whatsnew.md
  products/linux/14.0/common.php
  products/linux/14.0/common/index.md
  products/linux/14.0/guide/index.php
  products/linux/14.0/guide/installing-keyboard.php
  products/linux/14.0/index.md
  products/linux/14.0/index.php
  products/linux/14.0/linux_images/add-input-source-khmer-angkor.png
  products/linux/14.0/linux_images/add-input-source-khmer.png
  products/linux/14.0/linux_images/add-input-source.png
  products/linux/14.0/linux_images/download-khmer-angkor.png
  products/linux/14.0/linux_images/km-config-khmer-angkor.png
  products/linux/14.0/linux_images/km-config.png
  products/linux/14.0/linux_images/mobile viewport.png
  products/linux/14.0/linux_images/onboard.png
  products/linux/14.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/14.0/linux_images/region-and-language.png
  products/linux/14.0/linux_images/region-language-khmer-angkor.png
  products/linux/14.0/linux_images/search-khmer-angkor.png
  products/linux/14.0/start/index.md
  products/linux/14.0/start/installing-keyboard.md
Labels: fix

#309 auto: Keyman for Windows help deployment
  products/windows/14.0/index.md
Labels: auto

#311 fix(android): Add content for KMManager lexical model APIs
  developer/engine/android/14.0/KMManager/addLexicalModel.md
  developer/engine/android/14.0/KMManager/deregisterLexicalModel.md
  developer/engine/android/14.0/KMManager/getAssociatedLexicalModel.md
  developer/engine/android/14.0/KMManager/getLanguageCorrectionPreferenceKey.md
  developer/engine/android/14.0/KMManager/getLanguagePredictionPreferenceKey.md
  developer/engine/android/14.0/KMManager/index.php
  developer/engine/android/14.0/KMManager/registerAssociatedLexicalModel.md
  developer/engine/android/14.0/KMManager/registerLexicalModel.md
Labels: docs, fix

#317 fix(mac): Reorganize mac help
  products/mac/14.0/about/history.md
  products/mac/14.0/about/index.md
  products/mac/14.0/about/welcome.md
  products/mac/14.0/about/whatsnew.md
  products/mac/14.0/basic/config/index.md
  products/mac/14.0/basic/config/keyboards.md
  products/mac/14.0/basic/config/options.md
  products/mac/14.0/basic/config/support.md
  products/mac/14.0/basic/index.md
  products/mac/14.0/common/adware.md
  products/mac/14.0/common/bug.md
  products/mac/14.0/common/free.md
  products/mac/14.0/common/index.md
  products/mac/14.0/common/keyboards.md
  products/mac/14.0/common/os.md
  products/mac/14.0/common/osk.md
  products/mac/14.0/common/requirements.md
  products/mac/14.0/common/support.md
  products/mac/14.0/help/configuration.md
  products/mac/14.0/index.md
  products/mac/14.0/mac_images/add.png
  products/mac/14.0/mac_images/add_keyman.png
  products/mac/14.0/mac_images/apple_menu.png
  products/mac/14.0/mac_images/go_to_folder.png
  products/mac/14.0/mac_images/help_button.png
  products/mac/14.0/mac_images/icon-fonts.png
  products/mac/14.0/mac_images/icon-help.png
  products/mac/14.0/mac_images/icon-intro.png
  products/mac/14.0/mac_images/icon-keyman.png
  products/mac/14.0/mac_images/icon-osk.png
  products/mac/14.0/mac_images/icon-unicode.png
  products/mac/14.0/mac_images/information_button.png
  products/mac/14.0/mac_images/input_menu.png
  products/mac/14.0/mac_images/keyboards_menu.png
  products/mac/14.0/mac_images/keyman_config.png
  products/mac/14.0/mac_images/keyman_install.png
  products/mac/14.0/mac_images/keyman_menu_config.png
  products/mac/14.0/mac_images/menu_bar.png
  products/mac/14.0/mac_images/menu_bar_keyman.png
  products/mac/14.0/mac_images/osk_amharic.png
  products/mac/14.0/mac_images/privacy_accessibility.png
  products/mac/14.0/mac_images/privacy_files_and_folders.png
  products/mac/14.0/mac_images/privacy_input_monitoring.png
  products/mac/14.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/14.0/mac_images/remove.png
  products/mac/14.0/mac_images/remove_button.png
  products/mac/14.0/mac_images/remove_keyman.png
  products/mac/14.0/mac_images/system_preferences.png
  products/mac/14.0/start/install-keyboard.md
  products/mac/14.0/start/install-keyman.md
  products/mac/14.0/start/tutorial.md
  products/mac/14.0/troubleshooting/configure-security.md
  products/mac/14.0/troubleshooting/index.md
  products/mac/14.0/troubleshooting/uninstall-keyman.md
Labels: fix

#318 auto: Keyman for windows help deployment
  products/windows/15.0/TODO.md
  products/windows/15.0/about/index.md
  products/windows/15.0/advanced/locale_edit.md
  products/windows/15.0/basic/config/index.md
  products/windows/15.0/basic/config/options.md
  products/windows/15.0/basic/make-taskbar-icon-visible.md
  products/windows/15.0/basic/select-keyboard.md
  products/windows/15.0/basic/toolbox/character-map.md
  products/windows/15.0/common/index.md
  products/windows/15.0/context/index.md
  products/windows/15.0/index.md
  products/windows/15.0/start/tutorial.md
  products/windows/15.0/troubleshooting/font.md
  products/windows/15.0/troubleshooting/hidden.md
  products/windows/15.0/troubleshooting/index.md
Labels: auto
