Repository keymanapp/help.keyman.com, pull requests merged in 2021-01, with the labels that each got.

#282 fix: github guide link typos
  developer/keyboards/github/step-1.md
  developer/keyboards/github/step-3.md
Labels: fix

#283 fix: keyboard starter guide broken link
  developer/keyboards/starter/index.php
Labels: fix

#284 chore: github action php 7.4 dependency
  .github/workflows/ci.yml
Labels: chore

#278 docs: Configure mac security
  knowledge-base/kb0104.md
Labels: docs

#292 chore: reworks KMW examples to use init's Promise
  developer/engine/web/14.0/guide/examples/__auto-control.php
  developer/engine/web/14.0/guide/examples/__control-by-control.php
  developer/engine/web/14.0/guide/examples/__first-example.php
  developer/engine/web/14.0/guide/examples/__full-manual-control.php
  developer/engine/web/14.0/guide/examples/automatic-control.php
  developer/engine/web/14.0/guide/examples/control-by-control.php
  developer/engine/web/14.0/guide/examples/full-manual-control.php
  developer/engine/web/14.0/guide/examples/js/laokeys_load.js
  developer/engine/web/14.0/guide/examples/js/unified_loader.js
  developer/engine/web/14.0/guide/examples/manual-control.php
  developer/engine/web/14.0/guide/get-started.php
Labels: chore

#293 fix: sentry environment
  _includes/includes/head.php
Labels: fix

#290 change: reworks KMW examples to use init's Promise
  developer/engine/web/13.0/guide/examples/__auto-control.php
  developer/engine/web/13.0/guide/examples/__control-by-control.php
  developer/engine/web/13.0/guide/examples/__first-example.php
  developer/engine/web/13.0/guide/examples/__full-manual-control.php
  developer/engine/web/13.0/guide/examples/automatic-control.php
  developer/engine/web/13.0/guide/examples/control-by-control.php
  developer/engine/web/13.0/guide/examples/full-manual-control.php
  developer/engine/web/13.0/guide/examples/js/laokeys_load.js
  developer/engine/web/13.0/guide/examples/js/unified_loader.js
  developer/engine/web/13.0/guide/examples/manual-control.php
  developer/engine/web/13.0/guide/get-started.php
Labels: chore

#294 chore: Update browser icons
  cdn/dev/img/icon-engineweb.png
  cdn/dev/img/icon-web.png
Labels: chore

#296 chore: Uppdate KMEA system keyboard guide
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/emulator-800wi.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/emulator.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/main-activity-layout-800wi.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/main-activity-layout.png
  developer/engine/android/14.0/guides/system-keyboard/index.php
Labels: chore, docs

#295 chore: Update KMEA in-app guide for package files
  cdn/dev/img/engine/android/14.0/guides/in-app/android-emulator-tamil-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-emulator-tamil.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-adding-keyboard-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-adding-keyboard.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-assets-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-assets.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-starting-debug-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/android-studio-starting-debug.png
  cdn/dev/img/engine/android/14.0/guides/in-app/compiled-keyboard-file-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/compiled-keyboard-file.png
  cdn/dev/img/engine/android/14.0/guides/in-app/copy-keyboard-file-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/copy-keyboard-file.png
  cdn/dev/img/engine/android/14.0/guides/in-app/open-containing-folder-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/open-containing-folder.png
  cdn/dev/img/engine/android/14.0/guides/in-app/touch-layout-800wi.png
  cdn/dev/img/engine/android/14.0/guides/in-app/touch-layout.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/emulator-800wi.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/emulator.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/main-activity-layout-800wi.png
  cdn/dev/img/engine/android/14.0/guides/system-keyboard/main-activity-layout.png
  developer/engine/android/14.0/guides/in-app/index.php
  developer/engine/android/14.0/guides/system-keyboard/index.php
Labels: chore, docs

#299 chore: hosts and header maintenance
  _common/KeymanHosts.php
  _includes/includes/head.php
Labels: chore

#298 auto: Keyman for Windows help deployment
  products/windows/14.0/TODO.md
  products/windows/14.0/advanced/locale_edit.md
  products/windows/14.0/basic/config_tasks/hotkeys_tab.md
  products/windows/14.0/basic/config_tasks/keyboards_tab.md
  products/windows/14.0/basic/config_tasks/options_tab.md
  products/windows/14.0/basic/config_tasks/support_tab.md
  products/windows/14.0/basic/keyboard_tasks/enable_keyboard.md
  products/windows/14.0/basic/keyboard_tasks/uninstall_keyboard.md
  products/windows/14.0/basic/languageswitcher.md
  products/windows/14.0/basic/text_editor.md
  products/windows/14.0/basic/toolbox_tasks/charactermap.md
  products/windows/14.0/basic/toolbox_tasks/fonthelper.md
  products/windows/14.0/basic/toolbox_tasks/osk.md
  products/windows/14.0/basic/toolbox_tasks/toolbox.md
  products/windows/14.0/basic/traymenu.md
  products/windows/14.0/common/os.md
  products/windows/14.0/start/configure_computer.md
Labels: auto

#305 auto: Keyman for Windows help deployment
  products/windows/14.0/about/index.md
  products/windows/14.0/advanced/locale_edit.md
  products/windows/14.0/basic/select-keyboard.md
  products/windows/14.0/common/index.md
  products/windows/14.0/context/index.md
  products/windows/14.0/troubleshooting/hidden.md
  products/windows/14.0/troubleshooting/index.md
Labels: auto
