Repository keymanapp/help.keyman.com, pull requests merged in 2021-07, with the labels that each got.

#435 chore: Remove usage of loader script
  developer/engine/web/10.0/guide/adding-keyboards.php
  developer/engine/web/11.0/guide/adding-keyboards.php
  developer/engine/web/12.0/guide/adding-keyboards.php
  developer/engine/web/13.0/guide/adding-keyboards.php
  developer/engine/web/14.0/guide/adding-keyboards.php
  developer/engine/web/15.0/guide/adding-keyboards.php
Labels: chore, docs

#442 auto: Keyman for linux help deployment
  products/linux/15.0/index.md
  products/linux/15.0/reference/index.md
  products/linux/15.0/reference/km-config.md
  products/linux/15.0/reference/km-kvk2ldml.md
  products/linux/15.0/reference/km-package-get.md
  products/linux/15.0/reference/km-package-install.md
  products/linux/15.0/reference/km-package-list-installed.md
  products/linux/15.0/reference/km-package-uninstall.md
Labels: auto

#444 docs: improve virtual key documentation
  developer/language/guide/index.php
  developer/language/guide/rules.md
  developer/language/guide/virtual-keys.md
Labels: docs

#446 docs: add kmconvert 15.0 details
  developer/15.0/context/kmconvert.md
Labels: docs

#443 docs(ios/engine): ios spacebarText 🌌
  developer/engine/iphone-and-ipad/15.0/LanguageResource/index.md
  developer/engine/iphone-and-ipad/15.0/LanguageResource/index.php
  developer/engine/iphone-and-ipad/15.0/Manager/index.md
  developer/engine/iphone-and-ipad/15.0/Manager/index.php
  developer/engine/iphone-and-ipad/15.0/Manager/spacebarText.md
Labels: docs

#449 feat: Document KeymanWeb API calls returning a promise
  developer/engine/web/15.0/reference/core/addKeyboards.md
  developer/engine/web/15.0/reference/core/addKeyboardsForLanguage.md
  developer/engine/web/15.0/reference/core/index.php
  developer/engine/web/15.0/reference/core/init.md
  developer/engine/web/15.0/reference/keyboard_registration_errors.md
Labels: feat

#448 fix: link checker was skipping all links
  _includes/includes/head.php
Labels: fix

#451 docs: tweak instructions on how to drag files to github
  developer/keyboards/github/step-2.md
Labels: docs

#452 docs: note on use() and match behavior
  developer/language/guide/groups.md
  developer/language/guide/groups.php
  developer/language/reference/match.md
  developer/language/reference/match.php
  developer/language/reference/use.md
  developer/language/reference/use.php
Labels: docs
