Repository keymanapp/help.keyman.com, pull requests merged in 2021-05, with the labels that each got.

#388 chore: rework history links for 14.0 release
  version-history/index.md
  version-history/index.php
Labels: docs

#391 auto: Keyman for mac help deployment
  products/mac/15.0/about/requirements.md
Labels: auto

#389 docs: add new totalDownloads property
  developer/cloud/search/2.0/index.md
Labels: docs

#398 docs: add keyboard copyright advice
  developer/keyboards/_shared/organize-folder-structure.php
  developer/keyboards/github/step-0.md
  developer/language/guide/us-english.php
Labels: docs

#399 auto: Keyman for mac help deployment
  products/mac/15.0/mac_images/video.png
  products/mac/15.0/start/install-keyboard.md
  products/mac/15.0/start/install-keyman.md
Labels: auto

#400 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
Labels: auto

#401 auto: Keyman for windows help deployment
  products/windows/15.0/start/download-and-install-keyboard.md
Labels: auto

#406 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/history.md
  products/iphone-and-ipad/15.0/index.md
Labels: auto

#410 fix: Broken image links in knowledge base article
  knowledge-base/kb0040.md
Labels: fix
