Repository keymanapp/help.keyman.com, pull requests merged in 2021-03, with the labels that each got.

#323 auto: Keyman for mac help deployment
  products/mac/14.0/about/history.md
  products/mac/14.0/about/index.md
  products/mac/14.0/about/requirements.md
  products/mac/14.0/about/welcome.md
  products/mac/14.0/about/whatsnew.md
  products/mac/14.0/basic/config/index.md
  products/mac/14.0/basic/config/keyboards.md
  products/mac/14.0/basic/config/options.md
  products/mac/14.0/basic/config/support.md
  products/mac/14.0/basic/index.md
  products/mac/14.0/common/adware.md
  products/mac/14.0/common/bug.md
  products/mac/14.0/common/free.md
  products/mac/14.0/common/index.md
  products/mac/14.0/common/keyboards.md
  products/mac/14.0/common/os.md
  products/mac/14.0/common/osk.md
  products/mac/14.0/common/requirements.md
  products/mac/14.0/common/support.md
  products/mac/14.0/index.md
  products/mac/14.0/mac_images/add.png
  products/mac/14.0/mac_images/add_keyman.png
  products/mac/14.0/mac_images/apple_menu.png
  products/mac/14.0/mac_images/go_to_folder.png
  products/mac/14.0/mac_images/help_button.png
  products/mac/14.0/mac_images/icon-fonts.png
  products/mac/14.0/mac_images/icon-help.png
  products/mac/14.0/mac_images/icon-intro.png
  products/mac/14.0/mac_images/icon-keyman.png
  products/mac/14.0/mac_images/icon-osk.png
  products/mac/14.0/mac_images/icon-unicode.png
  products/mac/14.0/mac_images/information_button.png
  products/mac/14.0/mac_images/input_menu.png
  products/mac/14.0/mac_images/keyboards_menu.png
  products/mac/14.0/mac_images/keyman_config.png
  products/mac/14.0/mac_images/keyman_install.png
  products/mac/14.0/mac_images/keyman_menu_config.png
  products/mac/14.0/mac_images/menu_bar.png
  products/mac/14.0/mac_images/menu_bar_keyman.png
  products/mac/14.0/mac_images/osk_amharic.png
  products/mac/14.0/mac_images/privacy_accessibility.png
  products/mac/14.0/mac_images/privacy_files_and_folders.png
  products/mac/14.0/mac_images/privacy_input_monitoring.png
  products/mac/14.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/14.0/mac_images/remove.png
  products/mac/14.0/mac_images/remove_button.png
  products/mac/14.0/mac_images/remove_keyman.png
  products/mac/14.0/mac_images/system_preferences.png
  products/mac/14.0/start/index.md
  products/mac/14.0/start/install-keyboard.md
  products/mac/14.0/start/install-keyman.md
  products/mac/14.0/start/tutorial.md
  products/mac/14.0/troubleshooting/configure-security.md
  products/mac/14.0/troubleshooting/index.md
  products/mac/14.0/troubleshooting/uninstall-keyman.md
Labels: auto

#326 auto: Keyman for linux help deployment
  products/linux/14.0/about/history.md
  products/linux/14.0/about/index.md
  products/linux/14.0/about/welcome.md
  products/linux/14.0/about/whatsnew.md
  products/linux/14.0/common/index.md
  products/linux/14.0/index.md
  products/linux/14.0/linux_images/add-input-source-khmer-angkor.png
  products/linux/14.0/linux_images/add-input-source-khmer.png
  products/linux/14.0/linux_images/add-input-source.png
  products/linux/14.0/linux_images/download-khmer-angkor.png
  products/linux/14.0/linux_images/km-config-khmer-angkor.png
  products/linux/14.0/linux_images/km-config.png
  products/linux/14.0/linux_images/mobile viewport.png
  products/linux/14.0/linux_images/onboard.png
  products/linux/14.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/14.0/linux_images/region-and-language.png
  products/linux/14.0/linux_images/region-language-khmer-angkor.png
  products/linux/14.0/linux_images/search-khmer-angkor.png
  products/linux/14.0/start/index.md
  products/linux/14.0/start/installing-keyboard.md
Labels: auto

#330 docs(linux): Update documentation for caps lock
  developer/language/reference/caps.php
Labels: docs, help.keyman.com

#331 docs: expansions and CasedKeys store
  developer/language/guide/expansions.md
  developer/language/guide/history.md
  developer/language/guide/index.php
  developer/language/reference/casedkeys.md
  developer/language/reference/index.php
Labels: docs

#333 docs: Add whatsnew to Keyman Engine for Android
  cdn/dev/css/prism.css
  cdn/dev/js/prism.js
  developer/engine/android/14.0/index.php
  developer/engine/android/14.0/whatsnew.md
Labels: docs

#334 auto: Keyman for android help deployment
  products/android/14.0/about/whatsnew.md
Labels: auto

#337 chore: add redirect support to mdhost
  _includes/md/mdhost.php
Labels: chore

#338 chore: add redirect support to MarkdownHost 🍒
  _common/MarkdownHost.php
Labels: cherry-pick, chore

#343 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
Labels: auto

#339 chore: markdown - add comment block
  _common/MarkdownHost.php
Labels: chore

#346 docs: add example for final group
  developer/language/guide/groups.php
Labels: docs

#347 auto: Keyman for windows help deployment
  products/windows/14.0/context/base-keyboard.md
  products/windows/14.0/context/change-hotkey.md
  products/windows/14.0/context/configuration-hotkeys.md
  products/windows/14.0/context/configuration-keepintouch.md
  products/windows/14.0/context/configuration-keyboards.md
  products/windows/14.0/context/configuration-options.md
  products/windows/14.0/context/configuration-support.md
  products/windows/14.0/context/download-keyboard.md
  products/windows/14.0/context/index.md
  products/windows/14.0/context/install-keyboard-language.md
  products/windows/14.0/context/install-keyboard.md
  products/windows/14.0/context/keyman.md
  products/windows/14.0/context/online-update.md
  products/windows/14.0/context/proxy-configuration.md
  products/windows/14.0/context/text-editor.md
  products/windows/14.0/context/toolbox-charactermap.md
  products/windows/14.0/context/toolbox-fonthelper.md
  products/windows/14.0/context/toolbox-onscreenkeyboard.md
  products/windows/14.0/context/tray-menu.md
Labels: auto

#349 fix: markdown header parser was not parsing some headers
  _common/MarkdownHost.php
Labels: fix

#350 fix: markdown header parser was not parsing some headers 🍒
  _includes/md/mdhost.php
Labels: fix

#351 auto: Keyman for windows help deployment
  products/windows/14.0/about/whatsnew.md
Labels: auto

#353 feat: add isKeyboardLoaded
  developer/engine/android/14.0/KMManager/getDefaultKeyboard.md
  developer/engine/android/14.0/KMManager/getMaySendCrashReport.md
  developer/engine/android/14.0/KMManager/index.php
  developer/engine/android/14.0/KMManager/isKeyboardLoaded.md
  developer/engine/android/14.0/KMManager/setMaySendCrashReport.md
Labels: docs

#354 auto: Keyman for windows help deployment
  products/windows/14.0/context/index.md
  products/windows/14.0/desktop_images/osk_keyboard.png
  products/windows/14.0/desktop_images/tab-keyboards.png
  products/windows/14.0/desktop_images/tab-layout.png
  products/windows/14.0/troubleshooting/bootstrapper.md
  products/windows/14.0/troubleshooting/sigma.md
Labels: auto

#355 chore: minKeymanVersion spec tweak
  developer/cloud/keyboard_info/1.0/index.php
Labels: chore

#358 chore: B14S8 master staging
  developer/cloud/keyboard_info/1.0/index.php
Labels: chore

#360 auto: Keyman for ios help deployment
  products/iphone-and-ipad/14.0/basic/index.md
  products/iphone-and-ipad/14.0/basic/installing-custom-keyboards-dictionaries.md
  products/iphone-and-ipad/14.0/basic/sharing-keyboards.md
  products/iphone-and-ipad/14.0/index.md
  products/iphone-and-ipad/14.0/ios_images/keyboard-search-1.png
  products/iphone-and-ipad/14.0/ios_images/keyboard-search-2.png
  products/iphone-and-ipad/14.0/ios_images/keyboard-search-3.png
  products/iphone-and-ipad/14.0/ios_images/keyboard-search-4.png
  products/iphone-and-ipad/14.0/ios_images/keyboard-search-5.png
  products/iphone-and-ipad/14.0/ios_images/package-install-1.png
  products/iphone-and-ipad/14.0/ios_images/package-install-2.png
  products/iphone-and-ipad/14.0/ios_images/package-install-3.png
  products/iphone-and-ipad/14.0/ios_images/package-install-4.png
  products/iphone-and-ipad/14.0/ios_images/package-install-5.png
  products/iphone-and-ipad/14.0/start/index.md
  products/iphone-and-ipad/14.0/start/installing-packages.md
  products/iphone-and-ipad/14.0/start/searching-for-keyboards.md
Labels: auto

#361 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/whatsnew.md
  products/iphone-and-ipad/15.0/basic/index.md
  products/iphone-and-ipad/15.0/basic/installing-custom-keyboards-dictionaries.md
  products/iphone-and-ipad/15.0/basic/sharing-keyboards.md
  products/iphone-and-ipad/15.0/index.md
  products/iphone-and-ipad/15.0/ios_images/keyboard-search-1.png
  products/iphone-and-ipad/15.0/ios_images/keyboard-search-2.png
  products/iphone-and-ipad/15.0/ios_images/keyboard-search-3.png
  products/iphone-and-ipad/15.0/ios_images/keyboard-search-4.png
  products/iphone-and-ipad/15.0/ios_images/keyboard-search-5.png
  products/iphone-and-ipad/15.0/ios_images/package-install-1.png
  products/iphone-and-ipad/15.0/ios_images/package-install-2.png
  products/iphone-and-ipad/15.0/ios_images/package-install-3.png
  products/iphone-and-ipad/15.0/ios_images/package-install-4.png
  products/iphone-and-ipad/15.0/ios_images/package-install-5.png
  products/iphone-and-ipad/15.0/start/index.md
  products/iphone-and-ipad/15.0/start/installing-packages.md
  products/iphone-and-ipad/15.0/start/searching-for-keyboards.md
Labels: auto

#362 auto: Keyman for windows help deployment
  products/windows/15.0/about/whatsnew.md
  products/windows/15.0/context/base-keyboard.md
  products/windows/15.0/context/change-hotkey.md
  products/windows/15.0/context/configuration-hotkeys.md
  products/windows/15.0/context/configuration-keepintouch.md
  products/windows/15.0/context/configuration-keyboards.md
  products/windows/15.0/context/configuration-options.md
  products/windows/15.0/context/configuration-support.md
  products/windows/15.0/context/download-keyboard.md
  products/windows/15.0/context/index.md
  products/windows/15.0/context/install-keyboard-language.md
  products/windows/15.0/context/install-keyboard.md
  products/windows/15.0/context/keyman.md
  products/windows/15.0/context/online-update.md
  products/windows/15.0/context/proxy-configuration.md
  products/windows/15.0/context/text-editor.md
  products/windows/15.0/context/toolbox-charactermap.md
  products/windows/15.0/context/toolbox-fonthelper.md
  products/windows/15.0/context/toolbox-onscreenkeyboard.md
  products/windows/15.0/context/tray-menu.md
  products/windows/15.0/desktop_images/osk_keyboard.png
  products/windows/15.0/desktop_images/tab-keyboards.png
  products/windows/15.0/desktop_images/tab-layout.png
  products/windows/15.0/troubleshooting/bootstrapper.md
  products/windows/15.0/troubleshooting/sigma.md
Labels: auto

#364 chore: Revision of the iOS 14.0 engine guide
  cdn/dev/img/engine/ios/14.0/guides/in-app/find-package-via-developer-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/find-package-via-developer.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/fully-imported-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/fully-imported.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/import-keyboard-in-xcode-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/import-keyboard-in-xcode.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/ios-simulator-tamil-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/ios-simulator-tamil.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-layout-in-developer-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-layout-in-developer.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-load-code-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-load-code.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-resource-finder-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/keyboard-resource-finder.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/package-file-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/package-file.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/package-import.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/xcode-package-import-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/in-app/xcode-package-import.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/developer-add-css-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/developer-add-css.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/set-sys-kbd-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/set-sys-kbd.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/sys-kbd-active-800wi.png
  cdn/dev/img/engine/ios/14.0/guides/system-keyboard/sys-kbd-active.png
  developer/engine/iphone-and-ipad/14.0/guides/in-app/index.php
  developer/engine/iphone-and-ipad/14.0/guides/system-keyboard/index.php
Labels: chore, docs
