Repository keymanapp/help.keyman.com, pull requests merged in 2021-11, with the labels that each got.

#486 auto: Keyman for android help deployment
  products/android/15.0/basic/uninstalling-keyboards.md
Labels: auto

#485 chore: fix typo
  developer/language/reference/_nul.php
Labels: bug

#487 feat: u_xxxx_yyyy key identifiers
  developer/15.0/context/keyboard-editor.php
  developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.php
  developer/engine/web/15.0/reference/layoutspec.php
  developer/language/guide/history.md
  developer/language/guide/virtual-keys.md
Labels: feat

#490 auto: Keyman for linux help deployment
  products/linux/14.0/reference/km-config.md
Labels: auto
