Repository keymanapp/help.keyman.com, pull requests merged in 2021-06, with the labels that each got.

#411 chore: https for dev hosts
  _common/KeymanHosts.php
Labels: chore

#413 chore: Add link to YouTube channel
  developer/14.0/guides/intro.php
  developer/videos/index.md
Labels: docs

#414 auto: Keyman for linux help deployment
  products/linux/15.0/about/whatsnew.md
  products/linux/15.0/linux_images/video.png
Labels: auto

#415 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
  products/android/15.0/android_images/video.png
Labels: auto

#416 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/whatsnew.md
  products/iphone-and-ipad/15.0/ios_images/video.png
Labels: auto

#417 auto: Keyman for windows help deployment
  products/windows/15.0/about/whatsnew.md
  products/windows/15.0/desktop_images/video.png
Labels: auto

#418 docs: command line reference
  developer/14.0/context/kmconvert.md
  developer/14.0/context/kmconvert.php
  developer/14.0/guides/command-line.md
  developer/14.0/guides/index.php
Labels: docs

#422 fix: curl needs -L
  developer/14.0/guides/command-line.md
Labels: fix

#423 fix: km-package-install -f param
  developer/14.0/guides/command-line.md
Labels: fix

#421 auto: Keyman for mac help deployment
  products/mac/15.0/about/whatsnew.md
Labels: auto

#424 fix: update automerge action version to 0.14.2
  .github/workflows/auto-merge-keyman-server-pr.yml
Labels: fix

#426 auto: Keyman for linux help deployment
  products/linux/15.0/reference/km-config.md
  products/linux/15.0/reference/km-kvk2ldml.md
  products/linux/15.0/reference/km-package-get.md
  products/linux/15.0/reference/km-package-install.md
  products/linux/15.0/reference/km-package-list-installed.md
  products/linux/15.0/reference/km-package-uninstall.md
Labels: auto

#427 docs: Clarify init options
  developer/engine/web/15.0/reference/core/init.php
Labels: docs

#428 auto: Keyman for linux help deployment
  products/linux/15.0/reference/km-config.md
Labels: auto

#429 chore: fix keyboard_info displayName and languageName field requirement
  developer/cloud/keyboard_info/1.0/index.php
Labels: chore

#431 docs: spacebarText for Android Engine
  developer/engine/android/15.0/KMManager/getSpacebarText.md
  developer/engine/android/15.0/KMManager/index.php
  developer/engine/android/15.0/KMManager/setKeyboard.md
  developer/engine/android/15.0/KMManager/setKeyboard.php
  developer/engine/android/15.0/KMManager/setSpacebarText.md
Labels: docs

#432 docs(web): add spacebarText controls
  developer/engine/web/15.0/index.php
  developer/engine/web/15.0/reference/core/addKeyboards.md
  developer/engine/web/15.0/reference/core/addKeyboards.php
  developer/engine/web/15.0/reference/core/init.md
  developer/engine/web/15.0/reference/core/init.php
  developer/engine/web/15.0/whats-new.md
Labels: docs

#433 auto: Keyman for linux help deployment
  products/linux/15.0/about/history.md
  products/linux/15.0/about/index.md
  products/linux/15.0/about/welcome.md
  products/linux/15.0/about/whatsnew.md
  products/linux/15.0/common/index.md
  products/linux/15.0/index.md
  products/linux/15.0/reference/index.md
  products/linux/15.0/start/index.md
  products/linux/15.0/start/installing-keyboard.md
Labels: auto

#434 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
  products/android/15.0/android_images/settings-screen-ap.png
  products/android/15.0/android_images/spacebar-caption-ap.png
  products/android/15.0/basic/config/index.md
Labels: auto

#436 auto: Keyman for linux help deployment
  products/linux/14.0/about/whatsnew.md
  products/linux/14.0/linux_images/video.png
Labels: auto

#437 auto: Keyman for mac help deployment
  products/mac/14.0/about/whatsnew.md
Labels: auto

#438 auto: Keyman for android help deployment
  products/android/14.0/about/whatsnew.md
  products/android/14.0/android_images/video.png
Labels: auto

#439 auto: Keyman for ios help deployment
  products/iphone-and-ipad/14.0/about/whatsnew.md
  products/iphone-and-ipad/14.0/ios_images/video.png
Labels: auto

#440 auto: Keyman for windows help deployment
  products/windows/14.0/about/whatsnew.md
  products/windows/14.0/desktop_images/video.png
Labels: auto
