Repository keymanapp/help.keyman.com, pull requests merged in 2021-04, with the labels that each got.

#368 auto: Keyman for linux help deployment
  products/linux/14.0/common/index.md
Labels: auto

#370 auto: Keyman for android help deployment
  products/android/14.0/about/welcome.md
  products/android/14.0/android_images/settings6-ap.png
  products/android/14.0/start/installing-keyboards.md
Labels: auto

#372 auto: Keyman for android help deployment
  products/android/15.0/android_images/settings6-ap.png
  products/android/15.0/start/installing-keyboards.md
Labels: auto

#377 docs: keyman 14 upgrade and keyboard source download KBs
  knowledge-base/kb0105.md
  knowledge-base/kb0106.md
Labels: docs

#378 docs(web): osk.restorePosition()
  _includes/includes/phone-menu.php
  cdn/dev/css/template.css
  developer/engine/web/14.0/reference/osk/index.php
  developer/engine/web/14.0/reference/osk/restorePosition.md
Labels: docs

#380 fix: `setRect` parameter mismatch for `nosize` and `nomove`
  developer/engine/web/14.0/reference/osk/setRect.php
Labels: fix

#381 chore: Remove TODO files
  products/windows/14.0/TODO.md
  products/windows/15.0/TODO.md
Labels: chore

#383 chore: remove obsolete code
  cdn/dev/js/kbd-docs.js
  cdn/dev/js/kmlive.js
Labels: chore

#384 chore: Update link to lexical-model interface
  developer/14.0/guides/lexical-models/advanced/model-definition-file.php
Labels: chore

#385 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
Labels: auto

#382 fix: we should not use backtick in live code yet
  cdn/dev/js/kbd-docs.js
Labels: fix
