Repository keymanapp/help.keyman.com, pull requests merged in 2022-10, with the labels that each got.

#608 fix: builder script for Windows 🦭
  build.sh
Labels: bug, staging

#615 fix: links to tutorial steps
  developer/16.0/guides/develop/tutorial/index.php
  developer/16.0/guides/develop/tutorial/step-1.php
  developer/16.0/guides/develop/tutorial/step-2.php
  developer/16.0/guides/develop/tutorial/step-3.php
  developer/16.0/guides/develop/tutorial/step-4.php
  developer/16.0/guides/develop/tutorial/step-5.php
  developer/16.0/guides/develop/tutorial/step-6.php
  developer/16.0/guides/develop/tutorial/step-7.php
  developer/16.0/guides/develop/tutorial/step-8.php
  developer/16.0/guides/develop/tutorial/step-9.php
Labels: fix

#616 feat: Add support for Kubernetes 🦭
  .gitattributes
  .github/workflows/ci.yml
  Dockerfile
  build.sh
  resources/keyman-site.conf
  resources/kubectl/help-kubectl-dev.yaml
  resources/kubectl/help-kubectl.yaml
Labels: staging

#619 auto: Keyman for android help deployment
  products/android/16.0/about/whatsnew.md
  products/android/16.0/index.md
Labels: auto

#622 docs: deprecate alignInputs
  developer/engine/web/16.0/reference/core/alignInputs.md
  developer/engine/web/16.0/reference/core/alignInputs.php
  developer/engine/web/16.0/reference/core/index.md
  developer/engine/web/16.0/reference/core/index.php
Labels: docs

#623 docs: model cloud API endpoints
  developer/cloud/index.md
  developer/cloud/model/1.0/index.md
  developer/cloud/model/index.md
Labels: docs

#624 docs: add reference for BCP 47
  developer/16.0/context/new-lm-project-parameters.php
  developer/16.0/context/package-editor.php
  developer/16.0/guides/distribute/tutorial/step-3.php
  developer/16.0/guides/lexical-models/tutorial/step-2.php
  developer/16.0/reference/bcp-47.md
  developer/16.0/reference/file-types/metadata.md
  developer/16.0/reference/file-types/metadata.php
  developer/16.0/reference/index.md
  developer/16.0/reference/index.php
Labels: docs

#628 auto: Keyman for linux help deployment
  products/linux/16.0/about/whatsnew.md
  products/linux/16.0/index.md
  products/linux/16.0/reference/index.md
Labels: auto

#629 auto: Keyman for mac help deployment
  products/mac/16.0/about/requirements.md
  products/mac/16.0/about/whatsnew.md
  products/mac/16.0/common/keyboards.md
  products/mac/16.0/common/os.md
  products/mac/16.0/index.md
Labels: auto

#630 auto: Keyman for ios help deployment
  products/iphone-and-ipad/16.0/about/whatsnew.md
  products/iphone-and-ipad/16.0/index.md
Labels: auto

#631 auto: Keyman for windows help deployment
  products/windows/16.0/about/whatsnew.md
  products/windows/16.0/basic/config/options.md
  products/windows/16.0/index.md
Labels: auto

#632 auto: Keyman for linux help deployment
  products/linux/17.0/about/history.md
  products/linux/17.0/about/index.md
  products/linux/17.0/about/welcome.md
  products/linux/17.0/about/whatsnew.md
  products/linux/17.0/common/index.md
  products/linux/17.0/index.md
  products/linux/17.0/linux_images/add-input-source-khmer-angkor.png
  products/linux/17.0/linux_images/add-input-source-khmer.png
  products/linux/17.0/linux_images/add-input-source.png
  products/linux/17.0/linux_images/download-khmer-angkor.png
  products/linux/17.0/linux_images/km-config-khmer-angkor.png
  products/linux/17.0/linux_images/km-config.png
  products/linux/17.0/linux_images/mobile viewport.png
  products/linux/17.0/linux_images/onboard.png
  products/linux/17.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/17.0/linux_images/region-and-language.png
  products/linux/17.0/linux_images/region-language-khmer-angkor.png
  products/linux/17.0/linux_images/search-khmer-angkor.png
  products/linux/17.0/linux_images/video.png
  products/linux/17.0/reference/index.md
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
  products/linux/17.0/start/index.md
  products/linux/17.0/start/installing-keyboard.md
Labels: auto

#634 auto: Keyman for mac help deployment
  products/mac/17.0/about/history.md
  products/mac/17.0/about/index.md
  products/mac/17.0/about/requirements.md
  products/mac/17.0/about/welcome.md
  products/mac/17.0/about/whatsnew.md
  products/mac/17.0/basic/config/index.md
  products/mac/17.0/basic/config/keyboards.md
  products/mac/17.0/basic/config/options.md
  products/mac/17.0/basic/config/support.md
  products/mac/17.0/basic/index.md
  products/mac/17.0/common/adware.md
  products/mac/17.0/common/bug.md
  products/mac/17.0/common/free.md
  products/mac/17.0/common/index.md
  products/mac/17.0/common/keyboards.md
  products/mac/17.0/common/os.md
  products/mac/17.0/common/osk.md
  products/mac/17.0/common/requirements.md
  products/mac/17.0/common/support.md
  products/mac/17.0/index.md
  products/mac/17.0/mac_images/add.png
  products/mac/17.0/mac_images/add_keyman.png
  products/mac/17.0/mac_images/apple_menu.png
  products/mac/17.0/mac_images/go_to_folder.png
  products/mac/17.0/mac_images/help_button.png
  products/mac/17.0/mac_images/icon-fonts.png
  products/mac/17.0/mac_images/icon-help.png
  products/mac/17.0/mac_images/icon-intro.png
  products/mac/17.0/mac_images/icon-keyman.png
  products/mac/17.0/mac_images/icon-osk.png
  products/mac/17.0/mac_images/icon-unicode.png
  products/mac/17.0/mac_images/information_button.png
  products/mac/17.0/mac_images/input_menu.png
  products/mac/17.0/mac_images/keyboards_menu.png
  products/mac/17.0/mac_images/keyman_config.png
  products/mac/17.0/mac_images/keyman_install.png
  products/mac/17.0/mac_images/keyman_menu_config.png
  products/mac/17.0/mac_images/menu_bar.png
  products/mac/17.0/mac_images/menu_bar_keyman.png
  products/mac/17.0/mac_images/osk_amharic.png
  products/mac/17.0/mac_images/privacy_accessibility.png
  products/mac/17.0/mac_images/privacy_files_and_folders.png
  products/mac/17.0/mac_images/privacy_input_monitoring.png
  products/mac/17.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/17.0/mac_images/remove.png
  products/mac/17.0/mac_images/remove_button.png
  products/mac/17.0/mac_images/remove_keyman.png
  products/mac/17.0/mac_images/system_preferences.png
  products/mac/17.0/mac_images/video.png
  products/mac/17.0/start/index.md
  products/mac/17.0/start/install-keyboard.md
  products/mac/17.0/start/install-keyman.md
  products/mac/17.0/start/tutorial.md
  products/mac/17.0/troubleshooting/configure-security.md
  products/mac/17.0/troubleshooting/index.md
  products/mac/17.0/troubleshooting/uninstall-keyman.md
Labels: auto
