Repository keymanapp/help.keyman.com, pull requests merged in 2022-04, with the labels that each got.

#526 fix: help offset
  cdn/dev/js/kbd-docs.js
  cdn/dev/js/kmlive.js
Labels: fix

#530 auto: Keyman for linux help deployment
  products/linux/15.0/about/whatsnew.md
Labels: auto

#531 auto: Keyman for mac help deployment
  products/mac/15.0/about/requirements.md
  products/mac/15.0/common/keyboards.md
  products/mac/15.0/common/os.md
  products/mac/15.0/index.md
Labels: auto

#532 auto: Keyman for android help deployment
  products/android/15.0/about/system-requirements.md
Labels: auto

#533 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/whatsnew.md
Labels: auto

#534 auto: Keyman for windows help deployment
  products/windows/15.0/basic/config/options.md
  products/windows/15.0/index.md
Labels: auto

#537 auto: Keyman for linux help deployment
  products/linux/16.0/about/whatsnew.md
Labels: auto

#538 auto: Keyman for windows help deployment
  products/windows/16.0/basic/config/options.md
  products/windows/16.0/index.md
Labels: auto

#539 auto: Keyman for ios help deployment
  products/iphone-and-ipad/16.0/about/whatsnew.md
Labels: auto

#540 auto: Keyman for mac help deployment
  products/mac/16.0/about/requirements.md
  products/mac/16.0/common/keyboards.md
  products/mac/16.0/common/os.md
  products/mac/16.0/index.md
Labels: auto

#541 auto: Keyman for mac help deployment
  products/mac/15.0/about/whatsnew.md
Labels: auto

#542 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/system-requirements.md
  products/iphone-and-ipad/15.0/about/whatsnew.md
Labels: auto

#543 docs: clarify setup.exe must be unsigned
  knowledge-base/kb0035.md
Labels: docs

#544 auto: Keyman for mac help deployment
  products/mac/16.0/about/whatsnew.md
Labels: auto

#545 auto: Keyman for ios help deployment
  products/iphone-and-ipad/16.0/about/system-requirements.md
  products/iphone-and-ipad/16.0/about/whatsnew.md
Labels: auto

#549 auto: Keyman for windows help deployment
  products/windows/15.0/about/requirements.md
  products/windows/15.0/about/whatsnew.md
  products/windows/15.0/common/old_version.md
  products/windows/15.0/common/os.md
Labels: auto

#550 auto: Keyman for windows help deployment
  products/windows/16.0/about/requirements.md
  products/windows/16.0/about/whatsnew.md
  products/windows/16.0/common/old_version.md
  products/windows/16.0/common/os.md
Labels: auto
