Repository keymanapp/help.keyman.com, pull requests merged in 2022-12, with the labels that each got.

#673 fix: update s.keyman.com refs to https
  _includes/includes/servervars.php
  developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
  developer/16.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
  developer/engine/web/10.0/reference/osk/classes.php
  developer/engine/web/11.0/reference/osk/classes.php
  developer/engine/web/12.0/reference/osk/classes.php
  developer/engine/web/13.0/reference/osk/classes.php
  developer/engine/web/14.0/reference/osk/classes.php
  developer/engine/web/15.0/reference/osk/classes.php
  developer/engine/web/16.0/reference/osk/classes.php
  developer/engine/web/2.0/guide/get-started.php
  developer/engine/web/2.0/reference/osk/classes.php
Labels: fix

#672 docs: add parens and type clarifications to Core headings
  developer/core/desktop/15.0/c-api/context-api.php
  developer/core/desktop/15.0/c-api/keyboard-api.php
  developer/core/desktop/15.0/c-api/state-api.php
  developer/core/desktop/16.0/c-api/context-api.php
  developer/core/desktop/16.0/c-api/index.php
  developer/core/desktop/16.0/c-api/keyboard-api.php
  developer/core/desktop/16.0/c-api/option-api.php
  developer/core/desktop/16.0/c-api/state-api.php
Labels: docs

#677 auto: Keyman for android help deployment
  products/android/17.0/about/whatsnew.md
Labels: auto
