Repository keymanapp/help.keyman.com, pull requests merged in 2022-05, with the labels that each got.

#548 feat: adds new properties for Web's getKeyboard API
  developer/engine/web/14.0/reference/core/getKeyboard.php
Labels: feat

#552 auto: Keyman for android help deployment
  products/android/15.0/android_images/settings-screen-ap.png
  products/android/15.0/basic/config/index.md
Labels: auto

#553 docs: link to Keyman Developer Lingtran tutorials
  developer/14.0/guides/develop/index.php
  developer/15.0/guides/develop/index.php
Labels: docs

#551 docs(windows): add description for install default parameter
  developer/15.0/reference/tools/setup.md
  developer/15.0/reference/tools/setup.php
  knowledge-base/kb0035.md
Labels: docs

#557 auto: Keyman for android help deployment
  products/android/16.0/android_images/settings-screen-ap.png
  products/android/16.0/basic/config/index.md
Labels: auto

#558 auto: Keyman for ios help deployment
  products/iphone-and-ipad/15.0/about/welcome.md
Labels: auto
