Repository keymanapp/help.keyman.com, pull requests merged in 2022-11, with the labels that each got.

#627 docs: kb0109 - blank keyboard on ios 16
  knowledge-base/assets/kb0109/allow-full-access.png
  knowledge-base/assets/kb0109/blank-keyboard-ios16.png
  knowledge-base/kb0109.md
Labels: staging, docs

#636 docs: kb0109 - blank keyboard on ios 16 🍒
  knowledge-base/assets/kb0109/allow-full-access.png
  knowledge-base/assets/kb0109/blank-keyboard-ios16.png
  knowledge-base/kb0109.md
Labels: cherry-pick, docs

#638 docs: macos privacy configuration
  products/mac/15.0/troubleshooting/configure-security.md
  products/mac/16.0/mac_images/privacy-accessibility-alert.png
  products/mac/16.0/mac_images/privacy-documents-alert.png
  products/mac/16.0/mac_images/privacy-keyman-alert.png
  products/mac/16.0/troubleshooting/configure-security.md
Labels: help.keyman.com, docs

#643 chore: Update builder.inc.sh
  resources/builder.inc.sh
Labels: staging

#645 chore: fix link to security configuration
  knowledge-base/kb0104.md
Labels: chore

#646 docs(developer): update keyman.initialized docs
  developer/engine/web/16.0/reference/core/init.md
  developer/engine/web/16.0/reference/core/initialized.md
  developer/engine/web/16.0/reference/core/initialized.php
Labels: docs

#647 auto: Keyman for linux help deployment
  products/linux/16.0/about/whatsnew.md
Labels: auto

#642 docs: macos privacy configuration 🍒
  products/mac/15.0/troubleshooting/configure-security.md
  products/mac/16.0/mac_images/privacy-accessibility-alert.png
  products/mac/16.0/mac_images/privacy-documents-alert.png
  products/mac/16.0/mac_images/privacy-keyman-alert.png
  products/mac/16.0/troubleshooting/configure-security.md
Labels: help.keyman.com, cherry-pick, docs

#648 auto: Keyman for mac help deployment
  products/mac/16.0/mac_images/privacy-accessibility-alert.png
  products/mac/16.0/mac_images/privacy-documents-alert.png
  products/mac/16.0/mac_images/privacy-keyman-alert.png
  products/mac/16.0/troubleshooting/configure-security.md
Labels: auto

#649 auto: Keyman for linux help deployment
  products/linux/16.0/reference/km-config.md
Labels: auto

#651 auto: Keyman for linux help deployment
  products/linux/16.0/reference/km-package-install.md
Labels: auto

#653 auto: Keyman for linux help deployment
  products/linux/16.0/about/whatsnew.md
Labels: auto

#654 auto: Keyman for android help deployment
  products/android/16.0/about/whatsnew.md
Labels: auto

#656 auto: Keyman for ios help deployment
  products/iphone-and-ipad/16.0/about/whatsnew.md
  products/iphone-and-ipad/16.0/start/installing-system-keyboard.md
Labels: auto

#657 auto: Keyman for mac help deployment
  products/mac/16.0/about/whatsnew.md
Labels: auto

#658 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-package-install.md
Labels: auto

#660 auto: Keyman for ios help deployment
  products/iphone-and-ipad/17.0/start/installing-system-keyboard.md
Labels: auto

#663 auto: Keyman for android help deployment
  products/android/16.0/about/whatsnew.md
Labels: auto

#664 auto: Keyman for mac help deployment
  products/mac/15.0/troubleshooting/configure-security.md
Labels: auto

#669 chore: Fix links to km_kbp_state
  developer/core/desktop/15.0/c-api/index.php
  developer/core/desktop/16.0/c-api/index.php
Labels: bug, docs
