Repository keymanapp/help.keyman.com, pull requests merged in 2022-02, with the labels that each got.

#498 auto: Keyman for linux help deployment
  products/linux/15.0/about/welcome.md
  products/linux/15.0/common/index.md
  products/linux/15.0/reference/index.md
Labels: auto

#500 docs: casing support
  developer/language/guide/history.md
  developer/language/guide/index.php
Labels: docs

#501 chore: Update kb0104.md PostEvent to All for tccutil
  knowledge-base/kb0104.md
Labels: chore

#502 auto: Keyman for android help deployment
  products/android/15.0/about/whatsnew.md
  products/android/15.0/basic/switching-between-keyboards.md
Labels: auto

#505 docs: Keyman Developer 15 changes
  developer/language/guide/history.md
  developer/language/guide/index.md
  developer/language/guide/index.php
  developer/language/guide/virtual-keys.md
  developer/language/reference/index.md
  products/windows/3.0/index.md
  products/windows/3.0/keyman32.pdf
  products/windows/3.0/km32lang.pdf
Labels: docs
