Repository keymanapp/help.keyman.com, pull requests merged in 2023-01, with the labels that each got.

#680 Merge Master from sprint a17s3 alpha
  keyboard/chalchiteko/1.0/chalchiteko.php
  keyboard/modi_inscript/1.0/modi_inscript.php
  keyboard/postmodern_english_uk_natural/1.3/pme_mobile_keyboard.jpg
  keyboard/postmodern_english_uk_natural/1.3/pme_uk_natural_desktop_keyboard.png
  keyboard/postmodern_english_uk_natural/1.3/postmodern_english_uk_natural.php
  keyboard/postmodern_english_us_natural/1.3/pme_mobile_keyboard.jpg
  keyboard/postmodern_english_us_natural/1.3/pme_us_natural_desktop_keyboard.png
  keyboard/postmodern_english_us_natural/1.3/postmodern_english_us_natural.php
  keyboard/sil_tchad/4.3/sil_tchad.php
Labels: chore

#682 cherrypick: fix casing to OFL links 🍒
  keyboard/ipauni11/1.0/ipauni11.php
Labels: cherry-pick, epic-linux-hosting

#681 Remove dev requirement for Composer [Take 2]
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  Readme.md
  build.sh
Labels: epic-linux-hosting

#685 fix: Move link of vendor/ from build.sh configure to start 🦭
  .github/workflows/ci.yml
  build.sh
Labels: epic-linux-hosting

#686 docs: Update targets.php
  developer/language/reference/targets.php
Labels: docs

#676 K8s convert pod to deployment
  resources/kubectl/help-kubectl-deploy.yaml
  resources/kubectl/help-kubectl-dev.yaml
  resources/kubectl/help-kubectl.yaml
Labels: staging, epic-linux-hosting

#687 auto: Keyman for windows help deployment
  products/windows/17.0/about/welcome.md
  products/windows/17.0/basic/config/keyboards.md
  products/windows/17.0/basic/enable-or-disable-keyboard.md
  products/windows/17.0/basic/uninstall-keyboard.md
  products/windows/17.0/desktop_images/download-keyboard-step0.png
  products/windows/17.0/desktop_images/download-keyboard-step5.png
  products/windows/17.0/desktop_images/keyboard-share.png
  products/windows/17.0/desktop_images/keyboards-hotkey.png
  products/windows/17.0/desktop_images/language-association.png
  products/windows/17.0/desktop_images/options-advanced.png
  products/windows/17.0/desktop_images/options-general.png
  products/windows/17.0/desktop_images/tab-add-lang.png
  products/windows/17.0/desktop_images/tab-add-popup.png
  products/windows/17.0/desktop_images/tab-hotkeys.png
  products/windows/17.0/desktop_images/tab-keyboards.png
  products/windows/17.0/desktop_images/tab-layout-detail1.png
  products/windows/17.0/desktop_images/tab-layout-detail2.png
  products/windows/17.0/desktop_images/tab-layout-disable.png
  products/windows/17.0/desktop_images/tab-layout-enable.png
  products/windows/17.0/desktop_images/tab-layout-help.png
  products/windows/17.0/desktop_images/tab-layout-share.png
  products/windows/17.0/desktop_images/tab-layout.png
  products/windows/17.0/desktop_images/tab-options2.png
  products/windows/17.0/desktop_images/tab-support.png
  products/windows/17.0/start/configure-computer.md
Labels: auto
