Repository keymanapp/help.keyman.com, pull requests merged in 2023-10, with the labels that each got.

#821 chore: Merge master to staging for Sprint A17S22 (part 2)
  keyboard/sil_cameroon_qwerty/6.0.9/sil_cameroon_qwerty.php
Labels: staging

#823 chore: Merge master to staging for Sprint A17S23
  keyboard/bu_phonetic/2.1/bu_phonetic.php
  keyboard/bu_phonetic/2.1/bukeys.pdf
  keyboard/chinuk_wawa/1.1/chinuk_wawa.php
  keyboard/colchis_latin/1.4.1/colchis_latin.php
  keyboard/colchis_phonetic/1.1/colchis_phonetic.php
  keyboard/elfdalian/1.0.5/elfdalian.php
  keyboard/gaahmg/1.0/gaahmg.php
  keyboard/gondi_gunjala_inscript/1.1/gondi_gunjala_inscript.php
  keyboard/old_hungarian/1.7.8/old_hungarian.php
  keyboard/rusyn/1.0.0/rusyn.php
  keyboard/sil_areare/1.1/keyboard_layout.png
  keyboard/sil_areare/1.1/sil_areare.php
Labels: staging

#820 fix: Add k8s step to pull shared-sites repo 🦭
  resources/kubectl/help-kubectl.yaml
Labels: staging

#826 chore: build path
  resources/kubectl/help-kubectl.yaml
Labels: chore

#827 chore: do build.sh configure in docker action
  .github/workflows/docker.yml
  resources/kubectl/help-kubectl.yaml
Labels: chore

#825 chore: canonical keyboard version documentation
  .github/workflows/ci.yml
  .gitignore
  .htaccess
  _includes/header.php
  _includes/includes/head.php
  _includes/includes/kb_doc_template.php
  cdn/dev/css/template.css
  keyboard/index.php
  resources/init-container.sh
Labels: chore

#828 chore: split container init into init-container.sh
  build.sh
  keyboard/_build_cache.php
  keyboard/index.php
  resources/init-container.sh
  resources/kubectl/help-kubectl.yaml
Labels: chore

#829 chore: yaml format
  resources/kubectl/help-kubectl.yaml
Labels: chore

#830 chore: Set line endings for .sh files
  .gitattributes
Labels: staging, epic-linux-hosting

#831 chore: cleanup tests
  .github/workflows/ci.yml
  Dockerfile
  build.sh
  composer.json
  phpunit.xml
  tests/InfrastructureTest.php
Labels: staging, chore

#834 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#833 docs: Add TSF knowledge base page
  knowledge-base/kb0110.md
Labels: docs

#835 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#836 auto: Keyman for windows help deployment
  products/windows/17.0/advanced/index.md
  products/windows/17.0/advanced/text_services_framework.md
  products/windows/17.0/basic/make-taskbar-icon-visible.md
  products/windows/17.0/basic/uninstall.md
  products/windows/17.0/desktop_images/win11-taskbar1.png
  products/windows/17.0/desktop_images/win11-taskbar2.png
  products/windows/17.0/desktop_images/win11-uninstall.png
  products/windows/17.0/desktop_images/win11_km_install_anywhere_1.png
  products/windows/17.0/index.md
  products/windows/17.0/start/download-and-install-keyman.md
  products/windows/17.0/troubleshooting/index.md
  products/windows/17.0/troubleshooting/install-app-from-anywhere.md
Labels: auto

#837 chore: auto PR merge after CI finished
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
  keyboard/fv_dene_zhatie/10.0/fv_dene_zhatie.php
Labels: chore

#798 chore: prepare keyboard_info 2.0 documentation 🎺
  developer/cloud/keyboard_info/2.0/index.md
Labels: feat, epic-package-metadata

#815 docs(developer): package editor 17.0, start of command line tools
  cdn/dev/img/developer/170/ui/frmAboutTike.png
  cdn/dev/img/developer/170/ui/frmLMPackageEditor_Build.png
  cdn/dev/img/developer/170/ui/frmModelsCompile.png
  cdn/dev/img/developer/170/ui/frmNew.png
  cdn/dev/img/developer/170/ui/frmNewLMProject.png
  cdn/dev/img/developer/170/ui/frmNewLMProjectParameters.png
  cdn/dev/img/developer/170/ui/frmNewLMProjectSelectLanguage.png
  cdn/dev/img/developer/170/ui/frmNewProject.png
  cdn/dev/img/developer/170/ui/frmNewProjectParameters.png
  cdn/dev/img/developer/170/ui/frmOptions_CharacterMap.png
  cdn/dev/img/developer/170/ui/frmOptions_Debugger.png
  cdn/dev/img/developer/170/ui/frmOptions_Editor.png
  cdn/dev/img/developer/170/ui/frmOptions_General.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Build.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Details.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Files.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Keyboards.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Select_BCP_47_Tag.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Shortcuts.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_Source.png
  cdn/dev/img/developer/170/ui/frmProject_Distribution.png
  developer/17.0/context/kmc.md
  developer/17.0/context/kmcomp.md
  developer/17.0/context/kmlmc.md
  developer/17.0/context/kmlmc.php
  developer/17.0/context/kmlmi.md
  developer/17.0/context/kmlmi.php
  developer/17.0/context/kmlmp.md
  developer/17.0/context/kmlmp.php
  developer/17.0/context/package-editor.md
  developer/17.0/context/package-editor.php
  developer/17.0/guides/command-line.md
  developer/17.0/guides/file-layout.md
  developer/17.0/guides/intro.php
Labels: docs

#822 docs: WelcomeFile in kps
  developer/17.0/guides/distribute/packages.php
  developer/17.0/reference/file-types/metadata.md
Labels: docs

#839 chore: Update kb0095.md
  knowledge-base/kb0095.md
Labels: chore, docs

#840 auto: Keyboard help deployment
  keyboard/fv_dene_zhatie/10.0/fv_dene_zhatie.php
  keyboard/fv_nuucaanul/9.1.4/Nuucaanul.png
  keyboard/fv_nuucaanul/9.1.4/fv_nuucaanul.php
Labels: auto

#844 chore: Update fv_dene_zhatie.php 10.0 broken link
  keyboard/fv_dene_zhatie/10.0/fv_dene_zhatie.php
Labels: chore

#842 auto: Keyboard help deployment
  keyboard/fv_dene_zhatie/10.0.1/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.0.1/fv_dene_zhatieU_.png
Labels: auto

#848 chore: tweak auto merging
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
Labels: chore

#846 auto: Keyboard help deployment
  keyboard/gff_tigre/1.0.2/TigreTyping-English.pdf
  keyboard/gff_tigre/1.0.2/gff_tigre.php
  keyboard/gff_tigre/1.0.2/kb.css
  keyboard/gff_tigrinya_eritrea/2.0.2/TigrinyaErTyping-English.pdf
  keyboard/gff_tigrinya_eritrea/2.0.2/gff_tigrinya_eritrea.php
  keyboard/gff_tigrinya_eritrea/2.0.2/kb.css
Labels: auto

#847 chore: Update displaymap.md
  developer/language/reference/displaymap.md
Labels: chore

#843 docs(developer): New package editor metadata fields
  .github/workflows/ci.yml
  cdn/dev/img/developer/170/ui/frmPackageEditor_EditExample.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_EditRelatedPackage.png
  cdn/dev/img/developer/170/ui/frmPackageEditor_SelectWebFonts.png
  developer/17.0/context/package-editor.md
  developer/17.0/context/select-web-fonts.md
Labels: docs

#852 chore: use auto merge if possible
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
Labels: chore

#851 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#858 chore: use different token for merge
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
Labels: chore

#859 chore: auth once more
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
Labels: chore

#853 auto: Keyboard help deployment
  keyboard/gff_tigrinya_ethiopia/2.0.3/TigrinyaEtTyping-English.pdf
  keyboard/gff_tigrinya_ethiopia/2.0.3/gff_tigrinya_ethiopia.php
  keyboard/gff_tigrinya_ethiopia/2.0.3/kb.css
Labels: auto

#850 chore: Merge master to staging for Sprint A17S24
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
  developer/cloud/keyboard_info/2.0/index.md
  developer/language/reference/displaymap.md
  keyboard/burushaski_girminas/2.0.24/burushaski_girminas.php
  keyboard/chinuk_wawa/1.2/chinuk_wawa.php
  keyboard/chinuk_wawa/1.3/chinuk_wawa.php
  keyboard/fv_dene_zhatie/10.0.1/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.0.1/fv_dene_zhatieU_.png
  keyboard/fv_dene_zhatie/10.0/fv_dene_zhatie.php
  keyboard/fv_nuucaanul/9.1.4/Nuucaanul.png
  keyboard/fv_nuucaanul/9.1.4/fv_nuucaanul.php
  keyboard/gaahmg/1.0.1/gaahmg.php
  keyboard/gff_tigre/1.0.2/TigreTyping-English.pdf
  keyboard/gff_tigre/1.0.2/gff_tigre.php
  keyboard/gff_tigre/1.0.2/kb.css
  keyboard/gff_tigrinya_eritrea/2.0.2/TigrinyaErTyping-English.pdf
  keyboard/gff_tigrinya_eritrea/2.0.2/gff_tigrinya_eritrea.php
  keyboard/gff_tigrinya_eritrea/2.0.2/kb.css
  keyboard/tai_tham_my/1.2/tai_tham_my.php
  knowledge-base/kb0095.md
  knowledge-base/kb0110.md
  products/windows/17.0/advanced/index.md
  products/windows/17.0/advanced/text_services_framework.md
  products/windows/17.0/basic/make-taskbar-icon-visible.md
  products/windows/17.0/basic/uninstall.md
  products/windows/17.0/desktop_images/win11-taskbar1.png
  products/windows/17.0/desktop_images/win11-taskbar2.png
  products/windows/17.0/desktop_images/win11-uninstall.png
  products/windows/17.0/desktop_images/win11_km_install_anywhere_1.png
  products/windows/17.0/index.md
  products/windows/17.0/start/download-and-install-keyman.md
  products/windows/17.0/troubleshooting/index.md
  products/windows/17.0/troubleshooting/install-app-from-anywhere.md
Labels: staging

#860 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#861 auto: Keyboard help deployment
  keyboard/newa_traditional_extended/1.0.1/newa_traditional_extended.php
Labels: auto

#862 auto: Keyboard help deployment
  keyboard/warang_citi/1.1.2/warang_citi.php
Labels: auto
