Repository keymanapp/help.keyman.com, pull requests merged in 2023-05, with the labels that each got.

#708 Update word-breaker.php
  developer/16.0/guides/lexical-models/advanced/word-breaker.php
Labels: bug

#709 Update index.php
  developer/16.0/guides/lexical-models/index.php
Labels: bug

#710 Update automatic-control.php
  developer/engine/web/16.0/guide/examples/automatic-control.php
  developer/engine/web/16.0/guide/examples/control-by-control.php
  developer/engine/web/16.0/guide/examples/full-manual-control.php
  developer/engine/web/16.0/guide/examples/manual-control.php
  developer/engine/web/17.0/guide/examples/automatic-control.php
  developer/engine/web/17.0/guide/examples/control-by-control.php
  developer/engine/web/17.0/guide/examples/full-manual-control.php
  developer/engine/web/17.0/guide/examples/manual-control.php
  keyboard/gff_harari/1.0/gff_harari.php
Labels: bug

#714 chore: Remove web.config files
  developer/10.0/web.config
  developer/13.0/guides/develop/web.config
  developer/13.0/guides/test/web.config
  developer/14.0/guides/develop/web.config
  developer/14.0/guides/test/web.config
  developer/15.0/guides/develop/web.config
  developer/15.0/guides/test/web.config
  developer/16.0/guides/develop/web.config
  developer/16.0/guides/test/web.config
  developer/9.0/web.config
  developer/core/desktop/web.config
  developer/engine/android/web.config
  developer/engine/iphone-and-ipad/web.config
  developer/engine/web/web.config
  kb/web.config
  keyboard/web.config
  knowledge-base/web.config
  products/android/version-history/web.config
  products/android/web.config
  products/desktop/web.config
  products/iphone-and-ipad/version-history/web.config
  products/iphone-and-ipad/web.config
  products/linux/web.config
  products/mac/13.0/web.config
  products/mac/web.config
  products/web/web.config
  products/windows/web.config
  web.config
Labels: staging

#715 chore: fixup CI for docker-hosted php
  .github/workflows/ci.yml
  .htaccess
  Dockerfile
  index.php
  kb/.htaccess
  knowledge-base/.htaccess
Labels: chore

#720 docs: versioning to markdown
  developer/cloud/versioning.md
  developer/cloud/versioning.php
Labels: docs
