Repository keymanapp/help.keyman.com, pull requests merged in 2023-11, with the labels that each got.

#863 auto: Keyboard help deployment
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultKeyboard).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(numericTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(numericTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftKeyboard).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala.php
  keyboard/gondi_gunjala_inscript/1.1.1/gondi_gunjala_inscript.php
  keyboard/newa_romanized/1.0.1/newa_romanized.php
Labels: auto

#864 auto: Keyboard help deployment
  keyboard/deseret/1.2/deseret.php
  keyboard/deseret/1.2/deseret_chart1.png
  keyboard/deseret/1.2/deseret_chart2.png
Labels: auto

#865 auto: Keyboard help deployment
  keyboard/burushaski_girminas_perso_arabic/1.25/bsk_perso_arabic_keyboard_keystrokes.png
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_additional_characters.png
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_girminas_perso_arabic.php
  keyboard/burushaski_girminas_perso_arabic/1.25/hunza_nagar_text.png
  keyboard/burushaski_girminas_perso_arabic/1.25/key_combination_chart_equation.png
  keyboard/burushaski_girminas_perso_arabic/1.25/orthography.png
  keyboard/burushaski_girminas_perso_arabic/1.25/stylesheet.css
  keyboard/burushaski_girminas_perso_arabic/1.25/yasin_text.png
Labels: auto

#866 auto: Keyboard help deployment
  keyboard/runeboard/2.2/runeboard.php
Labels: auto

#867 chore: Update "Key text" table for keymanweb-osk.ttf v4.0
  developer/17.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
Labels: staging

#870 auto: Keyboard help deployment
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_additional_characters.png
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_girminas_perso_arabic.php
  keyboard/burushaski_girminas_perso_arabic/1.25/stylesheet.css
Labels: auto

#869 chore: Merge master to staging for Sprint A17S25
  .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
  .github/workflows/auto-approve-keyman-server-pr.yml
  .github/workflows/auto-merge-keyman-server-pr.yml
  keyboard/burushaski_girminas/2.0.25/burushaski_girminas.php
  keyboard/burushaski_girminas/2.0.25/image_keyboard_guide2.png
  keyboard/burushaski_girminas_perso_arabic/1.25/bsk_perso_arabic_keyboard_keystrokes.png
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_additional_characters.png
  keyboard/burushaski_girminas_perso_arabic/1.25/burushaski_girminas_perso_arabic.php
  keyboard/burushaski_girminas_perso_arabic/1.25/hunza_nagar_text.png
  keyboard/burushaski_girminas_perso_arabic/1.25/key_combination_chart_equation.png
  keyboard/burushaski_girminas_perso_arabic/1.25/orthography.png
  keyboard/burushaski_girminas_perso_arabic/1.25/stylesheet.css
  keyboard/burushaski_girminas_perso_arabic/1.25/yasin_text.png
  keyboard/deseret/1.2/deseret.php
  keyboard/deseret/1.2/deseret_chart1.png
  keyboard/deseret/1.2/deseret_chart2.png
  keyboard/fv_dene_zhatie/10.0.2/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.0.2/fv_dene_zhatieU_.png
  keyboard/fv_kwakwala_liqwala/9.2.5/Kwakwala_LiqwalaU_.png
  keyboard/fv_kwakwala_liqwala/9.2.5/fv_kwakwala_liqwala.php
  keyboard/gff_tigrinya_ethiopia/2.0.3/TigrinyaEtTyping-English.pdf
  keyboard/gff_tigrinya_ethiopia/2.0.3/gff_tigrinya_ethiopia.php
  keyboard/gff_tigrinya_ethiopia/2.0.3/kb.css
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultKeyboard).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(defaultTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(numericTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(numericTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftKeyboard).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftTouch).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala(shiftTouchAndroid).png
  keyboard/gondi_gunjala/1.1.2/gondi_gunjala.php
  keyboard/gondi_gunjala_inscript/1.1.1/gondi_gunjala_inscript.php
  keyboard/malar_malayalam/1.7/malar_malayalam.pdf
  keyboard/malar_malayalam/1.7/malar_malayalam.php
  keyboard/malar_malayalam/1.7/malar_malayalam.svg
  keyboard/newa_romanized/1.0.1/newa_romanized.php
  keyboard/newa_traditional_extended/1.0.1/newa_traditional_extended.php
  keyboard/newa_traditional_extended/1.0/newa_traditional_extended.php
  keyboard/runeboard/2.2/runeboard.php
  keyboard/warang_citi/1.1.2/warang_citi.php
Labels: chore

#871 auto: Keyboard help deployment
  keyboard/bj_cree_east/9.1.1/bj_cree_east.php
  keyboard/bj_naskapi_classic/2.1.2/bj_naskapi_classic.php
  keyboard/bj_naskapi_common/1.4.1/Naskapi Unicode Keyboard Layout.pdf
  keyboard/bj_naskapi_common/1.4.1/bj_naskapi_common.php
  keyboard/bj_oji_cree/9.1.1/bj_oji_cree.php
Labels: auto

#872 auto: Keyboard help deployment
  keyboard/fv_dane_zaa_zaage/9.3/fv_dane_zaa_zaage.php
Labels: auto

#873 auto: Keyboard help deployment
  keyboard/fv_nuxalk/10.0/fv_nuxalk.php
Labels: auto

#875 auto: Keyboard help deployment
  keyboard/fv_anicinapemi8in/9.1.1/fv_anicinapemi8in.php
  keyboard/fv_anishinaabemowin/9.1.1/fv_anishinaabemowin.php
  keyboard/fv_atikamekw/9.1.1/fv_atikamekw.php
  keyboard/fv_australian/9.3.1/fv_australian.php
  keyboard/fv_blackfoot/9.2.1/fv_blackfoot.php
  keyboard/fv_bodewadminwen/9.1.1/fv_bodewadminwen.php
  keyboard/fv_cree_latin/9.1.1/fv_cree_latin.php
  keyboard/fv_dakota_mb/9.1.1/fv_dakota_mb.php
  keyboard/fv_dakota_sk/9.1.1/fv_dakota_sk.php
  keyboard/fv_dene_dzage/9.1.1/fv_dene_dzage.php
  keyboard/fv_dene_mb/9.2.1/fv_dene_mb.php
  keyboard/fv_dene_nt/9.2.1/fv_dene_nt.php
  keyboard/fv_denesuline/9.1.1/fv_denesuline.php
  keyboard/fv_denesuline_epsilon/9.1.4/ChipewyanEpsilon.png
  keyboard/fv_denesuline_epsilon/9.1.4/fv_denesuline_epsilon.php
  keyboard/fv_dexwlesucid/9.2.1/fv_dexwlesucid.php
  keyboard/fv_dine_bizaad/9.1.1/fv_dine_bizaad.php
  keyboard/fv_eastern_canadian_inuktitut/9.2.1/fv_eastern_canadian_inuktitut.php
  keyboard/fv_goyogohono/9.2.1/fv_goyogohono.php
  keyboard/fv_hailzaqvla/9.4.1/fv_hailzaqvla.php
  keyboard/fv_ilnu_innu_aimun/9.1.1/fv_ilnu_innu_aimun.php
  keyboard/fv_inuvialuktun/9.1.1/fv_inuvialuktun.php
  keyboard/fv_isga_iabi/9.1.1/fv_isga_iabi.php
  keyboard/fv_kanienkeha_e/9.1.3/Mohawk.png
  keyboard/fv_kanienkeha_e/9.1.3/fv_kanienkeha_e.php
  keyboard/fv_kashogotine_yati/9.1.1/fv_kashogotine_yati.php
  keyboard/fv_ktunaxa/9.1.3/fv_ktunaxa.php
  keyboard/fv_ktunaxa/9.1.3/ktunaxa.png
  keyboard/fv_lakota/9.1.1/fv_lakota.php
  keyboard/fv_lunaapeewi_huluniixsuwaakan/9.1.1/fv_lunaapeewi_huluniixsuwaakan.php
  keyboard/fv_maori/9.1.1/fv_maori.php
  keyboard/fv_moose_cree/9.2.1/fv_moose_cree.php
  keyboard/fv_nakoda/9.1.1/fv_nakoda.php
  keyboard/fv_naskapi/9.3.1/fv_naskapi.php
  keyboard/fv_neeaandeg/9.1.1/fv_neeaandeg.php
  keyboard/fv_nexwslayemucen/9.2.1/fv_nexwslayemucen.php
  keyboard/fv_nlha7kapmxtsin/9.1.1/fv_nlha7kapmxtsin.php
  keyboard/fv_northern_east_cree/9.2.1/fv_northern_east_cree.php
  keyboard/fv_ojibwa/9.3.1/fv_ojibwa.php
  keyboard/fv_onayotaaka/9.2.1/fv_onayotaaka.php
  keyboard/fv_onodagega_onondagega/9.2.1/fv_onodagega_onondagega.php
  keyboard/fv_onodowaga/9.2.1/fv_onodowaga.php
  keyboard/fv_sahugotine_yati/9.1.1/fv_sahugotine_yati.php
  keyboard/fv_severn_ojibwa/9.3.1/fv_severn_ojibwa.php
  keyboard/fv_shihgotine_yati/9.1.1/fv_shihgotine_yati.php
  keyboard/fv_skaru_re/9.2.1/fv_skaru_re.php
  keyboard/fv_skicinuwatuwewakon/9.1.1/fv_skicinuwatuwewakon.php
  keyboard/fv_skwxwumesh_snichim/9.2.1/fv_skwxwumesh_snichim.php
  keyboard/fv_southern_carrier/9.2.1/fv_southern_carrier.php
  keyboard/fv_swampy_cree/9.2.1/fv_swampy_cree.php
  keyboard/fv_tagizi_dene/9.2.1/fv_tagizi_dene.php
  keyboard/fv_tlicho_yatii/9.1.1/fv_tlicho_yatii.php
  keyboard/fv_tlingit/10.0.1/fv_tlingit.php
  keyboard/fv_tsuutina/9.1.1/fv_tsuutina.php
  keyboard/fv_uummarmiutun/9.1.1/fv_uummarmiutun.php
  keyboard/fv_uwikala/9.2.2/FVLogo.gif
  keyboard/fv_uwikala/9.2.2/fv_uwikala.php
  keyboard/fv_wendat/9.1.1/fv_wendat.php
  keyboard/fv_wobanakiodwawogan/9.1.1/fv_wobanakiodwawogan.php
Labels: auto

#876 chore: Remove redirect for live site 🦭
  .htaccess
Labels: staging

#877 chore: provide tier info in _control/info 🦭
  _control/info.php
  test.php
Labels: chore

#878 auto: Keyboard help deployment
  keyboard/fv_uwikala/9.3/FVLogo.gif
  keyboard/fv_uwikala/9.3/fv_uwikala.php
Labels: auto

#879 auto: Keyboard help deployment
  keyboard/kayan/1.5.2/kayan.php
Labels: auto

#880 auto: Keyboard help deployment
  keyboard/gondi_dev/1.1.2/gondi_dev.keyboard_layout_default.png
  keyboard/gondi_dev/1.1.2/gondi_dev.keyboard_layout_shift.png
  keyboard/gondi_dev/1.1.2/gondi_dev.php
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_default.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_itteke_example.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_itteke_how_to.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_j_longpress.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_numeric.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_period_longpress.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_s_longpress.png
  keyboard/gondi_dev/1.1.2/gondi_dev.touch_shift.png
Labels: auto

#881 auto: Keyboard help deployment
  keyboard/dega/2.0/dega.php
  keyboard/dega/2.0/touch_longpress.png
Labels: auto

#884 auto: Keyboard help deployment
  keyboard/sil_akebu/1.0.0/Togo.ico
  keyboard/sil_akebu/1.0.0/sil_akebu.php
Labels: auto

#885 auto: Keyboard help deployment
  keyboard/indigenous_nt/4.0.5/indigenous_nt.php
  keyboard/indigenous_nt/4.0.5/indigenous_nt_layout.pdf
  keyboard/indigenous_nt/4.0.5/indigenous_nt_layout.png
  keyboard/obolo_chwerty/1.2.2/chwerty_default.png
  keyboard/obolo_chwerty/1.2.2/chwerty_keycombi.png
  keyboard/obolo_chwerty/1.2.2/chwerty_mobi_alt.png
  keyboard/obolo_chwerty/1.2.2/chwerty_mobi_default.png
  keyboard/obolo_chwerty/1.2.2/chwerty_mobi_shift.png
  keyboard/obolo_chwerty/1.2.2/chwerty_shift.png
  keyboard/obolo_chwerty/1.2.2/chwertyftkey1.png
  keyboard/obolo_chwerty/1.2.2/chwertyftkey2.png
  keyboard/obolo_chwerty/1.2.2/chwertyftkey3.png
  keyboard/obolo_chwerty/1.2.2/obolo_chwerty.php
  keyboard/obolo_qwerty/1.1.1/obolo_qwerty.php
  keyboard/obolo_qwerty/1.1.1/qwerty_default.png
  keyboard/obolo_qwerty/1.1.1/qwerty_keycombi.png
  keyboard/obolo_qwerty/1.1.1/qwerty_mobialt.png
  keyboard/obolo_qwerty/1.1.1/qwerty_mobidefault.png
  keyboard/obolo_qwerty/1.1.1/qwerty_mobishifted.png
  keyboard/obolo_qwerty/1.1.1/qwerty_shifted.png
  keyboard/obolo_qwerty/1.1.1/qwertyftkey1.png
  keyboard/obolo_qwerty/1.1.1/qwertyftkey2.png
  keyboard/obolo_qwerty/1.1.1/qwertyftkey3.png
Labels: auto

#886 auto: Keyboard help deployment
  keyboard/behdini_arab/1.0.1/behdini_arab.php
  keyboard/sorani_behdini_arab_qwerty/1.0.1/sorani_behdini_arab_qwerty.php
Labels: auto

#882 chore: Add docs for Android HTML banner
  developer/engine/android/17.0/KMManager/copyHTMLBannerAssets.md
  developer/engine/android/17.0/KMManager/index.php
  developer/engine/android/17.0/KMManager/setHTMLBanner.md
Labels: staging

#889 docs(developer): clarify non-usage of virtual keys in output of rules
  developer/language/guide/virtual-keys.md
Labels: docs

#891 auto: Keyboard help deployment
  keyboard/dogra_inscript/1.0.2/dogra_inscript.php
  keyboard/lao_2008_basic/1.2.2/lao_2008_basic.php
  keyboard/lao_2008_basic/1.2.2/lao_2008_basicU_.png
  keyboard/lao_2008_basic/1.2.2/lao_2008_basicU_RA.png
  keyboard/lao_2008_basic/1.2.2/lao_2008_basicU_S.png
  keyboard/lao_2008_rapid/1.1.3/lao_2008_rapid.php
  keyboard/lao_2008_rapid/1.1.3/lao_2008_rapidU_.png
  keyboard/lao_2008_rapid/1.1.3/lao_2008_rapidU_RA.png
  keyboard/lao_2008_rapid/1.1.3/lao_2008_rapidU_S.png
  keyboard/makasar_inscript/1.0.2/makasar_inscript.php
  keyboard/masaram_gondi/1.2.2/gondi_keyboard_with_shift.jpg
  keyboard/masaram_gondi/1.2.2/gondi_keyboard_without_shift.jpg
  keyboard/masaram_gondi/1.2.2/icon.png
  keyboard/masaram_gondi/1.2.2/m_normal.png
  keyboard/masaram_gondi/1.2.2/m_shifted.png
  keyboard/masaram_gondi/1.2.2/masaram_gondi.php
Labels: auto

#883 chore: Remove legacy k8s files 🦭
  Readme.md
  resources/kubectl/help-kubectl-deploy.yaml
  resources/kubectl/help-kubectl-dev.yaml
  resources/kubectl/help-kubectl.yaml
Labels: staging

#892 auto: Keyboard help deployment
  keyboard/bhaiksuki_inscript/1.0.1/bhaiksuki_inscript.php
  keyboard/brahmi_inscript/1.0.1/brahmi_inscript.php
  keyboard/buhid/1.0.1/buhid.php
  keyboard/hatran_inscript/1.0.1/hatran_inscript.php
  keyboard/kharoshthi_inscript/1.0.2/kharoshthi_inscript.php
  keyboard/khojki_inscript/1.0.3/khojki_inscript.php
  keyboard/modi_inscript/1.0.1/modi_inscript.php
  keyboard/multani_inscript/1.0.2/multani_inscript.php
  keyboard/nabataean_inscript/1.0.1/nabataean_inscript.php
  keyboard/siddham_inscript/1.0.1/siddham_inscript.php
  keyboard/tagbanwa_inscript/1.0.2/tagbanwa_inscript.php
Labels: auto

#893 auto: Keyman for android help deployment
  products/android/16.0/about/whatsnew.md
Labels: auto
