Repository keymanapp/help.keyman.com, pull requests merged in 2023-09, with the labels that each got.

#803 chore: Remove references to keyboard-touch-mobile-emulator
  .htaccess
  developer/16.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
  developer/16.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic.php
  developer/16.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard.php
  developer/16.0/guides/test/index.md
  developer/16.0/guides/test/keyboard-touch-and-desktop.md
  developer/16.0/guides/test/lexical-model.md
  developer/engine/iphone-and-ipad/16.0/guides/in-app/index.php
Labels: staging

#801 fix: Use .localhost instead of .local 🦭
  _common/KeymanHosts.php
Labels: staging

#808 chore: Merge master to staging for Sprint A17S21
  keyboard/fv_hulquminum_combine/1.0/fv_hulquminum_combine.php
  keyboard/fv_kwakwala_liqwala/9.2.4/Kwakwala_LiqwalaU_.png
  keyboard/fv_kwakwala_liqwala/9.2.4/fv_kwakwala_liqwala.php
  keyboard/fv_southern_tutchone/9.2.1/fv_southern_tutchone.php
  keyboard/fv_taltan/9.1.5/FVLogo.gif
  keyboard/fv_taltan/9.1.5/Tahltan.png
  keyboard/fv_taltan/9.1.5/fv_taltan.php
  keyboard/gff_geez_emufi/1.0/EMUFI-Typing-Manual.pdf
  keyboard/gff_geez_emufi/1.0/GeezTyping-English.pdf
  keyboard/gff_geez_emufi/1.0/gff_geez_emufi.php
  keyboard/gff_geez_emufi/1.0/images/Anqetse-Haleita.png
  keyboard/gff_geez_emufi/1.0/images/Basic-and-Extended-Qirts.png
  keyboard/gff_geez_emufi/1.0/images/Diret-Difat-Short-Rikrik.png
  keyboard/gff_geez_emufi/1.0/images/Extending-Hidets.png
  keyboard/gff_geez_emufi/1.0/images/Ligatures.png
  keyboard/gff_geez_emufi/1.0/images/Marginal-Markers.png
  keyboard/gff_geez_emufi/1.0/images/Numeral-Input-List.png
  keyboard/gff_geez_emufi/1.0/images/Numeral-Input-Tree.png
  keyboard/gff_geez_emufi/1.0/images/Numeral-Styles-Compared.png
  keyboard/gff_geez_emufi/1.0/images/Punctuation-Arat-Neteb-Chaining.png
  keyboard/gff_geez_emufi/1.0/images/Punctuation-Chaining-Spacer.png
  keyboard/gff_geez_emufi/1.0/images/Punctuation-Input-List.png
  keyboard/gff_geez_emufi/1.0/images/Punctuation-Input-Tree.png
  keyboard/gff_geez_emufi/1.0/images/Punctuation-Stylus-Drags.png
  keyboard/gff_geez_emufi/1.0/images/Qirts-Extending-Hidets.png
  keyboard/gff_geez_emufi/1.0/images/Qirts-Input-List.png
  keyboard/gff_geez_emufi/1.0/images/Qirts-Input-Tree.png
  keyboard/gff_geez_emufi/1.0/images/Rubricated-AratNeteb.png
  keyboard/gff_geez_emufi/1.0/images/Rubricated-Semicolon.png
  keyboard/gff_geez_emufi/1.0/images/Variants.png
  keyboard/korean_rr/1.3/IME1.png
  keyboard/korean_rr/1.3/IME1a.png
  keyboard/korean_rr/1.3/IME2.png
  keyboard/korean_rr/1.3/IME3.png
  keyboard/korean_rr/1.3/IME4.png
  keyboard/korean_rr/1.3/PageDown.png
  keyboard/korean_rr/1.3/korean_rr.php
  keyboard/old_hungarian/1.7.5/old_hungarian.php
  products/mac/13.0/common-questions/osk.md
Labels: staging

#813 chore: Update site_suffix with KEYMAN_COM_PROXY_PORT 🦭
  _common/KeymanHosts.php
Labels: staging

#816 refactor: split common parts out of build.sh
  _common/docker.inc.sh
  _common/keyman-local-ports.inc.sh
  build.sh
Labels: staging, refactor

#817 feat: move common files to keymanapp/shared-sites
  .gitignore
  _common/JsonApiFailure.php
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _common/MarkdownHost.php
  _common/README.md
  _common/docker.inc.sh
  _common/keyman-local-ports.inc.sh
  build.sh
  resources/builder.inc.sh
Labels: staging, feat
