Repository keymanapp/help.keyman.com, pull requests merged in 2023-08, with the labels that each got.

#785 auto: Keyman for windows help deployment
  products/windows/17.0/about/requirements.md
  products/windows/17.0/advanced/text_services_framework.md
  products/windows/17.0/basic/config/options.md
  products/windows/17.0/basic/make-taskbar-icon-visible.md
  products/windows/17.0/basic/select-keyboard.md
  products/windows/17.0/basic/uninstall.md
  products/windows/17.0/common/os.md
  products/windows/17.0/common/requirements.md
  products/windows/17.0/troubleshooting/hidden.md
  products/windows/17.0/troubleshooting/index.md
Labels: auto

#784 Merge master to staging for Sprint A17S18
  keyboard/el_dari_clra/1.0.1/el_dari_clra.php
  keyboard/el_osmanya/1.0.1/el_osmanya.php
  keyboard/el_pan_sahelian/3.2.1/el_pan_sahelian.php
  keyboard/fv_nsilxcen/9.2/fv_nsilxcen.php
  keyboard/fv_nsilxcen/9.2/nsilxcenU_help.png
  keyboard/gff_amh_7/1.5.1/AmharicTyping-Amharic.pdf
  keyboard/gff_amh_7/1.5.1/AmharicTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/AwngiTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/BenchTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/BlinTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/GeezTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/MeenTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/SebatbeitTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/TigrignaErTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/TigrignaEtTyping-English.pdf
  keyboard/gff_amh_7/1.5.1/chart.pdf
  keyboard/gff_amh_7/1.5.1/gff_amh_7.php
  keyboard/grkpoly2/2.0.1/grkpoly2.php
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-package-install.md
Labels: staging

#799 epic: Add Docker container name 🦭
  build.sh
  resources/builder.inc.sh
Labels: staging, epic-linux-hosting
