Repository keymanapp/help.keyman.com, pull requests merged in 2024-10, with the labels that each got.

#1581 chore: convert docs in dev/engi/web/17/ref/osk
  developer/engine/web/17.0/reference/osk/addEventListener.md
  developer/engine/web/17.0/reference/osk/addEventListener.php
  developer/engine/web/17.0/reference/osk/classes.md
  developer/engine/web/17.0/reference/osk/getRect.md
  developer/engine/web/17.0/reference/osk/getRect.php
  developer/engine/web/17.0/reference/osk/hide.md
  developer/engine/web/17.0/reference/osk/hide.php
  developer/engine/web/17.0/reference/osk/index.md
  developer/engine/web/17.0/reference/osk/index.php
  developer/engine/web/17.0/reference/osk/isEnabled.md
  developer/engine/web/17.0/reference/osk/isEnabled.php
  developer/engine/web/17.0/reference/osk/isVisible.md
  developer/engine/web/17.0/reference/osk/isVisible.php
  developer/engine/web/17.0/reference/osk/removeEventListener.md
  developer/engine/web/17.0/reference/osk/removeEventListener.php
  developer/engine/web/17.0/reference/osk/setPos.md
  developer/engine/web/17.0/reference/osk/setPos.php
  developer/engine/web/17.0/reference/osk/setRect.md
  developer/engine/web/17.0/reference/osk/setRect.php
  developer/engine/web/17.0/reference/osk/show.md
  developer/engine/web/17.0/reference/osk/show.php
  developer/engine/web/17.0/reference/osk/userLocated.md
  developer/engine/web/17.0/reference/osk/userLocated.php
Labels: chore

#1582 chore: convert docs of dev/engi/web/17/ref/interface
  developer/engine/web/17.0/reference/interface/_nul.md
  developer/engine/web/17.0/reference/interface/_nul.php
  developer/engine/web/17.0/reference/interface/any.md
  developer/engine/web/17.0/reference/interface/any.php
  developer/engine/web/17.0/reference/interface/beep.md
  developer/engine/web/17.0/reference/interface/beep.php
  developer/engine/web/17.0/reference/interface/beepReset.md
  developer/engine/web/17.0/reference/interface/beepReset.php
  developer/engine/web/17.0/reference/interface/context.md
  developer/engine/web/17.0/reference/interface/context.php
  developer/engine/web/17.0/reference/interface/contextMatch.md
  developer/engine/web/17.0/reference/interface/contextMatch.php
  developer/engine/web/17.0/reference/interface/deadkeyMatch.md
  developer/engine/web/17.0/reference/interface/deadkeyMatch.php
  developer/engine/web/17.0/reference/interface/deadkeyOutput.md
  developer/engine/web/17.0/reference/interface/deadkeyOutput.php
  developer/engine/web/17.0/reference/interface/deleteContext.md
  developer/engine/web/17.0/reference/interface/deleteContext.php
  developer/engine/web/17.0/reference/interface/fullContextMatch.md
  developer/engine/web/17.0/reference/interface/fullContextMatch.php
  developer/engine/web/17.0/reference/interface/ifStore.md
  developer/engine/web/17.0/reference/interface/ifStore.php
  developer/engine/web/17.0/reference/interface/index.md
  developer/engine/web/17.0/reference/interface/index.php
  developer/engine/web/17.0/reference/interface/indexOutput.md
  developer/engine/web/17.0/reference/interface/indexOutput.php
  developer/engine/web/17.0/reference/interface/insertText.md
  developer/engine/web/17.0/reference/interface/insertText.php
  developer/engine/web/17.0/reference/interface/isKeypress.md
  developer/engine/web/17.0/reference/interface/isKeypress.php
  developer/engine/web/17.0/reference/interface/keyInformation.md
  developer/engine/web/17.0/reference/interface/keyInformation.php
  developer/engine/web/17.0/reference/interface/keyMatch.md
  developer/engine/web/17.0/reference/interface/keyMatch.php
  developer/engine/web/17.0/reference/interface/loadStore.md
  developer/engine/web/17.0/reference/interface/loadStore.php
  developer/engine/web/17.0/reference/interface/output.md
  developer/engine/web/17.0/reference/interface/output.php
  developer/engine/web/17.0/reference/interface/registerKeyboard.md
  developer/engine/web/17.0/reference/interface/registerKeyboard.php
  developer/engine/web/17.0/reference/interface/registerStub.md
  developer/engine/web/17.0/reference/interface/registerStub.php
  developer/engine/web/17.0/reference/interface/saveFocus.md
  developer/engine/web/17.0/reference/interface/saveFocus.php
  developer/engine/web/17.0/reference/interface/saveStore.md
  developer/engine/web/17.0/reference/interface/saveStore.php
  developer/engine/web/17.0/reference/interface/setStore.md
  developer/engine/web/17.0/reference/interface/setStore.php
  developer/engine/web/17.0/reference/interface/stateMatch.md
  developer/engine/web/17.0/reference/interface/stateMatch.php
Labels: chore

#1584 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0/LayoutU_.png
  keyboard/gautami_thamizh_tamil/1.0/LayoutU_RA.png
  keyboard/gautami_thamizh_tamil/1.0/LayoutU_S.png
  keyboard/gautami_thamizh_tamil/1.0/LayoutU_SRA.png
  keyboard/gautami_thamizh_tamil/1.0/gautami_thamizh_tamil.php
Labels: auto

#1587 auto: Keyboard help deployment
  keyboard/basic_kbdheb/1.1.1/basic_kbdheb.php
  keyboard/basic_kbdhebl3/1.1.1/basic_kbdhebl3.php
  keyboard/sil_hebrew/2.0.2/sil_hebrew.php
  keyboard/sil_hebrew_legacy/1.0.1/sil_hebrew_legacy.php
Labels: auto

#1590 auto: Keyboard help deployment
  keyboard/marchen_direct_input/1.0/marchen_direct_input.php
Labels: auto

#1591 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0.1/LayoutU_.png
  keyboard/gautami_thamizh_tamil/1.0.1/LayoutU_RA.png
  keyboard/gautami_thamizh_tamil/1.0.1/LayoutU_S.png
  keyboard/gautami_thamizh_tamil/1.0.1/LayoutU_SRA.png
  keyboard/gautami_thamizh_tamil/1.0.1/gautami_thamizh_tamil.pdf
  keyboard/gautami_thamizh_tamil/1.0.1/gautami_thamizh_tamil.php
Labels: auto

#1592 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0.1/gautami_thamizh_tamil.pdf
Labels: auto

#1597 auto: Keyboard help deployment
  keyboard/pt_pro/1.0.1/pt_pro.php
Labels: auto

#1594 chore: convert docs of dev/engi/web/17/ref/core
  developer/engine/web/17.0/reference/core/BuildVisualKeyboard.md
  developer/engine/web/17.0/reference/core/BuildVisualKeyboard.php
  developer/engine/web/17.0/reference/core/activatingUI.md
  developer/engine/web/17.0/reference/core/activatingUI.php
  developer/engine/web/17.0/reference/core/addEventListener.md
  developer/engine/web/17.0/reference/core/addEventListener.php
  developer/engine/web/17.0/reference/core/addHotKey.md
  developer/engine/web/17.0/reference/core/addHotKey.php
  developer/engine/web/17.0/reference/core/attachToControl.md
  developer/engine/web/17.0/reference/core/attachToControl.php
  developer/engine/web/17.0/reference/core/build.md
  developer/engine/web/17.0/reference/core/build.php
  developer/engine/web/17.0/reference/core/detachFromControl.md
  developer/engine/web/17.0/reference/core/detachFromControl.php
  developer/engine/web/17.0/reference/core/disableControl.md
  developer/engine/web/17.0/reference/core/disableControl.php
  developer/engine/web/17.0/reference/core/enableControl.md
  developer/engine/web/17.0/reference/core/enableControl.php
  developer/engine/web/17.0/reference/core/focusLastActiveElement.md
  developer/engine/web/17.0/reference/core/focusLastActiveElement.php
  developer/engine/web/17.0/reference/core/getActiveKeyboard.md
  developer/engine/web/17.0/reference/core/getActiveKeyboard.php
  developer/engine/web/17.0/reference/core/getActiveLanguage.md
  developer/engine/web/17.0/reference/core/getActiveLanguage.php
  developer/engine/web/17.0/reference/core/getKeyboard.md
  developer/engine/web/17.0/reference/core/getKeyboard.php
  developer/engine/web/17.0/reference/core/getKeyboardForControl.md
  developer/engine/web/17.0/reference/core/getKeyboardForControl.php
  developer/engine/web/17.0/reference/core/getKeyboards.md
  developer/engine/web/17.0/reference/core/getKeyboards.php
  developer/engine/web/17.0/reference/core/getLastActiveElement.md
  developer/engine/web/17.0/reference/core/getLastActiveElement.php
  developer/engine/web/17.0/reference/core/getSavedKeyboard.md
  developer/engine/web/17.0/reference/core/getSavedKeyboard.php
  developer/engine/web/17.0/reference/core/getUIState.md
  developer/engine/web/17.0/reference/core/getUIState.php
  developer/engine/web/17.0/reference/core/helpURL.md
  developer/engine/web/17.0/reference/core/helpURL.php
  developer/engine/web/17.0/reference/core/index.md
  developer/engine/web/17.0/reference/core/isCJK.md
  developer/engine/web/17.0/reference/core/isCJK.php
  developer/engine/web/17.0/reference/core/isChiral.md
  developer/engine/web/17.0/reference/core/isChiral.php
  developer/engine/web/17.0/reference/core/moveToElement.md
  developer/engine/web/17.0/reference/core/moveToElement.php
  developer/engine/web/17.0/reference/core/removeEventListener.md
  developer/engine/web/17.0/reference/core/removeEventListener.php
  developer/engine/web/17.0/reference/core/removeHotKey.md
  developer/engine/web/17.0/reference/core/removeHotKey.php
  developer/engine/web/17.0/reference/core/removeKeyboards.md
  developer/engine/web/17.0/reference/core/removeKeyboards.php
  developer/engine/web/17.0/reference/core/resetContext.md
  developer/engine/web/17.0/reference/core/resetContext.php
  developer/engine/web/17.0/reference/core/setActiveKeyboard.md
  developer/engine/web/17.0/reference/core/setActiveKeyboard.php
  developer/engine/web/17.0/reference/core/setKeyboardForControl.md
  developer/engine/web/17.0/reference/core/setKeyboardForControl.php
  developer/engine/web/17.0/reference/core/version.md
  developer/engine/web/17.0/reference/core/version.php
Labels: chore

#1595 chore: convert docs of dev/engi/web/17/troubleshooting
  developer/engine/web/17.0/troubleshooting/embedded_fonts.md
  developer/engine/web/17.0/troubleshooting/embedded_fonts.php
  developer/engine/web/17.0/troubleshooting/index.md
  developer/engine/web/17.0/troubleshooting/index.php
  developer/engine/web/17.0/troubleshooting/osk.md
  developer/engine/web/17.0/troubleshooting/osk.php
Labels: chore

#1596 chore: convert docs of dev/engi/web/17/ui
  developer/engine/web/17.0/ui/index.md
  developer/engine/web/17.0/ui/index.php
  developer/engine/web/17.0/ui/osk.md
  developer/engine/web/17.0/ui/osk.php
  developer/engine/web/17.0/ui/ui-button.md
  developer/engine/web/17.0/ui/ui-button.php
  developer/engine/web/17.0/ui/ui-floating.md
  developer/engine/web/17.0/ui/ui-floating.php
  developer/engine/web/17.0/ui/ui-toggle.md
  developer/engine/web/17.0/ui/ui-toggle.php
  developer/engine/web/17.0/ui/ui-toolbar.md
  developer/engine/web/17.0/ui/ui-toolbar.php
Labels: chore

#1598 auto: Keyboard help deployment
  keyboard/pt_pro/1.0.2/pt_pro.php
Labels: auto

#1599 auto: Keyboard help deployment
  keyboard/nandinagari_inscript/1.0/nandinagari_inscript.php
Labels: auto

#1601 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/2.0.1/taigi_viet_telex.php
  keyboard/taigi_viet_telex/2.0.1/taigitelexU_.png
  keyboard/taigi_viet_telex/2.0.1/taigitelexU_S.png
Labels: auto

#1600 chore: convert docs of dev/engi/iphone-ipad/16/index & /TypeKeymanPackage
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/findResource.md
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/findResource.php
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/index.md
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/index.php
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/installables.md
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/installables.php
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/installables_forLanguage.md
  developer/engine/iphone-and-ipad/16.0/TypedKeymanPackage/installables_forLanguage.php
  developer/engine/iphone-and-ipad/16.0/index.md
  developer/engine/iphone-and-ipad/16.0/index.php
Labels: chore

#1606 auto: Keyboard help deployment
  keyboard/pt_international/1.0/pt_international.php
Labels: auto

#1603 chore: convert docs of dev/engi/iphone-and-ipad/16/TextView
  developer/engine/iphone-and-ipad/16.0/TextView/dismissKeyboard.md
  developer/engine/iphone-and-ipad/16.0/TextView/dismissKeyboard.php
  developer/engine/iphone-and-ipad/16.0/TextView/index.md
  developer/engine/iphone-and-ipad/16.0/TextView/index.php
  developer/engine/iphone-and-ipad/16.0/TextView/setKeymanDelegate.md
  developer/engine/iphone-and-ipad/16.0/TextView/setKeymanDelegate.php
Labels: chore

#1563 fix: Skip CDN for --debug builds
  build.sh
  resources/init-container.sh
Labels: fix

#1605 chore: convert docs of dev/engi/iphone-and-ipad/16/package and /resource
  developer/engine/iphone-and-ipad/16.0/PackageWebViewController/index.md
  developer/engine/iphone-and-ipad/16.0/PackageWebViewController/index.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/getInstalledPackage.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/getInstalledPackage.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/index.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/index.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/install.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/install.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/installState.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/installState.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/installedPackages.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/installedPackages.php
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/prepareKMPInstall.md
  developer/engine/iphone-and-ipad/16.0/ResourceFileManager/prepareKMPInstall.php
Labels: chore

#1604 chore: convert docs of dev/engi/iphone-and-ipad/16/textfield
  developer/engine/iphone-and-ipad/16.0/TextField/dismissKeyboard.md
  developer/engine/iphone-and-ipad/16.0/TextField/dismissKeyboard.php
  developer/engine/iphone-and-ipad/16.0/TextField/index.md
  developer/engine/iphone-and-ipad/16.0/TextField/index.php
  developer/engine/iphone-and-ipad/16.0/TextField/setKeymanDelegate.md
  developer/engine/iphone-and-ipad/16.0/TextField/setKeymanDelegate.php
Labels: chore

#1608 fix: override KeymanWeb CSS for z-index for documentation OSK
  cdn/dev/css/keyboard.css
Labels: fix

#1616 auto: Keyboard help deployment
  keyboard/old_north_arabian_phonetic/1.0/old_north_arabian_phonetic.php
Labels: auto

#1612 chore: convert docs of `developer\engine\iphone-and-ipad\16.0\Manager`
  developer/engine/iphone-and-ipad/16.0/Manager/addKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/addKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/canAddNewKeyboards.md
  developer/engine/iphone-and-ipad/16.0/Manager/canAddNewKeyboards.php
  developer/engine/iphone-and-ipad/16.0/Manager/currentKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/currentKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/dismissKeyboardPicker.md
  developer/engine/iphone-and-ipad/16.0/Manager/dismissKeyboardPicker.php
  developer/engine/iphone-and-ipad/16.0/Manager/downloadKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/downloadKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/downloadLexicalModel.md
  developer/engine/iphone-and-ipad/16.0/Manager/downloadLexicalModel.php
  developer/engine/iphone-and-ipad/16.0/Manager/fontNameForKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/fontNameForKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/hideKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/hideKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/keyboardHeight.md
  developer/engine/iphone-and-ipad/16.0/Manager/keyboardHeight.php
  developer/engine/iphone-and-ipad/16.0/Manager/removeKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/removeKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/setKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/setKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/showKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/showKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/showKeyboardPicker.md
  developer/engine/iphone-and-ipad/16.0/Manager/showKeyboardPicker.php
  developer/engine/iphone-and-ipad/16.0/Manager/stateForKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/stateForKeyboard.php
  developer/engine/iphone-and-ipad/16.0/Manager/stateForLexicalModel.md
  developer/engine/iphone-and-ipad/16.0/Manager/stateForLexicalModel.php
  developer/engine/iphone-and-ipad/16.0/Manager/switchToNextKeyboard.md
  developer/engine/iphone-and-ipad/16.0/Manager/switchToNextKeyboard.php
Labels: chore

#1626 auto: Keyman for developer help deployment
  developer/18.0/reference/file-types/kmp.md
  developer/18.0/reference/file-types/kmx.md
Labels: auto

#1627 auto: Keyboard help deployment
  keyboard/inscriptional_pahlavi_phonetic/1.0/inscriptional_pahlavi_phonetic.php
  keyboard/psalter_pahlavi_phonetic/1.0/psalter_pahlavi_phonetic.php
Labels: auto

#1613 chore: convert docs of `developer\engine\iphone-and-ipad\16.0\KeymanPackage` & `\LanguageResource`
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/index.md
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/index.php
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/installableResourceSets.md
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/installableResourceSets.php
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/installableResources.md
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/installableResources.php
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/key.md
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/key.php
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/pageURL.md
  developer/engine/iphone-and-ipad/16.0/KeymanPackage/pageURL.php
  developer/engine/iphone-and-ipad/16.0/LanguageResource/LanguageResourceFullID.md
  developer/engine/iphone-and-ipad/16.0/LanguageResource/LanguageResourceFullID.php
  developer/engine/iphone-and-ipad/16.0/LanguageResource/index.md
Labels: chore, docs

#1614 chore: convert docs of `developer\engine\iphone-and-ipad\16.0\KeyboardPickerBarButtonItem` and `\KeyboardPickerButton`
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerBarButtonItem/index.md
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerBarButtonItem/index.php
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerButton/index.md
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerButton/index.php
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerButton/setTitle.md
  developer/engine/iphone-and-ipad/16.0/KeyboardPickerButton/setTitle.php
Labels: chore, docs

#1615 chore: convert docs of `developer\engine\iphone-and-ipad\16.0\guides`
  developer/engine/iphone-and-ipad/16.0/guides/in-app/index.md
  developer/engine/iphone-and-ipad/16.0/guides/in-app/index.php
  developer/engine/iphone-and-ipad/16.0/guides/index.md
  developer/engine/iphone-and-ipad/16.0/guides/index.php
  developer/engine/iphone-and-ipad/16.0/guides/system-keyboard/index.md
  developer/engine/iphone-and-ipad/16.0/guides/system-keyboard/index.php
Labels: chore, docs

#1628 auto: Keyboard help deployment
  keyboard/hakka/1.2/consonants.png
  keyboard/hakka/1.2/h.png
  keyboard/hakka/1.2/hakka.php
  keyboard/hakka/1.2/taigitelexU_.png
  keyboard/hakka/1.2/taigitelexU_S.png
  keyboard/hakka/1.2/tones.png
  keyboard/hakka/1.2/vowels.png
Labels: auto

#1629 auto: Keyboard help deployment
  keyboard/inscriptional_parthian_phonetic/1.0/inscriptional_parthian_phonetic.php
Labels: auto

#1630 auto: Keyboard help deployment
  keyboard/yezidi/1.0.1/yezidi.php
Labels: auto

#1639 auto: Keyboard help deployment
  keyboard/yo/1.0.3/yo.php
  keyboard/yo/1.0.3/yofl-l.jpg
  keyboard/yo/1.0.3/yofl-l1.jpg
Labels: auto

#1640 auto: Keyboard help deployment
  keyboard/khudawadi_inscript/1.0/khudawadi_inscript.php
Labels: auto

#1641 auto: Keyboard help deployment
  keyboard/mahajani_inscript/1.0/mahajani_inscript.php
Labels: auto

#1645 docs: update file layout link for DISCUS
  developer/keyboards/standard/index.md
Labels: docs

#1646 auto: Keyboard help deployment
  keyboard/old_persian/1.0/old_persian.php
Labels: auto

#1647 auto: Keyboard help deployment
  keyboard/taiwan_austronesian/1.0/default.png
  keyboard/taiwan_austronesian/1.0/number.png
  keyboard/taiwan_austronesian/1.0/shift.png
  keyboard/taiwan_austronesian/1.0/taiwan_austronesian.php
  keyboard/taiwan_austronesian/1.0/welcome.htm
Labels: auto

#1650 auto: Keyboard help deployment
  keyboard/avestan_phonetic/1.0/avestan_phonetic.php
Labels: auto

#1659 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/common-types.commontypesmessages.md
  developer/18.0/reference/messages/km01009.md
  developer/18.0/reference/messages/kmc-package.packagecompilermessages.md
Labels: auto

#1660 auto: Keyboard help deployment
  keyboard/manga_ajami_azerty/1.0/manga_ajami_azerty.php
  keyboard/manga_ajami_qwerty/1.0/manga_ajami_qwerty.php
  keyboard/manga_latin_azerty/1.0/manga_latin_azerty.php
  keyboard/manga_latin_qwerty/1.0/manga_latin_qwerty.php
Labels: auto

#1661 auto: Keyboard help deployment
  keyboard/taiwan_austronesian/1.1/TAU_.png
  keyboard/taiwan_austronesian/1.1/TAU_S.png
  keyboard/taiwan_austronesian/1.1/default.png
  keyboard/taiwan_austronesian/1.1/number.png
  keyboard/taiwan_austronesian/1.1/shift.png
  keyboard/taiwan_austronesian/1.1/taiwan_austronesian.php
Labels: auto

#1662 auto: Keyboard help deployment
  keyboard/gff_amharic/3.1.2/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/3.1.2/AmharicTyping-English.pdf
  keyboard/gff_amharic/3.1.2/gff_amharic.php
  keyboard/gff_amharic/3.1.2/images/gff_amharic-default-1.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-default-2-orig.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-default-2.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-default-3.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-default-4.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-numerals-1.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-numerals-2.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-numerals-3.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-numerals-4.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-punctuation-1.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-punctuation-2.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-punctuation-3.jpeg
  keyboard/gff_amharic/3.1.2/images/gff_amharic-punctuation-4.jpeg
  keyboard/gff_amharic/3.1.2/kb.css
  keyboard/gff_awngi_xamtanga/1.0.3/AwngiXamtangaTyping-English.pdf
  keyboard/gff_awngi_xamtanga/1.0.3/gff_awngi_xamtanga.php
  keyboard/gff_awngi_xamtanga/1.0.3/kb.css
  keyboard/gff_blin/1.5.5/BlinTyping-English.pdf
  keyboard/gff_blin/1.5.5/gff_blin.php
  keyboard/gff_blin/1.5.5/kb.css
  keyboard/gff_ethiopic/1.0.2/EthiopicTyping-English.pdf
  keyboard/gff_ethiopic/1.0.2/gff_ethiopic.php
  keyboard/gff_ethiopic/1.0.2/kb.css
  keyboard/gff_geez/2.0.2/GeezTyping-English.pdf
  keyboard/gff_geez/2.0.2/gff_geez.php
  keyboard/gff_gurage/1.0.1/GurageTyping-English.pdf
  keyboard/gff_gurage/1.0.1/GurageTyping-Gurage.pdf
  keyboard/gff_gurage/1.0.1/gff_gurage.php
  keyboard/gff_gurage/1.0.1/kb.css
  keyboard/gff_gurage_and_amharic/1.1.1/gff_gurage_and_amharic.php
  keyboard/gff_harari/1.0.5/HarariTyping-English.pdf
  keyboard/gff_harari/1.0.5/gff_harari.php
  keyboard/gff_harari/1.0.5/images/gff_harari-default-1.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-default-2.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-default-3.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-default-4.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-default-5.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-default-6.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-extra-1.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-extra-2.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-extra-3.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-labiovelar-1.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-labiovelar-2.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-punctuation-1.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-punctuation-2.jpeg
  keyboard/gff_harari/1.0.5/images/gff_harari-punctuation-3.jpeg
  keyboard/gff_harari/1.0.5/kb.css
  keyboard/gff_tigre/1.0.3/TigreTyping-English.pdf
  keyboard/gff_tigre/1.0.3/gff_tigre.php
  keyboard/gff_tigre/1.0.3/kb.css
  keyboard/gff_tigrinya_eritrea/2.0.3/TigrinyaErTyping-English.pdf
  keyboard/gff_tigrinya_eritrea/2.0.3/gff_tigrinya_eritrea.php
  keyboard/gff_tigrinya_eritrea/2.0.3/kb.css
  keyboard/gff_tigrinya_ethiopia/2.0.4/TigrinyaEtTyping-English.pdf
  keyboard/gff_tigrinya_ethiopia/2.0.4/gff_tigrinya_ethiopia.php
  keyboard/gff_tigrinya_ethiopia/2.0.4/kb.css
Labels: auto

#1663 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km00029.md
  developer/17.0/reference/messages/km00f01.md
  developer/17.0/reference/messages/kmc-ldml.compilermessages.md
Labels: auto

#1664 auto: Keyboard help deployment
  keyboard/gautami_bangla_bengali/1.0/LayoutU_.png
  keyboard/gautami_bangla_bengali/1.0/LayoutU_S.png
  keyboard/gautami_bangla_bengali/1.0/gautami_bangla_bengali.pdf
  keyboard/gautami_bangla_bengali/1.0/gautami_bangla_bengali.php
  keyboard/gautami_devanagari/1.0/LayoutU_.png
  keyboard/gautami_devanagari/1.0/LayoutU_S.png
  keyboard/gautami_devanagari/1.0/gautami_devanagari.pdf
  keyboard/gautami_devanagari/1.0/gautami_devanagari.php
  keyboard/gautami_thamizh_tamil/1.0.2/LayoutU_.png
  keyboard/gautami_thamizh_tamil/1.0.2/LayoutU_S.png
  keyboard/gautami_thamizh_tamil/1.0.2/gautami_thamizh_tamil.pdf
  keyboard/gautami_thamizh_tamil/1.0.2/gautami_thamizh_tamil.php
Labels: auto

#1666 auto: Keyboard help deployment
  keyboard/bj_mista_wasaha_cree/1.2.1/bj_mista_wasaha_cree.php
Labels: auto
