Repository keymanapp/help.keyman.com, pull requests merged in 2024-03, with the labels that each got.

#1050 docs(windows): new knowledge base 113 about right-to-left keyboards with third-party applications
  knowledge-base/assets/kb0113/openoffice-step2.png
  knowledge-base/assets/kb0113/openoffice-step3.png
  knowledge-base/assets/kb0113/openoffice-step4.png
  knowledge-base/assets/kb0113/openoffice-step5.png
  knowledge-base/assets/kb0113/openoffice-step6.png
  knowledge-base/kb0113.md
Labels: docs

#1039 chore: end of polishing the rest of the kb files
  knowledge-base/kb0097.md
  knowledge-base/kb0101.md
  knowledge-base/kb0106.md
  knowledge-base/kb0108.md
Labels: chore

#1079 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1081 auto: Keyboard help deployment
  keyboard/br_nativo/1.0/br_nativo.php
Labels: auto

#1082 auto: Keyboard help deployment
  keyboard/sil_euro_latin/3.0.0/currency.png
  keyboard/sil_euro_latin/3.0.0/digraphs.png
  keyboard/sil_euro_latin/3.0.0/lowercase.png
  keyboard/sil_euro_latin/3.0.0/numbers.png
  keyboard/sil_euro_latin/3.0.0/prefix.png
  keyboard/sil_euro_latin/3.0.0/sil_euro_latin.php
  keyboard/sil_euro_latin/3.0.0/symbols.png
  keyboard/sil_euro_latin/3.0.0/uppercase.png
Labels: auto

#1084 auto: Keyman for linux help deployment
  products/linux/18.0/reference/km-config.md
  products/linux/18.0/reference/km-kvk2ldml.md
  products/linux/18.0/reference/km-package-get.md
  products/linux/18.0/reference/km-package-install.md
  products/linux/18.0/reference/km-package-list-installed.md
  products/linux/18.0/reference/km-package-uninstall.md
Labels: auto

#1083 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1077 chore: setup file layout for compiler messages
  developer/17.0/reference/errors/index.php
  developer/17.0/reference/index.md
  developer/17.0/reference/messages/index.md
Labels: chore

#1086 docs(developer): tweak content around fonts
  developer/17.0/guides/distribute/tutorial/step-2.php
Labels: docs

#1087 docs(developer): `kmc message` reference
  developer/17.0/reference/kmc/cli/reference.md
Labels: docs

#1091 auto: Keyman for linux help deployment
  products/linux/18.0/about/whatsnew.md
  products/linux/18.0/common/index.md
  products/linux/18.0/linux_images/download-khmer-angkor.png
  products/linux/18.0/linux_images/km-config-khmer-angkor.png
  products/linux/18.0/linux_images/km-config.png
  products/linux/18.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/18.0/linux_images/region-language-khmer-angkor.png
  products/linux/18.0/linux_images/search-khmer-angkor.png
Labels: auto

#1092 auto: Keyman for mac help deployment
  products/mac/18.0/about/whatsnew.md
Labels: auto

#1093 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/about/whatsnew.md
  products/iphone-and-ipad/18.0/basic/keyboard-usage.md
  products/iphone-and-ipad/18.0/index.md
  products/iphone-and-ipad/18.0/ios_images/key-submenu.png
  products/iphone-and-ipad/18.0/ios_images/system-keyboard-cal.png
Labels: auto

#1094 auto: Keyman for android help deployment
  products/android/18.0/about/whatsnew.md
  products/android/18.0/android_images/confirm-english-dictionary-delete-ap.png
  products/android/18.0/android_images/confirm-khmer-delete-ap.png
  products/android/18.0/android_images/dist-install1-at.png
  products/android/18.0/android_images/dl-success-ap.png
  products/android/18.0/android_images/english-dictionaries-ap.png
  products/android/18.0/android_images/english-dictionary-info-ap.png
  products/android/18.0/android_images/english-settings-ap.png
  products/android/18.0/android_images/khmer-settings-ap.png
  products/android/18.0/android_images/select_language.png
  products/android/18.0/android_images/settings-2-installed-languages-ap.png
  products/android/18.0/android_images/settings-khmer-info-ap.png
  products/android/18.0/android_images/settings-screen-install-keyboard-dictionary.png
  products/android/18.0/android_images/settings-str-dictionary-ap.png
  products/android/18.0/android_images/settings-str-settings-ap.png
  products/android/18.0/android_images/settings-two-installed-languages-ap.png
  products/android/18.0/android_images/settings1-at.png
  products/android/18.0/android_images/settings2-at.png
  products/android/18.0/android_images/settings7-at.png
  products/android/18.0/android_images/uninstall-dictionary-notification-ap.png
  products/android/18.0/android_images/uninstall-notification-ap.png
Labels: auto

#1095 auto: Keyman for windows help deployment
  products/windows/18.0/about/whatsnew.md
Labels: auto

#1100 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/common-types.commontypesmessages.md
  developer/17.0/reference/messages/km01003.md
  developer/17.0/reference/messages/km01004.md
Labels: auto

#1012 chore: polish kb63-72 files
  knowledge-base/assets/kb0065/flashing_blue.png
  knowledge-base/kb0063.md
  knowledge-base/kb0064.md
  knowledge-base/kb0065.md
  knowledge-base/kb0066.md
  knowledge-base/kb0067.md
  knowledge-base/kb0068.md
  knowledge-base/kb0069.md
  knowledge-base/kb0070.md
  knowledge-base/kb0071.md
  knowledge-base/kb0072.md
Labels: chore

#1102 chore: warn that compiler targets are deprecated
  developer/language/guide/compile-targets.md
Labels: chore

#1112 fix: restore baselayout documentation
  developer/language/reference/baselayout.md
Labels: fix

#1113 auto: Keyman for mac help deployment
  products/mac/16.0/mac_images/privacy-accessibility-alert.png
  products/mac/16.0/mac_images/privacy-documents-alert.png
  products/mac/16.0/mac_images/privacy-keyman-alert.png
  products/mac/16.0/troubleshooting/configure-security.md
Labels: auto

#1114 auto: Keyboard help deployment
  keyboard/fv_dane_zaa_zaage/9.3/fv_dane_zaa_zaage.php
Labels: auto

#1115 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km0000f.md
  developer/17.0/reference/messages/kmc-ldml.compilermessages.md
Labels: auto

#1116 auto: Keyboard help deployment
  keyboard/sil_euro_latin/3.0.1/currency.png
  keyboard/sil_euro_latin/3.0.1/digraphs.png
  keyboard/sil_euro_latin/3.0.1/lowercase.png
  keyboard/sil_euro_latin/3.0.1/numbers.png
  keyboard/sil_euro_latin/3.0.1/prefix.png
  keyboard/sil_euro_latin/3.0.1/sil_euro_latin.php
  keyboard/sil_euro_latin/3.0.1/symbols.png
  keyboard/sil_euro_latin/3.0.1/uppercase.png
Labels: auto

#1118 auto: Keyman for android help deployment
  products/android/17.0/about/index.md
  products/android/17.0/about/privacy.md
  products/android/17.0/index.md
Labels: auto

#1119 auto: Keyman for android help deployment
  products/android/18.0/about/index.md
  products/android/18.0/about/privacy.md
  products/android/18.0/index.md
Labels: auto

#1121 auto: Keyboard help deployment
  keyboard/rawang/1.7/rawang-tablet.md
  keyboard/rawang/1.7/rawang.php
Labels: auto

#1122 auto: Keyboard help deployment
  keyboard/balochi_phonetic/1.6/balochi_phonetic.php
Labels: auto

#1123 auto: Keyboard help deployment
  keyboard/nepali_romanized/1.0.0/nepali_romanized.php
Labels: auto

#1124 auto: Keyboard help deployment
  keyboard/poorna_malayalam_extended_inscript/1.0/poorna_malayalam_extended_inscript.php
  keyboard/poorna_malayalam_extended_inscript/1.0/poorna_malayalam_extended_inscript_layout.png
  keyboard/poorna_malayalam_typewriter/1.0/poorna_malayalam_extended_inscript.php
  keyboard/poorna_malayalam_typewriter/1.0/poorna_malayalam_typewriter_layout.png
Labels: auto

#1125 auto: Keyboard help deployment
  keyboard/poorna_malayalam_typewriter/1.0/poorna_malayalam_typewriter.php
Labels: auto

#1126 auto: Keyboard help deployment
  keyboard/kreative_superlatin/1.1/kreative_superlatin.php
  keyboard/sil_ipa/1.8.7/sil_ipa.php
Labels: auto

#1127 docs: tweak platform.md wording
  developer/language/reference/platform.md
Labels: docs

#1129 auto: Keyboard help deployment
  keyboard/fv_hailzaqvla/9.5.1/fv_hailzaqvla.php
Labels: auto

#1130 docs(core): add 17.0 docs
  developer/core/desktop/17.0/background.md
  developer/core/desktop/17.0/building.md
  developer/core/desktop/17.0/changes.md
  developer/core/desktop/17.0/index.md
  developer/core/desktop/17.0/json-schema.md
  developer/core/desktop/17.0/keyboards.md
  developer/core/desktop/17.0/options.md
  developer/core/desktop/17.0/processor.md
  developer/core/desktop/17.0/state.md
Labels: docs

#1131 auto: Keyboard help deployment
  keyboard/fv_henqeminem/10.0/Henqeminem_U_.png
  keyboard/fv_henqeminem/10.0/Henqeminem_U_RA.png
  keyboard/fv_henqeminem/10.0/fv_henqeminem.php
  keyboard/fv_secwepemctsin/9.2/Secwepemctsin.png
  keyboard/fv_secwepemctsin/9.2/fv_secwepemctsin.php
Labels: auto

#1132 auto: Keyboard help deployment
  keyboard/pt_azerty/1.0/pt_azerty.php
Labels: auto

#1090 docs(developer): context help for LDML windows
  cdn/dev/img/developer/170/ui/frmLDMLEditor.png
  cdn/dev/img/developer/170/ui/frmNewLDMLProjectParameters.png
  developer/17.0/context/index.md
  developer/17.0/context/ldml-debug.md
  developer/17.0/context/ldml-editor.md
  developer/17.0/context/new-ldml-project-parameters.md
Labels: docs

#1105 chore: convert files in developer/17.0/guides/distribute
  developer/17.0/guides/distribute/index.md
  developer/17.0/guides/distribute/index.php
  developer/17.0/guides/distribute/install-kmp-android.md
  developer/17.0/guides/distribute/install-kmp-android.php
  developer/17.0/guides/distribute/install-kmp-ios.md
  developer/17.0/guides/distribute/install-kmp-ios.php
  developer/17.0/guides/distribute/packages.md
  developer/17.0/guides/distribute/packages.php
  developer/17.0/guides/distribute/tutorial/index.md
  developer/17.0/guides/distribute/tutorial/index.php
  developer/17.0/guides/distribute/tutorial/step-1.md
  developer/17.0/guides/distribute/tutorial/step-1.php
  developer/17.0/guides/distribute/tutorial/step-2.md
  developer/17.0/guides/distribute/tutorial/step-2.php
  developer/17.0/guides/distribute/tutorial/step-3.md
  developer/17.0/guides/distribute/tutorial/step-3.php
  developer/17.0/guides/distribute/tutorial/step-4.md
  developer/17.0/guides/distribute/tutorial/step-4.php
  developer/17.0/guides/distribute/tutorial/step-5.md
  developer/17.0/guides/distribute/tutorial/step-5.php
  developer/17.0/guides/distribute/tutorial/step-6.md
  developer/17.0/guides/distribute/tutorial/step-6.php
Labels: chore

#1109 chore: convert files in lexical-model
  developer/17.0/guides/lexical-models/index.md
  developer/17.0/guides/lexical-models/index.php
  developer/17.0/guides/lexical-models/intro/index.md
  developer/17.0/guides/lexical-models/intro/index.php
  developer/17.0/guides/lexical-models/tutorial/index.md
  developer/17.0/guides/lexical-models/tutorial/index.php
  developer/17.0/guides/lexical-models/tutorial/step-1.md
  developer/17.0/guides/lexical-models/tutorial/step-1.php
  developer/17.0/guides/lexical-models/tutorial/step-2.md
  developer/17.0/guides/lexical-models/tutorial/step-2.php
  developer/17.0/guides/lexical-models/tutorial/step-3.md
  developer/17.0/guides/lexical-models/tutorial/step-3.php
  developer/17.0/guides/lexical-models/tutorial/step-4.md
  developer/17.0/guides/lexical-models/tutorial/step-4.php
Labels: chore

#1111 chore: convert files in reference and index file
  developer/17.0/index.md
  developer/17.0/index.php
  developer/17.0/reference/editor-themes.md
  developer/17.0/reference/editor-themes.php
  developer/17.0/reference/errors/index.md
  developer/17.0/reference/errors/index.php
Labels: chore

#1099 chore: convert 17.0 developer/context
  developer/17.0/context/about-tike.md
  developer/17.0/context/character-map.md
  developer/17.0/context/debug.md
  developer/17.0/context/editor.md
  developer/17.0/context/index.md
  developer/17.0/context/key-test.md
  developer/17.0/context/keyboard-editor.md
  developer/17.0/context/messages.md
  developer/17.0/context/messages.php
  developer/17.0/context/model-editor.md
  developer/17.0/context/model-editor.php
  developer/17.0/context/new-lm-project-parameters.md
  developer/17.0/context/new-lm-project-parameters.php
  developer/17.0/context/new-project-parameters.md
  developer/17.0/context/new-project-parameters.php
  developer/17.0/context/new-project.md
  developer/17.0/context/new-project.php
  developer/17.0/context/new.md
  developer/17.0/context/new.php
  developer/17.0/context/options.md
  developer/17.0/context/options.php
  developer/17.0/context/package-editor.md
  developer/17.0/context/project.md
  developer/17.0/context/project.php
  developer/17.0/context/startup.md
  developer/17.0/context/startup.php
Labels: chore

#1106 chore: convert files in 17.0/guides
  developer/17.0/guides/index.md
  developer/17.0/guides/index.php
  developer/17.0/guides/intro.md
  developer/17.0/guides/intro.php
Labels: chore

#1108 chore: convert all files in 17.0/guides/lexical-model/distribute/ and ../distribute/tutorial
  developer/17.0/guides/lexical-models/distribute/index.md
  developer/17.0/guides/lexical-models/distribute/index.php
  developer/17.0/guides/lexical-models/distribute/packages.md
  developer/17.0/guides/lexical-models/distribute/packages.php
  developer/17.0/guides/lexical-models/distribute/tutorial/index.md
  developer/17.0/guides/lexical-models/distribute/tutorial/index.php
  developer/17.0/guides/lexical-models/distribute/tutorial/step-1.md
  developer/17.0/guides/lexical-models/distribute/tutorial/step-1.php
  developer/17.0/guides/lexical-models/distribute/tutorial/step-2.md
  developer/17.0/guides/lexical-models/distribute/tutorial/step-2.php
  developer/17.0/guides/lexical-models/distribute/tutorial/step-3.md
  developer/17.0/guides/lexical-models/distribute/tutorial/step-3.php
  developer/17.0/guides/lexical-models/distribute/tutorial/step-4.md
  developer/17.0/guides/lexical-models/distribute/tutorial/step-4.php
  developer/17.0/guides/lexical-models/distribute/tutorial/step-5.md
  developer/17.0/guides/lexical-models/distribute/tutorial/step-5.php
Labels: chore

#1137 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km09003.md
  developer/17.0/reference/messages/km09004.md
  developer/17.0/reference/messages/km0900b.md
  developer/17.0/reference/messages/km0900c.md
  developer/17.0/reference/messages/km0900f.md
  developer/17.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
Labels: auto

#1138 auto: Keyboard help deployment
  keyboard/fv_statimcets/9.1.4/Statimcets.png
  keyboard/fv_statimcets/9.1.4/fv_statimcets.php
Labels: auto

#1133 fix: escape entities in left-hand menu and title
  _includes/includes/head.php
  _includes/includes/index-content.php
Labels: fix

#1136 docs(developer): Add What's New page
  developer/17.0/index.md
  developer/17.0/whats-new.md
Labels: docs

#1139 auto: Keyboard help deployment
  keyboard/fv_secwepemctsin/9.2/fv_secwepemctsin.php
Labels: auto

#1140 auto: Keyboard help deployment
  keyboard/kreative_supercyrillic/1.1/kreative_supercyrillic.php
Labels: auto

#1141 auto: Keyboard help deployment
  keyboard/fv_plains_cree/11.0/fv_plains_cree.php
  keyboard/fv_plains_cree/11.0/plains_creeU_.png
Labels: auto

#1134 chore: support `latest-version` url format
  .htaccess
  _includes/includes/index-content.php
  _includes/includes/page-version.php
Labels: chore

#1142 auto: Keyboard help deployment
  keyboard/kreative_superipa/1.1/kreative_superipa.php
Labels: auto

#1110 chore: convert files in ./guides/web
  developer/17.0/guides/web/guide_kmw_automatic_control.php
  developer/17.0/guides/web/guide_kmw_automatic_control_loaded.php
  developer/17.0/guides/web/guide_kmw_control_by_control.php
  developer/17.0/guides/web/guide_kmw_defaults.php
  developer/17.0/guides/web/guide_kmw_full_manual_control.php
  developer/17.0/guides/web/guide_kmw_manual_control.php
Labels: chore

#1107 chore: convert all files in 17.0/guides/lexical-model/advanced
  developer/17.0/guides/lexical-models/advanced/index.md
  developer/17.0/guides/lexical-models/advanced/index.php
  developer/17.0/guides/lexical-models/advanced/model-definition-file.md
  developer/17.0/guides/lexical-models/advanced/model-definition-file.php
  developer/17.0/guides/lexical-models/advanced/punctuation.md
  developer/17.0/guides/lexical-models/advanced/punctuation.php
  developer/17.0/guides/lexical-models/advanced/search-term-to-key.md
  developer/17.0/guides/lexical-models/advanced/search-term-to-key.php
  developer/17.0/guides/lexical-models/advanced/unicode-breaker-extension.md
  developer/17.0/guides/lexical-models/advanced/word-breaker.md
  developer/17.0/guides/lexical-models/advanced/word-breaker.php
Labels: chore

#1144 auto: Keyboard help deployment
  keyboard/sil_tanguat/1.0/sil_tanguat.php
Labels: auto

#1145 auto: Keyboard help deployment
  keyboard/korean_phonetic/1.0/korean_phonetic.php
  keyboard/korean_phonetic/1.0/style.css
Labels: auto

#1149 auto: Keyboard help deployment
  keyboard/sudest/1.0.1/sudest.php
Labels: auto

#1147 chore: 17.0 context documentation updates
  cdn/dev/img/developer/170/ui/BuildTab.png
  cdn/dev/img/developer/170/ui/LongPress_Flicks_Multitaps.png
  cdn/dev/img/developer/170/ui/OnScreenKeyboard.png
  cdn/dev/img/developer/170/ui/TouchLayout_Design.png
  cdn/dev/img/developer/170/ui/TouchLayout_Design_2.png
  cdn/dev/img/developer/170/ui/frmModelEditor_Build.png
  cdn/dev/img/developer/170/ui/frmModelEditor_Details.png
  cdn/dev/img/developer/170/ui/frmNewLMProjectParameters.png
  cdn/dev/img/developer/170/ui/frmNewProject.png
  cdn/dev/img/developer/170/ui/frmOptions_CharacterMap.png
  cdn/dev/img/developer/170/ui/frmOptions_Debugger.png
  cdn/dev/img/developer/170/ui/frmOptions_Editor.png
  cdn/dev/img/developer/170/ui/frmOptions_General.png
  cdn/dev/img/developer/170/ui/frmOptions_Server.png
  developer/17.0/context/character-map.md
  developer/17.0/context/index.md
  developer/17.0/context/key-test.md
  developer/17.0/context/keyman-developer.md
  developer/17.0/context/kmc.md
  developer/17.0/context/kmcomp.md
  developer/17.0/context/ldml-debug.md
  developer/17.0/context/ldml-editor.md
  developer/17.0/context/new-ldml-project-parameters.md
  developer/17.0/context/new-lm-project-parameters.md
  developer/17.0/context/select-web-fonts.md
  developer/17.0/context/server.md
Labels: chore

#1152 auto: Keyboard help deployment
  keyboard/fv_klahoose/10.1/FVLogo.gif
  keyboard/fv_klahoose/10.1/fv_klahoose.php
  keyboard/fv_skwxwumesh_snichim/9.3/fv_skwxwumesh_snichim.php
Labels: auto

#1154 chore: fixup links to keyman.com
  _includes/includes/header.php
  _includes/includes/no-menu.php
  _includes/includes/phone-menu.php
  _includes/includes/servervars.php
  _includes/includes/top-menu.php
  contact/index.php
Labels: chore

#1155 chore: seed Developer 18.0 documentation
  developer/18.0/index.md
  developer/18.0/reference/index.md
Labels: chore

#1135 docs(developer): copy touch layout reference material
  developer/17.0/reference/file-types/keyman-touch-layout.md
Labels: docs

#1157 auto: Keyboard help deployment
  keyboard/fv_southern_carrier/10.0/fv_SouthernCarrierGuide.pdf
  keyboard/fv_southern_carrier/10.0/fv_southern_carrier.php
Labels: auto

#1158 auto: Keyboard help deployment
  keyboard/kreative_supersymbol/1.1/kreative_supersymbol.php
Labels: auto

#1159 auto: Keyboard help deployment
  keyboard/nguphing/1.0/nguphing.php
Labels: auto

#1160 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km0000c.md
  developer/17.0/reference/messages/kmc-ldml.compilermessages.md
Labels: auto

#1162 auto: Keyboard help deployment
  keyboard/afghan_turkmen/2.0/afghan_turkmen.php
  keyboard/fv_haisla/2.0/fv_haisla.php
  keyboard/fv_haisla/2.0/fv_haisla_keycombos.pdf
  keyboard/ife_mn/1.0.1/ife_mn.php
Labels: auto

#1163 auto: Keyman for linux help deployment
  products/linux/18.0/reference/km-config.md
  products/linux/18.0/reference/km-kvk2ldml.md
  products/linux/18.0/reference/km-package-get.md
  products/linux/18.0/reference/km-package-install.md
  products/linux/18.0/reference/km-package-list-installed.md
  products/linux/18.0/reference/km-package-uninstall.md
Labels: auto
