Repository keymanapp/help.keyman.com, pull requests merged in 2024-02, with the labels that each got.

#964 chore: Merge master to staging for sprint A17S31
  developer/engine/web/15.0/guide/get-started.php
  developer/engine/web/16.0/guide/get-started.php
  developer/engine/web/17.0/guide/get-started.php
  keyboard/chinuk_wawa/1.4/chinuk_wawa.php
  keyboard/eo_plus/3.0/eo_plus.css
  keyboard/eo_plus/3.0/eo_plus.php
  keyboard/idc_deseret/1.0/idc_deseret.php
  keyboard/sil_tagdal/1.0/sil_tagdal.php
Labels: staging

#970 auto: Keyboard help deployment
  keyboard/eo_plus/3.0.1/eo_plus.css
  keyboard/eo_plus/3.0.1/eo_plus.php
Labels: auto

#966 auto: Keyman for linux help deployment
  products/linux/16.0/reference/km-config.md
  products/linux/16.0/reference/km-kvk2ldml.md
  products/linux/16.0/reference/km-package-get.md
  products/linux/16.0/reference/km-package-install.md
  products/linux/16.0/reference/km-package-list-installed.md
  products/linux/16.0/reference/km-package-uninstall.md
Labels: auto

#976 Merge staging to production for Sprint A17S31
  developer/16.0/guides/lexical-models/distribute/index.md
  developer/16.0/guides/lexical-models/distribute/index.php
  developer/16.0/guides/lexical-models/distribute/packages.md
  developer/16.0/guides/lexical-models/distribute/packages.php
  developer/17.0/guides/develop/touch-keyboard-tutorial/index.md
  developer/17.0/guides/develop/touch-keyboard-tutorial/index.php
  developer/17.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard.md
  developer/17.0/guides/develop/touch-keyboard-tutorial/making-touch-keyboard.php
Labels: production

#979 Update staging to use shared-sites v0.4
  build.sh
Labels: staging

#986 auto: Keyboard help deployment
  keyboard/fv_hailzaqvla/9.5/fv_hailzaqvla.php
Labels: auto

#971 chore: convert 'developer/16.0/guides/lexical-models/tutorial/...'
  developer/16.0/guides/lexical-models/tutorial/index.md
  developer/16.0/guides/lexical-models/tutorial/index.php
  developer/16.0/guides/lexical-models/tutorial/step-1.md
  developer/16.0/guides/lexical-models/tutorial/step-1.php
  developer/16.0/guides/lexical-models/tutorial/step-2.md
  developer/16.0/guides/lexical-models/tutorial/step-2.php
  developer/16.0/guides/lexical-models/tutorial/step-3.md
  developer/16.0/guides/lexical-models/tutorial/step-3.php
  developer/16.0/guides/lexical-models/tutorial/step-4.md
  developer/16.0/guides/lexical-models/tutorial/step-4.php
Labels: chore

#973 chore: convert 'developer/16.0/guides/...'
  developer/16.0/guides/index.md
  developer/16.0/guides/index.php
  developer/16.0/guides/intro.md
  developer/16.0/guides/intro.php
Labels: chore

#974 chore: convert 3f 'developer/16.0/context/...'
  developer/16.0/context/kmlmc.md
  developer/16.0/context/kmlmc.php
  developer/16.0/context/kmlmi.md
  developer/16.0/context/kmlmi.php
  developer/16.0/context/kmlmp.md
  developer/16.0/context/kmlmp.php
Labels: chore

#975 chore: convert 'developer/16.0/context/...'
  developer/16.0/context/messages.md
  developer/16.0/context/messages.php
Labels: chore

#972 chore: convert 'developer/16.0/guides/lexical-models/intro/index' & 'developer/16.0/guides/lexical-models/index'
  developer/16.0/guides/lexical-models/index.md
  developer/16.0/guides/lexical-models/index.php
  developer/16.0/guides/lexical-models/intro/index.md
  developer/16.0/guides/lexical-models/intro/index.php
Labels: chore

#980 chore: convert 5 files in 'developer/16/context/...'
  developer/16.0/context/new.md
  developer/16.0/context/new.php
  developer/16.0/context/options.md
  developer/16.0/context/options.php
  developer/16.0/context/package-editor.md
  developer/16.0/context/package-editor.php
  developer/16.0/context/project.md
  developer/16.0/context/project.php
  developer/16.0/context/startup.md
  developer/16.0/context/startup.php
Labels: chore

#981 chore: convert 'developer/16.0/reference/tools/index.php'
  developer/16.0/reference/tools/index.md
  developer/16.0/reference/tools/index.php
Labels: chore

#990 auto: Keyboard help deployment
  keyboard/fv_nsilxcen/9.3/fv_nsilxcen.php
  keyboard/fv_nsilxcen/9.3/nsilxcenU_help.png
Labels: auto

#991 auto: Keyboard help deployment
  keyboard/fv_denesuline/10.0.1/fv_denesuline.php
  keyboard/fv_denesuline_epsilon/10.0.1/ChipewyanEpsilon.png
  keyboard/fv_denesuline_epsilon/10.0.1/fv_denesuline_epsilon.php
Labels: auto

#997 auto: Keyboard help deployment
  keyboard/fv_cree_latin/10.0/fv_cree_latin.php
  keyboard/fv_cree_latin/10.0/fv_cree_latinU_.png
Labels: auto

#993 chore: Add _control/alive.txt
  _control/alive.txt
Labels: staging, chore

#998 chore: master into staging B17S1
  keyboard/eo_plus/3.0.1/eo_plus.css
  keyboard/eo_plus/3.0.1/eo_plus.php
  keyboard/fv_anishinaabemowin/10.0.1/anishinaabemowinU_.png
  keyboard/fv_anishinaabemowin/10.0.1/fv_anishinaabemowin.php
  keyboard/fv_cree_latin/10.0/fv_cree_latin.php
  keyboard/fv_cree_latin/10.0/fv_cree_latinU_.png
  keyboard/fv_denesuline/10.0.1/fv_denesuline.php
  keyboard/fv_denesuline_epsilon/10.0.1/ChipewyanEpsilon.png
  keyboard/fv_denesuline_epsilon/10.0.1/fv_denesuline_epsilon.php
  keyboard/fv_hailzaqvla/9.5/fv_hailzaqvla.php
  keyboard/fv_nsilxcen/9.3/fv_nsilxcen.php
  keyboard/fv_nsilxcen/9.3/nsilxcenU_help.png
  products/linux/16.0/reference/km-config.md
  products/linux/16.0/reference/km-kvk2ldml.md
  products/linux/16.0/reference/km-package-get.md
  products/linux/16.0/reference/km-package-install.md
  products/linux/16.0/reference/km-package-list-installed.md
  products/linux/16.0/reference/km-package-uninstall.md
Labels: chore, production

#1002 chore: Add info to .htaccess
  .htaccess
  _control/info.php
Labels: production

#988 chore: Cleanup unused .htaccess comments
  .htaccess
Labels: staging

#1013 auto: Keyboard help deployment
  keyboard/aramaic/1.1/aramaic.php
  keyboard/hcesar/1.1.1/hcesar.php
  keyboard/ipauni11/1.0/ipauni11.php
Labels: auto

#1011 chore: no redirect for 404
  .htaccess
  _includes/errors/404.php
Labels: chore

#1018 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1019 auto: Keyman for linux help deployment
  products/linux/18.0/about/history.md
  products/linux/18.0/about/index.md
  products/linux/18.0/about/welcome.md
  products/linux/18.0/about/whatsnew.md
  products/linux/18.0/common/index.md
  products/linux/18.0/index.md
  products/linux/18.0/linux_images/add-input-source-khmer-angkor.png
  products/linux/18.0/linux_images/add-input-source-khmer.png
  products/linux/18.0/linux_images/add-input-source.png
  products/linux/18.0/linux_images/download-khmer-angkor.png
  products/linux/18.0/linux_images/km-config-khmer-angkor.png
  products/linux/18.0/linux_images/km-config.png
  products/linux/18.0/linux_images/mobile viewport.png
  products/linux/18.0/linux_images/onboard.png
  products/linux/18.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/18.0/linux_images/region-and-language.png
  products/linux/18.0/linux_images/region-language-khmer-angkor.png
  products/linux/18.0/linux_images/search-khmer-angkor.png
  products/linux/18.0/linux_images/video.png
  products/linux/18.0/reference/index.md
  products/linux/18.0/reference/km-config.md
  products/linux/18.0/reference/km-kvk2ldml.md
  products/linux/18.0/reference/km-package-get.md
  products/linux/18.0/reference/km-package-install.md
  products/linux/18.0/reference/km-package-list-installed.md
  products/linux/18.0/reference/km-package-uninstall.md
  products/linux/18.0/start/index.md
  products/linux/18.0/start/installing-keyboard.md
Labels: auto

#1020 auto: Keyman for mac help deployment
  products/mac/18.0/about/history.md
  products/mac/18.0/about/index.md
  products/mac/18.0/about/requirements.md
  products/mac/18.0/about/welcome.md
  products/mac/18.0/about/whatsnew.md
  products/mac/18.0/basic/config/index.md
  products/mac/18.0/basic/config/keyboards.md
  products/mac/18.0/basic/config/options.md
  products/mac/18.0/basic/config/support.md
  products/mac/18.0/basic/index.md
  products/mac/18.0/common/adware.md
  products/mac/18.0/common/bug.md
  products/mac/18.0/common/free.md
  products/mac/18.0/common/index.md
  products/mac/18.0/common/keyboards.md
  products/mac/18.0/common/os.md
  products/mac/18.0/common/osk.md
  products/mac/18.0/common/requirements.md
  products/mac/18.0/common/support.md
  products/mac/18.0/index.md
  products/mac/18.0/mac_images/add.png
  products/mac/18.0/mac_images/add_keyman.png
  products/mac/18.0/mac_images/apple_menu.png
  products/mac/18.0/mac_images/go_to_folder.png
  products/mac/18.0/mac_images/help_button.png
  products/mac/18.0/mac_images/icon-fonts.png
  products/mac/18.0/mac_images/icon-help.png
  products/mac/18.0/mac_images/icon-intro.png
  products/mac/18.0/mac_images/icon-keyman.png
  products/mac/18.0/mac_images/icon-osk.png
  products/mac/18.0/mac_images/icon-unicode.png
  products/mac/18.0/mac_images/information_button.png
  products/mac/18.0/mac_images/input_menu.png
  products/mac/18.0/mac_images/keyboards_menu.png
  products/mac/18.0/mac_images/keyman_config.png
  products/mac/18.0/mac_images/keyman_install.png
  products/mac/18.0/mac_images/keyman_menu_config.png
  products/mac/18.0/mac_images/menu_bar.png
  products/mac/18.0/mac_images/menu_bar_keyman.png
  products/mac/18.0/mac_images/osk_amharic.png
  products/mac/18.0/mac_images/privacy_accessibility.png
  products/mac/18.0/mac_images/privacy_files_and_folders.png
  products/mac/18.0/mac_images/privacy_input_monitoring.png
  products/mac/18.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/18.0/mac_images/remove.png
  products/mac/18.0/mac_images/remove_button.png
  products/mac/18.0/mac_images/remove_keyman.png
  products/mac/18.0/mac_images/system_preferences.png
  products/mac/18.0/mac_images/video.png
  products/mac/18.0/start/index.md
  products/mac/18.0/start/install-keyboard.md
  products/mac/18.0/start/install-keyman.md
  products/mac/18.0/start/tutorial.md
  products/mac/18.0/troubleshooting/configure-security.md
  products/mac/18.0/troubleshooting/index.md
  products/mac/18.0/troubleshooting/uninstall-keyman.md
Labels: auto

#1025 auto: Keyman for android help deployment
  products/android/17.0/android_images/dist-install1-ap.png
  products/android/17.0/android_images/dist-storage-permission-ap.png
  products/android/17.0/android_images/english-dictionaries-ap.png
  products/android/17.0/android_images/settings-khmer-info-ap.png
  products/android/17.0/android_images/settings-suggestions-ap.png
  products/android/17.0/android_images/settings1-ap.png
  products/android/17.0/android_images/settings2-ap.png
  products/android/17.0/android_images/settings3-ap.png
  products/android/17.0/android_images/settings4-ap.png
  products/android/17.0/android_images/settings5-ap.png
  products/android/17.0/android_images/settings7-ap.png
  products/android/17.0/android_images/themed-banner.png
  products/android/17.0/basic/index.md
  products/android/17.0/basic/using-keyman-browser.md
  products/android/17.0/basic/using-the-banner.md
  products/android/17.0/context/gestures.md
  products/android/17.0/context/index.md
  products/android/17.0/context/menu-phone.md
  products/android/17.0/context/menu-tablet.md
  products/android/17.0/index.md
  products/android/17.0/start/enabling-system-keyboard.md
Labels: auto

#978 chore: convert 4 in 'developer/16/context/...'
  developer/16.0/context/model-editor.md
  developer/16.0/context/model-editor.php
  developer/16.0/context/new-lm-project-parameters.md
  developer/16.0/context/new-lm-project-parameters.php
  developer/16.0/context/new-project-parameters.md
  developer/16.0/context/new-project-parameters.php
  developer/16.0/context/new-project.md
  developer/16.0/context/new-project.php
Labels: chore, production

#1000 chore: polish kb3-kb13 files
  knowledge-base/kb0003.md
  knowledge-base/kb0004.md
  knowledge-base/kb0005.md
  knowledge-base/kb0006.md
  knowledge-base/kb0007.md
  knowledge-base/kb0008.md
  knowledge-base/kb0009.md
  knowledge-base/kb0010.md
  knowledge-base/kb0011.md
  knowledge-base/kb0012.md
  knowledge-base/kb0013.md
Labels: chore

#1027 auto: Keyboard help deployment
  keyboard/yo/1.0.2/yo.php
  keyboard/yo/1.0.2/yofl-l.jpg
  keyboard/yo/1.0.2/yofl-l1.jpg
Labels: auto

#996 docs(linux): Add KB article troubleshooting typing problems on Linux
  knowledge-base/kb0111.md
Labels: docs

#1029 auto: Keyboard help deployment
  keyboard/fv_hlgaagilda_xaayda_kil/9.3/fv_hlgaagilda_xaayda_kil.php
Labels: auto

#1030 auto: Keyboard help deployment
  keyboard/itrans_bengali/1.0.2/itrans_bengali.php
  keyboard/itrans_bengali/1.0.2/itrans_bengaliU_.png
  keyboard/itrans_bengali/1.0.2/itrans_bengaliU_S.png
Labels: auto

#1031 auto: Keyboard help deployment
  keyboard/yo/1.0.2/yofl-l.jpg
  keyboard/yo/1.0.2/yofl-l1.jpg
Labels: auto

#1026 chore: cherrypick -- Cleanup unused .htaccess comments
  .htaccess
Labels: chore

#1034 auto: Keyman for android help deployment
  products/android/17.0/about/whatsnew.md
  products/android/17.0/android_images/dist-install1-at.png
  products/android/17.0/android_images/settings1-at.png
  products/android/17.0/android_images/settings2-at.png
  products/android/17.0/android_images/settings7-at.png
Labels: auto

#1035 auto: Keyman for ios help deployment
  products/iphone-and-ipad/17.0/about/whatsnew.md
Labels: auto

#1004 chore: polish kb31-40 files
  knowledge-base/kb0031.md
  knowledge-base/kb0032.md
  knowledge-base/kb0033.md
  knowledge-base/kb0034.md
  knowledge-base/kb0035.md
  knowledge-base/kb0036.md
  knowledge-base/kb0037.md
  knowledge-base/kb0038.md
  knowledge-base/kb0040.md
Labels: chore

#1001 chore: polish kb14-kb20 files
  knowledge-base/kb0014.md
  knowledge-base/kb0015.md
  knowledge-base/kb0016.md
  knowledge-base/kb0017.md
  knowledge-base/kb0018.md
  knowledge-base/kb0019.md
  knowledge-base/kb0020.md
Labels: chore

#1040 auto: Keyman for linux help deployment
  products/linux/17.0/common/index.md
  products/linux/17.0/linux_images/download-khmer-angkor.png
  products/linux/17.0/linux_images/km-config-khmer-angkor.png
  products/linux/17.0/linux_images/km-config.png
  products/linux/17.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/17.0/linux_images/region-language-khmer-angkor.png
  products/linux/17.0/linux_images/search-khmer-angkor.png
Labels: auto

#1041 auto: Keyman for mac help deployment
  products/mac/17.0/about/whatsnew.md
Labels: auto

#1045 auto: Keyman for ios help deployment
  products/iphone-and-ipad/17.0/basic/keyboard-usage.md
  products/iphone-and-ipad/17.0/index.md
  products/iphone-and-ipad/17.0/ios_images/key-submenu.png
  products/iphone-and-ipad/17.0/ios_images/system-keyboard-cal.png
Labels: auto

#1046 auto: Keyboard help deployment
  keyboard/shebek/0.9.2/shebek.php
Labels: auto

#1047 auto: Keyboard help deployment
  keyboard/kashmiri_phonetic/1.0/kashmiri_phonetic.php
Labels: auto

#1048 auto: Keyboard help deployment
  keyboard/kashmiri_phonetic/1.0.1/kashmiri_phonetic.php
Labels: auto

#1042 chore: convert all files in troubleshooting
  troubleshooting/hardwarekeyboards.md
  troubleshooting/hardwarekeyboards.php
  troubleshooting/index.md
  troubleshooting/index.php
Labels: chore

#1003 chore: polish and remove html tags in kb21-30 files
  knowledge-base/kb0014.md
  knowledge-base/kb0016.md
  knowledge-base/kb0021.md
  knowledge-base/kb0022.md
  knowledge-base/kb0023.md
  knowledge-base/kb0024.md
  knowledge-base/kb0025.md
  knowledge-base/kb0026.md
  knowledge-base/kb0027.md
  knowledge-base/kb0028.md
  knowledge-base/kb0029.md
  knowledge-base/kb0030.md
Labels: chore

#1051 auto: Keyboard help deployment
  keyboard/bj_cree_east/9.2.0/bj_cree_east.php
  keyboard/bj_oji_cree/9.2.0/bj_oji_cree.php
Labels: auto

#1052 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1053 auto: Keyman for android help deployment
  products/android/17.0/android_images/confirm-english-dictionary-delete-ap.png
  products/android/17.0/android_images/confirm-khmer-delete-ap.png
  products/android/17.0/android_images/dist-install1-at.png
  products/android/17.0/android_images/dl-success-ap.png
  products/android/17.0/android_images/english-dictionaries-ap.png
  products/android/17.0/android_images/english-dictionary-info-ap.png
  products/android/17.0/android_images/english-settings-ap.png
  products/android/17.0/android_images/khmer-settings-ap.png
  products/android/17.0/android_images/select_language.png
  products/android/17.0/android_images/settings-2-installed-languages-ap.png
  products/android/17.0/android_images/settings-khmer-info-ap.png
  products/android/17.0/android_images/settings-screen-install-keyboard-dictionary.png
  products/android/17.0/android_images/settings-str-dictionary-ap.png
  products/android/17.0/android_images/settings-str-settings-ap.png
  products/android/17.0/android_images/settings-two-installed-languages-ap.png
  products/android/17.0/android_images/settings1-at.png
  products/android/17.0/android_images/settings2-at.png
  products/android/17.0/android_images/settings7-at.png
  products/android/17.0/android_images/uninstall-dictionary-notification-ap.png
  products/android/17.0/android_images/uninstall-notification-ap.png
Labels: auto

#1005 chore: polish kb41-51 files
  knowledge-base/kb0041.md
  knowledge-base/kb0042.md
  knowledge-base/kb0043.md
  knowledge-base/kb0044.md
  knowledge-base/kb0045.md
  knowledge-base/kb0046.md
  knowledge-base/kb0047.md
  knowledge-base/kb0048.md
  knowledge-base/kb0049.md
  knowledge-base/kb0050.md
  knowledge-base/kb0051.md
Labels: chore

#1055 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1056 auto: Keyboard help deployment
  keyboard/fv_klahoose/10.0/FVLogo.gif
  keyboard/fv_klahoose/10.0/fv_klahoose.php
Labels: auto

#1063 auto: Keyman for linux help deployment
  products/linux/18.0/reference/km-config.md
  products/linux/18.0/reference/km-kvk2ldml.md
  products/linux/18.0/reference/km-package-get.md
  products/linux/18.0/reference/km-package-install.md
  products/linux/18.0/reference/km-package-list-installed.md
  products/linux/18.0/reference/km-package-uninstall.md
Labels: auto

#1057 docs: kmc command line compiler 📚
  developer/17.0/context/kmc.md
  developer/17.0/context/kmcomp.md
  developer/17.0/context/kmlmc.md
  developer/17.0/context/kmlmi.md
  developer/17.0/context/kmlmp.md
  developer/17.0/guides/command-line.md
  developer/17.0/reference/file-layout.md
  developer/17.0/reference/file-types/index.md
  developer/17.0/reference/file-types/xml.md
  developer/17.0/reference/index.md
  developer/17.0/reference/kmc/cli/get-started.md
  developer/17.0/reference/kmc/cli/index.md
  developer/17.0/reference/kmc/cli/kmcomp-migration.md
  developer/17.0/reference/kmc/cli/messages/index.md
  developer/17.0/reference/kmc/cli/reference.md
  developer/17.0/reference/kmc/index.md
  developer/17.0/reference/tools/index.md
  developer/17.0/reference/tools/index.php
  developer/17.0/reference/user-settings.md
Labels: docs

#1059 docs: infrastructure around the kmc API documentation 📚
  .htaccess
  _includes/includes/index-content.php
  _includes/kmdev.php
  _includes/kmdevhtml.php
  _includes/kmdist.php
  _includes/kmdisthtml.php
  _includes/kmdistrtf.php
  _includes/kmhelp.php
  _includes/kmhelphtml.php
  build.sh
  cdn/dev/css/template.css
  developer/17.0/reference/api/.keep
Labels: docs

#1066 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1067 auto: Keyman for windows help deployment
  products/windows/17.0/about/whatsnew.md
Labels: auto

#1068 auto: Keyboard help deployment
  keyboard/fv_dakelh/9.1.5/DakelhLatin.png
  keyboard/fv_dakelh/9.1.5/fv_dakelh.php
Labels: auto

#1069 auto: Keyboard help deployment
  keyboard/fv_kashogotine_yati/10.0/fv_kashogotine_yati.php
  keyboard/fv_kashogotine_yati/10.0/fv_kashogotine_yati_U_.png
Labels: auto

#1071 auto: Keyman for linux help deployment
  products/linux/17.0/about/whatsnew.md
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1072 auto: Keyboard help deployment
  keyboard/knyaw/1.0.1/knyaw.php
Labels: auto

#1073 auto: Keyboard help deployment
  keyboard/hcesar/1.2/hcesar.php
Labels: auto

#1006 chore: polish kb52-62 files
  knowledge-base/kb0052.md
  knowledge-base/kb0053.md
  knowledge-base/kb0054.md
  knowledge-base/kb0055.md
  knowledge-base/kb0056.md
  knowledge-base/kb0057.md
  knowledge-base/kb0058.md
  knowledge-base/kb0059.md
  knowledge-base/kb0060.md
  knowledge-base/kb0061.md
  knowledge-base/kb0062.md
Labels: chore

#1060 docs: links to kmc api docs 📚
  developer/17.0/reference/kmc/api/index.md
  developer/17.0/reference/kmc/index.md
Labels: docs

#1038 chore: polish kb83-93
  knowledge-base/kb0083.md
  knowledge-base/kb0084.md
  knowledge-base/kb0085.md
  knowledge-base/kb0086.md
  knowledge-base/kb0087.md
  knowledge-base/kb0088.md
  knowledge-base/kb0089.md
  knowledge-base/kb0090.md
  knowledge-base/kb0091.md
  knowledge-base/kb0092.md
  knowledge-base/kb0093.md
Labels: chore

#1075 auto: Keyman for developer help deployment
  developer/17.0/reference/api/.keep
  developer/17.0/reference/api/index.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruse._constructor_.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruse.getstrings.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruse.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.includecounts.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.puabase.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.stripdottedcircle.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskrewritepua.analyze.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskrewritepua.clear.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskrewritepua.data.md
  developer/17.0/reference/api/kmc-analyze.analyzeoskrewritepua.md
  developer/17.0/reference/api/kmc-analyze.analyzermessages.fatal_unexpectedexception.md
  developer/17.0/reference/api/kmc-analyze.analyzermessages.info_scanningfile.md
  developer/17.0/reference/api/kmc-analyze.analyzermessages.md
  developer/17.0/reference/api/kmc-analyze.md
Labels: auto
