Repository keymanapp/help.keyman.com, pull requests merged in 2024-11, with the labels that each got.

#1670 chore: support debug flag for error logging
  .gitignore
  .htaccess
  .user.ini
  Readme.md
  build.sh
Labels: chore

#1668 feat: Add optional `language` header to set HTML lang attribute 📓
  _includes/header.php
  _includes/includes/head.php
  _includes/includes/kb_doc_template.php
  _includes/includes/template.php
Labels: feat

#1672 auto: Keyboard help deployment
  keyboard/dives_akuru_inscript/1.0/dives_akuru_inscript.php
Labels: auto

#1673 auto: Keyboard help deployment
  keyboard/cypriot/1.0.1/cypriot.php
  keyboard/linear_b/1.0.1/linear_b.php
Labels: auto

#1669 chore: support developer/engine/windows
  .htaccess
Labels: chore

#1675 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km00f05.md
  developer/18.0/reference/messages/kmc-ldml.ldmlcompilermessages.md
Labels: auto

#1676 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/getGlobeKeyAction.md
  developer/engine/android/18.0/KMManager/getLexicalModelsList.md
Labels: auto

#1677 auto: Keyman for ios help deployment
  developer/engine/iphone-and-ipad/18.0/KeyboardPickerBarButtonItem/index.md
  developer/engine/iphone-and-ipad/18.0/KeyboardPickerButton/index.md
  developer/engine/iphone-and-ipad/18.0/KeyboardPickerButton/setTitle.md
  developer/engine/iphone-and-ipad/18.0/KeymanPackage/index.md
  developer/engine/iphone-and-ipad/18.0/KeymanPackage/installableResourceSets.md
  developer/engine/iphone-and-ipad/18.0/KeymanPackage/installableResources.md
  developer/engine/iphone-and-ipad/18.0/KeymanPackage/key.md
  developer/engine/iphone-and-ipad/18.0/KeymanPackage/pageURL.md
  developer/engine/iphone-and-ipad/18.0/LanguageResource/LanguageResourceFullID.md
  developer/engine/iphone-and-ipad/18.0/LanguageResource/index.md
  developer/engine/iphone-and-ipad/18.0/Manager/addKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/canAddNewKeyboards.md
  developer/engine/iphone-and-ipad/18.0/Manager/currentKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/dismissKeyboardPicker.md
  developer/engine/iphone-and-ipad/18.0/Manager/downloadKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/downloadLexicalModel.md
  developer/engine/iphone-and-ipad/18.0/Manager/fontNameForKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/hideKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/index.md
  developer/engine/iphone-and-ipad/18.0/Manager/keyboardHeight.md
  developer/engine/iphone-and-ipad/18.0/Manager/removeKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/setKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/showKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/showKeyboardPicker.md
  developer/engine/iphone-and-ipad/18.0/Manager/spacebarText.md
  developer/engine/iphone-and-ipad/18.0/Manager/stateForKeyboard.md
  developer/engine/iphone-and-ipad/18.0/Manager/stateForLexicalModel.md
  developer/engine/iphone-and-ipad/18.0/Manager/switchToNextKeyboard.md
  developer/engine/iphone-and-ipad/18.0/PackageWebViewController/index.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/getInstalledPackage.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/index.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/install.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/installState.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/installedPackages.md
  developer/engine/iphone-and-ipad/18.0/ResourceFileManager/prepareKMPInstall.md
  developer/engine/iphone-and-ipad/18.0/TextField/dismissKeyboard.md
  developer/engine/iphone-and-ipad/18.0/TextField/index.md
  developer/engine/iphone-and-ipad/18.0/TextField/setKeymanDelegate.md
  developer/engine/iphone-and-ipad/18.0/TextView/dismissKeyboard.md
  developer/engine/iphone-and-ipad/18.0/TextView/index.md
  developer/engine/iphone-and-ipad/18.0/TextView/setKeymanDelegate.md
  developer/engine/iphone-and-ipad/18.0/TypedKeymanPackage/findResource.md
  developer/engine/iphone-and-ipad/18.0/TypedKeymanPackage/index.md
  developer/engine/iphone-and-ipad/18.0/TypedKeymanPackage/installables.md
  developer/engine/iphone-and-ipad/18.0/TypedKeymanPackage/installables_forLanguage.md
  developer/engine/iphone-and-ipad/18.0/guides/in-app/index.md
  developer/engine/iphone-and-ipad/18.0/guides/index.md
  developer/engine/iphone-and-ipad/18.0/guides/system-keyboard/index.md
  developer/engine/iphone-and-ipad/18.0/index.md
Labels: auto

#1678 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0300b.md
  developer/18.0/reference/messages/km0300c.md
  developer/18.0/reference/messages/kmc-model.modelcompilermessages.md
Labels: auto

#1679 auto: Keyboard help deployment
  keyboard/sogdian_phonetic/1.0/sogdian_phonetic.php
Labels: auto

#1682 auto: Keyboard help deployment
  keyboard/kawi_inscript/1.0/kawi_inscript.php
  keyboard/wenchow/1.1.3/consonant.png
  keyboard/wenchow/1.1.3/uchauU_.png
  keyboard/wenchow/1.1.3/uchauU_S.png
  keyboard/wenchow/1.1.3/vowel.png
  keyboard/wenchow/1.1.3/wenchow.php
Labels: auto

#1683 auto: Keyboard help deployment
  keyboard/sil_bunong/1.6/phone_longpress.png
  keyboard/sil_bunong/1.6/sil_bunong.php
Labels: auto

#1684 chore: more /developer/core/desktop to /developer/core
  developer/core/.htaccess
  developer/core/11.0/building.php
  developer/core/11.0/c-api/context-api.php
  developer/core/11.0/c-api/index.php
  developer/core/11.0/c-api/keyboard-api.php
  developer/core/11.0/c-api/option-api.php
  developer/core/11.0/c-api/state-api.php
  developer/core/11.0/index.php
  developer/core/11.0/json-schema.php
  developer/core/14.0/building.php
  developer/core/14.0/c-api/context-api.php
  developer/core/14.0/c-api/index.php
  developer/core/14.0/c-api/keyboard-api.php
  developer/core/14.0/c-api/option-api.php
  developer/core/14.0/c-api/state-api.php
  developer/core/14.0/index.php
  developer/core/14.0/json-schema.php
  developer/core/15.0/building.php
  developer/core/15.0/c-api/context-api.php
  developer/core/15.0/c-api/index.php
  developer/core/15.0/c-api/keyboard-api.php
  developer/core/15.0/c-api/option-api.php
  developer/core/15.0/c-api/state-api.php
  developer/core/15.0/index.php
  developer/core/15.0/json-schema.php
  developer/core/16.0/building.php
  developer/core/16.0/c-api/context-api.md
  developer/core/16.0/c-api/index.md
  developer/core/16.0/c-api/keyboard-api.md
  developer/core/16.0/c-api/option-api.md
  developer/core/16.0/c-api/state-api.md
  developer/core/16.0/index.php
  developer/core/16.0/json-schema.php
  developer/core/17.0/background.md
  developer/core/17.0/building.md
  developer/core/17.0/changes.md
  developer/core/17.0/index.md
  developer/core/17.0/json-schema.md
  developer/core/17.0/keyboards.md
  developer/core/17.0/options.md
  developer/core/17.0/processor.md
  developer/core/17.0/state.md
  developer/core/desktop/.htaccess
  developer/core/index.php
  developer/core/web/index.php
Labels: chore

#1686 chore: update sources in README.md
  README.md
Labels: chore

#1690 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.md
  developer/18.0/reference/api/kmc-analyze.analyzeoskcharacteruseoptions.mergemapfile.md
  developer/18.0/reference/kmc/cli/reference.md
  developer/18.0/reference/messages/km0205a.md
  developer/18.0/reference/messages/km02091.md
  developer/18.0/reference/messages/km02092.md
  developer/18.0/reference/messages/km02099.md
  developer/18.0/reference/messages/km020a9.md
  developer/18.0/reference/messages/km06003.md
  developer/18.0/reference/messages/km06004.md
  developer/18.0/reference/messages/km06005.md
  developer/18.0/reference/messages/km06006.md
  developer/18.0/reference/messages/km07002.md
  developer/18.0/reference/messages/kmc-analyze.analyzermessages.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
  developer/18.0/reference/messages/kmc-kmn.kmwcompilermessages.md
Labels: auto

#1691 auto: Keyboard help deployment
  keyboard/greek_polytonic_plus/2.0/MacOS_1_chart.png
  keyboard/greek_polytonic_plus/2.0/MacOS_2_chart.png
  keyboard/greek_polytonic_plus/2.0/Windows_1_chart.png
  keyboard/greek_polytonic_plus/2.0/Windows_2_chart.png
  keyboard/greek_polytonic_plus/2.0/greek_polytonic_plus.php
  keyboard/greek_polytonic_plus/2.0/greek_polytonic_plus_user_guide.pdf
Labels: auto

#1692 auto: Keyboard help deployment
  keyboard/mjh_hudum/1.0/001.png
  keyboard/mjh_hudum/1.0/002.png
  keyboard/mjh_hudum/1.0/003.png
  keyboard/mjh_hudum/1.0/004.png
  keyboard/mjh_hudum/1.0/mjh_hudum.php
Labels: auto

#1694 auto: Keyman for android help deployment
  products/android/18.0/about/system-requirements.md
Labels: auto

#1696 auto: Keyboard help deployment
  keyboard/greek_polytonic_plus/2.0/greek_polytonic_plus.php
Labels: auto

#1697 auto: Keyboard help deployment
  keyboard/taiwan_austronesian/1.2/TAU_.png
  keyboard/taiwan_austronesian/1.2/TAU_S.png
  keyboard/taiwan_austronesian/1.2/default.png
  keyboard/taiwan_austronesian/1.2/number.png
  keyboard/taiwan_austronesian/1.2/shift.png
  keyboard/taiwan_austronesian/1.2/taiwan_austronesian.php
Labels: auto

#1698 auto: Keyman for developer help deployment
  developer/18.0/reference/kmc/cli/reference.md
Labels: auto

#1699 auto: Keyboard help deployment
  keyboard/anglo_furthorc_english/1.0/anglo_furthorc_english.php
  keyboard/anglo_furthorc_english/1.0/englishfuthorcU_.png
  keyboard/anglo_furthorc_english/1.0/englishfuthorcU_S.png
Labels: auto

#1700 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/3.0/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.0/taigitelexU_.png
  keyboard/taigi_viet_telex/3.0/taigitelexU_S.png
Labels: auto

#1702 auto: Keyboard help deployment
  keyboard/karambolpoular/1.0/karambolpoular.php
Labels: auto

#1703 auto: Keyboard help deployment
  keyboard/triqui_itunyoso/1.0/triqui_itunyoso.php
Labels: auto

#1704 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0/gautami_inditran.pdf
  keyboard/gautami_inditran/1.0/gautami_inditran.php
  keyboard/gautami_inditran/1.0/transcrip.png
  keyboard/gautami_inditran/1.0/translit.png
Labels: auto

#1708 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.1/gautami_inditran.pdf
  keyboard/gautami_inditran/1.0.1/gautami_inditran.php
  keyboard/gautami_inditran/1.0.1/transcrip.png
  keyboard/gautami_inditran/1.0.1/translit.png
Labels: auto

#1709 auto: Keyboard help deployment
  keyboard/wenchow/1.1.4/consonant.png
  keyboard/wenchow/1.1.4/uchauU_.png
  keyboard/wenchow/1.1.4/uchauU_S.png
  keyboard/wenchow/1.1.4/vowel.png
  keyboard/wenchow/1.1.4/wenchow.php
Labels: auto

#1710 auto: Keyboard help deployment
  keyboard/laz/1.0.4/laz.php
Labels: auto

#1714 auto: Keyboard help deployment
  keyboard/basic_kbdolch/1.0.1/basic_kbdolch.php
Labels: auto

#1717 auto: Keyboard help deployment
  keyboard/sil_hmd_plrd/1.3/sil_hmd_plrd.php
Labels: auto

#1719 chore: add new issues to Keyman project automatically
  .github/workflows/add-to-keyman-project.yml
Labels: chore

#1723 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.2/gautami_inditran.pdf
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
  keyboard/gautami_inditran/1.0.2/transcrip.png
  keyboard/gautami_inditran/1.0.2/translit.png
Labels: auto

#1725 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
Labels: auto
