Repository keymanapp/help.keyman.com, pull requests merged in 2024-12, with the labels that each got.

#1726 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
Labels: auto

#1727 auto: Keyboard help deployment
  keyboard/sil_pan_africa_mnemonic/1.2.1/sil_pan_africa_mnemonic.php
  keyboard/sil_pan_africa_positional/1.2.1/sil_pan_africa_positional.php
Labels: auto

#1729 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km09011.md
  developer/18.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
Labels: auto

#1731 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0.3/LayoutU_.png
  keyboard/gautami_thamizh_tamil/1.0.3/LayoutU_S.png
  keyboard/gautami_thamizh_tamil/1.0.3/consonants.png
  keyboard/gautami_thamizh_tamil/1.0.3/gautami_thamizh_tamil.pdf
  keyboard/gautami_thamizh_tamil/1.0.3/gautami_thamizh_tamil.php
  keyboard/gautami_thamizh_tamil/1.0.3/vowels.png
Labels: auto

#1732 auto: Keyboard help deployment
  keyboard/basic_kbdtifi2/1.0.1/basic_kbdtifi2.php
  keyboard/indonesian_suku/1.0.1/indonesian_suku.php
  keyboard/jawa/2.0.2/jawa.php
  keyboard/kreative_superlatin/1.1.1/kreative_superlatin.php
  keyboard/nailangs/1.3.3/1lang.jpg
  keyboard/nailangs/1.3.3/Android-promo-graphic-for-desktop-Futago-copy.png
  keyboard/nailangs/1.3.3/layout.png
  keyboard/nailangs/1.3.3/nailangs.php
  keyboard/sil_cameroon_azerty/6.1.1/AzertyColor.png
  keyboard/sil_cameroon_azerty/6.1.1/Cameroon.ico
  keyboard/sil_cameroon_azerty/6.1.1/azerty-en.php
  keyboard/sil_cameroon_azerty/6.1.1/azerty-fr.php
  keyboard/sil_cameroon_azerty/6.1.1/e_chart.png
  keyboard/sil_cameroon_azerty/6.1.1/e_tableau.png
  keyboard/sil_cameroon_azerty/6.1.1/globe.png
  keyboard/sil_cameroon_azerty/6.1.1/ic_launcher.png
  keyboard/sil_cameroon_azerty/6.1.1/kb.css
  keyboard/sil_cameroon_azerty/6.1.1/longpress-azerty.png
  keyboard/sil_cameroon_azerty/6.1.1/modkeys-en-a.png
  keyboard/sil_cameroon_azerty/6.1.1/modkeys-fr-a.png
  keyboard/sil_cameroon_azerty/6.1.1/sil-logo-blue.png
  keyboard/sil_cameroon_azerty/6.1.1/sil_cameroon_azerty.php
  keyboard/sil_cameroon_qwerty/6.1.1/Cameroon.ico
  keyboard/sil_cameroon_qwerty/6.1.1/QwertyColor.png
  keyboard/sil_cameroon_qwerty/6.1.1/e_chart.png
  keyboard/sil_cameroon_qwerty/6.1.1/e_tableau.png
  keyboard/sil_cameroon_qwerty/6.1.1/globe.png
  keyboard/sil_cameroon_qwerty/6.1.1/ic_launcher.png
  keyboard/sil_cameroon_qwerty/6.1.1/kb.css
  keyboard/sil_cameroon_qwerty/6.1.1/longpress-qwerty.png
  keyboard/sil_cameroon_qwerty/6.1.1/modkeys-en-q.png
  keyboard/sil_cameroon_qwerty/6.1.1/modkeys-fr-q.png
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-ch-en.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-ch-fr.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-de-en.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-de-fr.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-uk-en.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-uk-fr.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-uk.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-us-en.php
  keyboard/sil_cameroon_qwerty/6.1.1/qwerty-us-fr.php
  keyboard/sil_cameroon_qwerty/6.1.1/sil-logo-blue.png
  keyboard/sil_cameroon_qwerty/6.1.1/sil_cameroon_qwerty.php
  keyboard/sil_nigeria_odd_vowels/1.6.1/sil_nigeria_odd_vowels.php
Labels: auto

#1733 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
Labels: auto

#1671 docs: kb on transient language code identifiers on Keyman for Windows
  knowledge-base/assets/kb0116/add_language_to_keyboard_error.png
  knowledge-base/assets/kb0116/armenian_keyboard_add_language_dialog.png
  knowledge-base/assets/kb0116/armenian_keyboard_no_language.png
  knowledge-base/kb0105.md
  knowledge-base/kb0116.md
Labels: docs

#1736 auto: Keyboard help deployment
  keyboard/gff_ethiopic/1.0.3/EthiopicTyping-English.pdf
  keyboard/gff_ethiopic/1.0.3/gff_ethiopic.php
  keyboard/gff_ethiopic/1.0.3/kb.css
  keyboard/gff_harege_fidelat/1.1.1/gff_harege_fidelat.php
  keyboard/gff_harege_fidelat/1.1.1/images/gff_harege_fidelat-default-1.jpeg
  keyboard/gff_harege_fidelat/1.1.1/images/gff_harege_fidelat-default-2.jpeg
  keyboard/gff_harege_fidelat/1.1.1/images/gff_harege_fidelat-default-3.jpeg
  keyboard/gff_harege_fidelat/1.1.1/images/gff_harege_fidelat-numerals-1.jpeg
  keyboard/gff_harege_fidelat/1.1.1/images/gff_harege_fidelat-punctuation-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/gff_mesobe_fidelat.php
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-default-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-default-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-default-3.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-numerals-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-punctuation-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-punctuation-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.1/images/gff_mesobe_fidelat-tablet-punctuation-1.jpeg
  keyboard/sil_ethiopic/2.0.7/sil_ethiopic.php
  keyboard/sil_ethiopic_power_g/1.2.6/sil_ethiopic_power_g.php
Labels: auto

#1741 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0.3/gautami_thamizh_tamil.php
  keyboard/sil_jarai/1.2/sil_jarai.php
Labels: auto

#1735 docs: clarify MIT license documentation
  developer/keyboards/advanced/step-0.md
Labels: docs

#1742 auto: Keyman for android help deployment
  products/android/18.0/android_images/disable-suggestions.png
  products/android/18.0/basic/using-the-banner.md
Labels: auto

#1743 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-copy.keymanprojectcopier.run.md
  developer/18.0/reference/kmc/cli/reference.md
  developer/18.0/reference/messages/common-types.commontypesmessages.md
  developer/18.0/reference/messages/km01002.md
  developer/18.0/reference/messages/km01003.md
  developer/18.0/reference/messages/km01004.md
  developer/18.0/reference/messages/km0b011.md
  developer/18.0/reference/messages/kmc-copy.copiermessages.md
  developer/core/18.0/background.md
  developer/core/18.0/changes.md
  developer/core/18.0/index.md
  developer/core/18.0/keyboards.md
  developer/core/18.0/options.md
  developer/core/18.0/processor.md
  developer/core/18.0/state.md
Labels: auto

#1744 feat: move to GFM-style alerts
  build.sh
  cdn/dev/css/template.css
Labels: feat

#1745 fix: remove .php extension when redirecting URLs in /keyboard
  .htaccess
  keyboard/redir.php
Labels: fix

#1746 chore: bootstrap v0.13
  build.sh
Labels: chore

#1747 chore: shared sites v0.14
  build.sh
Labels: chore

#1748 auto: Keyman for developer help deployment
  developer/18.0/reference/file-types/metadata.md
Labels: auto

#1749 feat: add alerts to knowledge base pages
  knowledge-base/index.php
Labels: feat

#1713 feat: two samples of integrating keyman videos onto help.keyman.com
  _includes/includes/footer.php
  cdn/dev/js/videoloader.js
  developer/videos/index.md
Labels: feat

#1688 docs: kb on install a keyman keyboard without any language association
  knowledge-base/assets/kb0117/khmer_angkor_keyboard_add_language_dialog.png
  knowledge-base/assets/kb0117/khmer_angkor_keyboard_details.png
  knowledge-base/assets/kb0117/khmer_angkor_no_language.png
  knowledge-base/assets/kb0117/open_command_prompt_as_administrator.jpg
  knowledge-base/kb0117.md
Labels: docs

#1751 auto: Keyboard help deployment
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
Labels: auto

#1753 auto: Keyboard help deployment
  keyboard/sil_jarai/1.2.1/sil_jarai.php
Labels: auto

#1757 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0.3/gautami_thamizh_tamil.php
Labels: auto
