Repository keymanapp/help.keyman.com, pull requests merged in 2024-06, with the labels that each got.

#1292 auto: Keyboard help deployment
  keyboard/khmer_angkor/1.4/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/1.4/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/1.4/khmer_angkor.php
  keyboard/khmer_angkor/1.4/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/1.4/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/1.4/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/1.4/khmer_angkor/image001.png
  keyboard/khmer_angkor/1.4/khmer_angkor/image002.png
  keyboard/khmer_angkor/1.4/khmer_angkor/image003.png
  keyboard/khmer_angkor/1.4/khmer_angkor/image004.png
  keyboard/khmer_angkor/1.4/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/1.4/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/1.4/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/1.4/khmer_angkor/themedata.thmx
Labels: auto

#1301 auto: Keyboard help deployment
  keyboard/kui_odia_winscript/1.0/kui_odia_winscript.php
Labels: auto

#1302 auto: Keyboard help deployment
  keyboard/gff_sbs/1.0.7/SBS-Typing-English.pdf
  keyboard/gff_sbs/1.0.7/gff_sbs.php
Labels: auto

#1308 auto: Keyboard help deployment
  keyboard/kui_odia_winscript/1.0.1/kui_odia_winscript.php
  keyboard/nyiakeng_puachue_hmong/1.0/nyiakeng_puachue_hmong.php
  keyboard/obolo_chwerty/1.5/chwerty_default.png
  keyboard/obolo_chwerty/1.5/chwerty_keycombi.png
  keyboard/obolo_chwerty/1.5/chwerty_mobi_alt.png
  keyboard/obolo_chwerty/1.5/chwerty_mobi_default.png
  keyboard/obolo_chwerty/1.5/chwerty_mobi_shift.png
  keyboard/obolo_chwerty/1.5/chwerty_shift.png
  keyboard/obolo_chwerty/1.5/chwertyftkey1.png
  keyboard/obolo_chwerty/1.5/chwertyftkey2.png
  keyboard/obolo_chwerty/1.5/chwertyftkey3.png
  keyboard/obolo_chwerty/1.5/obolo_chwerty.php
  keyboard/sil_devanagari_typewriter/1.1.2/sil_devanagari_typewriter.php
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxv.php
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxvU_.png
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxvU_S.png
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxv_.png
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxv_N.png
  keyboard/taigi_sdwxv/1.0.1/taigi_sdwxv_S.png
  keyboard/taigi_telex/1.0.1/taigi_telex.php
  keyboard/taigi_telex/1.0.1/taigitelexU_.png
  keyboard/taigi_telex/1.0.1/taigitelexU_S.png
  keyboard/taigi_telex/1.0.1/taigitelex_.png
  keyboard/taigi_telex/1.0.1/taigitelex_N.png
  keyboard/taigi_telex/1.0.1/taigitelex_S.png
Labels: auto

#1309 auto: Keyboard help deployment
  keyboard/uma_graphic/1.0.1/uma_graphic.php
Labels: auto

#1310 auto: Keyboard help deployment
  keyboard/pau_cin_hau/1.0/pau_cin_hau.php
  keyboard/ugaritic/1.0/ugaritic.php
Labels: auto

#1313 auto: Keyboard help deployment
  keyboard/alephwithbeth/1.0.6/KeyboardLayout.png
  keyboard/alephwithbeth/1.0.6/KeyboardLayoutAlt.png
  keyboard/alephwithbeth/1.0.6/KeyboardLayoutShift.png
  keyboard/alephwithbeth/1.0.6/alephwithbeth.php
  keyboard/fv_plains_cree/11.0.2/fv_plains_cree.php
  keyboard/fv_plains_cree/11.0.2/plains_creeU_.png
  keyboard/fv_sguuxs/1.0.1/fv_sguuxs.php
  keyboard/fv_sguuxs/1.0.1/fv_sguuxsU_.png
  keyboard/grantha_inscript/1.0/grantha_inscript.php
  keyboard/nag_mundari/1.0/nag_mundari.php
  keyboard/rac_yidgha/1.1.1/RAC.jpg
  keyboard/rac_yidgha/1.1.1/rac_yidgha base.png
  keyboard/rac_yidgha/1.1.1/rac_yidgha shift.png
  keyboard/rac_yidgha/1.1.1/rac_yidgha.php
  keyboard/takri_inscript/1.0/takri_inscript.php
Labels: auto

#1304 chore: cleanup definition lists and styling
  cdn/dev/css/template.css
  developer/17.0/context/new-ldml-project-parameters.md
  developer/17.0/context/package-editor.md
  developer/17.0/context/server.md
  developer/17.0/reference/kmc/cli/reference.md
  developer/17.0/reference/user-settings.md
  developer/cloud/model/1.0/index.md
  developer/cloud/model/index.md
  developer/cloud/version/2.0/index.md
  developer/engine/web/15.0/reference/keyboard_properties.md
  developer/engine/web/16.0/reference/keyboard_properties.md
  developer/engine/web/17.0/reference/keyboard_properties.md
  developer/language/reference/baselayout.md
Labels: chore

#1314 auto: Keyboard help deployment
  keyboard/hanifi_rohingya/1.0/hanifi_rohingya.php
Labels: auto

#1315 auto: Keyboard help deployment
  keyboard/balochi_phonetic/1.6.2/balochi_phonetic.php
Labels: auto

#1316 auto: Keyboard help deployment
  keyboard/fv_dene_zhatie/10.0.3/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.0.3/fv_dene_zhatieU_.png
  keyboard/fv_hailzaqvla/9.5.2/fv_hailzaqvla.php
  keyboard/sil_greek_polytonic/1.6/sil_greek_polytonic.php
  keyboard/sil_greek_polytonic/1.6/sil_greek_polytonicU_.png
  keyboard/sil_greek_polytonic/1.6/sil_greek_polytonicU_S.png
Labels: auto

#1318 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km04020.md
  developer/18.0/reference/messages/kmc-package.compilermessages.md
Labels: auto

#1319 auto: Keyboard help deployment
  keyboard/pahawh_hmong_basic/1.0/pahawh_hmong_basic.php
Labels: auto

#1303 docs: Add windows-package-installer notes to whats-new.md
  developer/17.0/whats-new.md
Labels: docs

#1321 auto: Keyboard help deployment
  keyboard/samaritan/1.0/samaritan.php
Labels: auto

#1241 docs(developer): keyboard submission and design principles
  developer/keyboards/advanced/index.md
  developer/keyboards/github/index.md
  developer/keyboards/index.md
  developer/keyboards/index.php
  developer/keyboards/standard/index.md
Labels: docs

#1322 auto: Keyboard help deployment
  keyboard/medefaidrin/1.0/medefaidrin.php
  keyboard/sil_ethiopic/2.0.5/sil_ethiopic.php
Labels: auto

#1300 docs: remove 'Step' wording for distribution of packages
  developer/17.0/guides/distribute/packages.md
Labels: docs

#1326 auto: Keyboard help deployment
  keyboard/naijatype/59/naijatype.php
Labels: auto

#1327 auto: Keyboard help deployment
  keyboard/sil_ethiopic_power_g/1.2.4/sil_ethiopic_power_g.php
Labels: auto

#1330 auto: Keyboard help deployment
  keyboard/sgaw_karen/1.0/sgaw_karen.php
  keyboard/sil_mende_kikakui/1.0/MobileLongpress.png
  keyboard/sil_mende_kikakui/1.0/sil_mende_kikakui.php
Labels: auto

#1332 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0000c.md
  developer/18.0/reference/messages/km0000f.md
  developer/18.0/reference/messages/km00014.md
  developer/18.0/reference/messages/kmc-ldml.compilermessages.md
Labels: auto

#1333 auto: Keyboard help deployment
  keyboard/kaithi_inscript/1.0/kaithi_inscript.php
Labels: auto

#1337 auto: Keyboard help deployment
  keyboard/saurashtra_inscript/1.0/saurashtra_inscript.php
Labels: auto

#1338 auto: Keyboard help deployment
  keyboard/naijatype/60/naijatype.php
Labels: auto

#1344 auto: Keyboard help deployment
  keyboard/fv_ojibwa/10.0/Ojibwa.pdf
  keyboard/fv_ojibwa/10.0/fv_ojibwa.php
  keyboard/fv_ojibwa/10.0/ojibwa_U_.png
  keyboard/fv_ojibwa_rdot/1.0/Ojibwa_rdot.pdf
  keyboard/fv_ojibwa_rdot/1.0/fv_ojibwa_rdot.php
  keyboard/fv_ojibwa_rdot/1.0/fv_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa/10.0/Severn_Ojibwa.pdf
  keyboard/fv_severn_ojibwa/10.0/fv_severn_ojibwa.php
  keyboard/fv_severn_ojibwa/10.0/severn_ojibwa_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.0/fv_severn_ojibwa_rdot.php
  keyboard/fv_severn_ojibwa_rdot/1.0/fv_severn_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.0/severn_ojibwa_rdot.pdf
Labels: auto

#1345 auto: Keyboard help deployment
  keyboard/laz/1.0.3/laz.php
Labels: auto

#1346 auto: Keyboard help deployment
  keyboard/fv_henqeminem/10.1/fv_henqeminem.php
  keyboard/fv_ojibwa/10.0.1/Ojibwa.pdf
  keyboard/fv_ojibwa/10.0.1/fv_ojibwa.php
  keyboard/fv_ojibwa/10.0.1/ojibwa_U_.png
  keyboard/fv_ojibwa_rdot/1.0.1/Ojibwa_rdot.pdf
  keyboard/fv_ojibwa_rdot/1.0.1/fv_ojibwa_rdot.php
  keyboard/fv_ojibwa_rdot/1.0.1/fv_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa/10.0.1/Severn_Ojibwa.pdf
  keyboard/fv_severn_ojibwa/10.0.1/fv_severn_ojibwa.php
  keyboard/fv_severn_ojibwa/10.0.1/severn_ojibwa_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.0.1/fv_severn_ojibwa_rdot.php
  keyboard/fv_severn_ojibwa_rdot/1.0.1/fv_severn_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.0.1/severn_ojibwa_rdot.pdf
Labels: auto

#1347 auto: Keyboard help deployment
  keyboard/fv_shashishalhem/9.2/fv_shashishalhem.php
Labels: auto

#1348 auto: Keyboard help deployment
  keyboard/sharada_inscript/1.0/sharada_inscript.php
  keyboard/sil_cipher_music/1.2/sil_cipher_music.php
Labels: auto

#1349 auto: Keyboard help deployment
  keyboard/sil_tchad_qwerty/5.3/Td.css
  keyboard/sil_tchad_qwerty/5.3/drapeau.tchad.png
  keyboard/sil_tchad_qwerty/5.3/sil-logo-blue.png
  keyboard/sil_tchad_qwerty/5.3/sil_tchad_logo.png
  keyboard/sil_tchad_qwerty/5.3/sil_tchad_qwerty.php
  keyboard/sil_tchad_qwerty/5.3/touche TD.png
  keyboard/sil_tchad_qwerty/5.3/windows.logo.png
Labels: auto

#1351 auto: Keyboard help deployment
  keyboard/sil_mende_kikakui/1.0.1/MobileLongpress.png
  keyboard/sil_mende_kikakui/1.0.1/sil_mende_kikakui.php
  keyboard/soyombo/1.0/soyombo.php
Labels: auto
