Repository keymanapp/help.keyman.com, pull requests merged in 2024-01, with the labels that each got.

#929 auto: Keyboard help deployment
  keyboard/himyarit_musnad/1.3/himyarit_musnad.php
Labels: auto

#930 auto: Keyboard help deployment
  keyboard/newa_traditional_extended/1.0.2/newa_traditional_extended.php
Labels: auto

#931 auto: Keyboard help deployment
  keyboard/armenian_mnemonic/1.1.9/armenian_mnemonic.php
  keyboard/armenian_mnemonic_r/1.0.9/armenian_mnemonic_r.php
Labels: auto

#932 auto: Keyboard help deployment
  keyboard/sil_limbu_phonetic/1.3.1/sil_limbu_phonetic.php
  keyboard/sil_limbu_typewriter/1.2.1/sil_limbu_typewriter.php
Labels: auto

#933 auto: Keyboard help deployment
  keyboard/eo_plus/1.0/eo_plus.css
  keyboard/eo_plus/1.0/eo_plus.php
  keyboard/eo_plus/1.0/key_anta.png
  keyboard/eo_plus/1.0/key_on.png
Labels: auto

#936 auto: Keyboard help deployment
  keyboard/eo_plus/1.0/eo_plus.php
Labels: auto

#938 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#937 chore: Merge master to staging for Sprint A17S29
  keyboard/armenian_mnemonic/1.1.9/armenian_mnemonic.php
  keyboard/armenian_mnemonic_r/1.0.9/armenian_mnemonic_r.php
  keyboard/cs-pinyin/1.3/cs-pinyin.php
  keyboard/dega/3.0/dega.php
  keyboard/dega/3.0/touch_longpress.png
  keyboard/eo_plus/1.0/eo_plus.css
  keyboard/eo_plus/1.0/eo_plus.php
  keyboard/eo_plus/1.0/key_anta.png
  keyboard/eo_plus/1.0/key_on.png
  keyboard/himyarit_musnad/1.3/himyarit_musnad.php
  keyboard/newa_traditional_extended/1.0.2/newa_traditional_extended.php
  keyboard/sil_limbu_phonetic/1.3.1/sil_limbu_phonetic.php
  keyboard/sil_limbu_typewriter/1.2.1/sil_limbu_typewriter.php
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: staging

#940 auto: Keyman for windows help deployment
  products/windows/17.0/basic/toolbox/character-map.md
Labels: auto

#941 auto: Keyboard help deployment
  keyboard/cs-pinyin/1.3/cs-pinyin.php
  keyboard/eo_plus/2.0/eo_plus.css
  keyboard/eo_plus/2.0/eo_plus.php
Labels: auto

#942 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#943 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#946 chore: Merge master to staging for Sprint A17S30
  keyboard/cs-pinyin/1.3/cs-pinyin.php
  keyboard/eo_plus/2.0/eo_plus.css
  keyboard/eo_plus/2.0/eo_plus.php
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
  products/windows/17.0/basic/toolbox/character-map.md
Labels: staging

#928 fix: changing a link in /developer/keyboards/advanced/step-5
  developer/keyboards/advanced/step-5.md
  knowledge-base/kb0033.md
Labels: fix

#934 chore: converted to md in developer/16.0/guides/develop/touch-keyboard…
  developer/16.0/guides/develop/touch-keyboard-tutorial/index.md
  developer/16.0/guides/develop/touch-keyboard-tutorial/index.php
Labels: chore

#947 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#948 auto: Keyman for android help deployment
  products/android/17.0/about/whatsnew.md
Labels: auto

#949 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#950 auto: Keyboard help deployment
  keyboard/yezidi/1.0/yezidi.php
Labels: auto

#953 chore: merge master into staging (A17S31 early)
  keyboard/yezidi/1.0/yezidi.php
  products/android/17.0/about/whatsnew.md
Labels: staging, chore

#951 chore: Add _control/ready
  .htaccess
  _control/ready.php
Labels: staging

#952 chore: 4 files markdown conversion 'developer/16.0/guides/distribute/[files]'
  developer/16.0/guides/distribute/index.md
  developer/16.0/guides/distribute/index.php
  developer/16.0/guides/distribute/install-kmp-android.md
  developer/16.0/guides/distribute/install-kmp-android.php
  developer/16.0/guides/distribute/install-kmp-ios.md
  developer/16.0/guides/distribute/install-kmp-ios.php
  developer/16.0/guides/distribute/packages.md
  developer/16.0/guides/distribute/packages.php
Labels: chore

#955 auto: Keyboard help deployment
  keyboard/sil_tagdal/1.0/sil_tagdal.php
Labels: auto

#956 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#957 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#958 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#959 auto: Keyboard help deployment
  keyboard/idc_deseret/1.0/idc_deseret.php
Labels: auto

#962 auto: Keyboard help deployment
  keyboard/chinuk_wawa/1.4/chinuk_wawa.php
Labels: auto

#963 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto
