Repository keymanapp/help.keyman.com, pull requests merged in 2024-09, with the labels that each got.

#1518 chore: Revert "change: use published Keyman Engine API to fetch keyboards in keyboard help pages"
  _includes/includes/head.php
  cdn/dev/js/kbd-docs.js
Labels: chore

#1520 docs: tweak any and notany docs for clarity
  developer/language/reference/any.md
  developer/language/reference/notany.md
Labels: docs

#1521 auto: Keyboard help deployment
  keyboard/meroitic_cursive/1.0/meroitic_cursive.php
Labels: auto

#1522 auto: Keyboard help deployment
  keyboard/palmyrene/1.0/palmyrene.php
Labels: auto

#1523 auto: Keyboard help deployment
  keyboard/lao_2008_basic/1.3/lao_2008_basic.php
  keyboard/lao_2008_basic/1.3/lao_2008_basicU_.png
  keyboard/lao_2008_basic/1.3/lao_2008_basicU_RA.png
  keyboard/lao_2008_basic/1.3/lao_2008_basicU_S.png
  keyboard/maltese/1.2/maltese.php
  keyboard/manichaean/1.1/manichaean.php
  keyboard/mro_phonetic/1.1/mro_phonetic.php
  keyboard/multi_pak_phonetic/1.1.2/multi_pak_phonetic.php
  keyboard/myancode_san/1.2/myancode_san.php
  keyboard/myancode_san/1.2/myancode_san_altgr.png
  keyboard/myancode_san/1.2/myancode_san_normal.png
  keyboard/myancode_san/1.2/myancode_san_shift.png
  keyboard/myancode_san/1.2/myancode_san_shift_altgr.png
Labels: auto

#1524 auto: Keyboard help deployment
  keyboard/palmyrene/1.0/palmyrene.php
Labels: auto

#1526 auto: Keyboard help deployment
  keyboard/armenian_mnemonic/1.2.0/armenian_mnemonic.php
Labels: auto

#1527 auto: Keyboard help deployment
  keyboard/armenian_mnemonic_r/1.2.0/armenian_mnemonic_r.php
  keyboard/russian_mnemonic_r/1.1.0/russian_mnemonic_r.php
Labels: auto

#1528 auto: Keyboard help deployment
  keyboard/old_permic/1.0/old_permic.php
Labels: auto

#1529 auto: Keyman for android help deployment
  products/android/18.0/android_images/ic_timelapse.png
  products/android/18.0/android_images/longpress-slider.png
  products/android/18.0/android_images/settings-screen-ap.png
  products/android/18.0/basic/config/adjust-longpress-delay.md
  products/android/18.0/basic/config/index.md
Labels: auto

#1517 chore: Update includecodes.md
  developer/language/reference/includecodes.md
Labels: chore

#1530 chore: Revert "chore: Revert "change: use published Keyman Engine API to fetch keyboards in keyboard help pages""
  _includes/includes/head.php
  cdn/dev/css/template.css
  cdn/dev/js/kbd-docs.js
Labels: chore

#1531 auto: Keyboard help deployment
  keyboard/sil_busa/1.5/sil_busa.php
  keyboard/sil_cham_phonetic/1.1/sil_cham_phonetic.php
  keyboard/sil_hawaiian/2.3/sil_hawaiian.php
Labels: auto

#1532 auto: Keyboard help deployment
  keyboard/sil_lisu_basic/1.1/sil_lisu_basic.php
  keyboard/sil_lisu_standard/1.1/sil_lisu_standard.php
Labels: auto

#1533 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km04020.md
  developer/17.0/reference/messages/km04021.md
  developer/17.0/reference/messages/km0800a.md
  developer/17.0/reference/messages/km09010.md
  developer/17.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
  developer/17.0/reference/messages/kmc-model-info.modelinfocompilermessages.md
  developer/17.0/reference/messages/kmc-package.compilermessages.md
Labels: auto

#1535 auto: Keyman for android help deployment
  products/android/18.0/about/privacy.md
  products/android/18.0/about/whatsnew.md
  products/android/18.0/basic/config/index.md
Labels: auto

#1536 auto: Keyboard help deployment
  keyboard/kirat_rai_inscript/1.1/kirat_rai_inscript.php
Labels: auto

#1537 auto: Keyboard help deployment
  keyboard/colchis_latin/1.5/colchis_latin.php
  keyboard/imperial_aramaic/1.0.0/imperial_aramaic.php
  keyboard/sil_limbu_phonetic/1.4/sil_limbu_phonetic.php
  keyboard/sil_limbu_typewriter/1.3/sil_limbu_typewriter.php
Labels: auto

#1538 auto: Keyboard help deployment
  keyboard/pinyin_typer/1.0/layoutU_.png
  keyboard/pinyin_typer/1.0/layoutU_S.png
  keyboard/pinyin_typer/1.0/pinyin.php
Labels: auto

#1539 auto: Keyboard help deployment
  keyboard/sil_hmd_plrd/1.2/sil_hmd_plrd.php
  keyboard/sil_lpo_plrd/1.2/sil_lpo_plrd.php
  keyboard/sil_ygp_plrd/1.2/sil_ygp_plrd.php
  keyboard/sil_yna_plrd/1.2/sil_yna_plrd.php
  keyboard/sil_ywq_plrd/1.2/sil_ywq_plrd.php
Labels: auto

#1540 auto: Keyboard help deployment
  keyboard/imperial_aramaic/1.0.0/LayoutU_.png
  keyboard/imperial_aramaic/1.0.0/LayoutU_S.png
  keyboard/imperial_aramaic/1.0.0/imperial_aramaic.php
  keyboard/kirat_rai_inscript/1.1.1/kirat_rai_inscript.php
Labels: auto

#1534 chore: switch to a usable link
  developer/engine/web/faq.php
Labels: fix

#1543 auto: Keyboard help deployment
  keyboard/sil_philippines/1.1/sil_philippines.php
  keyboard/sil_tepehuan/1.1/sil_tepehuan.php
  keyboard/sil_tunisian/1.1/sil_tunisian.php
Labels: auto

#1544 auto: Keyboard help deployment
  keyboard/sil_nigeria_dot/1.6/sil_nigeria_dot.php
  keyboard/sil_nigeria_odd_vowels/1.6/sil_nigeria_odd_vowels.php
  keyboard/sil_nigeria_underline/1.6/sil_nigeria_underline.php
  keyboard/sil_pan_africa_mnemonic/1.2/sil_pan_africa_mnemonic.php
  keyboard/sil_pan_africa_positional/1.2/sil_pan_africa_positional.php
Labels: auto

#1545 auto: Keyboard help deployment
  keyboard/beria_erfe_phonetic/1.0/beria_erfe_phonetic.php
Labels: auto

#1546 auto: Keyboard help deployment
  keyboard/pinyin_typer/1.0/pinyin_typer.php
Labels: auto

#1547 auto: Keyboard help deployment
  keyboard/sil_kayah_kali/1.3/sil_kayah_kali.php
  keyboard/sil_kayah_latn/1.2/sil_kayah_latn.php
  keyboard/sil_kayah_mymr/1.2/sil_kayah_mymr.php
  keyboard/sil_khowar/1.1/sil_khowar.php
  keyboard/sil_lepcha/1.1/sil_lepcha.php
  keyboard/sil_myanmar_mywinext/1.5/sil_myanmar_mywinext.php
  keyboard/sil_myanmar_mywinext/1.5/sil_myanmar_mywinextU_.png
  keyboard/sil_myanmar_mywinext/1.5/sil_myanmar_mywinextU_S.png
Labels: auto

#1549 auto: Keyboard help deployment
  keyboard/sil_mali_azerty/3.4/sil_mali_azerty.php
  keyboard/sil_mali_azerty/3.4/sil_mali_azertyU_.png
  keyboard/sil_mali_azerty/3.4/sil_mali_azertyU_S.png
  keyboard/sil_mali_qwertz/3.4/sil_mali_qwertz.php
  keyboard/sil_mali_qwertz/3.4/sil_mali_qwertzU_.png
  keyboard/sil_mali_qwertz/3.4/sil_mali_qwertzU_RA.png
  keyboard/sil_mali_qwertz/3.4/sil_mali_qwertzU_S.png
Labels: auto

#1550 auto: Keyboard help deployment
  keyboard/armenian_mnemonic/2.0.0/armenian_mnemonic.php
Labels: auto

#1551 auto: Keyboard help deployment
  keyboard/sil_el_ethiopian_latin/1.4.2/sil_el_ethiopian_latin.php
  keyboard/sil_ethiopic/2.0.6/sil_ethiopic.php
  keyboard/sil_ethiopic_power_g/1.2.5/sil_ethiopic_power_g.php
  keyboard/yiddish_pasekh/2.0.1/yiddish_pasekh.php
Labels: auto

#1552 auto: Keyboard help deployment
  keyboard/hakka/1.1/consonants.png
  keyboard/hakka/1.1/h.png
  keyboard/hakka/1.1/hakka.php
  keyboard/hakka/1.1/taigitelexU_.png
  keyboard/hakka/1.1/taigitelexU_S.png
  keyboard/hakka/1.1/tones.png
  keyboard/hakka/1.1/vowels.png
Labels: auto

#1553 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/common-types.commontypesmessages.md
  developer/17.0/reference/messages/km01008.md
Labels: auto

#1554 auto: Keyboard help deployment
  keyboard/imperial_aramaic/1.0.1/LayoutU_.png
  keyboard/imperial_aramaic/1.0.1/LayoutU_S.png
  keyboard/imperial_aramaic/1.0.1/imperial_aramaic.php
Labels: auto

#1555 auto: Keyboard help deployment
  keyboard/sil_zaiwa/1.0/sil_zaiwa.php
Labels: auto

#1556 auto: Keyboard help deployment
  keyboard/sil_zaiwa/1.1/sil_zaiwa.php
Labels: auto

#1557 auto: Keyboard help deployment
  keyboard/sil_hebr_grek_trans/1.2/sil_hebr_grek_trans.php
Labels: auto

#1558 auto: Keyboard help deployment
  keyboard/mozhi_malayalam/3.2.5/mozhi_layout.png
  keyboard/mozhi_malayalam/3.2.5/mozhi_malayalam.php
  keyboard/mozhi_malayalam/3.2.5/mozhi_malayalam.png
  keyboard/sil_greek_polytonic/1.8/phone-longpress.png
  keyboard/sil_greek_polytonic/1.8/sil_greek_polytonic.php
  keyboard/sil_khmer/2.1/sil_khmer.php
Labels: auto

#1559 auto: Keyboard help deployment
  keyboard/galaxie_greek_hebrew_positional/2.3/galaxie_greek_hebrew_positional.php
  keyboard/galaxie_greek_positional/2.3/galaxie_greek_positional.php
  keyboard/galaxie_greek_positional/2.3/keyboardchart.htm
  keyboard/galaxie_greek_positional/2.3/keyboardchart.php
  keyboard/galaxie_greek_positional/2.3/style.css
  keyboard/galaxie_hebrew_positional/2.3/galaxie_hebrew_positional.php
Labels: auto

#1561 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-ldml.ldmlkeyboardcompiler.md
  developer/18.0/reference/api/kmc-ldml.ldmlkeyboardcompiler.run.md
  developer/18.0/reference/api/kmc-ldml.ldmlkeyboardcompiler.write.md
  developer/18.0/reference/api/kmc-ldml.md
  developer/18.0/reference/messages/common-types.commontypesmessages.md
  developer/18.0/reference/messages/km01008.md
Labels: auto

#1562 auto: Keyboard help deployment
  keyboard/galaxie_greek_hebrew_mnemonic/3.4/galaxie_greek_hebrew_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.3/galaxie_greek_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.3/keyboardchart.htm
  keyboard/galaxie_greek_mnemonic/3.3/keyboardchart.php
  keyboard/galaxie_greek_mnemonic/3.3/style.css
  keyboard/galaxie_hebrew_mnemonic/3.3/galaxie_hebrew_mnemonic.php
Labels: auto

#1478 chore: updates SIL logo for help.keyman.com
  _includes/includes/embed_footer.php
  _includes/includes/footer.php
  build.sh
Labels: chore

#1564 auto: Keyboard help deployment
  keyboard/fv_denesuline_epsilon/10.0.2/ChipewyanEpsilon.png
  keyboard/fv_denesuline_epsilon/10.0.2/fv_denesuline_epsilon.php
Labels: auto

#1565 auto: Keyboard help deployment
  keyboard/meroitic_hieroglyphs/1.0/meroitic_hieroglyphs.php
Labels: auto

#1568 auto: Keyboard help deployment
  keyboard/old_uyghur/1.4/old_uyghur.php
Labels: auto

#1570 auto: Keyboard help deployment
  keyboard/sil_jarai/1.1/sil_jarai.php
Labels: auto

#1571 auto: Keyboard help deployment
  keyboard/fv_hailzaqvla/10/fv_hailzaqvla.php
Labels: auto

#1572 auto: Keyman for android help deployment
  products/android/18.0/android_images/settings-screen-ap.png
  products/android/18.0/basic/config/index.md
Labels: auto

#1573 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km00029.md
  developer/18.0/reference/messages/km00f01.md
  developer/18.0/reference/messages/kmc-ldml.ldmlcompilermessages.md
Labels: auto

#1577 chore: convert docs in dev/engi/web/17/ref
  developer/engine/web/17.0/reference/index.md
  developer/engine/web/17.0/reference/index.php
  developer/engine/web/17.0/reference/layouts.md
  developer/engine/web/17.0/reference/layouts.php
  developer/engine/web/17.0/reference/layoutspec.md
  developer/engine/web/17.0/reference/layoutspec.php
  developer/engine/web/17.0/reference/overview.md
  developer/engine/web/17.0/reference/overview.php
Labels: chore

#1580 auto: Keyboard help deployment
  keyboard/fv_hulquminum/9.2/fv_hulquminum.php
Labels: auto
