Repository keymanapp/help.keyman.com, pull requests merged in 2024-07, with the labels that each got.

#1352 auto: Keyboard help deployment
  keyboard/way/1.0/way.php
Labels: auto

#1353 auto: Keyboard help deployment
  keyboard/fv_diitiidatx/9.2/Diitiidatx.png
  keyboard/fv_diitiidatx/9.2/fv_diitiidatx.php
Labels: auto

#1354 auto: Keyboard help deployment
  keyboard/sil_greek_polytonic/1.7/sil_greek_polytonic.php
  keyboard/sil_greek_polytonic/1.7/sil_greek_polytonicU_.png
  keyboard/sil_greek_polytonic/1.7/sil_greek_polytonicU_S.png
Labels: auto

#1359 auto: Keyboard help deployment
  keyboard/naijatype/61/naijatype.php
Labels: auto

#1360 auto: Keyboard help deployment
  keyboard/way/1.0/way.php
Labels: auto

#1361 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km02079.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
Labels: auto

#1362 auto: Keyboard help deployment
  keyboard/arbore/2.0/arbore.php
Labels: auto

#1294 docs: Add remaining Keyman Engine for Android API's for KMManager
  developer/engine/android/18.0/KMKeyboard/index.md
  developer/engine/android/18.0/KMManager/executeHardwareKeystroke.md
  developer/engine/android/18.0/KMManager/getKMKeyboard.md
  developer/engine/android/18.0/KMManager/getLexicalModelInfo.md
  developer/engine/android/18.0/KMManager/getLexicalModelsList.md
  developer/engine/android/18.0/KMManager/getOrientation.md
  developer/engine/android/18.0/KMManager/index.md
  developer/engine/android/18.0/KMManager/lexicalModelExists.md
  developer/engine/android/18.0/KMManager/setCanRemoveKeyboard.md
  developer/engine/android/18.0/index.md
Labels: docs

#1369 auto: Keyboard help deployment
  keyboard/fv_anishinaabemowin/10.1/anishinaabemowinU_.png
  keyboard/fv_anishinaabemowin/10.1/fv_anishinaabemowin.php
Labels: auto

#1370 auto: Keyboard help deployment
  keyboard/arbore/2.0/arbore.php
Labels: auto

#1371 auto: Keyboard help deployment
  keyboard/sil_mende_kikakui/1.0.2/MobileLongpress.png
  keyboard/sil_mende_kikakui/1.0.2/sil_mende_kikakui.php
Labels: auto

#1372 auto: Keyboard help deployment
  keyboard/fv_cree_latin/10.2/fv_cree_latin.php
  keyboard/fv_cree_latin/10.2/fv_cree_latinU_.png
Labels: auto

#1373 auto: Keyboard help deployment
  keyboard/sil_hebrew/2.0/sil_hebrew.php
Labels: auto

#1374 auto: Keyboard help deployment
  keyboard/fv_diitiidatx/9.2.1/Diitiidatx.png
  keyboard/fv_diitiidatx/9.2.1/fv_diitiidatx.php
  keyboard/kaithi_inscript/1.0.1/kaithi_inscript.php
Labels: auto

#1375 auto: Keyboard help deployment
  keyboard/fv_smalgyax/9.2/Tsimshian.png
  keyboard/fv_smalgyax/9.2/fv_smalgyax.php
  keyboard/fv_stlatlimxec/9.3/FVLogo.gif
  keyboard/fv_stlatlimxec/9.3/Stlatlimxec.png
  keyboard/fv_stlatlimxec/9.3/fv_stlatlimxec.php
Labels: auto

#1376 auto: Keyboard help deployment
  keyboard/sil_mende_kikakui/1.0.3/MobileLongpress.png
  keyboard/sil_mende_kikakui/1.0.3/sil_mende_kikakui.php
Labels: auto

#1377 auto: Keyboard help deployment
  keyboard/rossel/1.6.1/rossel.php
Labels: auto

#1380 auto: Keyboard help deployment
  keyboard/fv_hulquminum_combine/2.0/fv_hulquminum_combine.php
  keyboard/fv_hulquminum_combine/2.0/fv_hulquminum_combine_U_.png
Labels: auto

#1378 docs: change two images in the how-to-download-and-install-keyman
  products/windows/17.0/desktop_images/setup-click2.png
  products/windows/17.0/desktop_images/setup-click3.png
Labels: docs

#1382 auto: Keyboard help deployment
  keyboard/formosa/1.0/formosa.php
Labels: auto

#1379 chore: remove composer reference
  Readme.md
Labels: chore

#1384 auto: Keyboard help deployment
  keyboard/fv_ojibwa_ifinal/1.0/fv_ojibwa_ifinal.php
  keyboard/fv_ojibwa_ifinal/1.0/fv_ojibwa_ifinal_U_.png
  keyboard/fv_ojibwa_ifinal/1.0/ojibwa_ifinals.pdf
Labels: auto

#1385 auto: Keyboard help deployment
  keyboard/phoenician/1.0/phoenician.php
Labels: auto

#1386 auto: Keyboard help deployment
  keyboard/foochow/1.0/consonants.png
  keyboard/foochow/1.0/foochow.php
  keyboard/foochow/1.0/h.png
  keyboard/foochow/1.0/ng.png
  keyboard/foochow/1.0/tones.png
  keyboard/foochow/1.0/uchauU_.png
  keyboard/foochow/1.0/uchauU_S.png
  keyboard/foochow/1.0/vowels.png
  keyboard/formosa/1.0.1/formosa.php
Labels: auto

#1391 auto: Keyboard help deployment
  keyboard/fv_dakelh/9.2/DakelhLatin.png
  keyboard/fv_dakelh/9.2/fv_dakelh.php
  keyboard/fv_dene_dzage/11.0/fv_dene_dzage.php
  keyboard/fv_dene_dzage/11.0/fv_dene_dzage_combinations.pdf
  keyboard/fv_hulquminum_combine/2.0/fv_hulquminum_combine.php
  keyboard/fv_ojibwa_ifinal_rdot/1.0/Ojibwa_ifinal_rdot.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0/fv_ojibwa_ifinal_rdot.php
  keyboard/fv_ojibwa_ifinal_rdot/1.0/fv_ojibwa_ifinal_rdot_U_.png
Labels: auto

#1392 auto: Keyboard help deployment
  keyboard/teochew/1.0/consonants.png
  keyboard/teochew/1.0/teochew.php
  keyboard/teochew/1.0/tones.png
  keyboard/teochew/1.0/uchauU_.png
  keyboard/teochew/1.0/uchauU_S.png
  keyboard/teochew/1.0/vowels.png
Labels: auto

#1393 auto: Keyboard help deployment
  keyboard/fv_dakelh/9.2/fv_dakelh.php
Labels: auto

#1394 auto: Keyboard help deployment
  keyboard/fv_dane_zaa_zaage/9.4/fv_dane_zaa_zaage.php
  keyboard/fv_dene_zhatie/10.2/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.2/fv_dene_zhatieU_.png
Labels: auto

#1395 auto: Keyboard help deployment
  keyboard/hainam/1.0/consonants.png
  keyboard/hainam/1.0/hainam.php
  keyboard/hainam/1.0/tones.png
  keyboard/hainam/1.0/uchauU_.png
  keyboard/hainam/1.0/uchauU_S.png
  keyboard/hainam/1.0/vowels1.png
  keyboard/hainam/1.0/vowels2.png
Labels: auto

#1396 auto: Keyboard help deployment
  keyboard/fv_tagizi_dene/9.3/fv_tagizi_dene.php
Labels: auto

#1397 auto: Keyboard help deployment
  keyboard/fv_dane_zaa_zaage/9.4/fv_dane_zaa_zaage.php
  keyboard/fv_dene_dzage/11.0.1/fv_dene_dzage.php
  keyboard/fv_dene_dzage/11.0.1/fv_dene_dzage_combinations.pdf
Labels: auto

#1398 auto: Keyboard help deployment
  keyboard/fv_hulquminum_combine/2.0.1/fv_hulquminum_combine.php
  keyboard/fv_hulquminum_combine/2.0.1/fv_hulquminum_combine_U_.png
Labels: auto

#1399 auto: Keyboard help deployment
  keyboard/fv_ktunaxa/10.0/fv_ktunaxa.php
  keyboard/fv_ktunaxa/10.0/ktunaxa.png
Labels: auto

#1400 auto: Keyboard help deployment
  keyboard/fv_gitsenimx/10.1.1/fv_gitsenimx.php
  keyboard/fv_gitsenimx/10.1.1/fv_gitsenimx_U_.png
  keyboard/fv_haisla/2.1/fv_haisla.php
  keyboard/fv_haisla/2.1/fv_haisla_keycombos.pdf
Labels: auto

#1401 auto: Keyboard help deployment
  keyboard/khmer_angkor/1.5/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/1.5/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/1.5/khmer_angkor.php
  keyboard/khmer_angkor/1.5/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/1.5/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/1.5/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/1.5/khmer_angkor/image001.png
  keyboard/khmer_angkor/1.5/khmer_angkor/image002.png
  keyboard/khmer_angkor/1.5/khmer_angkor/image003.png
  keyboard/khmer_angkor/1.5/khmer_angkor/image004.png
  keyboard/khmer_angkor/1.5/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/1.5/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/1.5/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/1.5/khmer_angkor/themedata.thmx
Labels: auto

#1402 auto: Keyboard help deployment
  keyboard/fv_tlingit/10.1/fv_tlingit.php
Labels: auto

#1403 auto: Keyboard help deployment
  keyboard/fv_dakelh/9.2.1/DakelhLatin.png
  keyboard/fv_dakelh/9.2.1/fv_dakelh.php
  keyboard/fv_dene_zhatie/10.2.1/fv_dene_zhatie.php
  keyboard/fv_dene_zhatie/10.2.1/fv_dene_zhatieU_.png
  keyboard/fv_gitsenimx/10.1.2/fv_gitsenimx.php
  keyboard/fv_gitsenimx/10.1.2/fv_gitsenimx_U_.png
  keyboard/fv_haisla/2.1/fv_haisla.php
  keyboard/fv_tagizi_dene/9.3/fv_tagizi_dene.php
Labels: auto

#1404 auto: Keyboard help deployment
  keyboard/fv_tsekehne/9.2/FVLogo.gif
  keyboard/fv_tsekehne/9.2/Sekani.png
  keyboard/fv_tsekehne/9.2/fv_tsekehne.php
Labels: auto

#1405 auto: Keyboard help deployment
  keyboard/sil_hebrew/2.0.1/sil_hebrew.php
Labels: auto

#1406 auto: Keyboard help deployment
  keyboard/fv_kashogotine_yati/10.1/fv_kashogotine_yati.php
  keyboard/fv_kashogotine_yati/10.1/fv_kashogotine_yati_U_.png
  keyboard/fv_kwadacha_tsekene/1.1/KwadachaTsekeneU_.png
  keyboard/fv_kwadacha_tsekene/1.1/fv_kwadacha_tsekene.php
  keyboard/fv_kwakwala/9.2/UKwakwala.png
  keyboard/fv_kwakwala/9.2/fv_kwakwala.php
Labels: auto

#1407 auto: Keyboard help deployment
  keyboard/fv_haisla/2.1.1/fv_haisla.php
  keyboard/fv_haisla/2.1.1/fv_haisla_keycombos.pdf
Labels: auto

#1408 auto: Keyboard help deployment
  keyboard/fv_tsilhqotin/9.2/Chilcotin.png
  keyboard/fv_tsilhqotin/9.2/FVLogo.gif
  keyboard/fv_tsilhqotin/9.2/fv_tsilhqotin.php
Labels: auto

#1409 auto: Keyboard help deployment
  keyboard/fv_skwxwumesh_snichim/10.0/fv_skwxwumesh_snichim.php
  keyboard/fv_skwxwumesh_snichim/10.0/skwxwumesh_U_.png
  keyboard/fv_skwxwumesh_snichim/10.0/skwxwumesh_U_S.png
Labels: auto

#1410 auto: Keyboard help deployment
  keyboard/fv_kwakwala_liqwala/9.3/Kwakwala_LiqwalaU_.png
  keyboard/fv_kwakwala_liqwala/9.3/fv_kwakwala_liqwala.php
  keyboard/fv_nisgaa/9.2/Nisgaa.png
  keyboard/fv_nisgaa/9.2/fv_nisgaa.php
Labels: auto

#1411 auto: Keyboard help deployment
  keyboard/fv_nlekepmxcin/9.5/fv_nlekepmxcin.php
  keyboard/fv_nlekepmxcin/9.5/fv_nlekepmxcin_U_.png
Labels: auto

#1412 auto: Keyboard help deployment
  keyboard/fv_nexwslayemucen/10.0/fv_nexwslayemucen.php
  keyboard/fv_nlakapamuxcheen/1.1/fv_nlakapamuxcheen.php
  keyboard/fv_nlakapamuxcheen/1.1/fv_nlakapamuxcheen_U_.png
  keyboard/fv_nlha7kapmxtsin/10.1/fv_nlha7kapmxtsin.php
  keyboard/fv_nlha7kapmxtsin/10.1/fv_nlha7kapmxtsin_U_.png
  keyboard/fv_nsilxcen/10.0/fv_nsilxcen.php
  keyboard/fv_nsilxcen/10.0/nsilxcenU_help.png
Labels: auto

#1413 auto: Keyboard help deployment
  keyboard/banne/1.0/banne.php
Labels: auto

#1414 auto: Keyboard help deployment
  keyboard/fv_haisla/2.1.2/fv_haisla.php
  keyboard/fv_haisla/2.1.2/fv_haisla_keycombos.pdf
  keyboard/fv_nuucaanul/9.2/Nuucaanul.png
  keyboard/fv_nuucaanul/9.2/fv_nuucaanul.php
  keyboard/fv_xaislakala/10.0/Haisla.png
  keyboard/fv_xaislakala/10.0/fv_xaislakala.php
Labels: auto

#1415 auto: Keyboard help deployment
  keyboard/fv_nuxalk/10.0.1/fv_nuxalk.php
Labels: auto

#1416 auto: Keyboard help deployment
  keyboard/fv_ojibwa/10.1/Ojibwa.pdf
  keyboard/fv_ojibwa/10.1/fv_ojibwa.php
  keyboard/fv_ojibwa/10.1/ojibwa_U_.png
Labels: auto

#1417 auto: Keyboard help deployment
  keyboard/cantonese_telex/1.0/cantonese_telex.php
  keyboard/cantonese_telex/1.0/consonants.png
  keyboard/cantonese_telex/1.0/leung.png
  keyboard/cantonese_telex/1.0/taigitelexU_.png
  keyboard/cantonese_telex/1.0/taigitelexU_S.png
  keyboard/cantonese_telex/1.0/taigitelex_.png
  keyboard/cantonese_telex/1.0/taigitelex_N.png
  keyboard/cantonese_telex/1.0/taigitelex_S.png
  keyboard/cantonese_telex/1.0/tones.png
  keyboard/cantonese_telex/1.0/vowels.png
Labels: auto

#1418 auto: Keyboard help deployment
  keyboard/fv_severn_ojibwa_rdot/1.1/fv_severn_ojibwa_rdot.php
  keyboard/fv_severn_ojibwa_rdot/1.1/fv_severn_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.1/severn_ojibwa_rdot.pdf
Labels: auto

#1419 auto: Keyboard help deployment
  keyboard/fv_ojibwa_ifinal/1.0.1/fv_ojibwa_ifinal.php
  keyboard/fv_ojibwa_ifinal/1.0.1/fv_ojibwa_ifinal_U_.png
  keyboard/fv_ojibwa_ifinal/1.0.1/ojibwa_ifinals.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.1/Ojibwa_ifinal_rdot.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.1/fv_ojibwa_ifinal_rdot.php
  keyboard/fv_ojibwa_ifinal_rdot/1.0.1/fv_ojibwa_ifinal_rdot_U_.png
  keyboard/fv_ojibwa_rdot/1.0.2/Ojibwa_rdot.pdf
  keyboard/fv_ojibwa_rdot/1.0.2/fv_ojibwa_rdot.php
  keyboard/fv_ojibwa_rdot/1.0.2/fv_ojibwa_rdot_U_.png
Labels: auto

#1420 auto: Keyboard help deployment
  keyboard/fv_severn_ojibwa/10.1/Severn_Ojibwa.pdf
  keyboard/fv_severn_ojibwa/10.1/fv_severn_ojibwa.php
  keyboard/fv_severn_ojibwa/10.1/severn_ojibwa_U_.png
Labels: auto

#1421 auto: Keyboard help deployment
  keyboard/mitterhofer/1.0/mitterhofer.php
Labels: auto

#1425 auto: Keyboard help deployment
  keyboard/fv_nlha7kapmxtsin/10.1.1/fv_nlha7kapmxtsin.php
  keyboard/fv_nlha7kapmxtsin/10.1.1/fv_nlha7kapmxtsin_U_.png
  keyboard/holikachuk/1.0/holikachuk.php
Labels: auto

#1426 auto: Keyboard help deployment
  keyboard/hcesar/1.3/hcesar.php
Labels: auto

#1427 auto: Keyboard help deployment
  keyboard/runeboard/3.0/runeboard.php
Labels: auto

#1428 auto: Keyboard help deployment
  keyboard/fv_plains_cree/11.1/fv_plains_cree.php
  keyboard/fv_plains_cree/11.1/plains_cree.pdf
  keyboard/fv_plains_cree/11.1/plains_creeU_.png
Labels: auto

#1429 auto: Keyboard help deployment
  keyboard/wenchow/1.1/wenchow.php
Labels: auto

#1430 auto: Keyboard help deployment
  keyboard/fv_sguuxs/1.1/fv_sguuxs.php
  keyboard/fv_sguuxs/1.1/fv_sguuxsU_.png
Labels: auto

#1431 auto: Keyboard help deployment
  keyboard/hcesar/1.3.1/hcesar.php
Labels: auto

#1432 auto: Keyboard help deployment
  keyboard/xpert/1.0/xpert.php
Labels: auto

#1433 auto: Keyboard help deployment
  keyboard/fv_southern_carrier/10.1/fv_SouthernCarrierGuide.pdf
  keyboard/fv_southern_carrier/10.1/fv_southern_carrier.php
  keyboard/fv_southern_carrier/10.1/fv_southern_carrier_U_.png
Labels: auto

#1434 auto: Keyboard help deployment
  keyboard/fv_southern_tutchone/9.3/fv_southern_tutchone.php
  keyboard/fv_statimcets/9.2/Statimcets.png
  keyboard/fv_statimcets/9.2/fv_statimcets.php
Labels: auto

#1435 auto: Keyboard help deployment
  keyboard/breton_chwerty/1.0/breton_chwerty.php
Labels: auto

#1436 auto: Keyboard help deployment
  keyboard/foochow/1.0.1/consonants.png
  keyboard/foochow/1.0.1/foochow.php
  keyboard/foochow/1.0.1/h.png
  keyboard/foochow/1.0.1/ng.png
  keyboard/foochow/1.0.1/tones.png
  keyboard/foochow/1.0.1/uchauU_.png
  keyboard/foochow/1.0.1/uchauU_S.png
  keyboard/foochow/1.0.1/vowels.png
  keyboard/runeboard/3.0/runeboard.php
Labels: auto

#1437 auto: Keyboard help deployment
  keyboard/wenchow/1.1.1/wenchow.php
Labels: auto

#1438 auto: Keyboard help deployment
  keyboard/glagolitic_phonetic/1.0/glagolitic_phonetic.php
Labels: auto

#1439 auto: Keyboard help deployment
  keyboard/romanian_popak/1.0/romanian_popak.php
Labels: auto

#1440 auto: Keyboard help deployment
  keyboard/fv_taltan/9.2/FVLogo.gif
  keyboard/fv_taltan/9.2/Tahltan.png
  keyboard/fv_taltan/9.2/fv_taltan.php
Labels: auto

#1441 auto: Keyboard help deployment
  keyboard/fv_nlekepmxcin/9.5.1/fv_nlekepmxcin.php
  keyboard/fv_nlekepmxcin/9.5.1/fv_nlekepmxcin_U_.png
Labels: auto

#1442 auto: Keyboard help deployment
  keyboard/fv_uwikala/9.4/FVLogo.gif
  keyboard/fv_uwikala/9.4/fv_uwikala.php
Labels: auto

#1443 auto: Keyboard help deployment
  keyboard/idoma/1.0/idoma.php
Labels: auto

#1444 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0205c.md
  developer/18.0/reference/messages/km0205d.md
  developer/18.0/reference/messages/km02060.md
  developer/18.0/reference/messages/km02061.md
  developer/18.0/reference/messages/km02063.md
  developer/18.0/reference/messages/km0207a.md
  developer/18.0/reference/messages/km0207b.md
  developer/18.0/reference/messages/km0501a.md
  developer/18.0/reference/messages/km0501f.md
  developer/18.0/reference/messages/km07001.md
  developer/18.0/reference/messages/km07006.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
  developer/18.0/reference/messages/kmc-kmn.kmwcompilermessages.md
  developer/18.0/reference/messages/kmc.infrastructuremessages.md
Labels: auto

#1449 auto: Keyboard help deployment
  keyboard/fv_hlgaagilda_xaayda_kil/9.4/fv_hlgaagilda_xaayda_kil.php
  keyboard/fv_hlgaagilda_xaayda_kil/9.4/fv_hlgaagilda_xaayda_kilU_.png
Labels: auto

#1450 auto: Keyboard help deployment
  keyboard/bukawa/3.0/bukawa.php
Labels: auto

#1453 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km02079.md
  developer/17.0/reference/messages/kmc-kmn.kmncompilermessages.md
Labels: auto

#1455 auto: Keyboard help deployment
  keyboard/fv_lekwungen/1.0/FVLogo.gif
  keyboard/fv_lekwungen/1.0/fv_lekwungen.php
  keyboard/fv_lekwungen/1.0/fv_lekwungen_U_.png
Labels: auto

#1456 auto: Keyboard help deployment
  keyboard/fv_haisla/2.1.3/fv_haisla.php
Labels: auto

#1457 auto: Keyboard help deployment
  keyboard/idoma/1.0.1/idoma.php
  keyboard/taigi_viet_telex/1.0/taigi_viet_telex.php
Labels: auto

#1458 auto: Keyboard help deployment
  keyboard/fv_natwits/9.2/Nat-Wits.png
  keyboard/fv_natwits/9.2/fv_natwits.php
Labels: auto

#1459 auto: Keyboard help deployment
  keyboard/fv_secwepemctsin/9.3/Secwepemctsin.png
  keyboard/fv_secwepemctsin/9.3/fv_secwepemctsin.php
Labels: auto

#1460 auto: Keyboard help deployment
  keyboard/phonetic_farsi/1.0/phonetic_farsi.php
Labels: auto

#1461 auto: Keyboard help deployment
  keyboard/fv_lekwungen/1.0/fv_lekwungen.php
Labels: auto

#1462 auto: Keyboard help deployment
  keyboard/fv_henqeminem/10.2/Henqeminem_U_.png
  keyboard/fv_henqeminem/10.2/Henqeminem_U_RA.png
  keyboard/fv_henqeminem/10.2/fv_henqeminem.php
Labels: auto

#1464 auto: Keyboard help deployment
  keyboard/fv_henqeminem/10.2.1/Henqeminem_U_.png
  keyboard/fv_henqeminem/10.2.1/Henqeminem_U_RA.png
  keyboard/fv_henqeminem/10.2.1/fv_henqeminem.php
  keyboard/fv_skwxwumesh_snichim/10.0/fv_skwxwumesh_snichim.php
Labels: auto

#1465 auto: Keyboard help deployment
  keyboard/fv_halqemeylem/9.2.1/Halqemeylem.png
  keyboard/fv_halqemeylem/9.2.1/fv_halqemeylem.php
Labels: auto

#1466 auto: Keyboard help deployment
  keyboard/fv_sencoten/9.2.3/Sencoten.png
  keyboard/fv_sencoten/9.2.3/fv_sencoten.php
Labels: auto

#1467 auto: Keyboard help deployment
  keyboard/fv_sencoten/9.2.3/fv_sencoten.php
Labels: auto
