Repository keymanapp/help.keyman.com, pull requests merged in 2024-08, with the labels that each got.

#1468 auto: Keyboard help deployment
  keyboard/fv_nexwslayemucen/11.0/fv_nexwslayemucen.php
  keyboard/fv_nexwslayemucen/11.0/klallam_U_.png
  keyboard/fv_shashishalhem/9.2.1/fv_shashishalhem.php
Labels: auto

#1469 auto: Keyboard help deployment
  keyboard/fv_klahoose/10.2/FVLogo.gif
  keyboard/fv_klahoose/10.2/fv_klahoose.php
Labels: auto

#1470 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-kmn.kmncompiler._constructor_.md
  developer/18.0/reference/api/kmc-kmn.kmncompiler.md
  developer/18.0/reference/messages/km02001.md
  developer/18.0/reference/messages/km02007.md
  developer/18.0/reference/messages/km02071.md
  developer/18.0/reference/messages/km02072.md
  developer/18.0/reference/messages/km0207a.md
  developer/18.0/reference/messages/km0208a.md
  developer/18.0/reference/messages/km020ae.md
  developer/18.0/reference/messages/km020c1.md
  developer/18.0/reference/messages/km07006.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
  developer/18.0/reference/messages/kmc-kmn.kmwcompilermessages.md
Labels: auto

#1471 auto: Keyboard help deployment
  keyboard/fv_anishinaabemowin/10.2/anishinaabemowinU_.png
  keyboard/fv_anishinaabemowin/10.2/fv_anishinaabemowin.php
  keyboard/fv_dane_zaa_zaage/9.4.1/fv_dane_zaa_zaage.php
  keyboard/fv_denesuline_epsilon/10.0.1/fv_denesuline_epsilon.php
  keyboard/fv_haisla/2.1.3/fv_haisla.php
  keyboard/fv_lekwungen/1.0.1/FVLogo.gif
  keyboard/fv_lekwungen/1.0.1/fv_lekwungen.php
  keyboard/fv_lekwungen/1.0.1/fv_lekwungen_U_.png
  keyboard/fv_nisgaa/9.2.1/Nisgaa.png
  keyboard/fv_nisgaa/9.2.1/fv_nisgaa.php
  keyboard/fv_nlakapamuxcheen/1.1/fv_nlakapamuxcheen.php
  keyboard/fv_nlha7kapmxtsin/10.1.2/fv_nlha7kapmxtsin.php
  keyboard/fv_nlha7kapmxtsin/10.1.2/fv_nlha7kapmxtsin_U_.png
  keyboard/fv_nsilxcen/10.0.1/fv_nsilxcen.php
  keyboard/fv_nsilxcen/10.0.1/nsilxcenU_help.png
  keyboard/fv_nuucaanul/9.2/fv_nuucaanul.php
  keyboard/fv_ojibwa/10.1/fv_ojibwa.php
  keyboard/fv_ojibwa_ifinal/1.0.2/fv_ojibwa_ifinal.php
  keyboard/fv_ojibwa_ifinal/1.0.2/fv_ojibwa_ifinal_U_.png
  keyboard/fv_ojibwa_ifinal/1.0.2/ojibwa_ifinals.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.2/Ojibwa_ifinal_rdot.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.2/fv_ojibwa_ifinal_rdot.php
  keyboard/fv_ojibwa_ifinal_rdot/1.0.2/fv_ojibwa_ifinal_rdot_U_.png
  keyboard/fv_ojibwa_rdot/1.0.3/Ojibwa_rdot.pdf
  keyboard/fv_ojibwa_rdot/1.0.3/fv_ojibwa_rdot.php
  keyboard/fv_ojibwa_rdot/1.0.3/fv_ojibwa_rdot_U_.png
  keyboard/fv_plains_cree/11.1/fv_plains_cree.php
  keyboard/fv_severn_ojibwa/10.1.1/Severn_Ojibwa.pdf
  keyboard/fv_severn_ojibwa/10.1.1/fv_severn_ojibwa.php
  keyboard/fv_severn_ojibwa/10.1.1/severn_ojibwa_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.1.1/fv_severn_ojibwa_rdot.php
  keyboard/fv_severn_ojibwa_rdot/1.1.1/fv_severn_ojibwa_rdot_U_.png
  keyboard/fv_severn_ojibwa_rdot/1.1.1/severn_ojibwa_rdot.pdf
  keyboard/fv_smalgyax/9.3/Tsimshian.png
  keyboard/fv_smalgyax/9.3/fv_smalgyax.php
  keyboard/fv_southern_carrier/10.1/fv_southern_carrier.php
  keyboard/fv_southern_tutchone/9.3/fv_southern_tutchone.php
  keyboard/fv_statimcets/9.2/fv_statimcets.php
  keyboard/fv_stlatlimxec/9.4/FVLogo.gif
  keyboard/fv_stlatlimxec/9.4/Stlatlimxec.png
  keyboard/fv_stlatlimxec/9.4/fv_stlatlimxec.php
  keyboard/fv_tagizi_dene/9.4/fv_tagizi_dene.php
  keyboard/fv_taltan/9.2/fv_taltan.php
  keyboard/fv_tlingit/10.1/fv_tlingit.php
  keyboard/fv_tsekehne/9.2/fv_tsekehne.php
  keyboard/fv_tsilhqotin/9.3/Chilcotin.png
  keyboard/fv_tsilhqotin/9.3/FVLogo.gif
  keyboard/fv_tsilhqotin/9.3/fv_tsilhqotin.php
  keyboard/fv_uwikala/9.4/fv_uwikala.php
Labels: auto

#1472 auto: Keyboard help deployment
  keyboard/korean_phonetic/2.0/korean_phonetic.php
  keyboard/korean_phonetic/2.0/style.css
Labels: auto

#1474 auto: Keyboard help deployment
  keyboard/french_zhjay/1.0/french_zhjay.php
Labels: auto

#1475 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/2.0/taigi_viet_telex.php
Labels: auto

#1476 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/2.0/taigi_viet_telex.php
Labels: auto

#1477 auto: Keyboard help deployment
  keyboard/ife_mn/1.1/ife_mn.php
Labels: auto

#1480 auto: Keyboard help deployment
  keyboard/foochow/consonants.png
  keyboard/foochow/foochow.php
  keyboard/foochow/h.png
  keyboard/foochow/ng.png
  keyboard/foochow/tones.png
  keyboard/foochow/uchauU_.png
  keyboard/foochow/uchauU_S.png
  keyboard/foochow/vowels.png
Labels: auto

#1481 auto: Keyboard help deployment
  keyboard/taichow/1.0.1/consonant.png
  keyboard/taichow/1.0.1/taichow.php
  keyboard/taichow/1.0.1/uchauU_.png
  keyboard/taichow/1.0.1/uchauU_S.png
  keyboard/taichow/1.0.1/vowel1.png
  keyboard/taichow/1.0.1/vowel2.png
  keyboard/taichow/1.0.1/vowel3.png
Labels: auto

#1482 auto: Keyboard help deployment
  keyboard/nias/1.0.1/nias.php
Labels: auto

#1483 auto: Keyboard help deployment
  keyboard/foochow/1.1/consonants.png
  keyboard/foochow/1.1/foochow.php
  keyboard/foochow/1.1/h.png
  keyboard/foochow/1.1/ng.png
  keyboard/foochow/1.1/tones.png
  keyboard/foochow/1.1/uchauU_.png
  keyboard/foochow/1.1/uchauU_S.png
  keyboard/foochow/1.1/vowels.png
Labels: auto

#1484 auto: Keyboard help deployment
  keyboard/eastern_cham/1.2/eastern_cham.php
  keyboard/phonetic_farsi/1.0/phonetic_farsi.php
Labels: auto

#1485 auto: Keyboard help deployment
  keyboard/taichow/1.0.2/consonant.png
  keyboard/taichow/1.0.2/taichow.php
  keyboard/taichow/1.0.2/uchauU_.png
  keyboard/taichow/1.0.2/uchauU_S.png
  keyboard/taichow/1.0.2/vowel1.png
  keyboard/taichow/1.0.2/vowel2.png
  keyboard/taichow/1.0.2/vowel3.png
Labels: auto

#1486 auto: Keyboard help deployment
  keyboard/cham_latin/1.1/Cham-Latin-Layout.png
  keyboard/cham_latin/1.1/cham_latin.php
Labels: auto

#1487 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km04021.md
  developer/18.0/reference/messages/km0800a.md
  developer/18.0/reference/messages/km09010.md
  developer/18.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
  developer/18.0/reference/messages/kmc-model-info.modelinfocompilermessages.md
  developer/18.0/reference/messages/kmc-package.packagecompilermessages.md
Labels: auto

#1488 auto: Keyboard help deployment
  keyboard/hakka/1.0/consonants.png
  keyboard/hakka/1.0/h.png
  keyboard/hakka/1.0/hakka.php
  keyboard/hakka/1.0/taigitelexU_.png
  keyboard/hakka/1.0/taigitelexU_S.png
  keyboard/hakka/1.0/tones.png
  keyboard/hakka/1.0/vowels.png
Labels: auto

#1489 auto: Keyboard help deployment
  keyboard/burushaski_girminas_perso_arabic/1.26/bsk_perso_arabic_keyboard_keystrokes.png
  keyboard/burushaski_girminas_perso_arabic/1.26/burushaski_additional_characters.png
  keyboard/burushaski_girminas_perso_arabic/1.26/burushaski_girminas_perso_arabic.php
  keyboard/burushaski_girminas_perso_arabic/1.26/burushaski_keyboard_orthography_guide.pdf
  keyboard/burushaski_girminas_perso_arabic/1.26/hunza_nagar_text.png
  keyboard/burushaski_girminas_perso_arabic/1.26/key_combination_chart_equation.png
  keyboard/burushaski_girminas_perso_arabic/1.26/orthography.png
  keyboard/burushaski_girminas_perso_arabic/1.26/yasin_text.png
Labels: auto

#1491 auto: Keyboard help deployment
  keyboard/teochew/1.1/consonants.png
  keyboard/teochew/1.1/teochew.php
  keyboard/teochew/1.1/tones.png
  keyboard/teochew/1.1/uchauU_.png
  keyboard/teochew/1.1/uchauU_S.png
  keyboard/teochew/1.1/vowels.png
Labels: auto

#1493 auto: Keyboard help deployment
  keyboard/cs_pinyin/1.4/About the Four Corner Method.pdf
  keyboard/cs_pinyin/1.4/cs_pinyin.php
  keyboard/cs_pinyin/1.4/using simplified chinese.pdf
Labels: auto

#1494 auto: Keyboard help deployment
  keyboard/old_hungarian/1.7.9/old_hungarian.php
Labels: auto

#1496 auto: Keyboard help deployment
  keyboard/naijatype/63/naijatype.php
  keyboard/wenchow/1.1.2/consonant.png
  keyboard/wenchow/1.1.2/uchauU_.png
  keyboard/wenchow/1.1.2/uchauU_S.png
  keyboard/wenchow/1.1.2/vowel.png
  keyboard/wenchow/1.1.2/wenchow.php
Labels: auto

#1497 auto: Keyboard help deployment
  keyboard/old_hungarian/1.8/old_hungarian.php
Labels: auto

#1498 auto: Keyboard help deployment
  keyboard/yiddish_pasekh/2.0/yiddish_pasekh.php
Labels: auto

#1499 docs(developer): link to kmx, kmx+ file formats
  developer/17.0/reference/file-types/kmx.md
Labels: docs

#1501 auto: Keyboard help deployment
  keyboard/old_hungarian/1.9/old_hungarian.php
Labels: auto

#1502 auto: Keyboard help deployment
  keyboard/vithkuqi/1.1/vithkuqi.php
Labels: auto

#1503 auto: Keyboard help deployment
  keyboard/taichow/1.0.3/consonant.png
  keyboard/taichow/1.0.3/taichow.php
  keyboard/taichow/1.0.3/uchauU_.png
  keyboard/taichow/1.0.3/uchauU_S.png
  keyboard/taichow/1.0.3/vowel1.png
  keyboard/taichow/1.0.3/vowel2.png
  keyboard/taichow/1.0.3/vowel3.png
Labels: auto

#1504 auto: Keyboard help deployment
  keyboard/itrans_bengali/1.1.0/itrans_bengali.php
  keyboard/itrans_bengali/1.1.0/itrans_bengaliU_.png
  keyboard/itrans_bengali/1.1.0/itrans_bengaliU_S.png
  keyboard/itrans_devanagari_hindi/1.4.0/itrans_devanagari_hindi.php
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedic.php
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedicU_.png
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedicU_RA.png
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedicU_RC.png
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedicU_S.png
  keyboard/itrans_devanagari_sanskrit_vedic/1.3.0/itrans_devanagari_sanskrit_vedicU_S_edited.png
  keyboard/itrans_gujarati/1.3.0/itrans_gujarati.php
  keyboard/itrans_gujarati/1.3.0/itrans_gujaratiU_.png
  keyboard/itrans_gujarati/1.3.0/itrans_gujaratiU_S.png
  keyboard/itrans_gurmukhi/1.1/itrans_gurmukhi.php
  keyboard/itrans_gurmukhi/1.1/itrans_gurmukhi.png
  keyboard/itrans_odia/1.1/itrans_odia.php
  keyboard/itrans_odia/1.1/itrans_odia.png
Labels: auto

#1505 auto: Keyboard help deployment
  keyboard/gautami_thamizh_tamil/1.0/gautami_thamizh_tamil.pdf
  keyboard/gautami_thamizh_tamil/1.0/gautami_thamizh_tamil.php
Labels: auto

#1506 chore: update kb72
  knowledge-base/kb0072.md
Labels: chore

#1507 auto: Keyboard help deployment
  keyboard/basic_kbdcherp/1.1.0/basic_kbdcherp.php
  keyboard/basic_kbdinuk2/1.2/basic_kbdinuk2.php
  keyboard/basic_kbdiulat/1.2/basic_kbdiulat.php
  keyboard/basic_kbdkhmr/1.2/basic_kbdkhmr.php
  keyboard/basic_kbdlt2/1.2/basic_kbdlt2.php
  keyboard/basic_kbdsors1/1.2/basic_kbdsors1.php
  keyboard/basic_kbdsw09/1.2/basic_kbdsw09.php
Labels: auto

#1272 change: use published Keyman Engine API to fetch keyboards in keyboard help pages
  _includes/includes/head.php
  cdn/dev/js/kbd-docs.js
Labels: change

#1510 auto: Keyboard help deployment
  keyboard/nlci_bengali_winscript/2.1/nlci_bengali_winscript.php
  keyboard/nlci_gujarati_winscript/2.1/Gujarati keyboard.png
  keyboard/nlci_gujarati_winscript/2.1/nlci_gujarati_winscript.php
  keyboard/nlci_gurmukhi_winscript/2.1/nlci_gurmukhi_winscript.php
  keyboard/nlci_ipa/2.1/nlci_ipa.php
  keyboard/nlci_kannada_winscript/2.1/kannada.png
  keyboard/nlci_kannada_winscript/2.1/nlci_kannada_winscript.php
  keyboard/nlci_malayalam_winscript/2.1/malayalam.png
  keyboard/nlci_malayalam_winscript/2.1/nlci_malayalam_winscript.php
  keyboard/nlci_oriya_winscript/2.1/nlci_oriya_winscript.php
  keyboard/nlci_tamil_winscript/2.1/nlci_tamil_winscript.php
  keyboard/nlci_tamil_winscript/2.1/tamil keyboard.png
  keyboard/nlci_telugu_winscript/2.1/nlci_telugu_winscript.php
Labels: auto

#1511 auto: Keyboard help deployment
  keyboard/aramaic_hebrew/1.3/aramaic_hebrew.php
  keyboard/aramaic_hebrew/1.3/font-license.txt
  keyboard/aramaic_hebrew/1.3/key-altl.gif
  keyboard/aramaic_hebrew/1.3/key-altr.gif
  keyboard/aramaic_hebrew/1.3/key-backspace.gif
  keyboard/aramaic_hebrew/1.3/key-bkslash.gif
  keyboard/aramaic_hebrew/1.3/key-capslock.gif
  keyboard/aramaic_hebrew/1.3/key-ctrll.gif
  keyboard/aramaic_hebrew/1.3/key-ctrlr.gif
  keyboard/aramaic_hebrew/1.3/key-enter.gif
  keyboard/aramaic_hebrew/1.3/key-plain.gif
  keyboard/aramaic_hebrew/1.3/key-shift102.gif
  keyboard/aramaic_hebrew/1.3/key-shiftl.gif
  keyboard/aramaic_hebrew/1.3/key-shiftr.gif
  keyboard/aramaic_hebrew/1.3/key-space.gif
  keyboard/aramaic_hebrew/1.3/key-tab.gif
  keyboard/aramaic_hebrew/1.3/melthoguide.pdf
  keyboard/athinkra_vai/1.3/athinkra_vai.php
  keyboard/athinkra_vai_typewriter/1.3/athinkra_vai_typewriter.php
  keyboard/coptic_greek/2.3/coptic_greek.php
  keyboard/syriac_aramaic/1.3/syriac_aramaic.php
Labels: auto

#1512 auto: Keyboard help deployment
  keyboard/kadu_kadu/1.0/kadu_kadu.php
Labels: auto

#1508 chore: Update link in kb0072.md
  knowledge-base/kb0072.md
Labels: chore

#1509 docs: add language example
  cdn/dev/img/developer/170/ui/frmEditLanguageExample.png
  developer/17.0/context/edit-language-example.md
  developer/17.0/context/index.md
Labels: docs

#1513 chore: minor tweaks to all-versions history
  _includes/includes/history_utils.php
  version-history/all-versions.php
  version-history/index.md
Labels: chore

#1515 auto: Keyboard help deployment
  keyboard/dene/2.2/dene.php
  keyboard/el_dari_clra/1.1/el_dari_clra.php
  keyboard/el_pan_sahelian/3.3/el_pan_sahelian.php
  keyboard/engram/2.1/engram.php
  keyboard/esperuni/1.2/esperuni.php
  keyboard/gandhari/2.9/gandhari-keyboard_keyman.pdf
  keyboard/gandhari/2.9/gandhari.php
  keyboard/gondi_gunjala_inscript/1.2/gondi_gunjala_inscript.php
  keyboard/greekclassical/1.3/chart.php
  keyboard/greekclassical/1.3/greekclassical.php
  keyboard/greekclassical/1.3/keys2.gif
  keyboard/greekclassical/1.3/tr.gif
Labels: auto

#1516 auto: Keyboard help deployment
  keyboard/zanabazar_square/1.0/zanabazar_square.php
Labels: auto
