Repository keymanapp/help.keyman.com, pull requests merged in 2024-05, with the labels that each got.

#1225 chore(developer): Update whats-new.md
  developer/17.0/whats-new.md
Labels: chore

#1226 chore(developer): cleanup minor typos
  developer/17.0/reference/kmc/cli/kmcomp-migration.md
Labels: chore

#1228 auto: Keyman for linux help deployment
  products/linux/18.0/reference/km-config.md
  products/linux/18.0/reference/km-kvk2ldml.md
  products/linux/18.0/reference/km-package-get.md
  products/linux/18.0/reference/km-package-install.md
  products/linux/18.0/reference/km-package-list-installed.md
  products/linux/18.0/reference/km-package-uninstall.md
Labels: auto

#1229 auto: Keyman for mac help deployment
  products/mac/18.0/about/requirements.md
  products/mac/18.0/common/os.md
  products/mac/18.0/common/requirements.md
Labels: auto

#1230 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1231 auto: Keyman for mac help deployment
  products/mac/17.0/about/requirements.md
  products/mac/17.0/common/os.md
  products/mac/17.0/common/requirements.md
Labels: auto

#1232 auto: Keyman for developer help deployment
  developer/17.0/reference/messages/km0401f.md
  developer/17.0/reference/messages/kmc-package.compilermessages.md
Labels: auto

#1240 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1242 auto: Keyboard help deployment
  keyboard/gff_gurage_legacy/0.51/GurageTyping-Legacy-English.pdf
  keyboard/gff_gurage_legacy/0.51/GurageTyping-Legacy-Gurage.pdf
  keyboard/gff_gurage_legacy/0.51/gff_gurage_legacy.php
Labels: auto

#1243 auto: Keyboard help deployment
  keyboard/sil_khmer/1.5/sil_khmer.php
Labels: auto

#1247 auto: Keyboard help deployment
  keyboard/fv_nlakapamuxcheen/1.0/fv_nlakapamuxcheen.php
  keyboard/fv_nlakapamuxcheen/1.0/fv_nlakapamuxcheen_U_.png
Labels: auto

#1248 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1249 auto: Keyboard help deployment
  keyboard/sil_khmer/2.0/sil_khmer.php
Labels: auto

#1250 auto: Keyboard help deployment
  keyboard/fv_dene_dzage/10.0/fv_dene_dzage.php
  keyboard/fv_dene_dzage/10.0/fv_dene_dzage_combinations.pdf
  keyboard/fv_nlekepmxcin/9.4/fv_nlekepmxcin.php
  keyboard/fv_nlekepmxcin/9.4/fv_nlekepmxcin_U_.png
Labels: auto

#1251 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0401f.md
  developer/18.0/reference/messages/kmc-package.compilermessages.md
Labels: auto

#1253 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1254 auto: Keyboard help deployment
  keyboard/fv_henqeminem/10.1/Henqeminem_U_.png
  keyboard/fv_henqeminem/10.1/Henqeminem_U_RA.png
  keyboard/fv_henqeminem/10.1/fv_henqeminem.php
Labels: auto

#1255 auto: Keyboard help deployment
  keyboard/laz/1.0.2/laz.php
Labels: auto

#1256 auto: Keyboard help deployment
  keyboard/fv_nlakapamuxcheen/1.0.1/fv_nlakapamuxcheen.php
  keyboard/fv_nlakapamuxcheen/1.0.1/fv_nlakapamuxcheen_U_.png
Labels: auto

#1257 auto: Keyboard help deployment
  keyboard/fv_sencoten/9.2.2/Sencoten.png
  keyboard/fv_sencoten/9.2.2/fv_sencoten.php
Labels: auto

#1258 auto: Keyboard help deployment
  keyboard/fv_nlakapamuxcheen/1.0.2/fv_nlakapamuxcheen.php
  keyboard/fv_nlakapamuxcheen/1.0.2/fv_nlakapamuxcheen_U_.png
Labels: auto

#1259 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1260 auto: Keyman for linux help deployment
  products/linux/17.0/reference/km-config.md
  products/linux/17.0/reference/km-kvk2ldml.md
  products/linux/17.0/reference/km-package-get.md
  products/linux/17.0/reference/km-package-install.md
  products/linux/17.0/reference/km-package-list-installed.md
  products/linux/17.0/reference/km-package-uninstall.md
Labels: auto

#1261 chore: current version 17.0
  .htaccess
Labels: chore

#1262 docs: Update version.md
  developer/language/reference/version.md
Labels: docs

#1263 auto: Keyboard help deployment
  keyboard/fv_shashishalhem/9.2/Shashishalhem.png
  keyboard/fv_shashishalhem/9.2/fv_shashishalhem.php
Labels: auto

#1265 fix: keyman.options has become keyman.config.options
  cdn/dev/js/kbd-docs.js
Labels: fix

#1269 auto: Keyboard help deployment
  keyboard/fv_gitsenimx/10.1.0/fv_gitsenimx.php
  keyboard/fv_gitsenimx/10.1.0/fv_gitsenimx_U_.png
Labels: auto

#1266 chore: refresh kb0013 details
  knowledge-base/assets/kb0013/sentry.png
  knowledge-base/kb0013.md
Labels: chore

#1268 chore: Convert KMManager to Markdown
  developer/engine/android/18.0/KMManager/index.md
  developer/engine/android/18.0/KMManager/index.php
Labels: chore

#1273 auto: Keyman for linux help deployment
  products/linux/18.0/about/whatsnew.md
Labels: auto

#1274 auto: Keyman for mac help deployment
  products/mac/18.0/about/whatsnew.md
Labels: auto

#1275 auto: Keyman for windows help deployment
  products/windows/18.0/about/whatsnew.md
Labels: auto

#1278 fix: temporarily roll back to keymanweb 16.0.147
  _includes/includes/head.php
Labels: fix

#1281 auto: Keyboard help deployment
  keyboard/camoes/1.0/camoes.php
  keyboard/fv_haisla/2.0.1/fv_haisla.php
  keyboard/fv_plains_cree/11.0.1/fv_plains_cree.php
  keyboard/fv_plains_cree/11.0.1/plains_creeU_.png
Labels: auto

#1282 auto: Keyboard help deployment
  keyboard/chorasmian/1.0/chorasmian.php
  keyboard/elymaic/1.0/elymaic.php
Labels: auto

#1283 docs: Clarify &keyboardversion vs &version
  developer/language/reference/keyboardversion.md
  developer/language/reference/version.md
Labels: docs

#1280 feat: include the version switcher in the errors page and show where the URL's subpath is located across the versions' folders
  _includes/errors/404.php
  _includes/includes/page-version.php
Labels: help.keyman.com, feat

#1287 feat: keyboard help files now have keyboard download links
  _includes/includes/kb_doc_template.php
Labels: help.keyman.com, feat

#1284 chore: update image of virtual key identifier
  cdn/dev/img/developer/170/ui/frmKeyTest.png
  developer/17.0/context/key-test.md
Labels: chore

#1270 docs: Add getOrientation, getWindowDensity, and getWindowSize APIs
  developer/engine/android/18.0/KMManager/getOrientation.md
  developer/engine/android/18.0/KMManager/getWindowDensity.md
  developer/engine/android/18.0/KMManager/getWindowSize.md
  developer/engine/android/18.0/KMManager/index.md
Labels: docs

#1289 chore: change url
  developer/17.0/guides/develop/index.md
Labels: chore

#1291 chore: fix typo in kb0042.md
  knowledge-base/kb0042.md
Labels: chore

#1290 chore: update kb0002.md
  knowledge-base/kb0002.md
Labels: chore
