Repository keymanapp/help.keyman.com, pull requests merged in 2025-06, with the labels that each got.

#2103 auto: Keyboard help deployment
  keyboard/taichow/2.0/consonant.png
  keyboard/taichow/2.0/taichow.php
  keyboard/taichow/2.0/uchauU_.png
  keyboard/taichow/2.0/uchauU_S.png
  keyboard/taichow/2.0/vowel1.png
  keyboard/taichow/2.0/vowel2.png
  keyboard/taichow/2.0/vowel3.png
Labels: auto

#2106 auto: Keyboard help deployment
  keyboard/netgkb/1.0/netgkb.php
Labels: auto

#2093 fix: edit correct page for developer, engine help
  _includes/includes/com.keyman.help.editpage.inc.php
  _includes/includes/footer.php
Labels: fix

#2111 auto: Keyboard help deployment
  keyboard/sil_tepehuan/1.1.1/sil_tepehuan.php
  keyboard/sil_wayuu/1.1.2/sil_wayuu.php
  keyboard/tlahuica/1.0.2/all_layers.png
  keyboard/tlahuica/1.0.2/alt_layer.png
  keyboard/tlahuica/1.0.2/main_layer.png
  keyboard/tlahuica/1.0.2/phone_keyboard.png
  keyboard/tlahuica/1.0.2/shift_alt_layer.png
  keyboard/tlahuica/1.0.2/shift_layer.png
  keyboard/tlahuica/1.0.2/tlahuica.php
  keyboard/tlahuica/1.0.2/u_long_press.png
Labels: auto

#2113 auto: Keyboard help deployment
  keyboard/ausephon/11.0.2/ausephon.php
  keyboard/ausephon/11.0.2/layout150.png
  keyboard/basic_kbdgn/1.0.3/basic_kbdgn.php
  keyboard/bukawa/3.0.1/bukawa.php
  keyboard/choctaw_modern/1.0.1/choctaw_modern.php
  keyboard/clavbur9/9.1.2/clavbur9.php
  keyboard/easy_chakma/2.0.0/easy_chakma.php
  keyboard/embera_north/10.1.6/embera_north.php
  keyboard/haroi/1.2.3/haroi.php
  keyboard/lahu/1.1.3/lahu.php
  keyboard/libtralo/1.6.6/libtralo.php
  keyboard/libtralo/1.6.6/libtralo.png
  keyboard/sil_bari/1.1.3/sil_bari.php
  keyboard/sil_buang/1.2.1/sil_buang.php
  keyboard/sil_busa/1.5.2/sil_busa.php
  keyboard/sil_eastern_congo/1.5.4/sil_eastern_congo.php
  keyboard/sil_hawaiian/2.3.1/sil_hawaiian.php
  keyboard/sil_indic_roman/1.4.2/sil_indic_roman.php
  keyboard/sil_ipa/2.0.2/sil_ipa.php
  keyboard/sil_kayah_latn/1.2.1/sil_kayah_latn.php
  keyboard/sil_madi/1.0.2/phone_longpress.png
  keyboard/sil_madi/1.0.2/sil_madi.php
  keyboard/sil_moore/2.1.2/sil_moore.php
  keyboard/sil_sahu/1.0.2/sil_sahu.php
Labels: auto

#2114 auto: Keyboard help deployment
  keyboard/sil_mali_azerty/3.4.2/sil_mali_azerty.php
  keyboard/sil_mali_azerty/3.4.2/sil_mali_azertyU_.png
  keyboard/sil_mali_azerty/3.4.2/sil_mali_azertyU_S.png
  keyboard/sil_mali_qwerty/4.0.3/TableauTouchesQWertyCouleur.pdf
  keyboard/sil_mali_qwerty/4.0.3/mali_all.png
  keyboard/sil_mali_qwerty/4.0.3/mali_shift.png
  keyboard/sil_mali_qwerty/4.0.3/sil_mali_qwerty.php
  keyboard/sil_mali_qwertz/3.4.2/sil_mali_qwertz.php
Labels: auto

#2115 auto: Keyboard help deployment
  keyboard/el_harari_latin/2.1.3/el_harari_latin.php
  keyboard/galaxie_greek_mnemonic/3.3/galaxie_greek_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.3/keyboardchart.php
  keyboard/galaxie_greek_positional/2.3.2/galaxie_greek_positional.php
  keyboard/galaxie_greek_positional/2.3.2/keyboardchart.php
  keyboard/galaxie_hebrew_mnemonic/3.3.1/galaxie_hebrew_mnemonic.php
  keyboard/kayan/1.5.3/kayan.php
  keyboard/landuma/1.1.4/landuma.php
  keyboard/nlci_ipa/2.1/nlci_ipa.php
  keyboard/orma/1.1/orma.php
  keyboard/quinault/1.0.1/quinault.php
  keyboard/sil_akebu/1.0.0/sil_akebu.php
  keyboard/sil_bwe_karen/1.0.2/sil_bwe_karen.php
  keyboard/sil_el_ethiopian_latin/1.4.4/sil_el_ethiopian_latin.php
  keyboard/sil_hebr_grek_trans/1.2/sil_hebr_grek_trans.php
  keyboard/sil_kvl_kayaw/1.2.3/sil_kvl_kayaw.php
  keyboard/sil_philippines/1.1/sil_philippines.php
  keyboard/sil_temiar/2.0.1/sil_temiar.php
  keyboard/sil_uganda_tanzania/1.1.2/sil_uganda_tanzania.php
  keyboard/tawallammat_latin/1.2/tawallammat_latin.php
  keyboard/tlahuica/1.0.2/tlahuica.php
Labels: auto

#2117 auto: Keyboard help deployment
  keyboard/mingrelian_cyrillic/1.1/mingrelian_cyrillic.php
Labels: auto

#2116 chore: polish alerts and remove span tags
  developer/language/reference/_keywordsbytype.md
  developer/language/reference/index.md
Labels: chore

#2122 auto: Keyboard help deployment
  keyboard/vietnam/1.0.8/vietnam.php
Labels: auto

#2125 auto: Keyboard help deployment
  keyboard/cantonese_telex/3.0.2/cantonese_telex.php
  keyboard/cantonese_telex/3.0.2/consonants.png
  keyboard/cantonese_telex/3.0.2/tones.png
  keyboard/cantonese_telex/3.0.2/vowels.png
Labels: auto

#2127 auto: Keyboard help deployment
  keyboard/gff_mesobe_fidelat/1.1.2/gff_mesobe_fidelat.php
  keyboard/gff_mesobe_fidelat/1.1.2/html.css
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-default-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-default-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-default-3.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-numerals-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-punctuation-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-punctuation-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.2/images/gff_mesobe_fidelat-tablet-punctuation-1.jpeg
Labels: auto

#2128 auto: Keyboard help deployment
  keyboard/gff_amharic/3.2.2/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/3.2.2/AmharicTyping-English.pdf
  keyboard/gff_amharic/3.2.2/gff_amharic.php
  keyboard/gff_amharic/3.2.2/html.css
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-default-1.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-default-2.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-default-3.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-default-4.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-numerals-1.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-numerals-2.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-numerals-3.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-numerals-4.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-punctuation-1.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-punctuation-2.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-punctuation-3.jpeg
  keyboard/gff_amharic/3.2.2/images/phone/gff_amharic-phone-punctuation-4.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-default-1.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-default-2.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-default-3.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-default-4.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-numerals-1.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-numerals-2.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-punctuation-1.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-punctuation-2.jpeg
  keyboard/gff_amharic/3.2.2/images/tablet/gff_amharic-tablet-punctuation-3.jpeg
  keyboard/gff_amharic/3.2.2/kb.css
  keyboard/gff_harege_fidelat/1.1.2/gff_harege_fidelat.php
  keyboard/gff_harege_fidelat/1.1.2/html.css
  keyboard/gff_harege_fidelat/1.1.2/images/gff_harege_fidelat-default-1.jpeg
  keyboard/gff_harege_fidelat/1.1.2/images/gff_harege_fidelat-default-2.jpeg
  keyboard/gff_harege_fidelat/1.1.2/images/gff_harege_fidelat-default-3.jpeg
  keyboard/gff_harege_fidelat/1.1.2/images/gff_harege_fidelat-numerals-1.jpeg
  keyboard/gff_harege_fidelat/1.1.2/images/gff_harege_fidelat-punctuation-1.jpeg
Labels: auto

#2130 auto: Keyboard help deployment
  keyboard/hong_kong/1.0.3/consonants.png
  keyboard/hong_kong/1.0.3/hong_kong.php
  keyboard/hong_kong/1.0.3/tones.png
  keyboard/hong_kong/1.0.3/vowels.png
Labels: auto

#2132 auto: Keyboard help deployment
  keyboard/lavanya/2.0/lavanya.php
Labels: auto

#2120 chore: add download shared font folder and use alerts
  knowledge-base/kb0106.md
Labels: chore

#2119 chore: additional deadkey example from community site
  developer/language/reference/deadkey.md
Labels: chore

#2143 auto: Keyboard help deployment
  keyboard/cymraeg_fodern/1.0/cymraeg_fodern.php
  keyboard/devanagari_kagapa_phonetic/1.0/devanagari_kagapa_phonetic.php
  keyboard/english_shavian_igc/1.3/english_shavian_igc.php
  keyboard/english_shavian_igc/1.3/shavian_alphabet_reading_key.png
  keyboard/english_shavian_jafl/1.1/english_shavian_jafl.php
  keyboard/english_shavian_jafl/1.1/shavian_alphabet_reading_key.png
  keyboard/english_shavian_jafl/1.1/shaw_jafl_phone_latin_default.png
  keyboard/english_shavian_jafl/1.1/shaw_jafl_phone_latin_shift.png
  keyboard/english_shavian_jafl/1.1/shaw_jafl_phone_numbers.png
  keyboard/english_shavian_jafl/1.1/shaw_jafl_phone_shift.png
  keyboard/english_shavian_jafl/1.1/shaw_jafl_phone_symbols.png
  keyboard/english_shavian_qwerty/1.2/english_shavian_qwerty.php
  keyboard/english_shavian_qwerty/1.2/shavian_alphabet_reading_key.png
  keyboard/gff_amharic/3.2.3/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/3.2.3/AmharicTyping-English.pdf
  keyboard/gff_amharic/3.2.3/gff_amharic.php
  keyboard/gff_amharic/3.2.3/html.css
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-default-1.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-default-2.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-default-3.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-default-4.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-numerals-1.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-numerals-2.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-numerals-3.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-numerals-4.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-punctuation-1.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-punctuation-2.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-punctuation-3.jpeg
  keyboard/gff_amharic/3.2.3/images/phone/gff_amharic-phone-punctuation-4.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-default-1.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-default-2.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-default-3.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-default-4.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-numerals-1.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-numerals-2.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-punctuation-1.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-punctuation-2.jpeg
  keyboard/gff_amharic/3.2.3/images/tablet/gff_amharic-tablet-punctuation-3.jpeg
  keyboard/gff_amharic/3.2.3/kb.css
  keyboard/gff_harege_fidelat/1.1.3/gff_harege_fidelat.php
  keyboard/gff_harege_fidelat/1.1.3/html.css
  keyboard/gff_harege_fidelat/1.1.3/images/gff_harege_fidelat-default-1.jpeg
  keyboard/gff_harege_fidelat/1.1.3/images/gff_harege_fidelat-default-2.jpeg
  keyboard/gff_harege_fidelat/1.1.3/images/gff_harege_fidelat-default-3.jpeg
  keyboard/gff_harege_fidelat/1.1.3/images/gff_harege_fidelat-numerals-1.jpeg
  keyboard/gff_harege_fidelat/1.1.3/images/gff_harege_fidelat-punctuation-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/gff_mesobe_fidelat.php
  keyboard/gff_mesobe_fidelat/1.1.3/html.css
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-default-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-default-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-default-3.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-numerals-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-punctuation-1.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-punctuation-2.jpeg
  keyboard/gff_mesobe_fidelat/1.1.3/images/gff_mesobe_fidelat-tablet-punctuation-1.jpeg
  keyboard/korean_9_keys/2.0/1.png
  keyboard/korean_9_keys/2.0/korea_9_keys.php
  keyboard/korean_9_keys/2.0/old-hangul.png
  keyboard/korean_9_keys/2.0/touch.png
  keyboard/modi_kagapa_phonetic/1.0/modi_kagapa_phonetic.php
Labels: auto
