Repository keymanapp/help.keyman.com, pull requests merged in 2025-07, with the labels that each got.

#2150 auto: Keyman for developer help deployment
  developer/19.0/context/keyboard-editor.md
  developer/19.0/guides/develop/touch-keyboard-tutorial/gestures.md
  developer/19.0/guides/develop/touch-keyboard-tutorial/index.md
  developer/19.0/images/touch-keyboard-tutorial/touch-layout-gestures.jpg
  developer/19.0/main/credits.md
  developer/19.0/main/license.md
Labels: auto, automerge

#2153 auto: Keyboard help deployment
  keyboard/fulfulde_borgu_ajami_azerty/1.0/fulfulde_borgu_ajami_azerty.php
Labels: auto

#2156 auto: Keyboard help deployment
  keyboard/fulfulde_borgu_ajami_azerty/1.0.1/fulfulde_borgu_ajami_azerty.php
Labels: auto

#2158 auto: Keyboard help deployment
  keyboard/jorai/1.1/jorai.php
Labels: auto

#2160 auto: Keyman for developer help deployment
  developer/19.0/context/package-editor.md
Labels: auto, automerge

#2157 docs: fix error of index() rule example
  developer/language/reference/_index.md
Labels: docs

#2164 auto: Keyboard help deployment
  keyboard/bassa_vah/1.1.1/bassa_vah.php
Labels: auto

#2166 auto: Keyboard help deployment
  keyboard/slaviature/1.0/slaviature.php
Labels: auto

#2167 auto: Keyboard help deployment
  keyboard/ga/1.1/ga.php
Labels: auto

#2168 auto: Keyboard help deployment
  keyboard/korean_9_keys/3.0/1.png
  keyboard/korean_9_keys/3.0/default.png
  keyboard/korean_9_keys/3.0/korea_9_keys.php
  keyboard/korean_9_keys/3.0/old-hangul.png
  keyboard/korean_9_keys/3.0/shift.png
  keyboard/korean_9_keys/3.0/touch.png
Labels: auto

#2171 auto: Keyboard help deployment
  keyboard/gff_amh_7/1.6/AmharicTyping-Amharic.pdf
  keyboard/gff_amh_7/1.6/AmharicTyping-English.pdf
  keyboard/gff_amh_7/1.6/AwngiTyping-English.pdf
  keyboard/gff_amh_7/1.6/BenchTyping-English.pdf
  keyboard/gff_amh_7/1.6/BlinTyping-English.pdf
  keyboard/gff_amh_7/1.6/GeezTyping-English.pdf
  keyboard/gff_amh_7/1.6/MeenTyping-English.pdf
  keyboard/gff_amh_7/1.6/SebatbeitTyping-English.pdf
  keyboard/gff_amh_7/1.6/TigrignaErTyping-English.pdf
  keyboard/gff_amh_7/1.6/TigrignaEtTyping-English.pdf
  keyboard/gff_amh_7/1.6/chart.pdf
  keyboard/gff_amh_7/1.6/gff_amh_7.php
  keyboard/gff_amh_7/1.6/html.css
Labels: auto

#2172 auto: Keyboard help deployment
  keyboard/sisaali/1.0/sisaali.php
Labels: auto

#2173 auto: Keyman for developer help deployment
  developer/19.0/context/keyboard-editor.md
  developer/19.0/images/ui/OnScreenKeyboard_ISO.png
Labels: auto, automerge

#2174 auto: Keyboard help deployment
  keyboard/vietnam/2.0.1/vietnam.php
Labels: auto

#2176 auto: Keyboard help deployment
  keyboard/nzema/1.0/nzema.php
Labels: auto

#2177 auto: Keyboard help deployment
  keyboard/jinland/1.0/jinland.php
Labels: auto

#2178 auto: Keyboard help deployment
  keyboard/phonetic_farsi/2.0.1/phonetic_farsi.php
Labels: auto

#2182 auto: Keyboard help deployment
  keyboard/kazakh_arabic/1.0.2/kazakh_arabic.php
Labels: auto

#2183 auto: Keyboard help deployment
  keyboard/gff_amharic/3.3/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/3.3/AmharicTyping-English.pdf
  keyboard/gff_amharic/3.3/gff_amharic.php
  keyboard/gff_amharic/3.3/html.css
  keyboard/gff_amharic/3.3/images/Ethiopic-Font-Samples-920w.png
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-default-1.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-default-2.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-default-3.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-default-4.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-numerals-1.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-numerals-2.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-numerals-3.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-numerals-4.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-punctuation-1.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-punctuation-2.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-punctuation-3.jpeg
  keyboard/gff_amharic/3.3/images/phone/gff_amharic-phone-punctuation-4.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-default-1.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-default-2.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-default-3.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-default-4.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-numerals-1.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-numerals-2.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-punctuation-1.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-punctuation-2.jpeg
  keyboard/gff_amharic/3.3/images/tablet/gff_amharic-tablet-punctuation-3.jpeg
  keyboard/gff_amharic/3.3/kb.css
Labels: auto

#2186 auto: Keyboard help deployment
  keyboard/naijatype/65/naijatype.php
Labels: auto
