Repository keymanapp/help.keyman.com, pull requests merged in 2025-01, with the labels that each got.

#1758 chore: changes to use https and fix linking
  developer/10.0/guides/distribute/tutorial/step-4.php
  developer/11.0/guides/distribute/tutorial/step-4.php
  developer/12.0/guides/distribute/tutorial/step-4.php
  developer/13.0/guides/distribute/tutorial/step-4.php
  developer/14.0/guides/distribute/tutorial/step-4.php
  developer/15.0/guides/distribute/tutorial/step-4.php
  developer/16.0/guides/distribute/tutorial/step-4.php
Labels: chore

#1754 fix: 404 Not Found link in docs
  keyboard/burushaski_girminas/2.0.24/burushaski_girminas.php
  products/android/10.0/index.php
Labels: fix

#1764 auto: Keyboard help deployment
  keyboard/cantonese_telex/1.2.2/cantonese_telex.php
  keyboard/cantonese_telex/1.2.2/consonants.png
  keyboard/cantonese_telex/1.2.2/leung.png
  keyboard/cantonese_telex/1.2.2/taigitelexU_.png
  keyboard/cantonese_telex/1.2.2/taigitelexU_S.png
  keyboard/cantonese_telex/1.2.2/taigitelex_.png
  keyboard/cantonese_telex/1.2.2/taigitelex_N.png
  keyboard/cantonese_telex/1.2.2/taigitelex_S.png
  keyboard/cantonese_telex/1.2.2/tones.png
  keyboard/cantonese_telex/1.2.2/vowels.png
Labels: auto

#1765 auto: Keyman for mac help deployment
  products/mac/18.0/start/install-keyboard.md
  products/mac/18.0/start/install-keyman.md
Labels: auto

#1766 auto: Keyman for developer help deployment
  developer/18.0/guides/intro.md
Labels: auto

#1767 auto: Keyboard help deployment
  keyboard/colchis_latin/1.6/colchis_latin.php
Labels: auto

#1768 auto: Keyboard help deployment
  keyboard/indonesia/2.0.2/indonesia.php
Labels: auto

#1769 auto: Keyboard help deployment
  keyboard/taichow/1.0.4/consonant.png
  keyboard/taichow/1.0.4/taichow.php
  keyboard/taichow/1.0.4/uchauU_.png
  keyboard/taichow/1.0.4/uchauU_S.png
  keyboard/taichow/1.0.4/vowel1.png
  keyboard/taichow/1.0.4/vowel2.png
  keyboard/taichow/1.0.4/vowel3.png
Labels: auto

#1770 auto: Keyboard help deployment
  keyboard/winchus/0.9.7/winchus.php
Labels: auto

#1773 auto: Keyboard help deployment
  keyboard/mjh_hudum/1.0.1/mjh_hudum.php
Labels: auto

#1774 auto: Keyboard help deployment
  keyboard/mjh_aligali/1.0.1/mjh_aligali.php
Labels: auto

#1778 auto: Keyboard help deployment
  keyboard/mjh_manchu/1.0.1/mjh_manchu.php
Labels: auto

#1779 auto: Keyboard help deployment
  keyboard/mjh_sibe/1.0.1/mjh_sibe.php
Labels: auto

#1782 auto: Keyboard help deployment
  keyboard/soqotri_arabic/1.1/soqotri_arabic.php
Labels: auto

#1783 auto: Keyboard help deployment
  keyboard/mjh_todo/1.0.1/mjh_todo.php
Labels: auto

#1784 auto: Keyboard help deployment
  keyboard/manchu/1.0/lowercase.png
  keyboard/manchu/1.0/manchu.php
  keyboard/manchu/1.0/uppercase.png
Labels: auto

#1785 auto: Keyboard help deployment
  keyboard/dakota_smsc/1.5/dakota_smsc.php
Labels: auto

#1786 auto: Keyboard help deployment
  keyboard/dakota_smsc/1.5.1/CorrectFont.png
  keyboard/dakota_smsc/1.5.1/Overdot.png
  keyboard/dakota_smsc/1.5.1/Picture1.png
  keyboard/dakota_smsc/1.5.1/Picture2.png
  keyboard/dakota_smsc/1.5.1/accent.png
  keyboard/dakota_smsc/1.5.1/accentpc.png
  keyboard/dakota_smsc/1.5.1/dakota_smsc.php
  keyboard/dakota_smsc/1.5.1/emoji.png
  keyboard/dakota_smsc/1.5.1/equal.png
  keyboard/dakota_smsc/1.5.1/globe.png
  keyboard/dakota_smsc/1.5.1/lowercasepc.png
  keyboard/dakota_smsc/1.5.1/n.png
  keyboard/dakota_smsc/1.5.1/nleft.png
  keyboard/dakota_smsc/1.5.1/nright.png
  keyboard/dakota_smsc/1.5.1/overdotpc.png
  keyboard/dakota_smsc/1.5.1/tilde.png
  keyboard/dakota_smsc/1.5.1/uppercasepc.png
  keyboard/dakota_smsc/1.5.1/windowsshortcut.png
Labels: auto

#1793 auto: Keyman for web help deployment
  developer/engine/web/18.0/guide/adding-keyboards.md
Labels: auto

#1794 auto: Keyman for developer help deployment
  developer/18.0/context/keyboard-editor.md
  developer/18.0/guides/distribute/tutorial/step-2.md
  developer/18.0/guides/distribute/tutorial/step-4.md
  developer/18.0/guides/lexical-models/distribute/tutorial/step-5.md
  developer/18.0/reference/messages/km04003.md
  developer/18.0/reference/messages/km04004.md
  developer/18.0/reference/messages/km04005.md
  developer/18.0/reference/messages/km04008.md
  developer/18.0/reference/messages/km04009.md
  developer/18.0/reference/messages/km0400a.md
  developer/18.0/reference/messages/km0400d.md
  developer/18.0/reference/messages/km0400e.md
  developer/18.0/reference/messages/km0400f.md
  developer/18.0/reference/messages/km04011.md
  developer/18.0/reference/messages/km0401d.md
  developer/18.0/reference/messages/km04022.md
  developer/18.0/reference/messages/kmc-package.packagecompilermessages.md
  developer/core/18.0/options.md
Labels: auto

#1795 auto: Keyboard help deployment
  keyboard/dakota_smsc/1.5.1/dakota_smsc.php
Labels: auto

#1796 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/3.0.1/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.0.1/taigitelexU_.png
  keyboard/taigi_viet_telex/3.0.1/taigitelexU_S.png
Labels: auto

#1797 auto: Keyboard help deployment
  keyboard/foochow/1.2.1/consonants.png
  keyboard/foochow/1.2.1/foochow.php
  keyboard/foochow/1.2.1/h.png
  keyboard/foochow/1.2.1/ng.png
  keyboard/foochow/1.2.1/tones.png
  keyboard/foochow/1.2.1/uchauU_.png
  keyboard/foochow/1.2.1/uchauU_S.png
  keyboard/foochow/1.2.1/vowels.png
Labels: auto

#1798 auto: Keyboard help deployment
  keyboard/sil_nubian/1.2.6/sil_nubian.php
Labels: auto

#1777 chore: fixes broken internal URLs
  developer/11.0/context/kmcomp.php
  developer/12.0/context/kmcomp.php
  developer/13.0/context/kmcomp.php
  developer/14.0/context/kmcomp.php
  developer/15.0/context/kmcomp.php
  developer/16.0/context/kmcomp.md
Labels: bug

#1800 auto: Keyboard help deployment
  keyboard/manchu/1.0.1/lowercase.png
  keyboard/manchu/1.0.1/manchu.php
  keyboard/manchu/1.0.1/uppercase.png
  keyboard/taigi_viet_telex/3.0.2/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.0.2/taigitelexU_.png
  keyboard/taigi_viet_telex/3.0.2/taigitelexU_S.png
Labels: auto

#1799 chore: upgrade to shared v0.15
  build.sh
Labels: chore

#1801 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/context/gestures.md
  products/iphone-and-ipad/18.0/context/index.md
  products/iphone-and-ipad/18.0/index.md
  products/iphone-and-ipad/18.0/ios_images/gesture-hint.png
Labels: auto

#1802 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km04023.md
  developer/18.0/reference/messages/km04024.md
  developer/18.0/reference/messages/km04025.md
  developer/18.0/reference/messages/km04026.md
  developer/18.0/reference/messages/kmc-package.packagecompilermessages.md
Labels: auto

#1806 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0a007.md
  developer/18.0/reference/messages/kmc-generate.generatormessages.md
Labels: auto

#1807 auto: Keyboard help deployment
  keyboard/cantonese_telex/2.0/cantonese_telex.php
  keyboard/cantonese_telex/2.0/consonants.png
  keyboard/cantonese_telex/2.0/leung.png
  keyboard/cantonese_telex/2.0/taigitelexU_.png
  keyboard/cantonese_telex/2.0/taigitelexU_S.png
  keyboard/cantonese_telex/2.0/taigitelex_.png
  keyboard/cantonese_telex/2.0/taigitelex_N.png
  keyboard/cantonese_telex/2.0/taigitelex_S.png
  keyboard/cantonese_telex/2.0/tones.png
  keyboard/cantonese_telex/2.0/vowels.png
Labels: auto

#1755 fix: links to the available version of docs
  developer/language/guide/virtual-keys.md
  products/iphone-and-ipad/10.0/installing-custom-keyboards.php
  products/iphone-and-ipad/11.0/installing-custom-keyboards.php
  products/iphone-and-ipad/12.0/installing-custom-keyboards.php
  products/iphone-and-ipad/13.0/installing-custom-keyboards.php
  products/iphone-and-ipad/2.0/installing-custom-keyboards.php
  products/windows/10.0/docs/advanced_locale_edit.php
  products/windows/11.0/docs/advanced_locale_edit.php
  products/windows/12.0/docs/advanced_locale_edit.php
  products/windows/13.0/docs/advanced_locale_edit.php
Labels: fix

#1809 auto: Keyman for web help deployment
  developer/engine/web/18.0/guide/examples/__auto-control.html
  developer/engine/web/18.0/guide/examples/__control-by-control.html
  developer/engine/web/18.0/guide/examples/__first-example.html
  developer/engine/web/18.0/guide/examples/__full-manual-control.html
  developer/engine/web/18.0/guide/examples/__manual-control.html
Labels: auto

#1810 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0a008.md
  developer/18.0/reference/messages/km0a009.md
  developer/18.0/reference/messages/km0a00a.md
  developer/18.0/reference/messages/kmc-generate.generatormessages.md
Labels: auto

#1811 auto: Keyboard help deployment
  keyboard/slp1_deva/1.0/slp1_deva.php
Labels: auto

#1804 chore: fixes broken internal URLs in `products/android/`
  products/android/10.0/index.php
  products/android/2.0/index.php
Labels: fix, chore

#1805 chore: changes h2 to h1 tags
  developer/index.php
  index.php
  keyboard/index.php
  products/index.php
Labels: chore

#1812 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-generate.generatoroptions.icon.md
  developer/18.0/reference/api/kmc-generate.generatoroptions.md
  developer/18.0/reference/kmc/cli/reference.md
  developer/18.0/reference/messages/km0b01c.md
  developer/18.0/reference/messages/km0b01d.md
  developer/18.0/reference/messages/km0b01e.md
  developer/18.0/reference/messages/km0b01f.md
  developer/18.0/reference/messages/km0b020.md
  developer/18.0/reference/messages/kmc-copy.copiermessages.md
Labels: auto

#1813 auto: Keyboard help deployment
  keyboard/easy_arabic/1.0/easy_arabic.php
Labels: auto

#1814 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/3.0.3/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.0.3/taigitelexU_.png
  keyboard/taigi_viet_telex/3.0.3/taigitelexU_S.png
Labels: auto

#1815 auto: Keyman for mac help deployment
  products/mac/18.0/about/history.md
  products/mac/18.0/about/requirements.md
  products/mac/18.0/about/welcome.md
  products/mac/18.0/about/whatsnew.md
  products/mac/18.0/basic/index.md
  products/mac/18.0/start/install-keyboard.md
  products/mac/18.0/troubleshooting/index.md
  products/mac/18.0/troubleshooting/uninstall-keyman.md
Labels: auto

#1816 auto: Keyman for ios help deployment
  developer/engine/iphone-and-ipad/18.0/guides/in-app/index.md
  developer/engine/iphone-and-ipad/18.0/guides/system-keyboard/index.md
  products/iphone-and-ipad/18.0/about/history.md
  products/iphone-and-ipad/18.0/about/index.md
  products/iphone-and-ipad/18.0/about/welcome.md
  products/iphone-and-ipad/18.0/about/whatsnew.md
  products/iphone-and-ipad/18.0/basic/index.md
  products/iphone-and-ipad/18.0/context/gestures.md
  products/iphone-and-ipad/18.0/start/index.md
  products/iphone-and-ipad/18.0/troubleshooting/index.md
Labels: auto

#1818 auto: Keyman for windows help deployment
  products/windows/18.0/about/history.md
  products/windows/18.0/about/requirements.md
  products/windows/18.0/about/welcome.md
  products/windows/18.0/about/whatsnew.md
  products/windows/18.0/index.md
  products/windows/18.0/start/download-and-install-keyboard.md
  products/windows/18.0/start/download-and-install-keyman.md
  products/windows/18.0/troubleshooting/index.md
Labels: auto

#1819 auto: Keyboard help deployment
  keyboard/slp1_deva/1.0/slp1_deva.php
  keyboard/slp1_roman/1.0/slp1_roman.php
Labels: auto

#1820 chore: adjust anchor and bookmark link
  developer/engine/android/15.0/index.php
  developer/keyboards/github/step-2.md
Labels: bug, chore

#1822 auto: Keyman for android help deployment
  developer/engine/android/18.0/whatsnew.md
  products/android/18.0/about/history.md
  products/android/18.0/about/welcome.md
  products/android/18.0/about/whatsnew.md
  products/android/18.0/start/installing-keyboards.md
  products/android/18.0/troubleshooting/grant-storage-permission.md
  products/android/18.0/troubleshooting/index.md
Labels: auto

#1823 auto: Keyman for windows help deployment
  products/windows/18.0/start/tutorial.md
Labels: auto

#1824 auto: Keyman for developer help deployment
  developer/18.0/guides/lexical-models/advanced/unicode-breaker-extension.md
  developer/18.0/guides/lexical-models/advanced/word-breaker.md
  developer/18.0/reference/file-types/metadata.md
  developer/18.0/reference/file-types/tsv.md
Labels: auto

#1825 auto: Keyboard help deployment
  keyboard/burushaski_girminas/2.1.0/burushaski_girminas.php
  keyboard/burushaski_girminas/2.1.0/image_keyboard_guide2.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/bsk_perso_arabic_keyboard_keystrokes.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/burushaski_additional_characters.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/burushaski_girminas_perso_arabic.php
  keyboard/burushaski_girminas_perso_arabic/2.0.0/burushaski_keyboard_orthography_guide.pdf
  keyboard/burushaski_girminas_perso_arabic/2.0.0/hunza_nagar_text.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/key_combination_chart_equation.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/orthography.png
  keyboard/burushaski_girminas_perso_arabic/2.0.0/yasin_text.png
  keyboard/easy_chakma/2.0.0/easy_chakma.php
  keyboard/easy_chakma/2.0.0/images/image001.jpg
  keyboard/easy_chakma/2.0.0/images/image002.jpg
  keyboard/easy_chakma/2.0.0/images/image003.jpg
  keyboard/easy_chakma/2.0.0/images/image004.png
  keyboard/easy_chakma/2.0.0/images/image005.png
  keyboard/easy_chakma/2.0.0/images/image006.png
  keyboard/udi_keyboard/1.2.0/Udi_Documentation-en.pdf
  keyboard/udi_keyboard/1.2.0/Udi_Documentation-ru.pdf
  keyboard/udi_keyboard/1.2.0/udi_keyboard.php
  keyboard/vietnamese_telex/1.6.0/vietnamese_telex.php
Labels: auto

#1826 auto: Keyman for android help deployment
  products/android/17.0/troubleshooting/grant-storage-permission.md
Labels: auto

#1821 fix: prevent KeymanWeb load of keyboards that do not have .js versions
  cdn/dev/js/kbd-docs.js
Labels: fix

#1828 auto: Keyboard help deployment
  keyboard/rac_shina/1.2.0/rac_shina.php
  keyboard/rac_shina/1.2.0/rac_shina_layout.png
Labels: auto

#1830 auto: Keyboard help deployment
  keyboard/old_hungarian_carpathian_highlands/1.0/old_hungarian_carpathian_highlands.php
Labels: auto

#1803 chore: fixes Blocked due to other 4xx issue in Google Search Console
  developer/cloud/search/1.0/index.php
  developer/cloud/search/2.0/index.md
Labels: chore

#1831 auto: Keyman for web help deployment
  developer/engine/web/18.0/guide/examples/__auto-control.html
  developer/engine/web/18.0/guide/examples/__control-by-control.html
  developer/engine/web/18.0/guide/examples/__first-example.html
  developer/engine/web/18.0/guide/examples/__full-manual-control.html
  developer/engine/web/18.0/guide/examples/__manual-control.html
Labels: auto

#1832 auto: Keyman for android help deployment
  developer/engine/android/18.0/guides/in-app/index.md
  developer/engine/android/18.0/guides/system-keyboard/index.md
  products/android/18.0/about/index.md
  products/android/18.0/basic/index.md
  products/android/18.0/context/gestures.md
  products/android/18.0/start/enabling-system-keyboard.md
  products/android/18.0/start/index.md
  products/android/18.0/troubleshooting/grant-storage-permission.md
Labels: auto

#1833 auto: Keyman for windows help deployment
  developer/engine/windows/18.0/api/index.md
  products/windows/18.0/about/credits.md
  products/windows/18.0/about/index.md
  products/windows/18.0/about/license.md
  products/windows/18.0/advanced/index.md
  products/windows/18.0/basic/index.md
  products/windows/18.0/basic/uninstall-keyboard.md
  products/windows/18.0/basic/uninstall.md
  products/windows/18.0/basic/update.md
  products/windows/18.0/start/index.md
  products/windows/18.0/start/tutorial.md
Labels: auto

#1834 auto: Keyman for ios help deployment
  developer/engine/iphone-and-ipad/18.0/guides/in-app/index.md
  developer/engine/iphone-and-ipad/18.0/guides/system-keyboard/index.md
  products/iphone-and-ipad/18.0/about/index.md
  products/iphone-and-ipad/18.0/basic/index.md
  products/iphone-and-ipad/18.0/context/gestures.md
  products/iphone-and-ipad/18.0/start/index.md
Labels: auto

#1835 auto: Keyman for developer help deployment
  developer/18.0/reference/api/kmc-copy.copieroptions.md
  developer/18.0/reference/api/kmc-copy.copieroptions.relocateexternalfiles.md
  developer/18.0/reference/api/kmc-copy.keymanprojectcopier.md
  developer/18.0/reference/api/kmc-copy.keymanprojectcopier.relocateexternalfiles.md
  developer/18.0/reference/api/kmc-keyboard-info.keyboardinfocompiler._constructor_.md
  developer/18.0/reference/api/kmc-keyboard-info.keyboardinfocompiler.md
  developer/18.0/reference/kmc/cli/reference.md
  developer/18.0/reference/messages/common-types.commontypesmessages.md
  developer/18.0/reference/messages/km01003.md
Labels: auto
