Repository keymanapp/help.keyman.com, pull requests merged in 2025-04, with the labels that each got.

#1968 auto: Keyboard help deployment
  keyboard/greek_tonizo/1.0.2/greek_tonizo.php
  keyboard/greek_tonizo/1.0.2/kbd.jpg
  keyboard/greek_tonizo/1.0.2/kbd1.jpg
  keyboard/greek_tonizo/1.0.2/kbd3.jpg
  keyboard/greek_tonizo/1.0.2/kbd4.jpg
Labels: auto

#1971 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km09011.md
  developer/18.0/reference/messages/km09012.md
  developer/18.0/reference/messages/km09013.md
  developer/18.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
Labels: auto

#1973 auto: Keyboard help deployment
  keyboard/masaba/1.0/masaba.php
Labels: auto

#1975 auto: Keyboard help deployment
  keyboard/basic_kbdcherp/1.1.0/basic_kbdcherp.php
  keyboard/basic_kbdgr1/1.1/basic_kbdgr1.php
  keyboard/basic_kbdtajik/1.1/basic_kbdtajik.php
  keyboard/buhid/1.0.1/buhid.php
  keyboard/clavbur9/9.1.1/clavbur9.php
  keyboard/colchis_phonetic/1.1/colchis_phonetic.php
  keyboard/eo_plus/3.0.1/eo_plus.php
  keyboard/fv_gwichin/9.2.1/fv_gwichin.php
  keyboard/fv_nlekepmxcin/9.5.1/fv_nlekepmxcin.php
  keyboard/fv_nsilxcen/10.0.1/fv_nsilxcen.php
  keyboard/fv_ojibwa_rdot/1.0.3/fv_ojibwa_rdot.php
  keyboard/fv_severn_ojibwa/10.1.2/fv_severn_ojibwa.php
  keyboard/fv_severn_ojibwa_rdot/1.1.1/fv_severn_ojibwa_rdot.php
  keyboard/fv_southern_tutchone/9.3/fv_southern_tutchone.php
  keyboard/fv_tagizi_dene/9.4/fv_tagizi_dene.php
  keyboard/galaxie_greek_mnemonic/3.3/galaxie_greek_mnemonic.php
  keyboard/galaxie_hebrew_mnemonic/3.3.1/galaxie_hebrew_mnemonic.php
  keyboard/gautami_bangla_bengali/1.0/gautami_bangla_bengali.php
  keyboard/gautami_devanagari/1.0/gautami_devanagari.php
  keyboard/gff_amharic/3.1.2/gff_amharic.php
  keyboard/gff_amharic_classic/2.0/gff_amharic_classic.php
  keyboard/gff_gurage_and_amharic/1.1.1/gff_gurage_and_amharic.php
  keyboard/gff_sbs/1.0.8/gff_sbs.php
  keyboard/gondi_tel/1.0.2/gondi_tel.php
  keyboard/korean_phonetic/2.0/korean_phonetic.php
  keyboard/manga_ajami_azerty/1.0/manga_ajami_azerty.php
  keyboard/manga_ajami_qwerty/1.0/manga_ajami_qwerty.php
  keyboard/manga_latin_azerty/1.0/manga_latin_azerty.php
  keyboard/manga_latin_qwerty/1.0/manga_latin_qwerty.php
  keyboard/masaram_gondi/1.2.2/masaram_gondi.php
  keyboard/nlci_ipa/2.1/nlci_ipa.php
  keyboard/numanggang/1.0/numanggang.php
  keyboard/pukapuka/1.3/pukapuka.php
  keyboard/rac_brahui/1.0.1/rac_brahui.php
  keyboard/rawang/1.7/rawang.php
  keyboard/shahmukhi_phonetic/1.1/shahmukhi_phonetic.php
  keyboard/sil_brao/1.0.2/sil_brao.php
  keyboard/sil_korda_latin/3.0/sil_korda_latin.php
  keyboard/sil_korean_morse/2.0/sil_korean_morse.php
  keyboard/sil_makuri/1.0.1/sil_makuri.php
  keyboard/sil_sgaw_karen/1.1.2/sil_sgaw_karen.php
  keyboard/soqotri_arabic/1.1/soqotri_arabic.php
  keyboard/sorani_behdini_arab_qwerty/1.0.2/sorani_behdini_arab_qwerty.php
  keyboard/srr_ajami_qwerty/1.1/srr_ajami_qwerty.php
  keyboard/thamizha_new_typewriter/2.2.1/thamizha_new_typewriter.php
  keyboard/vm_tamil_modular/1.2.1/vm_tamil_modular.php
Labels: auto

#1976 auto: Keyboard help deployment
  keyboard/hoisan/1.0/consonants.png
  keyboard/hoisan/1.0/hoisan.php
  keyboard/hoisan/1.0/tones.png
  keyboard/hoisan/1.0/vowels.png
Labels: auto

#1978 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/applyKeyboardHeight.md
  developer/engine/android/18.0/KMManager/getDefaultKeyboardHeight.md
  developer/engine/android/18.0/KMManager/getKeyboardHeight.md
  products/android/18.0/basic/config/adjust-keyboard-height.md
Labels: auto

#1980 auto: Keyboard help deployment
  keyboard/zanan/1.0/zanan.php
Labels: auto

#1982 auto: Keyboard help deployment
  keyboard/luo_lakeside/1.0.1/luo_lakeside.php
Labels: auto

#1983 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/applyKeyboardHeight.md
Labels: auto

#1984 auto: Keyboard help deployment
  keyboard/fv_hailzaqvla/10/fv_hailzaqvla.php
  keyboard/unifon/1.0/unifon.php
Labels: auto

#1985 auto: Keyboard help deployment
  keyboard/belgian_typewriter/1.0/belgian_typewriter.php
Labels: auto

#1986 auto: Keyboard help deployment
  keyboard/hong_kong/1.0/consonants.png
  keyboard/hong_kong/1.0/hong_kong.php
  keyboard/hong_kong/1.0/tones.png
  keyboard/hong_kong/1.0/vowels.png
Labels: auto

#1987 auto: Keyboard help deployment
  keyboard/greek_tonizo/1.0.3/greek_tonizo.php
  keyboard/greek_tonizo/1.0.3/kbd.jpg
  keyboard/greek_tonizo/1.0.3/kbd1.jpg
  keyboard/greek_tonizo/1.0.3/kbd3.jpg
  keyboard/sil_ipa/2.0.0/sil_ipa.php
Labels: auto

#1988 auto: Keyboard help deployment
  keyboard/vietnam/1.0.5/vietnam.php
Labels: auto

#1989 auto: Keyboard help deployment
  keyboard/khmer_angkor/2.2/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/2.2/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/2.2/khmer_angkor.php
  keyboard/khmer_angkor/2.2/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/2.2/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/2.2/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/2.2/khmer_angkor/image001.png
  keyboard/khmer_angkor/2.2/khmer_angkor/image002.png
  keyboard/khmer_angkor/2.2/khmer_angkor/image003.png
  keyboard/khmer_angkor/2.2/khmer_angkor/image004.png
  keyboard/khmer_angkor/2.2/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/2.2/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/2.2/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/2.2/khmer_angkor/themedata.thmx
Labels: auto

#1992 auto: Keyman for web help deployment
  developer/engine/web/18.0/reference/osk/classes.md
Labels: auto

#1993 auto: Keyboard help deployment
  keyboard/sil_ipa/2.0.1/sil_ipa.php
Labels: auto

#1995 auto: Keyboard help deployment
  keyboard/cantonese_telex/3.0/cantonese_telex.php
  keyboard/cantonese_telex/3.0/consonants.png
  keyboard/cantonese_telex/3.0/tones.png
  keyboard/cantonese_telex/3.0/vowels.png
Labels: auto

#2001 auto: Keyboard help deployment
  keyboard/vietnam/1.0.6/vietnam.php
Labels: auto

#2002 auto: Keyboard help deployment
  keyboard/shahmukhi_phonetic/1.1.1/shahmukhi_phonetic.php
Labels: auto

#2004 auto: Keyman for windows help deployment
  products/windows/18.0/common/os.md
  products/windows/18.0/common/requirements.md
  products/windows/18.0/index.md
Labels: auto

#2005 auto: Keyman for developer help deployment
  developer/19.0/reference/messages/km09011.md
  developer/19.0/reference/messages/km09012.md
  developer/19.0/reference/messages/km09013.md
  developer/19.0/reference/messages/kmc-keyboard-info.keyboardinfocompilermessages.md
Labels: auto

#2006 auto: Keyboard help deployment
  keyboard/vietnam/1.0.7/vietnam.php
Labels: auto

#2007 auto: Keyman for windows help deployment
  products/windows/19.0/common/os.md
  products/windows/19.0/common/requirements.md
  products/windows/19.0/index.md
Labels: auto

#2008 auto: Keyboard help deployment
  keyboard/hindi_flick/1.0/hindi_flick.php
Labels: auto

#2009 auto: Keyboard help deployment
  keyboard/gff_amharic/3.1.3/AmharicTyping-Amharic.pdf
  keyboard/gff_amharic/3.1.3/AmharicTyping-English.pdf
  keyboard/gff_amharic/3.1.3/gff_amharic.php
  keyboard/gff_amharic/3.1.3/images/gff_amharic-default-1.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-default-2-orig.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-default-2.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-default-3.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-default-4.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-numerals-1.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-numerals-2.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-numerals-3.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-numerals-4.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-punctuation-1.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-punctuation-2.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-punctuation-3.jpeg
  keyboard/gff_amharic/3.1.3/images/gff_amharic-punctuation-4.jpeg
  keyboard/gff_amharic/3.1.3/kb.css
Labels: auto

#2010 auto: Keyman for android help deployment
  developer/engine/android/19.0/KMManager/applyKeyboardHeight.md
  developer/engine/android/19.0/KMManager/setHTMLBanner.md
Labels: auto

#2011 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/applyKeyboardHeight.md
  developer/engine/android/18.0/KMManager/setHTMLBanner.md
Labels: auto

#2014 chore: stable-18.0 (shared-sites v0.21)
  build.sh
Labels: chore

#2013 fix: Disallow all bots since staging site doesn't need to be indexed
  robots.txt
Labels: staging

#2015 auto: Keyboard help deployment
  keyboard/hindi_flick/1.0/hindi_flick.php
Labels: auto

#2016 auto: Keyboard help deployment
  keyboard/nlci_gujarati_winscript/2.1/nlci_gujarati_winscript.php
  keyboard/remington_gail/1.0/remington_gail.php
  keyboard/sil_korda_jamo/3.0/sil_korda_jamo.php
  keyboard/sil_korda_latin/3.0/sil_korda_latin.php
  keyboard/sil_senegal_bqj_azerty/1.0.1/sil_senegal_bqj_azerty.php
Labels: auto

#2018 auto: Keyboard help deployment
  keyboard/basic_kbdiulat/1.2.1/basic_kbdiulat.php
  keyboard/cantonese_telex/3.0.1/cantonese_telex.php
  keyboard/cantonese_telex/3.0.1/consonants.png
  keyboard/cantonese_telex/3.0.1/tones.png
  keyboard/cantonese_telex/3.0.1/vowels.png
  keyboard/enggano/1.0.1/enggano.php
  keyboard/hainam/1.0.1/consonants.png
  keyboard/hainam/1.0.1/hainam.php
  keyboard/hainam/1.0.1/tones.png
  keyboard/hainam/1.0.1/uchauU_.png
  keyboard/hainam/1.0.1/uchauU_S.png
  keyboard/hainam/1.0.1/vowels1.png
  keyboard/hainam/1.0.1/vowels2.png
  keyboard/hong_kong/1.0.2/consonants.png
  keyboard/hong_kong/1.0.2/hong_kong.php
  keyboard/hong_kong/1.0.2/tones.png
  keyboard/hong_kong/1.0.2/vowels.png
  keyboard/obolo_chwerty/1.5.2/chwerty_default.png
  keyboard/obolo_chwerty/1.5.2/chwerty_keycombi.png
  keyboard/obolo_chwerty/1.5.2/chwerty_mobi_alt.png
  keyboard/obolo_chwerty/1.5.2/chwerty_mobi_default.png
  keyboard/obolo_chwerty/1.5.2/chwerty_mobi_shift.png
  keyboard/obolo_chwerty/1.5.2/chwerty_shift.png
  keyboard/obolo_chwerty/1.5.2/chwertyftkey1.png
  keyboard/obolo_chwerty/1.5.2/chwertyftkey2.png
  keyboard/obolo_chwerty/1.5.2/chwertyftkey3.png
  keyboard/obolo_chwerty/1.5.2/obolo_chwerty.php
  keyboard/obolo_qwerty/1.1.3/obolo_qwerty.php
  keyboard/obolo_qwerty/1.1.3/qwerty_default.png
  keyboard/obolo_qwerty/1.1.3/qwerty_keycombi.png
  keyboard/obolo_qwerty/1.1.3/qwerty_mobialt.png
  keyboard/obolo_qwerty/1.1.3/qwerty_mobidefault.png
  keyboard/obolo_qwerty/1.1.3/qwerty_mobishifted.png
  keyboard/obolo_qwerty/1.1.3/qwerty_shifted.png
  keyboard/obolo_qwerty/1.1.3/qwertyftkey1.png
  keyboard/obolo_qwerty/1.1.3/qwertyftkey2.png
  keyboard/obolo_qwerty/1.1.3/qwertyftkey3.png
Labels: auto

#2025 auto: Keyboard help deployment
  keyboard/sil_akebu/1.0.0/sil_akebu.php
  keyboard/sil_buang/1.2/sil_buang.php
  keyboard/sil_busa/1.5.1/sil_busa.php
  keyboard/sil_cheyenne/1.1.1/sil_cheyenne.php
  keyboard/sil_hawaiian/2.3/sil_hawaiian.php
  keyboard/sil_korean_morse/2.0/sil_korean_morse.php
  keyboard/sil_sahu/1.0.1/sil_sahu.php
  keyboard/sil_senegal_bsc_azerty/1.0.2/sil_senegal_bsc_azerty.php
  keyboard/sil_senegal_cou_azerty/1.0.3/sil_senegal_cou_azerty.php
  keyboard/sil_senegal_cou_qwerty/1.1.2/sil_senegal_cou_qwerty.php
  keyboard/sil_senegal_csk_azerty/1.0.1/sil_senegal_csk_azerty.php
  keyboard/sil_senegal_dyo_azerty/1.0.1/sil_senegal_dyo_azerty.php
  keyboard/sil_senegal_gsl_azerty/1.0.1/sil_senegal_gsl_azerty.php
  keyboard/sil_senegal_knf_azerty/1.0.1/sil_senegal_knf_azerty.php
  keyboard/sil_senegal_krx_azerty/1.0.1/sil_senegal_krx_azerty.php
  keyboard/sil_senegal_krx_qwerty/1.1.0/sil_senegal_krx_qwerty.php
  keyboard/sil_senegal_ndv_azerty/1.0.1/sil_senegal_ndv_azerty.php
  keyboard/sil_senegal_sav_azerty/1.0.1/sil_senegal_sav_azerty.php
  keyboard/sil_senegal_snf_azerty/1.0.1/sil_senegal_snf_azerty.php
  keyboard/sil_senegal_srr_azerty/1.0.1/sil_senegal_srr_azerty.php
  keyboard/sil_senegal_wo_azerty/1.0.1/sil_senegal_wo_azerty.php
  keyboard/sil_tai_dam_lao/2.1/sil_tai_dam_lao.php
  keyboard/sil_tai_dam_latin/1.5/sil_tai_dam_latin.php
  keyboard/sil_tai_dam_typewriter/1.2/sil_tai_dam_typewriter.php
  keyboard/sil_tanguat/1.0/sil_tanguat.php
  keyboard/sil_tepehuan/1.1/sil_tepehuan.php
  keyboard/sil_yupik_cyrillic/2.1/sil_yupik_cyrillic.php
  keyboard/sil_yupik_cyrillic_ru/1.0/sil_yupik_cyrillic_ru.php
  keyboard/sil_yupik_cyrillic_ru/1.0/sil_yupik_cyrillic_ru_russian.php
Labels: auto

#2026 auto: Keyboard help deployment
  keyboard/bj_cree_east_james_bay/1.2/bj_cree_east_james_bay.php
  keyboard/bj_cree_woods/1.3/bj_cree_woods.php
  keyboard/bj_mista_wasaha_cree/1.2.1/bj_mista_wasaha_cree.php
  keyboard/bj_oji_cree/9.2.0/bj_oji_cree.php
  keyboard/galaxie_greek_mnemonic/3.3/galaxie_greek_mnemonic.php
  keyboard/galaxie_greek_mnemonic/3.3/keyboardchart.php
  keyboard/gautami_bangla_bengali/1.0/gautami_bangla_bengali.php
  keyboard/gautami_devanagari/1.0/gautami_devanagari.php
  keyboard/gautami_inditran/1.0.2/gautami_inditran.php
  keyboard/gautami_thamizh_tamil/1.0.3/gautami_thamizh_tamil.php
  keyboard/nepali_romanized/1.0.1/nepali_romanized.php
Labels: auto

#2027 auto: Keyboard help deployment
  keyboard/gff_amh_7/1.5.1/gff_amh_7.php
  keyboard/gff_amh_7/1.5.1/html.css
  keyboard/gff_amharic/3.1.3/gff_amharic.php
  keyboard/gff_amharic/3.1.3/html.css
  keyboard/gff_amharic/3.1.3/kb.css
  keyboard/gff_amharic_classic/2.0/gff_amharic_classic.php
  keyboard/gff_amharic_classic/2.0/html.css
  keyboard/gff_awngi_xamtanga/1.0.3/gff_awngi_xamtanga.php
  keyboard/gff_awngi_xamtanga/1.0.3/html.css
  keyboard/gff_blin/1.5.5/gff_blin.php
  keyboard/gff_blin/1.5.5/html.css
  keyboard/gff_ethiopic/1.0.3/gff_ethiopic.php
  keyboard/gff_ethiopic/1.0.3/html.css
  keyboard/gff_geez/2.0.2/gff_geez.php
  keyboard/gff_geez/2.0.2/html.css
  keyboard/gff_geez_emufi/1.0.1/gff_geez_emufi.php
  keyboard/gff_geez_emufi/1.0.1/html.css
  keyboard/gff_gurage/1.0.1/gff_gurage.php
  keyboard/gff_gurage/1.0.1/html.css
  keyboard/gff_gurage_legacy/1.0.1/gff_gurage_legacy.php
  keyboard/gff_gurage_legacy/1.0.1/html.css
  keyboard/gff_harari/1.0.5/gff_harari.php
  keyboard/gff_harari/1.0.5/html.css
  keyboard/gff_harege_fidelat/1.1.1/gff_harege_fidelat.php
  keyboard/gff_harege_fidelat/1.1.1/html.css
  keyboard/gff_mesobe_fidelat/1.1.1/gff_mesobe_fidelat.php
  keyboard/gff_mesobe_fidelat/1.1.1/html.css
  keyboard/gff_musnad/1.0.1/gff_musnad.php
  keyboard/gff_sbs/1.0.8/gff_sbs.php
  keyboard/gff_tigre/1.0.3/gff_tigre.php
  keyboard/gff_tigre/1.0.3/html.css
  keyboard/gff_tigrinya_eritrea/2.0.3/gff_tigrinya_eritrea.php
  keyboard/gff_tigrinya_eritrea/2.0.3/html.css
  keyboard/gff_tigrinya_ethiopia/2.0.4/gff_tigrinya_ethiopia.php
  keyboard/gff_tigrinya_ethiopia/2.0.4/html.css
Labels: auto

#2032 auto: Keyboard help deployment
  keyboard/dakota_smsc/1.5.1/dakota_smsc.php
  keyboard/embera_north/10.1.5/embera_north.php
  keyboard/gondi_dev/1.1.2/gondi_dev.php
  keyboard/gondi_gunjala/1.1.3/gondi_gunjala.php
  keyboard/gondi_gunjala_inscript/1.2/gondi_gunjala_inscript.php
  keyboard/gondi_tel/1.0.2/gondi_tel.php
  keyboard/indigenous_nt/4.0.6/indigenous_nt.php
  keyboard/irula_tamil_winscript/3.0/irula_tamil_winscript.php
  keyboard/landuma/1.1.3/landuma.php
  keyboard/mozhi_malayalam/3.2.6/mozhi_malayalam.php
  keyboard/nlci_bengali_winscript/2.1/nlci_bengali_winscript.php
  keyboard/nlci_devanagari_winscript/2.2.1/nlci_devanagari_winscript.php
  keyboard/nlci_kannada_winscript/2.1/nlci_kannada_winscript.php
  keyboard/nlci_malayalam_winscript/2.1/nlci_malayalam_winscript.php
  keyboard/nlci_oriya_winscript/2.1/nlci_oriya_winscript.php
  keyboard/nlci_tamil_winscript/2.2/nlci_tamil_winscript.php
  keyboard/nlci_telugu_winscript/2.1/nlci_telugu_winscript.php
  keyboard/pukapuka/1.3/pukapuka.php
  keyboard/rac_kashmiri/1.0/rac_kashmiri.php
Labels: auto

#2033 auto: Keyboard help deployment
  keyboard/inuktitut_pirurvik/1.4.1/inuktitut_pirurvik.php
Labels: auto
