Repository keymanapp/help.keyman.com, pull requests merged in 2025-03, with the labels that each got.

#1904 auto: Keyman for android help deployment
  developer/engine/android/19.0/KMManager/getLongpressDelay.md
  developer/engine/android/19.0/KMManager/index.md
  developer/engine/android/19.0/KMManager/sendOptionsToKeyboard.md
  developer/engine/android/19.0/KMManager/setLongpressDelay.md
Labels: auto

#1905 auto: Keyman for web help deployment
  developer/engine/web/19.0/guide/examples/__manual-control.html
  developer/engine/web/19.0/guide/examples/manual-control.md
Labels: auto

#1906 auto: Keyman for developer help deployment
  developer/19.0/reference/messages/km020b1.md
  developer/19.0/reference/messages/km020b2.md
  developer/19.0/reference/messages/km05023.md
  developer/19.0/reference/messages/km05024.md
  developer/19.0/reference/messages/km05025.md
  developer/19.0/reference/messages/km05026.md
  developer/19.0/reference/messages/km05027.md
  developer/19.0/reference/messages/km05028.md
  developer/19.0/reference/messages/km0a002.md
  developer/19.0/reference/messages/km0b002.md
  developer/19.0/reference/messages/kmc-copy.copiermessages.md
  developer/19.0/reference/messages/kmc-generate.generatormessages.md
  developer/19.0/reference/messages/kmc-kmn.kmncompilermessages.md
  developer/19.0/reference/messages/kmc.infrastructuremessages.md
Labels: auto

#1902 docs: Update compile-targets.md for 19.0
  developer/language/guide/compile-targets.md
Labels: docs

#1903 docs: Fix typo in headers.md
  developer/language/guide/headers.md
Labels: docs

#1907 auto: Keyboard help deployment
  keyboard/vietnam/1.0.1/vietnam.php
Labels: auto

#1908 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/closeParentAppOnShowKeyboardPicker.md
  developer/engine/android/18.0/KMManager/dontCloseParentAppOnShowKeyboardPicker.md
  developer/engine/android/18.0/KMManager/index.md
Labels: auto

#1910 auto: Keyman for android help deployment
  products/android/18.0/about/whatsnew.md
Labels: auto

#1913 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/about/system-requirements.md
Labels: auto

#1914 auto: Keyboard help deployment
  keyboard/vietnam/1.0.2/vietnam.php
Labels: auto

#1915 auto: Keyboard help deployment
  keyboard/jerriais/1.0/jerriais.php
Labels: auto

#1917 auto: Keyboard help deployment
  keyboard/adinkra/1.0/AdinkraKeyboardLayout.png
  keyboard/adinkra/1.0/adinkra.php
Labels: auto

#1918 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km05003.md
  developer/18.0/reference/messages/kmc.infrastructuremessages.md
Labels: auto

#1919 auto: Keyboard help deployment
  keyboard/jerriais/1.0.1/jerriais.php
Labels: auto

#1921 auto: Keyboard help deployment
  keyboard/taigi_viet_telex/3.1/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.1/taigitelexU_.png
  keyboard/taigi_viet_telex/3.1/taigitelexU_S.png
Labels: auto

#1922 auto: Keyman for mac help deployment
  products/mac/18.0/mac_images/keyman-security-prompt-ventura.png
  products/mac/18.0/mac_images/open-apple-menu.png
  products/mac/18.0/mac_images/privacy-accessibility-enabled.png
  products/mac/18.0/mac_images/privacy-and-security-annotated.png
  products/mac/18.0/mac_images/privacy_accessibility.png
  products/mac/18.0/mac_images/privacy_files_and_folders.png
  products/mac/18.0/mac_images/privacy_input_monitoring.png
  products/mac/18.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/18.0/mac_images/system_preferences.png
  products/mac/18.0/troubleshooting/configure-security.md
Labels: auto

#1920 chore: use simpler bootstrap and shared sentry
  .gitignore
  _includes/2020/HelpKeymanComSentry.php
  _includes/includes/head.php
  _includes/includes/template.php
  build.sh
  cdn/dev/js/bundle.min.js.map
  cdn/dev/js/sentry.bundle.5.28.0.min.js
Labels: chore

#1924 auto: Keyman for mac help deployment
  products/mac/19.0/about/requirements.md
  products/mac/19.0/common/os.md
  products/mac/19.0/mac_images/keyman-security-prompt-ventura.png
  products/mac/19.0/mac_images/open-apple-menu.png
  products/mac/19.0/mac_images/privacy-accessibility-enabled.png
  products/mac/19.0/mac_images/privacy-and-security-annotated.png
  products/mac/19.0/mac_images/privacy_accessibility.png
  products/mac/19.0/mac_images/privacy_files_and_folders.png
  products/mac/19.0/mac_images/privacy_input_monitoring.png
  products/mac/19.0/mac_images/privacy_input_monitoring_locked.png
  products/mac/19.0/mac_images/system_preferences.png
  products/mac/19.0/troubleshooting/configure-security.md
Labels: auto

#1925 auto: Keyman for ios help deployment
  products/iphone-and-ipad/19.0/about/system-requirements.md
Labels: auto

#1926 auto: Keyman for android help deployment
  developer/engine/android/19.0/KMManager/closeParentAppOnShowKeyboardPicker.md
  developer/engine/android/19.0/KMManager/dontCloseParentAppOnShowKeyboardPicker.md
  developer/engine/android/19.0/KMManager/index.md
Labels: auto

#1927 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/basic/config/index.md
Labels: auto

#1928 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/getMaySendCrashReport.md
  developer/engine/android/18.0/KMManager/index.md
  developer/engine/android/18.0/KMManager/setMaySendCrashReport.md
  products/android/18.0/about/privacy.md
  products/android/18.0/basic/config/index.md
Labels: auto

#1929 auto: Keyboard help deployment
  keyboard/mingrelian_cyrillic/1.0/mingrelian_cyrillic.php
  keyboard/mingrelian_cyrillic/1.0/mingrelian_cyrillicU_.png
  keyboard/mingrelian_cyrillic/1.0/mingrelian_cyrillicU_S.png
  keyboard/mingrelian_cyrillic/1.0/mingrelian_cyrillicU_SRA.png
Labels: auto

#1930 auto: Keyman for developer help deployment
  developer/19.0/reference/messages/km05003.md
  developer/19.0/reference/messages/kmc.infrastructuremessages.md
Labels: auto

#1931 auto: Keyboard help deployment
  keyboard/winchus/1.1.1/01-capa-emoji-donde-360.png
  keyboard/winchus/1.1.1/02-primeros-emojis-360.png
  keyboard/winchus/1.1.1/03-otros-emojis-donde-360.png
  keyboard/winchus/1.1.1/04-volver-capa-emojis-principal-360.png
  keyboard/winchus/1.1.1/05-volver-al-teclado-360.png
  keyboard/winchus/1.1.1/06-presion-larga-360.png
  keyboard/winchus/1.1.1/07-signo-de-mas-174.png
  keyboard/winchus/1.1.1/08-cambiar-teclado-360.png
  keyboard/winchus/1.1.1/deslizar-360-1era-imagen.png
  keyboard/winchus/1.1.1/deslizar-360.gif
  keyboard/winchus/1.1.1/file-type-pdf-47.png
  keyboard/winchus/1.1.1/winchus.pdf
  keyboard/winchus/1.1.1/winchus.php
  keyboard/winchus/1.1.1/windows-30.png
Labels: auto

#1933 auto: Keyboard help deployment
  keyboard/winchus/1.2/01-capa-emoji-donde-360.png
  keyboard/winchus/1.2/02-primeros-emojis-360.png
  keyboard/winchus/1.2/03-otros-emojis-donde-360.png
  keyboard/winchus/1.2/04-volver-capa-emojis-principal-360.png
  keyboard/winchus/1.2/05-volver-al-teclado-360.png
  keyboard/winchus/1.2/06-presion-larga-360.png
  keyboard/winchus/1.2/07-signo-de-mas-174.png
  keyboard/winchus/1.2/08-cambiar-teclado-360.png
  keyboard/winchus/1.2/deslizar-360-1era-imagen.png
  keyboard/winchus/1.2/deslizar-360.gif
  keyboard/winchus/1.2/file-type-pdf-47.png
  keyboard/winchus/1.2/kb.css
  keyboard/winchus/1.2/teclado_winchus_alt_tran.png
  keyboard/winchus/1.2/teclado_winchus_may_tran.png
  keyboard/winchus/1.2/teclado_winchus_min_tran.png
  keyboard/winchus/1.2/winchus.pdf
  keyboard/winchus/1.2/winchus.php
  keyboard/winchus/1.2/windows-30.png
Labels: auto

#1935 auto: Keyboard help deployment
  keyboard/manchu/1.0.1/manchu.php
  keyboard/mingrelian_cyrillic/1.0/mingrelian_cyrillic.php
Labels: auto

#1936 auto: Keyboard help deployment
  keyboard/sahtu/2.0/sahtu.php
Labels: auto

#1937 auto: Keyboard help deployment
  keyboard/wakhi/3.0/wakhi.php
Labels: auto

#1938 auto: Keyboard help deployment
  keyboard/vietnam/1.0.3/vietnam.php
Labels: auto

#1939 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km020b3.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
Labels: auto

#1934 docs(developer): clarify usage of `nul` statement in rule output
  developer/language/reference/_nul.md
Labels: docs

#1940 auto: Keyboard help deployment
  keyboard/slp1_roman/1.0.1/slp1_roman.php
Labels: auto

#1942 fix: prepend slash to broken redirect in Windows 14 docs
  products/windows/.htaccess
Labels: fix

#1943 auto: Keyboard help deployment
  keyboard/khmer_angkor/2.1/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/2.1/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/2.1/khmer_angkor.php
  keyboard/khmer_angkor/2.1/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/2.1/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/2.1/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/2.1/khmer_angkor/image001.png
  keyboard/khmer_angkor/2.1/khmer_angkor/image002.png
  keyboard/khmer_angkor/2.1/khmer_angkor/image003.png
  keyboard/khmer_angkor/2.1/khmer_angkor/image004.png
  keyboard/khmer_angkor/2.1/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/2.1/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/2.1/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/2.1/khmer_angkor/themedata.thmx
Labels: auto

#1947 auto: Keyboard help deployment
  keyboard/chechen_latin/1.2/chechen_latin.php
  keyboard/luo_lakeside/1.0/luo_lakeside.php
  keyboard/taigi_viet_telex/3.1.1/taigi_viet_telex.php
  keyboard/taigi_viet_telex/3.1.1/taigitelexU_.png
  keyboard/taigi_viet_telex/3.1.1/taigitelexU_S.png
Labels: auto

#1948 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0200c.md
  developer/18.0/reference/messages/km0200d.md
  developer/18.0/reference/messages/km0200e.md
  developer/18.0/reference/messages/km0200f.md
  developer/18.0/reference/messages/km02010.md
  developer/18.0/reference/messages/km02012.md
  developer/18.0/reference/messages/km02013.md
  developer/18.0/reference/messages/km02014.md
  developer/18.0/reference/messages/km02015.md
  developer/18.0/reference/messages/km02018.md
  developer/18.0/reference/messages/km0201c.md
  developer/18.0/reference/messages/km02020.md
  developer/18.0/reference/messages/km02022.md
  developer/18.0/reference/messages/km02025.md
  developer/18.0/reference/messages/km02028.md
  developer/18.0/reference/messages/km0202c.md
  developer/18.0/reference/messages/km0202e.md
  developer/18.0/reference/messages/km0202f.md
  developer/18.0/reference/messages/km02030.md
  developer/18.0/reference/messages/km02035.md
  developer/18.0/reference/messages/km02037.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
Labels: auto

#1949 auto: Keyboard help deployment
  keyboard/basic_kbdkhmr/1.2.2/basic_kbdkhmr.php
  keyboard/basic_kbdkni/1.0.2/basic_kbdkni.php
  keyboard/easy_chakma/2.0.0/easy_chakma.php
  keyboard/khmer_advanced/1.1.0/khmer_advanced.php
  keyboard/khmer_angkor/2.1.1/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/2.1.1/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/2.1.1/khmer_angkor.php
  keyboard/khmer_angkor/2.1.1/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/2.1.1/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/2.1.1/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/2.1.1/khmer_angkor/image001.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/image002.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/image003.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/image004.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/2.1.1/khmer_angkor/themedata.thmx
  keyboard/krung/1.0.4/krung.php
  keyboard/krung/1.0.4/krung_romanization.pdf
  keyboard/sil_akha_act/1.0/sil_akha_act.php
  keyboard/sil_brao/1.0.2/sil_brao.php
  keyboard/sil_bunong/1.6.1/phone_longpress.png
  keyboard/sil_bunong/1.6.1/sil_bunong.php
  keyboard/sil_jarai/1.2.2/sil_jarai.php
  keyboard/sil_khmer/2.1.2/sil_khmer.php
Labels: auto

#1951 auto: Keyboard help deployment
  keyboard/luo_lakeside/1.0/luo_lakeside.php
Labels: auto

#1954 auto: Keyboard help deployment
  keyboard/ho_latin/1.0.1/acute-ho_latin.png
  keyboard/ho_latin/1.0.1/ho_latin-default_layer.png
  keyboard/ho_latin/1.0.1/ho_latin.php
  keyboard/ho_latin/1.0.1/tilde-ho_latin.png
Labels: auto

#1955 auto: Keyman for mac help deployment
  products/mac/18.0/basic/config/index.md
  products/mac/18.0/mac_images/add_keyman.png
  products/mac/18.0/mac_images/apple_menu.png
  products/mac/18.0/mac_images/input-menu-keyman-selected.png
  products/mac/18.0/mac_images/input_menu.png
  products/mac/18.0/mac_images/keyboard-add-input-source.png
  products/mac/18.0/mac_images/keyboard-input-sources-annotated.png
  products/mac/18.0/mac_images/keyboard-settings-annotated.png
  products/mac/18.0/mac_images/keyman-configuration-menu.png
  products/mac/18.0/mac_images/keyman-configuration-window.png
  products/mac/18.0/mac_images/keyman-keyboard-selected.png
  products/mac/18.0/mac_images/keyman_config.png
  products/mac/18.0/mac_images/keyman_menu_config.png
  products/mac/18.0/mac_images/menu-bar-with-keyman.png
  products/mac/18.0/mac_images/menu_bar.png
  products/mac/18.0/mac_images/menu_bar_keyman.png
  products/mac/18.0/start/install-keyboard.md
  products/mac/18.0/start/install-keyman.md
  products/mac/18.0/start/tutorial.md
  products/mac/18.0/troubleshooting/uninstall-keyman.md
Labels: auto

#1957 auto: Keyboard help deployment
  keyboard/sil_jarai/1.3/sil_jarai.php
Labels: auto

#1959 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/getPredictionsSuspended.md
  developer/engine/android/18.0/KMManager/index.md
  developer/engine/android/18.0/KMManager/setPredictionsSuspended.md
Labels: auto

#1960 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km0000d.md
  developer/18.0/reference/messages/kmc-ldml.ldmlcompilermessages.md
Labels: auto

#1961 auto: Keyboard help deployment
  keyboard/vietnam/1.0.4/vietnam.php
Labels: auto

#1965 auto: Keyboard help deployment
  keyboard/basic_kbdoldit/1.0.1/basic_kbdoldit.php
  keyboard/itrans_odia/1.1.1/itrans_odia.php
  keyboard/itrans_odia/1.1.1/itrans_odia.png
  keyboard/miluk_hanis_siuslaw/0.3/miluk_hanis_siuslaw.php
  keyboard/mjh_aligali/1.0.2/mjh_aligali.php
  keyboard/mjh_hudum/1.0.2/mjh_hudum.php
  keyboard/mjh_manchu/1.0.2/mjh_manchu.php
  keyboard/mjh_sibe/1.0.2/mjh_sibe.php
  keyboard/mjh_todo/1.0.2/mjh_todo.php
  keyboard/sil_devanagari_romanized/1.7.2/sil_devanagari_romanized.php
  keyboard/sil_devanagari_typewriter/1.1.3/sil_devanagari_typewriter.php
  keyboard/sil_el_ethiopian_latin/1.4.4/sil_el_ethiopian_latin.php
  keyboard/sil_tchad/4.3.2/sil_tchad.php
  keyboard/sil_tchad_qwerty/5.3.2/Td.css
  keyboard/sil_tchad_qwerty/5.3.2/drapeau.tchad.png
  keyboard/sil_tchad_qwerty/5.3.2/sil-logo-blue.png
  keyboard/sil_tchad_qwerty/5.3.2/sil_tchad_logo.png
  keyboard/sil_tchad_qwerty/5.3.2/sil_tchad_qwerty.php
  keyboard/sil_tchad_qwerty/5.3.2/touche TD.png
  keyboard/sil_tchad_qwerty/5.3.2/windows.logo.png
  keyboard/tsakonian/1.1.1/tsakonian.php
Labels: auto

#1966 auto: Keyman for developer help deployment
  developer/19.0/reference/messages/km0000d.md
  developer/19.0/reference/messages/km0200c.md
  developer/19.0/reference/messages/km0200d.md
  developer/19.0/reference/messages/km0200e.md
  developer/19.0/reference/messages/km0200f.md
  developer/19.0/reference/messages/km02010.md
  developer/19.0/reference/messages/km02012.md
  developer/19.0/reference/messages/km02013.md
  developer/19.0/reference/messages/km02014.md
  developer/19.0/reference/messages/km02015.md
  developer/19.0/reference/messages/km02018.md
  developer/19.0/reference/messages/km0201c.md
  developer/19.0/reference/messages/km02020.md
  developer/19.0/reference/messages/km02022.md
  developer/19.0/reference/messages/km02025.md
  developer/19.0/reference/messages/km02028.md
  developer/19.0/reference/messages/km0202c.md
  developer/19.0/reference/messages/km0202e.md
  developer/19.0/reference/messages/km0202f.md
  developer/19.0/reference/messages/km02030.md
  developer/19.0/reference/messages/km02035.md
  developer/19.0/reference/messages/km02037.md
  developer/19.0/reference/messages/km020b3.md
  developer/19.0/reference/messages/kmc-kmn.kmncompilermessages.md
  developer/19.0/reference/messages/kmc-ldml.ldmlcompilermessages.md
Labels: auto
