Repository keymanapp/help.keyman.com, pull requests merged in 2025-02, with the labels that each got.

#1839 auto: Keyboard help deployment
  keyboard/latinized_urdu/1.0/latinized_urdu.php
Labels: auto

#1840 auto: Keyman for developer help deployment
  developer/18.0/context/clone-github-project-parameters.md
  developer/18.0/context/clone-keyman-cloud-project-parameters.md
  developer/18.0/context/clone-local-project-parameters.md
  developer/18.0/context/new-project.md
  developer/18.0/images/ui/frmCloneGitHubProjectParameters.png
  developer/18.0/images/ui/frmCloneKeymanCloudProjectParameters.png
  developer/18.0/images/ui/frmCloneLocalProjectParameters.png
  developer/18.0/images/ui/frmNewProject.png
  developer/18.0/reference/api/kmc-copy.copieroptions.loglevel.md
  developer/18.0/reference/api/kmc-copy.copieroptions.md
  developer/18.0/reference/api/kmc-generate.generatoroptions.loglevel.md
  developer/18.0/reference/api/kmc-generate.generatoroptions.md
  developer/18.0/reference/kmc/cli/get-started.md
  developer/18.0/reference/kmc/cli/reference.md
  developer/18.0/reference/messages/km0b021.md
  developer/18.0/reference/messages/kmc-copy.copiermessages.md
Labels: auto

#1841 auto: Keyboard help deployment
  keyboard/nlci_tamil_winscript/2.2/nlci_tamil_winscript.php
  keyboard/nlci_tamil_winscript/2.2/tamil keyboard.png
Labels: auto

#1843 auto: Keyboard help deployment
  keyboard/arabic_w_o_dots/1.0/arabic_w_o_dots.php
  keyboard/arabic_w_o_dots/1.0/typing-guide-desktop-alternate-shifted.png
  keyboard/arabic_w_o_dots/1.0/typing-guide-desktop-alternate.png
  keyboard/arabic_w_o_dots/1.0/typing-guide-desktop-shifted.png
  keyboard/arabic_w_o_dots/1.0/typing-guide-desktop.png
  keyboard/arabic_w_o_dots/1.0/typing-guide-numbers.jpg
  keyboard/arabic_w_o_dots/1.0/typing-guide-symbols.jpg
  keyboard/arabic_w_o_dots/1.0/typing-guide.jpg
Labels: auto

#1844 auto: Keyboard help deployment
  keyboard/budukh/1.3/BudukhU_.png
  keyboard/budukh/1.3/BudukhU_RA.png
  keyboard/budukh/1.3/BudukhU_S.png
  keyboard/budukh/1.3/budukh.php
Labels: auto

#1842 fix: replace center tags with major-title classes for h1 tags, and styling
  cdn/dev/css/template.css
  developer/index.php
  index.php
  keyboard/index.php
  products/index.php
Labels: fix, chore

#1846 chore: add version 17 details to language history
  developer/language/guide/history.md
Labels: chore

#1847 auto: Keyboard help deployment
  keyboard/amuzgo_guerrero/1.0/amuzgo_guerrero.php
Labels: auto

#1849 auto: Keyboard help deployment
  keyboard/tengwar/1.0/tengwar.php
  keyboard/tengwar/1.0/typing-guide-desktop-alternate-shifted.png
  keyboard/tengwar/1.0/typing-guide-desktop-alternate.png
  keyboard/tengwar/1.0/typing-guide-desktop-shifted.png
  keyboard/tengwar/1.0/typing-guide-desktop.png
Labels: auto

#1850 auto: Keyboard help deployment
  keyboard/khmer_angkor/2.0/KAK_Documentation_EN.pdf
  keyboard/khmer_angkor/2.0/KAK_Documentation_KH.pdf
  keyboard/khmer_angkor/2.0/khmer_angkor.php
  keyboard/khmer_angkor/2.0/khmer_angkor/colorschememapping.xml
  keyboard/khmer_angkor/2.0/khmer_angkor/editdata.mso
  keyboard/khmer_angkor/2.0/khmer_angkor/filelist.xml
  keyboard/khmer_angkor/2.0/khmer_angkor/image001.png
  keyboard/khmer_angkor/2.0/khmer_angkor/image002.png
  keyboard/khmer_angkor/2.0/khmer_angkor/image003.png
  keyboard/khmer_angkor/2.0/khmer_angkor/image004.png
  keyboard/khmer_angkor/2.0/khmer_angkor/tabletAltGr.png
  keyboard/khmer_angkor/2.0/khmer_angkor/tabletDefault.png
  keyboard/khmer_angkor/2.0/khmer_angkor/tabletShift.png
  keyboard/khmer_angkor/2.0/khmer_angkor/themedata.thmx
Labels: auto

#1851 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km00f01.md
  developer/18.0/reference/messages/km00f03.md
  developer/18.0/reference/messages/km00f04.md
  developer/18.0/reference/messages/km00f05.md
  developer/18.0/reference/messages/km04027.md
  developer/18.0/reference/messages/km04028.md
  developer/18.0/reference/messages/km07002.md
  developer/18.0/reference/messages/km07003.md
  developer/18.0/reference/messages/km07004.md
  developer/18.0/reference/messages/km07005.md
  developer/18.0/reference/messages/km07006.md
  developer/18.0/reference/messages/km0a001.md
  developer/18.0/reference/messages/km0b001.md
  developer/18.0/reference/messages/km0b012.md
  developer/18.0/reference/messages/km0b013.md
  developer/18.0/reference/messages/km0b014.md
  developer/18.0/reference/messages/km0b015.md
  developer/18.0/reference/messages/km0b016.md
  developer/18.0/reference/messages/km0b017.md
  developer/18.0/reference/messages/km0b018.md
  developer/18.0/reference/messages/km0b019.md
  developer/18.0/reference/messages/km0b01a.md
  developer/18.0/reference/messages/km0b01b.md
  developer/18.0/reference/messages/kmc-copy.copiermessages.md
  developer/18.0/reference/messages/kmc-generate.generatormessages.md
  developer/18.0/reference/messages/kmc-kmn.kmwcompilermessages.md
  developer/18.0/reference/messages/kmc-package.packagecompilermessages.md
Labels: auto

#1853 auto: Keyman for linux help deployment
  products/linux/19.0/about/history.md
  products/linux/19.0/about/index.md
  products/linux/19.0/about/welcome.md
  products/linux/19.0/about/whatsnew.md
  products/linux/19.0/common/index.md
  products/linux/19.0/index.md
  products/linux/19.0/linux_images/add-input-source-khmer-angkor.png
  products/linux/19.0/linux_images/add-input-source-khmer.png
  products/linux/19.0/linux_images/add-input-source.png
  products/linux/19.0/linux_images/download-khmer-angkor.png
  products/linux/19.0/linux_images/km-config-khmer-angkor.png
  products/linux/19.0/linux_images/km-config.png
  products/linux/19.0/linux_images/mobile viewport.png
  products/linux/19.0/linux_images/onboard.png
  products/linux/19.0/linux_images/package-khmer-angkor-welcome.png
  products/linux/19.0/linux_images/region-and-language.png
  products/linux/19.0/linux_images/region-language-khmer-angkor.png
  products/linux/19.0/linux_images/search-khmer-angkor.png
  products/linux/19.0/linux_images/video.png
  products/linux/19.0/reference/index.md
  products/linux/19.0/reference/km-config.md
  products/linux/19.0/reference/km-kvk2ldml.md
  products/linux/19.0/reference/km-package-get.md
  products/linux/19.0/reference/km-package-install.md
  products/linux/19.0/reference/km-package-list-installed.md
  products/linux/19.0/reference/km-package-uninstall.md
  products/linux/19.0/start/index.md
  products/linux/19.0/start/installing-keyboard.md
Labels: auto

#1860 auto: Keyboard help deployment
  keyboard/tengwar/1.0/LayoutU_.png
  keyboard/tengwar/1.0/LayoutU_S.png
  keyboard/tengwar/1.0/tengwar.php
  keyboard/tengwar_quenya/1.1/keyboard_layout.png
  keyboard/tengwar_quenya/1.1/keyboard_layout_alt-shifted.png
  keyboard/tengwar_quenya/1.1/keyboard_layout_alt.png
  keyboard/tengwar_quenya/1.1/keyboard_layout_shifted.png
  keyboard/tengwar_quenya/1.1/mobile_keyboard_layout.jpg
  keyboard/tengwar_quenya/1.1/mobile_layout_numbers.jpg
  keyboard/tengwar_quenya/1.1/tengwar_quenya.php
Labels: auto

#1863 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/about/whatsnew.md
Labels: auto

#1864 auto: Keyman for mac help deployment
  products/mac/18.0/about/whatsnew.md
Labels: auto

#1865 auto: Keyboard help deployment
  keyboard/tengwar_quenya/1.2/keyboard_layout.png
  keyboard/tengwar_quenya/1.2/keyboard_layout_alt-shifted.png
  keyboard/tengwar_quenya/1.2/keyboard_layout_alt.png
  keyboard/tengwar_quenya/1.2/keyboard_layout_shifted.png
  keyboard/tengwar_quenya/1.2/mobile_keyboard_layout.jpg
  keyboard/tengwar_quenya/1.2/mobile_layout_numbers.jpg
  keyboard/tengwar_quenya/1.2/tengwar_quenya.php
Labels: auto

#1866 auto: Keyman for developer help deployment
  developer/18.0/whats-new.md
Labels: auto

#1867 auto: Keyboard help deployment
  keyboard/greek_tonizo/1.0/greek_tonizo.php
  keyboard/greek_tonizo/1.0/kbd.jpg
  keyboard/greek_tonizo/1.0/kbd1.jpg
  keyboard/greek_tonizo/1.0/kbd3.jpg
  keyboard/greek_tonizo/1.0/kbd4.jpg
Labels: auto

#1868 auto: Keyboard help deployment
  keyboard/sil_mon/1.0/sil_mon.php
Labels: auto

#1873 auto: Keyman for linux help deployment
  products/linux/18.0/about/whatsnew.md
Labels: auto

#1874 auto: Keyman for windows help deployment
  products/windows/18.0/about/whatsnew.md
Labels: auto

#1875 auto: Keyman for ios help deployment
  products/iphone-and-ipad/18.0/about/whatsnew.md
Labels: auto

#1876 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km05023.md
  developer/18.0/reference/messages/km05024.md
  developer/18.0/reference/messages/km05025.md
  developer/18.0/reference/messages/km05026.md
  developer/18.0/reference/messages/km05027.md
  developer/18.0/reference/messages/km05028.md
  developer/18.0/reference/messages/km0a002.md
  developer/18.0/reference/messages/km0b002.md
  developer/18.0/reference/messages/kmc-copy.copiermessages.md
  developer/18.0/reference/messages/kmc-generate.generatormessages.md
  developer/18.0/reference/messages/kmc.infrastructuremessages.md
Labels: auto

#1877 auto: Keyboard help deployment
  keyboard/irula_tamil_winscript/3.0/nlci_tamil_winscript.php
Labels: auto

#1881 auto: Keyboard help deployment
  keyboard/programmer_dvorak/1.0/layout-alternate-shifted.png
  keyboard/programmer_dvorak/1.0/layout-alternate.png
  keyboard/programmer_dvorak/1.0/layout-shifted.png
  keyboard/programmer_dvorak/1.0/layout.png
  keyboard/programmer_dvorak/1.0/programmer_dvorak.php
Labels: auto

#1882 auto: Keyman for web help deployment
  developer/engine/web/18.0/guide/examples/__manual-control.html
  developer/engine/web/18.0/guide/examples/manual-control.md
Labels: auto

#1883 auto: Keyman for android help deployment
  developer/engine/android/18.0/KMManager/getLongpressDelay.md
  developer/engine/android/18.0/KMManager/index.md
  developer/engine/android/18.0/KMManager/sendOptionsToKeyboard.md
  developer/engine/android/18.0/KMManager/setLongpressDelay.md
Labels: auto

#1884 auto: Keyboard help deployment
  keyboard/greek_tonizo/1.0.1/greek_tonizo.php
  keyboard/greek_tonizo/1.0.1/kbd.jpg
  keyboard/greek_tonizo/1.0.1/kbd1.jpg
  keyboard/greek_tonizo/1.0.1/kbd3.jpg
  keyboard/greek_tonizo/1.0.1/kbd4.jpg
Labels: auto

#1886 auto: Keyboard help deployment
  keyboard/easy_arabic/1.1/easy_arabic.php
  keyboard/easy_arabic/1.1/layout-alternate-shifted.png
  keyboard/easy_arabic/1.1/layout-alternate.png
  keyboard/easy_arabic/1.1/layout-shifted.png
  keyboard/easy_arabic/1.1/layout.png
Labels: auto

#1887 auto: Keyboard help deployment
  keyboard/tengwar_quenya/1.3/keyboard_layout.png
  keyboard/tengwar_quenya/1.3/keyboard_layout_alt-shifted.png
  keyboard/tengwar_quenya/1.3/keyboard_layout_alt.png
  keyboard/tengwar_quenya/1.3/keyboard_layout_shifted.png
  keyboard/tengwar_quenya/1.3/mobile_keyboard_layout.jpg
  keyboard/tengwar_quenya/1.3/mobile_layout_numbers.jpg
  keyboard/tengwar_quenya/1.3/tengwar_quenya.php
Labels: auto

#1891 auto: Keyman for developer help deployment
  developer/19.0/reference/messages/km00f06.md
  developer/19.0/reference/messages/kmc-ldml.ldmlcompilermessages.md
Labels: auto

#1892 auto: Keyboard help deployment
  keyboard/arabic_w_o_dots/1.0.1/arabic_w_o_dots.php
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-desktop-alternate-shifted.png
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-desktop-alternate.png
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-desktop-shifted.png
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-desktop.png
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-numbers.jpg
  keyboard/arabic_w_o_dots/1.0.1/typing-guide-symbols.jpg
  keyboard/arabic_w_o_dots/1.0.1/typing-guide.jpg
Labels: auto

#1896 auto: Keyboard help deployment
  keyboard/vietnam/1.0/vietnam.php
Labels: auto

#1897 auto: Keyboard help deployment
  keyboard/behdini_arab/1.0.2/behdini_arab.php
  keyboard/farsiman/1.0.2/farsiman.php
  keyboard/rac_aer/1.1.3/rac_aer.php
  keyboard/rac_aer/1.1.3/rac_aer_layout_for_help.png
  keyboard/rac_arabic/1.0.1/rac_arabic.php
  keyboard/rac_dhatki/1.0.1/rac_dhatki.php
  keyboard/rac_gawri/1.0.1/rac_gawri.php
  keyboard/rac_indus_kohistani/1.0.1/rac_indus_kohistani base.png
  keyboard/rac_indus_kohistani/1.0.1/rac_indus_kohistani shift.png
  keyboard/rac_indus_kohistani/1.0.1/rac_indus_kohistani.php
  keyboard/rac_pahari/1.0.1/rac_pahari.php
  keyboard/rac_saraiki/1.0.1/RAC.jpg
  keyboard/rac_saraiki/1.0.1/rac_saraiki.php
  keyboard/rac_shina/1.2.1/rac_shina.php
  keyboard/rac_shina/1.2.1/rac_shina_layout.png
  keyboard/rac_urdu/1.0.2/rac_urdu base.png
  keyboard/rac_urdu/1.0.2/rac_urdu shift.png
  keyboard/rac_urdu/1.0.2/rac_urdu.php
  keyboard/rac_ushojo/1.0.1/RAC.jpg
  keyboard/rac_ushojo/1.0.1/Rachitrali-Ushojo Keyboard Base version.png
  keyboard/rac_ushojo/1.0.1/Rachitrali-Ushojo Keyboard Shift version.png
  keyboard/rac_ushojo/1.0.1/rac_ushojo.php
  keyboard/rac_wadiyara/1.0.1/RAC.jpg
  keyboard/rac_wadiyara/1.0.1/rac_wadiyara.php
  keyboard/rac_wadiyara/1.0.1/rac_wadiyara_base.png
  keyboard/rac_wadiyara/1.0.1/rac_wadiyara_shift.png
  keyboard/rac_western_punjabi/1.0.2/RAC.jpg
  keyboard/rac_western_punjabi/1.0.2/keyboard_layout.png
  keyboard/rac_western_punjabi/1.0.2/rac_western_punjabi.php
  keyboard/rohingya_arab/1.1.2/rohingya_arab.php
  keyboard/sorani_behdini_arab_qwerty/1.0.2/sorani_behdini_arab_qwerty.php
  keyboard/yidgha/1.0.4/shift.png
  keyboard/yidgha/1.0.4/standard.png
  keyboard/yidgha/1.0.4/yidgha.php
Labels: auto

#1898 auto: Keyboard help deployment
  keyboard/tuareg_tifinagh/1.1.1/tuareg_tifinagh.php
Labels: auto

#1899 auto: Keyboard help deployment
  keyboard/el_pan_sahelian/3.3.1/el_pan_sahelian.php
  keyboard/fv_ojibwa_ifinal/1.0.3/fv_ojibwa_ifinal.php
  keyboard/fv_ojibwa_ifinal/1.0.3/fv_ojibwa_ifinal_U_.png
  keyboard/fv_ojibwa_ifinal/1.0.3/ojibwa_ifinals.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.3/Ojibwa_ifinal_rdot.pdf
  keyboard/fv_ojibwa_ifinal_rdot/1.0.3/fv_ojibwa_ifinal_rdot.php
  keyboard/fv_ojibwa_ifinal_rdot/1.0.3/fv_ojibwa_ifinal_rdot_U_.png
  keyboard/gff_gurage_legacy/1.0.1/GurageTyping-Legacy-English.pdf
  keyboard/gff_gurage_legacy/1.0.1/GurageTyping-Legacy-Gurage.pdf
  keyboard/gff_gurage_legacy/1.0.1/gff_gurage_legacy.php
  keyboard/gff_sbs/1.0.8/SBS-Typing-English.pdf
  keyboard/gff_sbs/1.0.8/gff_sbs.php
  keyboard/gilaki/1.1.1/gilaki.php
  keyboard/gilaki_phonetic/1.1.1/gilaki_phonetic.php
  keyboard/inscriptional_parthian_phonetic/1.0.1/inscriptional_parthian_phonetic.php
  keyboard/inuktitut_naqittaut/1.6.1/inuktitut_naqittaut.php
  keyboard/lao_phonetic/1.1.4/lao_phonetic.php
  keyboard/malar_tirhuta/1.0.2/malar_tirhuta.php
  keyboard/sil_ywq_plrd/1.3.1/sil_ywq_plrd.php
  keyboard/sundanese/1.0.7/sundanese.php
  keyboard/thamizha_bamini/2.2.1/keyrenderer.js
  keyboard/thamizha_bamini/2.2.1/keys2.gif
  keyboard/thamizha_bamini/2.2.1/sri.png
  keyboard/thamizha_bamini/2.2.1/style.css
  keyboard/thamizha_bamini/2.2.1/thamizha_bamini.php
  keyboard/thamizha_bamini/2.2.1/tr.gif
  keyboard/thamizha_new_typewriter/2.2.1/keys2.gif
  keyboard/thamizha_new_typewriter/2.2.1/sri.png
  keyboard/thamizha_new_typewriter/2.2.1/thamizha_new_typewriter.php
  keyboard/vm_tamil_modular/1.2.1/sri.png
  keyboard/vm_tamil_modular/1.2.1/vm_tamil_modular.php
  keyboard/vm_tamil_typewriter/1.2.1/sri.png
  keyboard/vm_tamil_typewriter/1.2.1/vm_tamil_typewriter.php
Labels: auto

#1900 auto: Keyboard help deployment
  keyboard/winchus/1.1/01-capa-emoji-donde-360.png
  keyboard/winchus/1.1/02-primeros-emojis-360.png
  keyboard/winchus/1.1/03-otros-emojis-donde-360.png
  keyboard/winchus/1.1/04-volver-capa-emojis-principal-360.png
  keyboard/winchus/1.1/05-volver-al-teclado-360.png
  keyboard/winchus/1.1/06-presion-larga-360.png
  keyboard/winchus/1.1/07-signo-de-mas-174.png
  keyboard/winchus/1.1/08-cambiar-teclado-360.png
  keyboard/winchus/1.1/deslizar-360-1era-imagen.png
  keyboard/winchus/1.1/deslizar-360.gif
  keyboard/winchus/1.1/file-type-pdf-47.png
  keyboard/winchus/1.1/winchus.pdf
  keyboard/winchus/1.1/winchus.php
  keyboard/winchus/1.1/windows-30.png
Labels: auto

#1890 docs(developer): clarify `context()` offset with `nul` and `if()`
  developer/language/reference/_index.md
  developer/language/reference/_nul.md
  developer/language/reference/context.md
Labels: docs

#1894 refactor: remove use of old $TestServer variable
  _includes/includes/__kmwheader.php
  _includes/includes/servervars.php
  developer/engine/web/1.0/tutorial.php
Labels: refactor

#1901 auto: Keyman for developer help deployment
  developer/18.0/reference/messages/km020b1.md
  developer/18.0/reference/messages/km020b2.md
  developer/18.0/reference/messages/kmc-kmn.kmncompilermessages.md
Labels: auto
