Repository keymanapp/help.keyman.com, pull requests merged in 2025-08, with the labels that each got.

#2191 auto: Keyboard help deployment
  keyboard/basic_kbdcherp/1.1.0/basic_kbdcherp.php
  keyboard/basic_kbdmon/1.1.1/basic_kbdmon.php
  keyboard/baybayin/1.2.1/baybayin.php
  keyboard/bu_phonetic/2.1/bu_phonetic.php
  keyboard/bukawa/3.0.1/bukawa.php
  keyboard/chechen_latin/1.2/chechen_latin.php
  keyboard/chinuk_wawa/1.4/chinuk_wawa.php
  keyboard/dazaga_gourane_karra/1.0.1/dazaga_gourane_karra.php
  keyboard/devanagari_kagapa_phonetic/1.0/devanagari_kagapa_phonetic.php
  keyboard/easy_chakma/2.0.0/easy_chakma.php
  keyboard/el_naija/1.2.1/el_naija.php
  keyboard/english_shavian_jafl/1.1/english_shavian_jafl.php
  keyboard/fv_tlingit/10.1/fv_tlingit.php
  keyboard/galaxie_hebrew_positional/2.3.1/galaxie_hebrew_positional.php
  keyboard/hanunoo/1.1.1/hanunoo.php
  keyboard/kmhmu_2008/1.1/kmhmu_2008.php
  keyboard/lao_pali/1.0.1/lao_pali.php
  keyboard/lao_pali_us/1.0.1/lao_pali_us.php
  keyboard/masaram_gondi/1.2.2/masaram_gondi.php
  keyboard/sil_busa/1.5.2/sil_busa.php
  keyboard/sil_hawaiian/2.3.1/sil_hawaiian.php
  keyboard/sil_kmhmu/1.8/sil_kmhmu.php
  keyboard/sil_tepehuan/1.1.1/sil_tepehuan.php
  keyboard/soqotri_arabic/1.1/soqotri_arabic.php
  keyboard/sp_lentan_ucsur/1.0/sp_lentan_ucsur.php
  keyboard/sp_pochin_ucsur/1.0/sp_pochin_ucsur.php
  keyboard/sp_wakalito_ucsur/1.0/sp_wakalito_ucsur.php
  keyboard/syriac_arabic/1.3.1/syriac_arabic.php
  keyboard/syriac_phonetic/1.3.1/syriac_phonetic.php
  keyboard/turkmen_cyrl/1.3/turkmen_cyrl.php
  keyboard/way/1.0/way.php
Labels: auto

#2192 maint: add labeler for issues and PRs
  .github/multi-labeler.yml
  .github/workflows/labeler.yml
Labels: maint

#2196 docs: Update multi-part Unicode identifiers version restriction note for Developer 18.0
  developer/language/reference/version.md
Labels: docs

#2199 style: fix osk-phone images for keyboard help pages
  cdn/dev/css/template.css
Labels: style

#2203 auto: Keyman for developer help deployment
  developer/19.0/reference/bcp-47.md
Labels: auto, automerge

#2202 chore: Merge master to staging for Sprint A19S9
  .github/multi-labeler.yml
  .github/workflows/labeler.yml
  cdn/dev/css/template.css
  developer/language/reference/version.md
  keyboard/basic_kbdcherp/1.1.0/basic_kbdcherp.php
  keyboard/basic_kbdmon/1.1.1/basic_kbdmon.php
  keyboard/basic_kbdtifi/1.0.1/basic_kbdtifi.php
  keyboard/basic_kbdtifi2/1.0.2/basic_kbdtifi2.php
  keyboard/baybayin/1.2.1/baybayin.php
  keyboard/bu_phonetic/2.1/bu_phonetic.php
  keyboard/bukawa/3.0.1/bukawa.php
  keyboard/chechen_latin/1.2/chechen_latin.php
  keyboard/chinuk_wawa/1.4/chinuk_wawa.php
  keyboard/dazaga_gourane_karra/1.0.1/dazaga_gourane_karra.php
  keyboard/devanagari_kagapa_phonetic/1.0/devanagari_kagapa_phonetic.php
  keyboard/easy_chakma/2.0.0/easy_chakma.php
  keyboard/el_naija/1.2.1/el_naija.php
  keyboard/english_shavian_jafl/1.1/english_shavian_jafl.php
  keyboard/fv_tlingit/10.1/fv_tlingit.php
  keyboard/galaxie_hebrew_positional/2.3.1/galaxie_hebrew_positional.php
  keyboard/hanunoo/1.1.1/hanunoo.php
  keyboard/kmhmu_2008/1.1/kmhmu_2008.php
  keyboard/lao_pali/1.0.1/lao_pali.php
  keyboard/lao_pali_us/1.0.1/lao_pali_us.php
  keyboard/masaram_gondi/1.2.2/masaram_gondi.php
  keyboard/sil_busa/1.5.2/sil_busa.php
  keyboard/sil_hawaiian/2.3.1/sil_hawaiian.php
  keyboard/sil_kmhmu/1.8/sil_kmhmu.php
  keyboard/sil_mon/1.2/sil_mon.php
  keyboard/sil_tawallammat/1.1.2/2d54.png
  keyboard/sil_tawallammat/1.1.2/2d54_2d5c.png
  keyboard/sil_tawallammat/1.1.2/2d5c.png
  keyboard/sil_tawallammat/1.1.2/2d7f.png
  keyboard/sil_tawallammat/1.1.2/sil_tawallammat.php
  keyboard/sil_tawallammat/1.1.2/sil_tawallammatU_.png
  keyboard/sil_tawallammat/1.1.2/sil_tawallammatU_RA.png
  keyboard/sil_tawallammat/1.1.2/sil_tawallammatU_S.png
  keyboard/sil_tepehuan/1.1.1/sil_tepehuan.php
  keyboard/soqotri_arabic/1.1/soqotri_arabic.php
  keyboard/sp_lentan_ucsur/1.0/sp_lentan_ucsur.php
  keyboard/sp_pochin_ucsur/1.0/sp_pochin_ucsur.php
  keyboard/sp_wakalito_ucsur/1.0/sp_wakalito_ucsur.php
  keyboard/syriac_arabic/1.3.1/syriac_arabic.php
  keyboard/syriac_phonetic/1.3.1/syriac_phonetic.php
  keyboard/tai_lanna_thai/1.0.1/tai_lanna_thai.php
  keyboard/tai_lanna_thai/1.0/tai_lanna_thai.php
  keyboard/turkmen_cyrl/1.3/turkmen_cyrl.php
  keyboard/wali/1.0/wali.php
  keyboard/way/1.0/way.php
Labels: staging

#2207 auto: Keyboard help deployment
  keyboard/sil_tchad_faux_azerty/5.3/Td.css
  keyboard/sil_tchad_faux_azerty/5.3/drapeau.tchad.png
  keyboard/sil_tchad_faux_azerty/5.3/sil-logo-blue.png
  keyboard/sil_tchad_faux_azerty/5.3/sil_tchad_faux_azerty.php
  keyboard/sil_tchad_faux_azerty/5.3/sil_tchad_logo.png
  keyboard/sil_tchad_faux_azerty/5.3/touche TD.png
  keyboard/sil_tchad_faux_azerty/5.3/windows.logo.png
Labels: auto

#2211 auto: Keyboard help deployment
  keyboard/sil_kcho/1.1/sil_kcho.php
  keyboard/sil_kcho/1.1/tones.png
  keyboard/sil_kcho/1.1/vowels.png
Labels: auto

#2215 auto: Keyboard help deployment
  keyboard/orma/1.2/orma.php
Labels: auto

#2219 auto: Keyboard help deployment
  keyboard/sil_hupdah/1.0/sil_hupdah.php
Labels: auto

#2221 auto: Keyboard help deployment
  keyboard/thamizha_bamini/2.2.2/keyrenderer.js
  keyboard/thamizha_bamini/2.2.2/keys2.gif
  keyboard/thamizha_bamini/2.2.2/sri.png
  keyboard/thamizha_bamini/2.2.2/style.css
  keyboard/thamizha_bamini/2.2.2/thamizha_bamini.php
  keyboard/thamizha_bamini/2.2.2/tr.gif
Labels: auto

#2224 auto: Keyboard help deployment
  keyboard/basic_kbda2/1.1.1/basic_kbda2.php
  keyboard/basic_kbdbash/1.1.1/basic_kbdbash.php
  keyboard/basic_kbdcz1/1.1.1/basic_kbdcz1.php
  keyboard/basic_kbdcz2/1.1.1/basic_kbdcz2.php
  keyboard/basic_kbdgeome/1.0/basic_kbdgeome.php
  keyboard/basic_kbdgkl/1.1.1/basic_kbdgkl.php
  keyboard/basic_kbdhau/1.0/basic_kbdhau.php
  keyboard/basic_kbdhaw/1.0/basic_kbdhaw.php
  keyboard/basic_kbdhebl3/1.1.1/basic_kbdhebl3.php
  keyboard/basic_kbdhept/1.2/basic_kbdhept.php
  keyboard/basic_kbdinen/1.0/basic_kbdinen.php
  keyboard/basic_kbdjav/1.0/basic_kbdjav.php
  keyboard/basic_kbdkyr/1.1.1/basic_kbdkyr.php
  keyboard/basic_kbdlt1/1.1/basic_kbdlt1.php
  keyboard/basic_kbdsyr1/1.3/basic_kbdsyr1.php
  keyboard/basic_kbdsyr2/1.2/basic_kbdsyr2.php
  keyboard/basic_kbdtt102/1.1.1/basic_kbdtt102.php
  keyboard/basic_kbdturme/1.1.1/basic_kbdturme.php
  keyboard/basic_kbdurdu/1.2.1/basic_kbdurdu.php
  keyboard/french_zhjay/1.0/french_zhjay.php
  keyboard/pt_international/1.0/pt_international.php
Labels: auto

#2228 auto: update shared-sites version to v1.0.3
  build.sh
Labels: auto
