Repository keymanapp/help.keyman.com, pull requests merged in 2025-09, with the labels that each got.

#2237 auto: Keyman for web help deployment
  developer/engine/web/19.0/troubleshooting/embedded_fonts.md
  developer/engine/web/19.0/troubleshooting/index.md
Labels: auto, automerge

#2238 auto: Keyman for windows help deployment
  developer/engine/windows/19.0/api/IKeyman/index.md
  developer/engine/windows/19.0/api/IKeymanControl/IsOnlineUpdateCheckOpen.md
  developer/engine/windows/19.0/api/IKeymanControl/IsTextEditorOpen.md
  developer/engine/windows/19.0/api/IKeymanControl/OpenHelp.md
  developer/engine/windows/19.0/api/IKeymanControl/OpenTextEditor.md
  developer/engine/windows/19.0/api/IKeymanControl/OpenUpdateCheck.md
  developer/engine/windows/19.0/api/IKeymanControl/index.md
  developer/engine/windows/19.0/index.md
Labels: auto, automerge

#2240 auto: Keyboard help deployment
  keyboard/lao_pali_extended/1.0/lao_pali_extended.php
Labels: auto

#2241 auto: Keyboard help deployment
  keyboard/gff_harari/1.0.6/HarariTyping-English.pdf
  keyboard/gff_harari/1.0.6/gff_harari.php
  keyboard/gff_harari/1.0.6/html.css
  keyboard/gff_harari/1.0.6/images/gff_harari-default-1.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-default-2.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-default-3.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-default-4.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-default-5.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-default-6.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-extra-1.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-extra-2.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-extra-3.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-labiovelar-1.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-labiovelar-2.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-punctuation-1.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-punctuation-2.jpeg
  keyboard/gff_harari/1.0.6/images/gff_harari-punctuation-3.jpeg
  keyboard/gff_harari/1.0.6/kb.css
Labels: auto

#2201 docs: new rota help page
  developer/keyboards/standard/index.md
  developer/language/guide/index.md
  developer/language/guide/rota-keys.md
Labels: docs

#2248 auto: Keyboard help deployment
  keyboard/beria_erfe_phonetic/1.2/beria_erfe_phonetic.php
Labels: auto

#2249 docs: add Control keys and control characters guide
  developer/language/guide/control-keys.md
  developer/language/guide/groups.md
  developer/language/guide/index.md
  developer/language/guide/virtual-keys.md
Labels: docs

#2252 auto: Keyboard help deployment
  keyboard/shanghai_jamo/1.0/ancientconsonants.png
  keyboard/shanghai_jamo/1.0/ancienttones.png
  keyboard/shanghai_jamo/1.0/ancientvowels.png
  keyboard/shanghai_jamo/1.0/default.png
  keyboard/shanghai_jamo/1.0/liampoconsonants.png
  keyboard/shanghai_jamo/1.0/liampotones.png
  keyboard/shanghai_jamo/1.0/liampovowels.png
  keyboard/shanghai_jamo/1.0/newshanghaiconsonants.png
  keyboard/shanghai_jamo/1.0/newshanghaivowels.png
  keyboard/shanghai_jamo/1.0/shanghai jamo.php
  keyboard/shanghai_jamo/1.0/shanghaiconsonants.png
  keyboard/shanghai_jamo/1.0/shanghaitones.png
  keyboard/shanghai_jamo/1.0/shanghaivowels.png
  keyboard/shanghai_jamo/1.0/shift.png
  keyboard/shanghai_jamo/1.0/soochowconsonants.png
  keyboard/shanghai_jamo/1.0/soochowtones.png
  keyboard/shanghai_jamo/1.0/soochowvowels.png
  keyboard/shanghai_jamo/1.0/wuconsonants.png
  keyboard/shanghai_jamo/1.0/wutones.png
  keyboard/shanghai_jamo/1.0/wuvowels.png
Labels: auto

#2259 auto: Keyboard help deployment
  keyboard/beria_erfe_phonetic/1.2.1/beria_erfe_phonetic.php
Labels: auto

#2261 auto: Keyboard help deployment
  keyboard/spanish_telex/1.0/spanish_telex.php
Labels: auto

#2264 auto: Keyboard help deployment
  keyboard/vietnam/2.0.2/vietnam.php
Labels: auto

#2265 auto: Keyboard help deployment
  keyboard/shanghai_jamo/1.0/shanghai_jamo.php
Labels: auto

#2269 auto: Keyman for linux help deployment
  products/linux/18.0/about/whatsnew.md
Labels: auto

#2270 auto: Keyboard help deployment
  keyboard/easy_arabic/1.1/easy_arabic.php
  keyboard/lao_phonetic/1.1.4/lao_phonetic.php
  keyboard/masaram_gondi/1.2.2/masaram_gondi.php
  keyboard/sil_dzongkha/1.2/sil_dzongkha.php
  keyboard/sil_eastern_congo/1.5.4/sil_eastern_congo.php
  keyboard/soninke_n_ti/1.0.1/soninke_n_ti.php
  keyboard/unifon/1.0/unifon.php
  keyboard/urdu_dvorak/1.1/urdu_dvorak.php
Labels: auto

#2275 auto: Keyboard help deployment
  keyboard/kmhmu_2008/1.1/kmhmu_2008.php
  keyboard/lao_2008_basic/1.3/lao_2008_basic.php
  keyboard/lao_2008_rapid/1.1.3/lao_2008_rapid.php
  keyboard/lao_pali/1.0.1/lao_pali.php
  keyboard/lao_pali_us/1.0.1/lao_pali_us.php
  keyboard/sil_kmhmu/1.8/sil_kmhmu.php
  keyboard/tibetan_direct_input/1.4/tibetan_direct_input.php
Labels: auto

#2276 auto: Keyman for android help deployment
  developer/engine/android/19.0/KMManager/getNavigationBarHeight.md
  developer/engine/android/19.0/KMManager/index.md
Labels: auto, automerge
